### ISSUE TITLE
Controls - Profile and rate profile switching.

### ISSUE THREAD

**Issue by makattack** [cleanflight/cleanflight#1000]
Under 1.8.1, I was able to configure all three profiles 0-2, along with all three rateprofiles such that I could select any rate profile from an AUX channel no matter which profile I was using. This does not seem to work under 1.9.0.

Under 1.8.1, I had this configuration: 
adjrange 0 0 4 950 2050 12 4

On a flip32+ running SBUS rc input (X4R-SB RX), I used to be able to use a three position switch to select different rateprofiles independent of the profile.

Additionally, the profile switching using stick commands used to result in the status/green LED blinking 1-3 times to indicate the profile selected. This no longer happens under 1.9.0 -- which does blink once for profile 0, but doesn't change the steady blink rate for profile 1 nor 2. That's also new in 1.9.0, for the status light to blink on a regular interval vs. stay steady on.

While searching the code to see if there was a change that looked to have obviously altered this behavior:
https://github.com/cleanflight/cleanflight/search?utf8=%E2%9C%93&q=changeControlRateProfile

I noticed that rc_controls.c, while including config.h which already has a prototype for the changeControlRateProfile() function, duplicates the function prototype just before a function definition for applySelectAdjustment() (line 574).

NOTE: CLI commands to change the rateprofile does work.

**Comment by Archon03** [comment]
While we're at it, can we make the "PID Tuning" tab number the profiles 0,1,2 like the CLI does (or vice versa, both use 1,2,3)?

**Comment by hydra** [comment]
@Archon03 that's a gui issue.  this issue is for the firmware.  please stay focussed.

@makattack I was using rate profile selection using 2 and 3 positions switches on 3 different transmitters on 4 different quads last week, pretty sure there's no fundamental problem with 1.9.0.

can you provide a config dump and screenshots;
1) screenshot of RX tab with switch in low position
2) screenshot of RX tab with swithc in high position
3) screenshot of Adjustments tab.

i suspect RX channel endpoints are incorrect or some other mis-configuration at this point.

**Comment by makattack** [comment]
Thanks for the analysis. Here is my config dump:

<pre>
# version
# Cleanflight/NAZE 1.9.0 May 31 2015 / 13:17:47 (98f7549)
# dump master

# mixer
mixer QUADX


# feature
feature -RX_PPM
feature -VBAT
feature -INFLIGHT_ACC_CAL
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -FAILSAFE
feature -SONAR
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DISPLAY
feature -ONESHOT125
feature -BLACKBOX
feature VBAT
feature RX_SERIAL
feature MOTOR_STOP
feature FAILSAFE
feature CURRENT_METER


# map
map AETR1234


# serial
serial 0 1 115200 57600 0 115200
serial 1 64 115200 57600 0 115200


# led
led 0 15,15:ES:IA:0
led 1 15,8:E:WF:0
led 2 15,7:E:WF:0
led 3 15,0:NE:IA:0
led 4 8,0:N:F:0
led 5 7,0:N:F:0
led 6 0,0:NW:IA:0
led 7 0,7:W:WF:0
led 8 0,8:W:WF:0
led 9 0,15:SW:IA:0
led 10 7,15:S:WF:0
led 11 8,15:S:WF:0
led 12 7,7:U:WF:0
led 13 8,7:U:WF:0
led 14 7,8:D:WF:0
led 15 8,8:D:WF:0
led 16 8,9::R:3
led 17 9,10::R:3
led 18 10,11::R:3
led 19 10,12::R:3
led 20 9,13::R:3
led 21 8,14::R:3
led 22 7,14::R:3
led 23 6,13::R:3
led 24 5,12::R:3
led 25 5,11::R:3
led 26 6,10::R:3
led 27 7,9::R:3
led 28 0,0:::0
led 29 0,0:::0
led 30 0,0:::0
led 31 0,0:::0


# color
color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 0,0,0
color 15 0,0,0

set looptime = 2500
set emf_avoidance = 0
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_scale = 30
set rssi_ppm_invert = 0
set input_filtering_mode = 0
set min_throttle = 1070
set max_throttle = 1850
set min_command = 1000
set servo_center_pulse = 1500
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set 3d_deadband_throttle = 50
set motor_pwm_rate = 400
set servo_pwm_rate = 50
set retarded_arm = 0
set disarm_kill_switch = 1
set auto_disarm_delay = 5
set small_angle = 25
set flaps_speed = 0
set fixedwing_althold_dir = 1
set reboot_character = 82
set gps_provider = 0
set gps_sbas_mode = 0
set gps_auto_config = 1
set gps_auto_baud = 0
set serialrx_provider = 2
set spektrum_sat_bind = 0
set telemetry_switch = 0
set telemetry_inversion = 0
set frsky_default_lattitude =  0.000
set frsky_default_longitude =  0.000
set frsky_coordinates_format = 0
set frsky_unit = 0
set frsky_vfas_precision = 0
set hott_alarm_sound_interval = 5
set battery_capacity = 0
set vbat_scale = 110
set vbat_max_cell_voltage = 43
set vbat_min_cell_voltage = 33
set vbat_warning_cell_voltage = 35
set current_meter_scale = 400
set current_meter_offset = 0
set multiwii_current_meter_output = 0
set current_meter_type = 1
set align_gyro = 0
set align_acc = 0
set align_mag = 0
set align_board_roll = 0
set align_board_pitch = 0
set align_board_yaw = 0
set max_angle_inclination = 500
set gyro_lpf = 42
set moron_threshold = 32
set gyro_cmpf_factor = 600
set gyro_cmpfm_factor = 250
set yaw_control_direction = 1
set pid_at_min_throttle = 1
set yaw_direction = 1
set yaw_jump_prevention_limit = 200
set tri_unarmed_servo = 1
set servo_lowpass_freq = 400
set servo_lowpass_enable = 0
set failsafe_delay = 10
set failsafe_off_delay = 200
set failsafe_throttle = 1000
set rx_min_usec = 985
set rx_max_usec = 2115
set acc_hardware = 0
set mag_hardware = 0
set blackbox_rate_num = 1
set blackbox_rate_denom = 1
set blackbox_device = 0

# dump profile

# profile
profile 0

# aux
aux 0 1 1 1300 1700
aux 1 2 1 1925 2100
aux 2 0 0 900 900
aux 3 0 0 900 900
aux 4 0 0 900 900
aux 5 0 0 900 900
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# adjrange
adjrange 0 0 4 900 2100 12 4
adjrange 1 1 2 1050 1125 6 6
adjrange 2 1 2 1250 1350 7 6
adjrange 3 1 2 1450 1550 8 6
adjrange 4 1 2 1650 1750 9 6
adjrange 5 1 2 1850 1950 10 6
adjrange 6 1 2 950 1050 0 6
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0

# servo
servo 0 1020 2000 1500 30 -1
servo 1 1020 2000 1500 30 -1
servo 2 1020 2000 1500 100 -1
servo 3 1020 2000 1500 100 -1
servo 4 1020 2000 1500 100 -1
servo 5 1020 2000 1500 100 -1
servo 6 1020 2000 1500 100 -1
servo 7 1020 2000 1500 100 -1
servo 8 1020 2000 1500 100 -1
servo 9 1020 2000 1500 100 -1

set gps_pos_p = 15
set gps_pos_i = 0
set gps_pos_d = 0
set gps_posr_p = 34
set gps_posr_i = 14
set gps_posr_d = 53
set gps_nav_p = 25
set gps_nav_i = 33
set gps_nav_d = 83
set gps_wp_radius = 200
set nav_controls_heading = 1
set nav_speed_min = 100
set nav_speed_max = 300
set nav_slew_rate = 30
set alt_hold_deadband = 40
set alt_hold_fast_change = 1
set deadband = 0
set yaw_deadband = 0
set throttle_correction_value = 0
set throttle_correction_angle = 800
set default_rate_profile = 0
set gimbal_flags = 1
set acc_lpf_factor = 4
set accxy_deadband = 40
set accz_deadband = 40
set accz_lpf_cutoff =  5.000
set acc_unarmedcal = 1
set acc_trim_pitch = 0
set acc_trim_roll = 0
set baro_tab_size = 21
set baro_noise_lpf =  0.600
set baro_cf_vel =  0.985
set baro_cf_alt =  0.965
set mag_declination = 0
set pid_controller = 1
set p_pitch = 57
set i_pitch = 11
set d_pitch = 15
set p_roll = 57
set i_roll = 11
set d_roll = 15
set p_yaw = 105
set i_yaw = 9
set d_yaw = 0
set p_pitchf =  2.500
set i_pitchf =  0.600
set d_pitchf =  0.060
set p_rollf =  2.500
set i_rollf =  0.600
set d_rollf =  0.060
set p_yawf =  8.000
set i_yawf =  0.500
set d_yawf =  0.050
set level_horizon =  3.000
set level_angle =  5.000
set sensitivity_horizon = 75
set p_alt = 50
set i_alt = 0
set d_alt = 0
set p_level = 90
set i_level = 10
set d_level = 100
set p_vel = 120
set i_vel = 45
set d_vel = 1
set yaw_p_limit = 500

# dump rates

# rateprofile
rateprofile 0

set rc_rate = 90
set rc_expo = 65
set rc_yaw_expo = 0
set thr_mid = 50
set thr_expo = 0
set roll_rate = 0
set pitch_rate = 0
set yaw_rate = 0
set tpa_rate = 0
set tpa_breakpoint = 1500
</pre>

Low position:
![image](https://cloud.githubusercontent.com/assets/2448573/8081122/2eb23752-0f40-11e5-86df-f2b3b4d1d390.png)

![image](https://cloud.githubusercontent.com/assets/2448573/8081058/666806be-0f3f-11e5-89cc-11ea4137d80d.png)

Middle position:
![image](https://cloud.githubusercontent.com/assets/2448573/8081071/8591b06c-0f3f-11e5-97a3-150512c50416.png)

High position:
![image](https://cloud.githubusercontent.com/assets/2448573/8081129/474409b2-0f40-11e5-8e50-3699df157ee8.png)

![image](https://cloud.githubusercontent.com/assets/2448573/8081081/a0c75396-0f3f-11e5-9f2a-0deca2ade2e3.png)

**Comment by makattack** [comment]
In thinking about this more, I tried also adjusting my endpoints for AUX5 to be between 1000-2000, but that didn't seem to change anything.

Perhaps the problem is how I'm testing this functionality? I'm in the CLI the whole time, starting with low position. I'll type "dump rates" and see rate profile 0. When I switch to the middle position, and repeat the command, it's still in rate profile 0.

I do notice, if I exit the CLI, and come back in, and issue "dump rates" I will see that it has changed, but I assumed it was only because it set the rate profile on reboot.

**Comment by hydra** [comment]
Yes, it's how you're testing it!

the adjustment controls from RX are ignored when in the CLI.  This is by design.

**Comment by hydra** [comment]
Please submit a new PR that updates the documentation if you find it is unclear.

**Comment by makattack** [comment]
Thank you Dominic. I can submit a PR for the documentation, but would also be happy at helping out with the update of it as well. What about the change in behaviour for the status LED on changing profiles? Do you think that warrants a new PR?
