### ISSUE TITLE
IO - Servo min/max/mid/rate configuration via MSP problem

### ISSUE THREAD

**Issue by ldonnay** [cleanflight/cleanflight#1002]
Using Cleanflight 1.9 with Configurator 0.65, updating of min/max/mid rate does not work. When clicking on save, there is no action: and log window does not display anything. When changing tab and coming back to Servo tab, values come back to previous version.
Servo Tilt is activated and when coming back to Cleanflight 1.8.1, everythingh is working.

**Comment by supergregg** [comment]
Sam problem here. Upgraded to 1.9.0 and now i cant get my plane to perform properly. All "compensation" directions are wrong. Had to revert to 1.8.1.

**Comment by DKDarkness** [comment]
Same problem. Running Cleanflight 1.9.0 for Naze32 on a Flip32+ board under configurator 0.65.0. Any changes made in the "Servos" tab when running tricopter or flying wing configuration, will not be saved. No log entry will be written either.
