### ISSUE TITLE
servo tilt overrides throttle channels when using the airplane/ fixed wing mix

### ISSUE THREAD

**Issue by craigbs** [cleanflight/cleanflight#1006]
servo tilt overrides throttle channels when using the airplane/ fixed wing mix

**Comment by hydra** [comment]
has this recently started happening or has it always done this?

**Comment by hydra** [comment]
looking at mixer.c it's always done it.

https://github.com/cleanflight/cleanflight/blob/master/src/main/flight/mixer.c#L452-L456

servos 0 and 1 are always used.

https://github.com/cleanflight/cleanflight/blob/master/src/main/flight/mixer.c#L497-L500

and here, SERVO_PLANE_INDEX_MIN SERVO_FLAPS == 2 and thus servos 0-4 are used.

**Comment by hydra** [comment]
Fix was simple enough, applied.  Please grab a development build that includes this change and test.

![screen shot 2015-06-10 at 14 31 51](https://cloud.githubusercontent.com/assets/57075/8083567/7925fd72-0f7d-11e5-9225-e0f10753b593.png)

**Comment by hydra** [comment]
It should be noted that the GUI also needs updating to support configuration, however the firmware itself does support it.

**Comment by hydra** [comment]
The second commit finally allows the computed gimbal servo value to be used to drive the servos.  without it the value was computed but never used except for display purposes.

**Comment by leothehuman** [comment]
Will this affect tricopter output layout? Can a tricopter use SERVO_TILT now?
