### ISSUE TITLE
Suggestion: Failsafe event logging

### ISSUE THREAD

**Issue by Arakon** [cleanflight/cleanflight#1011]
It would be quite useful to log RX failsafe events in the Blackbox logs, and display them in the BB-viewer (i.e. a red line/background while the event is ongoing).
I only just discovered that during my first FPV event, I apparently had several FS events after crashing/landing low in the grass, it would be useful to see if that occured more times.

**Comment by thenickdude** [comment]
Failsafe state logging will be added by #907
