### ISSUE TITLE
feature CURRENT_METER works only if LED_STRIP is enabled

### ISSUE THREAD

**Issue by goebish** [cleanflight/cleanflight#102]
feature CURRENT_METER works only if LED_STRIP is enabled.

feature
RX_PPM VBAT CURRENT_METER LED_STRIP
current meter works

feature
RX_PPM VBAT CURRENT_METER
current meter doesn't work

Checked on 3x Naze32 rev.5, with a pot on rc8 and an actual current meter.

**Comment by hydra** [comment]
There was an ADC/PWM pin mapping clash which has been fixed.

Please test latest firmware and update this issue when you have tested it.

If there is still a problem please re-open this issue.
