### ISSUE TITLE
HoTT - Hardware Serial Support

### ISSUE THREAD

**Issue by NOS-Copter** [cleanflight/cleanflight#1021]
Hello,

I'm new to github & Cleanflight. I found that HoTT-Telemetry wont work on Hardware Serial (think the same Problem which CopterFail has) so I looked for the Problem and kind of solved it. Please help me to improve this Code :)

The Problem is the switching from RX-Mode to TX-Mode and vice versa. I solved the Problem by replacing the serialSetMode(...) with close

line 426 in hott.c
        //serialSetMode(hottPort, MODE_TX);
        closeSerialPort(hottPort);
        hottPort = openSerialPort(portConfig->identifier, FUNCTION_TELEMETRY_HOTT, NULL, HOTT_BAUDRATE, MODE_TX, SERIAL_NOT_INVERTED);

equivalent for line 235
        //serialSetMode(hottPort, MODE_RX);
        closeSerialPort(hottPort);
        hottPort = openSerialPort(portConfig->identifier, FUNCTION_TELEMETRY_HOTT, NULL, HOTT_BAUDRATE, MODE_RX, SERIAL_NOT_INVERTED);

Sry for this way of Code... please tell me how to implement it without confusion of other changes.

Greetings NOS-Copter

**Comment by hydra** [comment]
I've tested and applied your workaround after examining the root cause - the hardware is never initialised for TX when using uart ports, with softserial both RX and TX pins are always initialised.

There is more cleanup work required.
