### ISSUE TITLE
more specific options on setting up servos, motors, and data lines

### ISSUE THREAD

**Issue by directgumby** [cleanflight/cleanflight#1039]
Hello,

I have a stack of the Naze32 and the OSDoge on a quad.  I chose to use the power connection from the OSDoge on motor pins 6.  

My issue is that I would like to support servo tilt and/or servo pitch control to a single output.  With the power coming in on pin 6 I cannot so easily enable servo tilt as I cannot currently connect a motor to that pin. Turning on the servo tilt will not currently work.

One option that I would like is the ability to set the motor output 1 or 5 to servo and have the motors on the other 4.  

In looking at other ways of controlling servos I notice I could use the AUX_FORWARD_CHANNEL_TO_SERVO_COUNT but that moves all 4 to the outputs disabling future use of the LED strip.

Ultimately i'd like to be able to more selectively set what is sent where.

If this could be done more cleanly in the configuration tool, that would be sweet!

Thanks,
Brett

**Comment by hydra** [comment]
This has already been requested, closing. See #884 and related issues.  Please search before creating new issues.
