### ISSUE TITLE
LED enhancement with VBAT

### ISSUE THREAD

**Issue by Fvk1960** [cleanflight/cleanflight#1048]
I like to propose a LED option to display the VBAT status. LEDS that changes from Green over yellow to RED indication battery voltage and at last flashing RED at minimum voltage.
To reduce battery consumption a dim function on all LED linear to batteryvoltage and or option to control brightness.
Thanks

**Comment by hydra** [comment]
Do you mean LED or LEDSTRIP?

**Comment by dkisselev** [comment]
I'm pretty sure LEDSTRIP.

Seconding the request though, being able to program a few nodes on the strip to show battery status would be pretty useful.

**Comment by Fvk1960** [comment]
Yes the ledstrip function.

**Comment by andymac4182** [comment]
It would be great to have this like Ring Thrust State. Where you could set the min and max or auto detected and it would show the battery going flat and changing colour as it did.
