### ISSUE TITLE
IO - SoftSerial input not working on STMF303 targets.

### ISSUE THREAD

**Issue by hydra** [cleanflight/cleanflight#1058]
For some reason the `TIM3_IRQHandler` is not called when the input pin transitions from HIGH to LOW.

I verfied that the CCER and DIER registers are configured correctly.

**Comment by borisbstyle** [comment]
Does this mean softserial is not working now at all?

**Comment by hydra** [comment]
No, and i fixed it yesterday too anyway after getting it working on the F3 boards.
