### ISSUE TITLE
SpracingF3 Bootloader Failed when flashing

### ISSUE THREAD

**Issue by borisbstyle** [cleanflight/cleanflight#1059]
Cant seem to get to flash mine. The board works fine for the rest. I can connect and change things.
![image](https://cloud.githubusercontent.com/assets/10757508/8387634/81ee832c-1c5a-11e5-8e44-205df3241229.png)

**Comment by fly4props** [comment]
I'm in the same boat, The board works but trying to upload new firm ware doesnt work. I am getting the same bootloader failed era.

**Comment by fly4props** [comment]
BorisBstyle try checking the box that says Manual Baud Rate. I forgot to check it even if the baudrate was set. Hope that helps you.

**Comment by borisbstyle** [comment]
Thanks. What baudrate did you select?

**Comment by borisbstyle** [comment]
i think this issue should be moved to the configurator if this is true than. It should select the proper settings automatically

**Comment by fly4props** [comment]
256000 Boris. Mine was selected just the check box had to be checked.

**Comment by borisbstyle** [comment]
Yes it works :D

**Comment by fly4props** [comment]
great!!!!

**Comment by Trussroads** [comment]
@hydra Does this mean you have you shipped the first batch then? 

>rubs hands together in anticipation!< :D
