### ISSUE TITLE
Build - Upgrade to GCC 4.9.x

### ISSUE THREAD

**Issue by hydra** [cleanflight/cleanflight#1078]
We can do this now #763 is fixed.
1. Update build system
2. Update docs

**Comment by pulsar256** [comment]
Addressed the GCC update in the Travis-Update PR: https://github.com/cleanflight/cleanflight/pull/1069 
findings so far:

- Confirmed VCP functionality on CC3D - all fine. 
- CJMCU builds exceed flash size: https://travis-ci.org/pulsar256/cleanflight/builds/69198401 / https://travis-ci.org/pulsar256/cleanflight/jobs/69198412

Other 4.9 builds can be downloaded / tested here: http://cleanflight.memoryleaks.org/builds/pulsar256_cleanflight/2015-07-01/

**Comment by tannewt** [comment]
Isn't this done?
