### ISSUE TITLE
Servo control not working as expected on CC3D in airplane mode

### ISSUE THREAD

**Issue by AustinSaintAubin** [cleanflight/cleanflight#1080]
Output channels on the CC3D does not work as expected when CC3D is in airplane mode.
Tested on CC3D nano,  flaw makes CC 3-D unusable with airplane mode.

**Comment by SteveAmor** [comment]
Which version of CF?

**Comment by giryan** [comment]
related(or a dupe of) https://github.com/cleanflight/cleanflight/issues/1076

**Comment by SteveAmor** [comment]
@AustinSaintAubin please can you close this issue.

**Comment by AustinSaintAubin** [comment]
Is related / dupe of #1076
