### ISSUE TITLE
Feature request: Adjust transmitter endpoints from within Cleanflight.

### ISSUE THREAD

**Issue by RCDaddy** [cleanflight/cleanflight#1087]
The ability to adjust tx endpoints from within cleanflight there are some transmitters where this is not possible (like a DX5e)

**Comment by digitalentity** [comment]
Already requested in #531. #618 adds the possibility to adjust endpoints separately for each channel

**Comment by RCDaddy** [comment]
My bad and thank you :)

**Comment by digitalentity** [comment]
No problem :)
