### ISSUE TITLE
Add extra beeper functionality, primarily options for disabling different beeps.

### ISSUE THREAD

**Issue by giryan** [cleanflight/cleanflight#1098]
I would like to be able to disable the beeper entirely at times, e.g. when I'm fiddling with my quad on my desk in the office. It's not always practical to physically disconnect it.

Also, conditional functionality:
* stop failsafe beeping when there is no RX connected.
* ignore-voltage range for the low battery beeper

**Comment by yuan0226** [comment]
Part of the code buzzer can be masked to achieve.

**Comment by hydra** [comment]
closing, handled by #2112
