### ISSUE TITLE
GUI Sensor Section - Kinematic Values

### ISSUE THREAD

**Issue by mehmetyldz87** [cleanflight/cleanflight#1102]
Dear Hydra, 

Could you add Kinematic Values [Roll , Pitch, Yaw (deg )] into Sensor Section.

**Comment by mehmetyldz87** [comment]
It will be useful for understand the board directions and also for test bench PID tunning

**Comment by jaapp** [comment]
You should look into the Blackbox features. Much more useful.

**Comment by mehmetyldz87** [comment]
Dear jaap,

Also we can use logging section , but Angle can be seen simultaneously

**Comment by jaapp** [comment]
I know these values are already available via MSP, which tools like EZ-GUI Ground Station can pick up an display.

**Comment by mehmetyldz87** [comment]
I am trying to obtain step response of my system on a test bench , so I apply some test and logged data, before star the test I want to measure the angle via GUI .

**Comment by thenickdude** [comment]
@mehmetyldz87 if you use Blackbox to record your test data, it will give you angle information from the IMU simultaneously (use the `--simulate-imu` command-line option to `blackbox_decode`)
