### ISSUE TITLE
Remove MSP telemetry.

### ISSUE THREAD

**Issue by hydra** [cleanflight/cleanflight#1106]
Does anyone use MSP telemetry?  I've a feeling no-one does.  I also feel that LTM #1010 would be better instead.

Considering removing it for 1.11.

**Comment by digitalentity** [comment]
I second this, LTM and/or MAVLink are better options for telemetry. MAVLink protocol has two-way support, LTM is usable at very low bitrates.

**Comment by Arakon** [comment]
I think quite a few people use mwosd with cleanflight, and I believe that does use msp?

**Comment by misakm** [comment]
I use mwosd but not sure about communication protocol.

**Comment by digitalentity** [comment]
@Arakon MSP protocol is not going anywhere. mwosd is using polling (bi-directional communication) to get required data from flight controller. MSP telemetry is uni-directional stream of data - probably not used by anybody. mwosd users should be fine if MSP telemetry is removed.

**Comment by Arakon** [comment]
Ah, great.

**Comment by sppnk** [comment]
I think many of the multiwii pilots, using mwosd are swapping the osd modules bettween models, as they are compatible with CF. 

I use the android EZIO apk to comunicate with the plane, (with BT or using openlrsng receiver). I dont know if mavlink is better, but AFAIK, MSP is an interesting protocol that is not dead.

**Comment by digitalentity** [comment]
Nobody is going to remove msp protocol, this issue is about removing msp
telemetry that is never used even by OSDs - they use polling.

**Comment by tracernz** [comment]
I'm pretty certain MWOSD can listen to MSP telemetry as I have used it in the past... In fact it definitely can https://github.com/ShikOfTheRa/scarab-osd/blob/master/MW_OSD/Serial.ino#L721

**Comment by Boomer91** [comment]
I'm using the unidirectional MSP telemetry to drive arduino based ledstrip animations using speed etc. What alternatives can I use if this would be deleted?

**Comment by thenickdude** [comment]
Bidirectional MSP.
