### ISSUE TITLE
Failsafe - Support RX's that can't stop sending signal

### ISSUE THREAD

**Issue by akomic** [cleanflight/cleanflight#112]
There are RC receivers that can't be configured not to send signal at all when connection with RC TX is lost, such as RangeLink LRS. Solution for this could be to treat FC failsafe as yet another flightmode and make it possible to trigger it with one of the AUX channels. This way RC RX failsafe can be set to trigger FC failsafe.

This could also be used for some sort of induced controlled crash-landing in case of emergency with a flip of the switch.

**Comment by Philippe-France** [comment]
Hi

I'm using a FUTABA R2004GF receiver (4ch, 2.4GHz FHSS), very basic receiver, with NAZE32 powered as usual with 5V from one of the ESC on a quadX.
When TX signal is lost, all 4 channels are frozen to 3V, then no PWM anymore.
With current cleanflight code (1.3.0 28dec2014) TX signal loss is not detected (failsafe feature enabled).
I don't know if this 3V freeze is a standard behavior of (low cost) receiver, may be you know ?
At the end this make me very nervous to start flying.

So my request would be to detect such 3V freeze as a RC TX signal loss.

By the way, any workaround with current cleanflight code would be appreciated.

Thank & congratulation for this huge job
Phil

**Comment by hydra** [comment]
This is done.
