### ISSUE TITLE
Target - Add support for Crazepony mini small four-axis with integrated radio receiver.

### ISSUE THREAD

**Issue by yuan0226** [cleanflight/cleanflight#1121]
Hi
I would like to migrate to Crazepony cleanflight mini small four-axis, crazepony hardware architecture and CJMCU like, the main chip using 36-pin stm32f103t8u6, attitude sensor MPU6050 I2C interface barometer MS5611 I2C interface, communication module chip NRF24l01 SPI interfaces, cleanflight such a good firmware should run for more flight control. Hope experts can give pointers, thank you.

**Comment by JohnieBraaf** [comment]
Seems pretty much identical to CJMCU hardware, sharing the schematics would be a first step I guess.

**Comment by yuan0226** [comment]
![_001](https://cloud.githubusercontent.com/assets/12129401/8768636/61d5a846-2eba-11e5-8f4f-181f7bb86a71.jpg)
![_002](https://cloud.githubusercontent.com/assets/12129401/8768638/67c6ff52-2eba-11e5-85e9-4e33334406dd.jpg)

**Comment by JohnieBraaf** [comment]
Pretty nice that is has an integrated Bluetooth module

**Comment by yuan0226** [comment]
First, thank you for the compliment. Piece Bluetooth chip is used in conjunction with mobile communications, it is available through Android phones APP control flight control. But our flight control code that is not very good, not very stable flight, and can not be completed at the stunts.

**Comment by hydra** [comment]
@yuan0226 Hi

Can you provide the developers with sample hardware?

Do you have links to the product so that people can buy the boards?

Are they in production right now?

If yes to all then yes, adding support should be possible.  It seems like a nice platform for developers to test indoors.

Do all the the processors in the boards have 128K or 64K?

**Comment by goebish** [comment]
https://github.com/goebish/cleanflight/tree/crazepony
https://github.com/cleanflight/cleanflight/compare/master...goebish:crazepony

**Comment by chr0n1x** [comment]
@goebish this is AWESOME. Thank you!

Were you planning on opening a PR anytime soon?

**Comment by goebish** [comment]
Yes, meanwhile you can build it from sources or follow instructions in the rcg thread.
