### ISSUE TITLE
Feature: Ability to reverse channel direction in cleanflight

### ISSUE THREAD

**Issue by 11digits** [cleanflight/cleanflight#1132]
A simple CLI command would be ok for starters, so we can invert the direction of the channels - there are many rx - tx out there than can't do that.

**Comment by JohnieBraaf** [comment]
Why would you need it. For RSSI there is already an CLI command to do so: https://github.com/cleanflight/cleanflight/pull/816

**Comment by 11digits** [comment]
1. I don't have RSSI
2. As stated, there are many TX-RX out there that are not configurable (channel direction)

**Comment by Arakon** [comment]
Those "many" wouldn't happen to be 20$ toy transmitters?
Even the most basic RTF transmitters I've seen from many years ago had a channel inversion switch, either in software or a physical switch.

**Comment by iforce2d** [comment]
I second this, and would also love to be able to trim the rc values. For example, suppose your pitch channel is reading 1485 with the stick centered - you could just add 15 to trim it to 1500.

I don't know about toy transmitters, but all my TXs so far are arduino based with no fancy features like trims or channel fiddling options. It would be much easier to change things in the Cleanflight config than to recompile and upload my arduino sketch just to trim the channels. OpenPilot config has these settings (and also endpoints) which makes setup easy for us 'toy' users.

**Comment by borisbstyle** [comment]
@iforce2d 
FC should not be responsible for correcting the trims from the TX. I know about openpilot having that tx wizzard. Could be a nice feature indeed to add in configurator in rx tab something like calibrate tx.

**Comment by hydra** [comment]
latest code already has rxrange, i just tested removing the check for min being lowerthan max and used `rxrange 3 2000 1000` and the throttle channel could be reversed.

**Comment by hydra** [comment]
The great thing here is that code was deleted to add this feature :smile:

**Comment by digitalentity** [comment]
@hydra it's funny that I've devised exactly the same solution, but didn't have a chance to post a PR :smile:
