### ISSUE TITLE
CLI doc for yaw_jump_prevention_limit

### ISSUE THREAD

**Issue by NicoLoco** [cleanflight/cleanflight#1133]
The CLI doc states the following values for yaw_jump_prevention_limit:
Min 200
Max 80
Default 500

it should be
Min 80
Max 500
Default 200

**Comment by borisbstyle** [comment]
Good find. I believe this was my fault :D

**Comment by borisbstyle** [comment]
https://github.com/cleanflight/cleanflight/pull/1134
