### ISSUE TITLE
Another beep issue, two medium, one short repeating

### ISSUE THREAD

**Issue by ggarman** [cleanflight/cleanflight#1135]
Hydra, anyone, what does 2 medium and one short repeating beeps mean?  It still arms and flies fine, beeping the whole time.

I have a Naze32 with Vbat connected and Telemetry connected to a D8RII-plus.  I've recently connected up telemetry so I disconnected the telemetry cable and un-ticked Telemetry in the GUI, it stopped the beeps for one battery then the beeps started again on the next battery.
 
Thanks!

**Comment by stronnag** [comment]
This is a support question, not an issue (bug). Please close the issue and ask for support on RC Groups or #cleanflight. Thanks.
