### ISSUE TITLE
OLED - Improve communication to avoid looptime fluctuations.

### ISSUE THREAD

**Issue by alvins82** [cleanflight/cleanflight#1136]
Not a big issue but was testing motors using motor tab and with OLED connected to my naze32 - everytime the OLED changes screen the motor stutters. Latest 1.9.0 release version.

Attached a video to show problem - https://youtu.be/QTql6PQvVqk

**Comment by JohnieBraaf** [comment]
I think previously the OLED could only work when not armed because it would use to much resources.

**Comment by alvins82** [comment]
Got it. It wasn't armed since I was using the motors tab. Can close if this is normal behaviour.

**Comment by hydra** [comment]
yes, it's normal behavior.  We need to improve the OLED communication code, I will change the title of the issue to reflect this.
