### ISSUE TITLE
Tricopter on CC3D servo doesn't work

### ISSUE THREAD

**Issue by copterino** [cleanflight/cleanflight#1139]
I saved configuration of Tricopter, connected servo on output 4 (Yaw). Mode RX_PPM.
After powering on servo goes 100% right and stalls in this position.
Also, it cannot be controlled from GUI.

**Comment by SteveAmor** [comment]
@copterino I suspect you are not connecting the servo to the correct output.  Please check the documentation for the correct connections: eg: http://www.rcgroups.com/forums/showthread.php?t=2233116

The GUI will not currently allow you to save the servo settings.  This is a known issue #991 

If this solves your (support) issue and is not actually a new bug, please can you close this issue.
