### ISSUE TITLE
pid_controller =2 causes highly unstable self levelling behaviour

### ISSUE THREAD

**Issue by stronnag** [cleanflight/cleanflight#114]
In self levelling modes (tested with horizon), using pid_controller=2 causes undesirable self-levelling behaviour. With default pitch/roll rate, self level after a loop or roll results in sloppy oscillations, usually recoverable. With pitch/roll = 0.7 (nice setting for crisp loops/rolls in horizon with pid_controller=0), after an attempted loop or roll, the vehicle enters extremely violent oscillations (+/- 45°), from which in the reporter's experience, you will not recover, and a high impact crash is inevitable.
 
The behaviour of pid_controller=2 in 'level' flight is excellent (i.e. not pushing the horizon/rate boundary).

**Comment by nebbian** [comment]
I'm actively looking at this issue now, have had some good flight tests today.  My solution involves an extra term to select how much of the stick's travel has levelling enabled.  The algorithm is very similar to rc911's 'stick mixing' solution on the kk2.

Airmanaf, note that the level p term is the angle mode levelling strength, while the level i term is the horizon levelling strength.  Bump up your level I term to make horizon mode more stable.

**Comment by nebbian** [comment]
Other issues with pid_controller 2 include not being able to do a full roll if your rates are low, as well as levelling out with a half roll instead of a half flip if the craft started with a half flip.  Both these issues are sorted out in my new code.

**Comment by hydra** [comment]
just caught your post on RCG - awesome, looking forwards to the PR!  Do you have a link to any relevant commits in your codebase I could see in the meantime?

**Comment by nebbian** [comment]
Heya Hydra, 
Yep you can have a look at this: https://github.com/nebbian/cleanflight/commit/1beb17913cd026fd7951756c65db2e9ceb52a779

Note that the unstable leveling behavior is still present, although the issues when flipping are now resolved.  I've got a plan with regard to the unstable levelling, watch this space.

**Comment by hydra** [comment]
is it possible for you to do one small PR to fix the flipping and then another one for the unstable leveling?

**Comment by nebbian** [comment]
I'll see if I can separate them, but they are related.

Flight testing:  https://www.youtube.com/watch?v=C_vZDNst6pM

**Comment by hydra** [comment]
nice demo, great stuff!

**Comment by stronnag** [comment]
Great demo. The final pre-fixed effort was so familiar, only I didn't catch it before the ground did! Looking forward to this one.

**Comment by nebbian** [comment]
I have a hex file ready for beta testing if anyone is interested in this.  

@stronnag I'd be interested in seeing if this helps with your issues.  I haven't been able to reliably replicate the wobbling issue with my setup, it has appeared once or twice.  I'd be very keen to hear your thoughts.

**Comment by stronnag** [comment]
@nebbian, I cloned your repo and build a binary. I'll fly it as soon as the weather permits (may be a while)

**Comment by stronnag** [comment]
@nebbian. Flew your repo build today, with pid_controller=2 and its standard PIDs (reduced P, increased I,D). Superb. No wobbles, slickest self-levelling ever. Smooth flips and rolls.

@hydra. Hope this can make it into master.

**Comment by nebbian** [comment]
I've tested this a lot more, it works really well.  Even had a couple of others try it out on the weekend, they all liked it, including one friend who had never done a roll before... he was doing double flips within a minute of taking the controls.

Pull request https://github.com/cleanflight/cleanflight/pull/351 created.

**Comment by hydra** [comment]
#351 is merged. Closing.
