### ISSUE TITLE
New servo settings (smix) not persistent across all profiles

### ISSUE THREAD

**Issue by stronnag** [cleanflight/cleanflight#1140]
The new tri yaw configuration `smix reverse 5 2 r` appears not to be persistent across profile changes, leading to unexpected violent rotation on take off and potential aircraft damage.

0. Have profile 0 and profile 1 identical other than some trivial PID settings.
1. Power on with profile 0 and reversed yaw (assumed now to be global, from `smix reverse` rather than per profile as previous `servo` stanza). Fly around a bit. 
2. Land, use the stick command to switch to profile 1.
3. Attempt to take off again. Despair as the craft rotates uncontrollably.

It would appear that the new 'global' servo settings are not persistent across profile switches. This is sub-optimal. The new  `smix` setting should be consistent across all profiles, as they are now global.

**Comment by stronnag** [comment]
Even if one powers on in profile != 0, one ends up in landing gear destroying rotational hell, alas.

**Comment by ethomas997** [comment]
@hydra This issue still exists with the current master as of 8/3/2015 (I just tested it).  Definite bug that needs to be fixed.

--ET

**Comment by hydra** [comment]
Agreed, will look into this

@stronnag thanks once again for excellent testing feedback and bug reporting - much appreciated - I owe you a beer at some point.

**Comment by sppnk** [comment]
When trying to reverse servos in custom airplane I get "parse error":

smix reverse 4 2 r
smix reverse 4 2 r
Parse error

May be because of PR #1283 Not sure
