### ISSUE TITLE
Flip32 test motor fail

### ISSUE THREAD

**Issue by madiron** [cleanflight/cleanflight#1146]
Hi, 

I flash my Flip32 with cleanflight. When go to Test Motor and start test the motors run all at the same speed when I moving the quadcopter.. it's normal?

**Comment by joshuabardwell** [comment]
The Motors tab causes a fixed output signal to be sent to the motors. They should all spin at the same speed. It's normal.

**Comment by madiron** [comment]
Thank's for response.. :)

in this video https://www.youtube.com/watch?v=J_NvkHAkyOw change spin when quad is moved.. why?

**Comment by joshuabardwell** [comment]
Because he's spinning up his motors by arming the quad. You're spinning up the motors using the "test" sliders on the Motors tab.

**Comment by madiron** [comment]
OK, Thanks Joshua ;)

**Comment by SteveAmor** [comment]
@madiron as this isn't a bug, can you please close this issue.
