### ISSUE TITLE
quadcopter graphics 

### ISSUE THREAD

**Issue by MichaelStanley34** [cleanflight/cleanflight#1148]
The quadcopter graphic that simulates the movement of the control board has turned from a quadcopter to a box with 'front' 'side' etc labels on each side of the box?

**Comment by JohnOCFII** [comment]
That is usually due to an installation error of the Cleanflight Configurator software.  The configurator can not find the image file data.  I'd recommend a re-installation of the Cleanflight Configurator.

**Comment by MichaelStanley34** [comment]
thanks

**Comment by joshuabardwell** [comment]
Also, if you are using a custom mixer.

**Comment by SteveAmor** [comment]
@MichaelStanley34 if a reinstall solves your problem, please close this issue.  If there is a bug, please raise as an issue under github.com/cleanflight/configurator
Thanks.

**Comment by MichaelStanley34** [comment]
Not sure if I understand a custom mixer?

**Comment by joshuabardwell** [comment]
https://github.com/cleanflight/cleanflight/blob/master/docs/Mixer.md#custom-motor-mixing

**Comment by MichaelStanley34** [comment]
reinstalled -all okay.

**Comment by SteveAmor** [comment]
@MichaelStanley34 that's great news.  Please can you close this issue.

**Comment by MichaelStanley34** [comment]
Can't work out how to close issue?

On 21 Jul 2015 2:58 pm, Steveis <notifications@github.com> wrote:

@MichaelStanley34<https://github.com/MichaelStanley34> that's great news. Please can you close this issue.
