### ISSUE TITLE
Cleanflight support the throttle back in the remote control?

### ISSUE THREAD

**Issue by yuan0226** [cleanflight/cleanflight#1154]
Hi
I would like to know whether the code Cleanflight support the throttle back in the remote control, so set high hover? What still needs to be configured? Thank you for your answer.

**Comment by yuan0226** [comment]
I was just wondering whether to support the throttle back in Cleanflight remote control, how is it so hard?

**Comment by digitalentity** [comment]
What's "throttle back in the remote control" ?

**Comment by yuan0226** [comment]
Throttle return the remote control.

**Comment by yuan0226** [comment]
油门回中的遥控

**Comment by yuan0226** [comment]
The throttle stick remote control can automatically reset to the middle position.

**Comment by joshuabardwell** [comment]
You mean spring loaded throttle, like a DJI controller?

**Comment by yuan0226** [comment]
Yes, as a novice, will be better adapted to the kind of remote control,cleanflight support that kind of remote control it?

**Comment by thenickdude** [comment]
Yes, this is basically what the "BARO" altitude hold flight mode does. It requires a barometer to be present.

**Comment by yuan0226** [comment]
What does this mean?It is the only barometer and set BARO mode together with DJI's remote control can achieve the kind of effect it?

**Comment by joshuabardwell** [comment]
The throttle can automatically return to center, or not. Cleanflight doesn't care. If the throttle has a spring, then it will automatically return to center. If the throttle doesn't have a spring, you will move the stick to center with your fingers. Cleanflight doesn't care which of those things happens.

**Comment by yuan0226** [comment]
Thank you for your help.
