### ISSUE TITLE
Not getting confirm beeps on oneshot

### ISSUE THREAD

**Issue by zeroyon** [cleanflight/cleanflight#1165]
Upgraded to 1.9.0 firmware and turned on oneshot but not getting the second round of confirm beeps anymore. 

Running rotorgeeks 30amps with BLheli 13.1.

Also setup a new quad with DYS40amps BLHeli 13.2 and also don't get oneshot confirm beeps.

**Comment by joshuabardwell** [comment]
The second round of confirmation beeps was a bug. It has been fixed. If you have Oneshot enabled and your ESCs work at all, Oneshot is working. Confirmation beeps are not needed.

**Comment by zeroyon** [comment]
Thanks for the reply Josh. Really helpful. :)

**Comment by joshuabardwell** [comment]
No problem!
