### ISSUE TITLE
port configuration won't save 

### ISSUE THREAD

**Issue by seniorcandy** [cleanflight/cleanflight#1170]
![qq 20150729145307](https://cloud.githubusercontent.com/assets/11422477/8951606/aaa10446-3601-11e5-9332-9dbf34a74f8c.jpg)
i clicked save and reboot, and then ,it said "closed"!
![qq 20150729145325](https://cloud.githubusercontent.com/assets/11422477/8951623/d6f50394-3601-11e5-9c06-2152ed2332e1.jpg)
when i connect again, nothing is saved

**Comment by SteveAmor** [comment]
Which board, version of CF and configurator?

**Comment by henn1001** [comment]
There always needs to be one Port with MSP.. why did you deactivate it? How do you expect to communicate with your board again if it would safe these settings?

**Comment by borisbstyle** [comment]
you need MSP indeed
