### ISSUE TITLE
problems about constraints when set up sonar on cc3d

### ISSUE THREAD

**Issue by seniorcandy** [cleanflight/cleanflight#1174]
1.Sonar support is not available when using the OpenPilot bootloader (OPBL).
    then what bootloader should i use?
2Sonar cannot be used in conjuction with SoftSerial or Parallel PWM.
    does SoftSerial  include dsm2 or dsmx ?

**Comment by xqoperator** [comment]
rebuild from source without OPBL and flash using native method (jumper + serial on main port)
