### ISSUE TITLE
Receiver Failsafe enabled but displayed as disabled

### ISSUE THREAD

**Issue by Walkeer** [cleanflight/cleanflight#1175]
Cleanfligt 1.9.0 naze32: all in defaults, SBUS receiver (FrSky). Receiver Failsafe disabled in GUI, but when I apply small throttle on my taranis Tx and then shut down the Tx, motors spins up to cca 1500 and quad takes off, stablized and continues to fly indefinitely (for sure more than 10s). When I enabled the feature and set throttle to 1000, all is as expected. Taranis set to send no commands when reception is lost and it was working ok in 1.8.1.

**Comment by borisbstyle** [comment]
This is already being covered in 1.10.0
https://github.com/cleanflight/cleanflight/issues/1184
https://github.com/cleanflight/cleanflight/pull/1190

**Comment by hydra** [comment]
closing, duplicate.
