### ISSUE TITLE
why the attitude is -1 when i use sonar on cc3d

### ISSUE THREAD

**Issue by seniorcandy** [cleanflight/cleanflight#1177]
![qq 20150803214806](https://cloud.githubusercontent.com/assets/11422477/9038784/98661fb0-3a29-11e5-97f7-c5cca559f2ba.jpg)

**Comment by seniorcandy** [comment]
i am sure the vcc, gnd, trig and echo have been connected correctly,
and i have tried 5v and 3.3v with vcc, but it doesn't work.

**Comment by seniorcandy** [comment]
then i connect a oscilloscope to trig and echo, but i can't see any pulse signal

**Comment by xqoperator** [comment]
Mine works like that:
trg - PB5 (pin 4 @ RCInput) blue
ech - PB0 (pin 5 @ RCInput) yellow
this is US-015 labeled sonar

**Comment by seniorcandy** [comment]
i have already found it out!
i try to power the hc-rs04 with 5v ,  and it work~~!!!!!!!!!!
but the doc says it should be 3.3v    : (
