### ISSUE TITLE
OSD(UART1) + BT (SoftSerial1) issue

### ISSUE THREAD

**Issue by BarendDS** [cleanflight/cleanflight#1187]
Hi,

I have a strange problem, 

FC = Flip32+0
I have the BT on softserial1(19200) and the OSD on UART1(115200).
I also use a D4RII on CPPM
OSD = Micro MinimOSD with MWOSD R1.4.1

BT,OSD and FC work fine for a minute or so. Then my Flip32 starts rebooting and my calibration sound of my SimonK ESC's starts beeping.

BT without OSD connected works fine.

When BT and OSD are both connected (connection to CF with BT not even initialized) the problem appears.

*Update*

I just did some more testing an the problem starts when I turn on my taranis. OSD and BT work when the TX is not on.

 BT works when TX on and OSD is not connected. 

Here's a video of the issue => https://youtu.be/glE9zaz7HOM

Anyone knows what might be the problem?

Tx in advance for the help.

Barend

**Comment by BarendDS** [comment]
Well I hadn't calibrated my mag meter, I did so now and the issue seems solved, could this have caused the issue?

Tx in advance

**Comment by leothehuman** [comment]
Please, close the issue. No relation to cleanflight at all.
