### ISSUE TITLE
Documentation - Add STM32F3Discovery pinouts

### ISSUE THREAD

**Issue by Felixrising** [cleanflight/cleanflight#12]
TauLabs FlyingF3 has these pinouts.. what are the pinouts for Baseflight 2 - Second Base?

e.g. https://github.com/lilvinz/OpenPilot/wiki/Discovery-F3-pin-assignment

**Comment by hydra** [comment]
What we need a PR for `Board - STM32F3Discovery.md` to document currently used pinouts.

**Comment by Davidsg33k** [comment]
I have the discovery boards, both F4 and F3 - *Running 1.12.0 CF"  "Thank You Hydra!!  for your work, I would like offer my time and service to help map these pins. So far have not seen a good pin map made so far unless you can list the current pin-out information link that would help.

also Let me know what i can do to help. thank you.

**Comment by Davidsg33k** [comment]
https://github.com/lilvinz/OpenPilot/wiki/Discovery-F3-pin-assignment
