### ISSUE TITLE
Flash CF on CC3D ... noway !!

### ISSUE THREAD

**Issue by mcd35** [cleanflight/cleanflight#1209]
Sorry, but still cannot flash , always same 
"Serial port successfully opened with ID: 19
2015-08-15 @ 11:23:43 -- No configuration received within 10 seconds, communication failed
2015-08-15 @ 11:23:43 -- Serial port successfully closed "

i load CPdriver, window find my CC3D as Coptercontrol, so Driver look ok,

![image](https://cloud.githubusercontent.com/assets/13808133/9288341/18201f96-4342-11e5-9eed-252ebff509b2.png)

COM 6 appear when i plug usb; so look fine also
![image](https://cloud.githubusercontent.com/assets/13808133/9288339/08c62f36-4342-11e5-8568-2fa5c03d9210.png)

then choose CC3D hex files/ or online

![image](https://cloud.githubusercontent.com/assets/13808133/9288342/2235e51a-4342-11e5-8a05-44675b0f3a43.png)

but cannot flash, because cannot connect card !!

2015-08-15 @ 11:31:30 -- Failed to open serial port

Tkanks for support!

**Comment by stronnag** [comment]
Strange, always works for me, using the main port and an FTDI (/dev/ttyUSB0), either with the configurator or more conveniently a script, both on full CC3D and Atom boards. 
````
#!/bin/bash
DEV=${1:-/dev/ttyUSB0}
SPEED=${2:-115200}

stty -F $DEV raw speed $SPEED -crtscts cs8 -parenb -cstopb -ixon
echo -n 'R' >$DEV
stm32flash -w obj/cleanflight_CC3D.hex -v -g 0x0 -b $SPEED $DEV
```
Maybe it's a windows thing.

**Comment by Arakon** [comment]
You can't flash a new hex via USB. The USB port is a virtual one that requires a software to run first, but the software can not run since you are trying to overwrite it. If you use an USB TTL convertert like the CP2102 or FTDI, you can flash easily using the main port.

**Comment by fftunes** [comment]
You need to have the CC3D powered with a receiver pack or BEC.
Without FTDI-adapter etc. as mentioned above you can only flash *.BIN-files via Openpilot bootloader.

**Comment by hydra** [comment]
closing - use forums or IRC for support.  If there improvements that can be made to the manual please submit a PR.
