### ISSUE TITLE
Previous version archive

### ISSUE THREAD

**Issue by Hwurzburg** [cleanflight/cleanflight#122]
Please create and maintain an old version repository, such as OpenLRS does, to allow using older versions of the Chrome Config and firmware for those who do not want the forced update...which often requires extensive re-setup if being used on multiple targets...
updates should be ELECTIVE not forced in any case, but if forced, at least allow users to choose to load the older config for continued use with existing platforms with older firmware

thanks!

**Comment by kelleysislander** [comment]
Dumb question maybe, but how does one install it after downloading?  Is there an exe in the archive?  Thanks ;)

**Comment by mikeller** [comment]
@kelleysislander: By using the 'Flash Firmware' tab in the cleanflight configurator.
