### ISSUE TITLE
Failsafe doesn't work on CC3D with  ppm encoder 

### ISSUE THREAD

**Issue by bk79** [cleanflight/cleanflight#1225]
I'm using CC3D with PPM sum encoder connected to pin 3, whenever I switch off the throttle goes to 850us immediately but the rest of the channel will keep on staying up at 1500us, Motors  stay at idle all the time without reaching failsafe and without deactivating

**Comment by thenickdude** [comment]
What is your `failsafe_throttle`, `failsafe_delay`, `failsafe_off_delay` and `rx_min_usec` set to?

**Comment by bk79** [comment]
Default settings

Il giorno 10:32 mar 18/ago/2015 Nicholas Sherlock <notifications@github.com>
ha scritto:

**Comment by stronnag** [comment]
cc3d + PPM failsafe works fine for me. Sure you have feature FAILSAFE enabled?

```
feature FAILSAFE

set failsafe_delay = 10
set failsafe_off_delay = 10
set failsafe_throttle = 1200
set rx_min_usec = 998  # fugly Orange R615x
set rx_max_usec = 2115
````

**Comment by bk79** [comment]
Sure it is but as explained I'm using a ppm encoder probably keeps by
itself all the channels except 3rd to 1500us

Il giorno 18:23 mar 18/ago/2015 stronnag <notifications@github.com> ha
scritto:

**Comment by bk79** [comment]
just a small update I've tried using a fs-ia6b with ppm sum the result is the same output is fronzen to the last value, that's the reason why it doesn't deactivate just for your information I'm using digitalentity fork but the code related to the failsafe is not affected

**Comment by bk79** [comment]
Probably I've figured out: Failsafe works if I disconnect fisically the cable from the PPM encoder, but if the ppm encoder is connected it doesn't clean all the channel and keeps up the helicopter as if the radio is still on

**Comment by bk79** [comment]
I think I've found the fix just setting rx_min_usec to something more than 900 that is the failsafe setting the ppm_encoder send in case of tx loss. putting 920 makes the trick
