### ISSUE TITLE
Should add a gyro & acc self test feature

### ISSUE THREAD

**Issue by Ozzy33** [cleanflight/cleanflight#1226]
Should add a gyro & acc self test feature that is built into the 6050, a simple check box for each, displaying the test value and the acceptable limits (+/-14%).

See page 27 here:
http://store.invensense.com/datashee...eet_V3%204.pdf

**Comment by jaapp** [comment]
Something went wrong with that link.

**Comment by Ozzy33** [comment]
Sorry, I was directed to post here and should of been been in the CFC thread, please close.

**Comment by thenickdude** [comment]
If it can perform a self test, then that's probably something that Cleanflight should be doing on every powerup (and refusing to fly) rather than in the Configurator.
