### ISSUE TITLE
Create Make target to debug cleanflight in qemu 

### ISSUE THREAD

**Issue by Echelon9** [cleanflight/cleanflight#1234]
This will probably looks similar to the below:

```
$ qemu-system-arm -cpu cortex-m3 -nographic -monitor null -serial null -semihosting -kernel $(TARGET_ELF) -gdb tcp::51234 -S
$ arm-none-eabi-gdb $(TARGET_ELF)
   (gdb) target remote localhost:51234
   (gdb) load
   (gdb) break main
   (gdb) continue
```

For maximum flexibility, i.e. without a specific attached ARM board, the `-semihosting` option could be dropped.

We may want to run unit tests via the semihosting interface. cf `--semihosting-config enable=on,target=native` and  `--semihosting-cmdline`

**Comment by hydra** [comment]
yes please, PR with developer setup guide wanted!

**Comment by Echelon9** [comment]
Great, I'll get cracking on this.

**Comment by Echelon9** [comment]
At present this is going to hard to support without out-of-tree qemu patches (e.g. https://beckus.github.io/qemu_stm32/). Pleasingly, there is ongoing activity on the qemu mailing list regarding Cortex-M3 cpu family support.

I am not currently aware of STM32 support in mainline qemu, or for the other boards cleanflight yet supports. And certainly not configured in Ubuntu's default packaged `qemu-system-arm`

**Comment by Echelon9** [comment]
Whilst I haven't yet made as much progress as I'd like, there's another interesting fork of QEMU customised for more support of Cortex-M cores (http://gnuarmeclipse.github.io/qemu/).
