### ISSUE TITLE
RX.md : RX loss configuration is confusing

### ISSUE THREAD

**Issue by NicoLoco** [cleanflight/cleanflight#1238]
The description of this feature is ambiguous:

>>The rxfail command takes 2 or 3 arguments.
>>Index of aux channel (AUX1 = 0, AUX2 = 1,...)"

which indicates that first channel is AUX1

and then 
>>Channels are always specified in the same order, regardless of your channel mapping.
>>Roll is 0
>>(...)
>>Aux channels are 4 onwards."

which indicates that first channel is Roll

**Comment by hydra** [comment]
Ahh yup, needs a correction.  I updated the docs but missed that bit.  Thanks for the heads up.
