### ISSUE TITLE
MSP Telemetry

### ISSUE THREAD

**Issue by snakescb** [cleanflight/cleanflight#1240]
Hi,

I am currently developing a tiny module with an stm32F303 which should serve as an universal telemetry interface receiving MSP or Mavlink messages, parses them and is sending them down via Jeti, Futaba, Frsky, Hott or Multiplex links. I have working prototypes on my desk which work well with Jeti and Cleanflight at the moment, the other protocols will be implemented later. I can provide schematics if requested and will upload the code to GitHub if there is an interest.

I was planning to use the cleanflight MSP telemetry feature to receive the data from the fc, but as I can see in the message list, there are no analog messages sent. So using this, no battery voltage, current or capacity information is available with msp telemetry. This for me would be the most important information when using a telemetry downlink.

Is it possible to add this message to msp telemetry by default for the next release? Or even make the messages which are sent configurable?

Regards
Christian

**Comment by henn1001** [comment]
See #1106

**Comment by hydra** [comment]
No, MSP telemetry is being deleted.  See #1106.

Yes, would love to see the code.  Adding support for widely used telemetry protocols into the core of cleanflight would be great.
