### ISSUE TITLE
Self leveling in inverted flight

### ISSUE THREAD

**Issue by xoga74** [cleanflight/cleanflight#1260]
Hello,

beeing new in 3D setup of cleanflight, i managed to flash my ESC's with BLheli 14.0 and am getting the setup using this explanation from issue 1302 : https://github.com/cleanflight/cleanflight/issues/1032

Since i started RC with planes, i'm not used to fly in rate mode and so i like the use of Horizon mode wich gives me the same feel as with planes, stick in the center, everything becomes level and safe again.  But when testing the 3D setup i hoped that when i made à roll from upside to inverted and switching the throttle from high to low, the quad would go in self leveling inverted, but it didn't, it still tries to level upside, with the result the earth is coming verry fast once it's rolled back to the upside leveling ...  

Someone can explain what i am doing wrong ?

Thanks,
Nicolas

**Comment by joshuabardwell** [comment]
I reckon the auto-level code isn't set up to compensate for 3D situations. Very few people fly 3D, and the ones that do, basically all fly rate mode. So I think you've found a bug!

**Comment by hydra** [comment]
Yes, the code for 3D flight needs improvement.

**Comment by xoga74** [comment]
Hello Hydra, saw you made some improvements on  last realease for 3D, did you manage to correct this bug with the new release ?
