### ISSUE TITLE
how can i do RTH on Failsafe RX Loss range?

### ISSUE THREAD

**Issue by ghostsharp** [cleanflight/cleanflight#1264]
This weekend i lost the signal and quad fall with failsafe and broke 1 arm. For prevent crash again by lost signal i putted GPS for RTH but i cant found how to activate RTH with Failsafe.

I tried to use rxfail but appear unknown command.

Thanks.

**Comment by hydra** [comment]
Duplicate, see #852

**Comment by hydra** [comment]
(It's coming, first things first)
