### ISSUE TITLE
Rate Profile Inflight Adj. And Saving Values

### ISSUE THREAD

**Issue by kitekid99** [cleanflight/cleanflight#1277]
I filed an issue back in the beginning of April 2015 regarding rate profile 1 and 2 overriding each others values for their respective rate profiles. For example, when in rate profile 1, I would set the RC Rate at 0 and Yaw Rate at .50. Then when I switched to rate profile 2, RC Rate would be set at 0 and Yaw Rate would be set to .50, but I had never moved them from the defaults under rate profile 2. I found the same to be true when working the opposite way. With RC Rate at 0  and Yaw Rate already at .50, and rate profile 2 selected, I would change RC Rate back to the default of .90 and Yaw Rate back to the default of 0. Then, unfortunately, when switching back to rate profile 1, the respective values had changed to match rate profile 2, but I never modified those values under rate profile 1 except for the very beginning. I know I had saved all my values and refreshed when needed, so I knew the problem was somewhere in the firmware because I could get the same issue to arise when using the CLI and not just the GUI. Well during that whole time, I had the rate profile inflight adjustment enabled. But remember, only 1 and 2 were sharing the values, 3 stood completely alone. Also, this was on 1.8.1.

Anyway, I was working with 1.8.1 again today, but this time the rate profile inflight adjustment was disabled. Lo and behold, rate profiles 1 and 2 were completely separate like they were supposed to be. I could change the yaw rate in 1 to .50 and the yaw rate in 2 to .60 and the values would stay the same with their respective profiles as I had set it up. So, I tested my theory. I enabled the rate profile inflight adjustment, and BAM, rate profiles 1 and 2 were acting up again. They were exhibiting the same weird behavior as back in April. I disabled the rate profile inflight adjustment, and rate profiles 1, 2, and 3 all worked like they would be expected to work with separate values for each.

I just wanted to bring this to the attention of the developers and others who know how to fix this issue because I do not. I do not know if this issue still exists in 1.9, but from some recent tuning I did on a friend's quad where I installed 1.9, I could not replicate the problem. So, the issue may be fixed, but for those of us who like 1.8.1, it is really a pain in the butt. I want to try three separate rate settings when flying, but I am unable to. I do not want to upgrade to 1.9 due to some micro oscillation corrections causing the motors to heat up too quickly. And, 1.8.1 works for me.

So, is there any way to fix this issue on a 1.8.1 modified version where I could have all three rate profiles separate under that inflight adjustment enabled? Please ask if you have any questions.

Thanks,
Andrew

**Comment by hydra** [comment]
rate profiles are profiles are independent.
