### ISSUE TITLE
Blackbox rewrite/erase old logging

### ISSUE THREAD

**Issue by borisbstyle** [cleanflight/cleanflight#1281]
@thenickdude 
Would it be possible to always have last blackbox logs? Perhaps something configurable for onboard flash.
For example 8mb onboard would always have the latest 8mb of data and previous data will be erased.

**Comment by thenickdude** [comment]
No, this isn't possible because the flash erase rate is too slow (we need to be able to erase faster than we write, and it's way slower than that).

**Comment by borisbstyle** [comment]
I already thought something like that. I guess openlog needs to get faster than :(

**Comment by joshuabardwell** [comment]
Need an SPI Openlogger or something.

**Comment by borisbstyle** [comment]
Blackbox files seem to reduce in size when compressed with around 25%.

**Comment by ledvinap** [comment]
@borisbstyle : I use Edison for logging now - https://www.sparkfun.com/products/13040. It needs some modification (the level translator oscillates on 5V, but works on 3.3V), but then it is trivial to connect to Sparky flexi port.
It is a bit expensive, but:
- 460800 blackbox logging
- automatic upload of blackbox logs to my server (rsync)
- cleanflight configurator over WIFI

What I am missing is OTA flash upgrade, sadly flexi port has wrong serial port ...

**Comment by thenickdude** [comment]
@borisbstyle better compression takes considerably more CPU time and/or memory, so it impacts loop times. I've got a branch here which uses Elias Delta/Gammma encoding (instead of all the other byte-wise Blackbox schemes) to save several bytes per iteration, but the looptime penalty doesn't make it worth it on our current CPUs.
