### ISSUE TITLE
STM32F3Discovery sensor alignment

### ISSUE THREAD

**Issue by franzflasch** [cleanflight/cleanflight#1289]
Hi!

I've just tested cleanflight on the stm32f3 discovery and discovered that the sensor alignment of the gyro and acc is wrong. You can easily see it when using the cleanflight configurator. The accelerometer and the gyro are working against each other. 

I changed:
#define GYRO_L3GD20_ALIGN CW90_DEG
to
#define GYRO_L3GD20_ALIGN CW270_DEG
in STM32F3DISCOVERY/target.h
and it worked for me.

Regards,
Franz

**Comment by hydra** [comment]
thanks.  Will fix now.
