### ISSUE TITLE
SPARKY hang-up with master at 7fe674a57d18175bdb64b0e80aa562bf2d0011ba

### ISSUE THREAD

**Issue by ProDrone** [cleanflight/cleanflight#1304]
I uploaded commit 7fe674a57d18175bdb64b0e80aa562bf2d0011ba to a SPARKY and the board just hangs-up. Commit 786588756ef5543fcd9e5de6c4b53e41a943e800 does not have this problem, so it seems due to commit 6706abdb2ec813007bef87f5d4f93fb013a46cc5

The strange thing is that when i put some other works in progress on top of latest master at 7fe674a57d18175bdb64b0e80aa562bf2d0011ba then the SPARKY does not hang-up ????

__Can other SPARKY owners please confirm this?__ (maybe my SPARKY board is broken)

**Comment by hydra** [comment]
impossible, no production code was changed other than whitespace in 6706abd

works on my sparky boards

**Comment by ProDrone** [comment]
__You are right!__
I repeated it 5 times (switching versions) before i opened the issue. And now i cannot reproduce the error... :confused: I guess i did something consistently wrong (first time playing with SPARKY hardware).

Is it normal when using the VCP USB port that the cycle times are extremely long? Like this:

`set looptime = 0`
`cycle time to debug[0]; min. time to debug[1]; max. time to debug[3]`
![screenhunter_52](https://cloud.githubusercontent.com/assets/7206988/9825592/98058578-58d4-11e5-81e1-2f278532652d.jpg)
===

Repeated the same but using FTDI I/F to real uart port (flexi port):

![screenhunter_53](https://cloud.githubusercontent.com/assets/7206988/9825646/fb9bd646-58d4-11e5-883f-49ac792cc15b.jpg)
===

Again, using flexi port, but with `set mag_hardware = 1`:

![screenhunter_54](https://cloud.githubusercontent.com/assets/7206988/9825671/26211cdc-58d5-11e5-9142-f91de374bec8.jpg)
