### ISSUE TITLE
GPS - Incorrect nr of sats

### ISSUE THREAD

**Issue by xdigyx** [cleanflight/cleanflight#1305]
Hi,

I have connected my UBlox GPS to Flexi port. All seems to be working besides nr of sats: it shows 4, while I can see 3D fix on uCenter an 8 -11 on another FC.

**Comment by hydra** [comment]
Gonna need a lot more information than that!  Need exact details of your GPS unit, configuration dump of your GPS unit, wiring information and a dump of your cleanfliught settings.
