### ISSUE TITLE
Flight - Airplane yaw/RC input problem

### ISSUE THREAD

**Issue by xdigyx** [cleanflight/cleanflight#1306]
Hi,

I am using CC3D on my Bix Airplane. To get the yaw servo direction right I have to set reverse on my radio, but having this now arming is Yaw to the left which is often confusing me and this can cause I could crash my model.

And one bug I found: while motor is not spinning I can change yaw (servo) by RC input, but all yaw inputs seems to be not operating just when motor is spinning. Not sure what is about yaw stabilizing while model is flying (TODO).

**Comment by hydra** [comment]
Use latst 1.10.0 development version. use servo mixer, use servo reverse features.

The last thing you mention is not a bug.  It's intentional so you can check your servos.

**Comment by Pedroalbuquerque** [comment]
Hello, I'm using a Flip 32+ board with airplane configuraition and had the same problem with yaw not moving with sticks, if I have no throtle.


How can I control Yaw while landing with throtle cut ?

A see hydra saying that it is intensionla, but I could understand why, can you elaborate ?
