### ISSUE TITLE
Feature request : change profile with a 2 or 3 positions switch

### ISSUE THREAD

**Issue by johnwhite92** [cleanflight/cleanflight#1315]
Allow possibility to map a switch (aux1, aux2...) to change active profile between 0, 1, 2

Even if it's only available when quad is disarm, this feature would be great

Thanks

**Comment by dustin** [comment]
When disarmed, you can already change profiles with sticks:

    ↙←  == profile 0
    ↙↑  == profile 1
    ↙→  == profile 2

**Comment by joshuabardwell** [comment]
If memory serves, you can't change profiles when armed because you have to reload the PID controller. No mechanism exists to gracefully switch PID controllers while in flight.
