### ISSUE TITLE
bmp 180 support

### ISSUE THREAD

**Issue by handsomejackuk** [cleanflight/cleanflight#1317]
Just curious is bmp 180 barometer still supported on cleanflight,,,?

**Comment by SteveAmor** [comment]
Yes it is. Please can you close this issue (curious question)

**Comment by stronnag** [comment]
Yes is is supported (though you need a recent build for external I2C baro). Some of BMP 180 are mis-detected as MS5611 devices. This can be mitigated in the latest builds with the CLI stanza:
````
set baro_hardware = 2
````
Hydra, please close as requested by @handsomejackuk

**Comment by SteveAmor** [comment]
Fix for mis-detection in PR #1052

**Comment by SteveAmor** [comment]
@handsomejackuk if this information provides and answer to your question, can you please close this issue :)

**Comment by Tomal2v** [comment]
BMP 180 not detected on CC3D despite soldering and plugging in the battery correctly 
Help needed
