### ISSUE TITLE
Board - Naze rev6 support

### ISSUE THREAD

**Issue by hydra** [cleanflight/cleanflight#1321]
Add support for this board to Cleanflight.

BMP280 driver already done and waiting to merge.

MPU3050/6000/6050/6500/9150/9250 driver cleanup code is required as the Naze32 rev6 has a 6500 connected via i2c.

Assistance with this welcomed.

EDIT: I have deleted unrelated comments from this thread.  Please read the manual and search before commenting with configuration questions.  (e.g. sbus receiver configuration).

**Comment by borisbstyle** [comment]
I guess new target needed or you would prefer to have auto detection i2c or spi on mpu6500?

**Comment by hydra** [comment]
no new target needed, i am working on the cleanup now.

**Comment by YFZ450MANNY** [comment]
Sup fellas! To start off, I wanted to say thank u for all the hard work u guys put in to make our grown-up toys KICK ASS!! lol. The world would be a sad place without u all.. :) And then here comes the stupid question.. More or less when do u think I'll be able to use my rev6 Naze with CF? Judging by the above, I'd dare to say when CF ver 1.11 is released??

**Comment by hydra** [comment]
It's booting now.  PR with some changes to follow.

**Comment by hydra** [comment]
See #1326 

Binaries will be avilable on the build server shortly.

http://cleanflight.memoryleaks.org/builds/

**Comment by Nate0624** [comment]
Hey Gang,

I was able to flash the Rev 6 with the Hex from the nightly updates. However, the Accel doesn't appear to be working. Is it possible I jumped the gun? Can someone point me in the right direction if it is complete and ready for testing?

**Comment by jcowgar** [comment]
Flew 5-6 battery packs today on my Naze rev6 w/CleanFlight and all went just fine, no issues found. It even worked right out of the box with my Futaba SBUS, so the Inverter was enabled automatically when I selected SBUS like it should have been.

**Comment by nolimit01** [comment]
Jcowgar, where to get this CF for naze32 REV6?

**Comment by jcowgar** [comment]
@nolimit01 I do not know. I checked out from git and compiled myself.

**Comment by hydra** [comment]
@jcowgar @nolimit01 link in comment https://github.com/cleanflight/cleanflight/issues/1321#issuecomment-141692881

**Comment by RichDGD** [comment]
sorry Im a bit computer illiterate. how do i flash the above hex file to the rev6 board? i am using os x and have attempted to compile i got as far as running the arm prompt after adding bin file to my profile in nano but when entering the arm command in terminal it says command not found. is there an easier way, again i apologize if this is a stupid question. I've been driving myself crazy trying to get this board to work with cleanflight. no acc or gyro readings in gui

**Comment by jcowgar** [comment]
@RichDGD read the tutorial on compiling in OS X (https://github.com/cleanflight/cleanflight/blob/master/docs/development/Building%20in%20Mac%20OS%20X.md) or look at the links a few comments up. Hydra's comment above yours has a link to the right comment.

**Comment by nolimit01** [comment]
It's not letting me save as a hex file.

**Comment by RichDGD** [comment]
@nolimit01 I just renamed it as a hex file and now it's working perfectly

**Comment by nolimit01** [comment]
Hi RichDGD, I really need some help.

**Comment by nolimit01** [comment]
Hey Rich, where to download this file?

**Comment by Stingersswarm** [comment]
This might not be the best place to post this but I've been using the white x4r rx with the sbus hack providing an inverted sbus signal. Is there any way to turn off the rev6 serial inverter when using bus for use with the the white x4r? Since the normal sbus isn't available on it.

**Comment by nolimit01** [comment]
Got the file installed, re-setup board and the PIDS. Not so good, may have burned up a motor.

**Comment by Hoppper** [comment]
Hi!
Have problem enabling feature rx_serial
After rebooting still disabled. Other rx features works fine.

**Comment by Runfromrobots** [comment]
I have the same issue as Hoppper ^ - I can enable rx_serial, I can check "serial based receiver" all I want but every time I save or reboot it automatically turns them back off :(

**Comment by borisbstyle** [comment]
Maybe you didnt select the proper settings for rx_serial and it resets
because of that

2015-09-29 13:35 GMT+02:00 MK <notifications@github.com>:

**Comment by Runfromrobots** [comment]
@borisbstyle so, first I set serialrx_provider=2 (unless they changed the order of providers I believe this is specifically SBUS), then I enable rx_serial - I've tried putting the commands in a different order, I've tried working in the configuration tab rather than the CLI, and every time I save/reboot it deselects :(

**Comment by borisbstyle** [comment]
You need to disable PPM or PWM and than enable serial rx I believe

2015-09-29 15:11 GMT+02:00 MK <notifications@github.com>:

**Comment by JasonB91** [comment]
Having immense problems getting Spektrum Sat (DSM X or DSM 2) to bind with the new Rev6 board. Soldered sat wire direct to the top, from left to right (3.3V, Negative, Signal). 

We're seeing that when using set spektrum_sat_bind = 9, and unplug USB, and power up with 12V input, sat will not initiate bind. Upon reconnect to usb and dump performed on CLI, board defaults back to "0" instead of "9". 

http://www.rcgroups.com/forums/showpost.php?p=32813814&postcount=54

Using this firmware. ^^

At this point, totally lost and beyond frustrated. What am I missing? 

![img_0136](https://cloud.githubusercontent.com/assets/13261800/10204989/92cd6cf8-6773-11e5-8563-2584e2e7b516.JPG)

**Comment by sjtrny** [comment]
Any further progress @hydra? I received a whole stack of the rev6 but am waiting for CF support until I ship.

**Comment by hydra** [comment]
@JasonB91 no idea without testing, can someone else verify this issue please.

**Comment by hydra** [comment]
@sjtrny Still gathering feedback, 1.10.0 had higher priority.   1.10.0 bug fixes come first, then we can look at new features and board support.

**Comment by JasonB91** [comment]
@hydra I was able to bind the sat outside the Naze and CF, by binding with an AR6210. It does work with the supported Spektrum port however with the picture I provided.

**Comment by MJ666** [comment]
What happens when you reconnect via USB the second time instead of 12V. Since the port is the same as on the REV5 boards I don't see any reason why it should not work with REV6? Not sure if the timing of the bind impulses is affected by the new revision of the board? I don't have one of this yet so I can not test. Have used the binding with many different boards till today and never had issues. I even don't own an full receiver fro alternative binding and using LemonRX DSMX sats in all my copters. I have never tested an original spectrum sat.

**Comment by JasonB91** [comment]
@MJ666 We tried both with USB 5V, and direct 3s 12V power. 

http://rotorgeeks.com/index.php?route=product/product&product_id=70

Note at bottom: 

Attention Spektrum satellite users - satellite binding is not currently working with Rev 6 hardware - you must bind your satellite with separately with a receiver before connecting to the Naze board
Instruction on how to bind the satellite directly from the flight control board,   For great value and proven range, check out the Lemon Rx Spektrum compatible satellites.

**Comment by MJ666** [comment]
I may need to get one or two Rev6 boards to make it work again. It's working for so many other FC's. It's likely something very trivial.

**Comment by hydra** [comment]
driver changes and baro merged to master.

**Comment by sjtrny** [comment]
So now all future nightly builds will have experimental rev6 support?

**Comment by hydra** [comment]
yes

**Comment by FAYDID** [comment]
Hey Hydra, amazing work! Would really like to move from Baseflight to CleanFlight before my first flight on my new quad. Any updates would be awesome. I got most of the way through on the latest version. 

Some issues, could not get gyro, accel or baro to connect and it was pretty unresponsive. Also had some usb connection intermittency. Looking forward to a stable release!

**Comment by MototechRyan** [comment]
Thank you for your awesome work Hydra. I'm having an issue when clicking save and reboot. It hangs in reboot and when I click another tab it says "waiting for data". I've waited up to 10 minutes with no change. My only option is to click disconnect. Also note when connecting, the green light blinks the entire time my naze32 rev 6 is connected. I don't mind waiting for a stable release, but am happy to offer any help I can testing binaries.

**Comment by hydra** [comment]
@MototechRyan steps to reproduce please.  Sure you flashed it correctly?  full chip erase? video? config dump?

**Comment by MototechRyan** [comment]
I think something is wrong with my board. Cause i reflashed with baseflight and its doing the same thing in baseflight. Cancel my issue comment. Ive ordered a rev 5 and will wait for the 1.11 release to use my rev 6 with cleanflight. I will try to get the video and config dump. But feel you development gurus time would be better spent on other issues.

**Comment by FAYDID** [comment]
I am having the same issue as @MototechRyan. My board is woking fine however in baseflight. I can post any info needed. Just let me know.

**Comment by ProDrone** [comment]
I noticed the same behaviour with my __naze rev5.__
- go to PORTS tab and click on Save and Reboot.
- Log window reports (last displayed lines):
~~~
2015-10-19 @ 23:56:52 -- EEPROM saved
2015-10-19 @ 23:56:52 -- Device - Rebooting
~~~
- Clicking on any other tab after that hangs up waiting for data.
- Disconnect and reconnect gets all back to normal (until steps are repeated - consistently).

Used:
cleanflight master at 526f4777a24e6963ded6e6b92060350aa0e95878
configurator development branch at 7bf70092d35f9e96d1b681c3cc1cda2450049098

**Comment by borisbstyle** [comment]
This is a configurator issue right?

I have seen this on all firmwares since the latest configurator.
Op 20 okt. 2015 00:07 schreef "ProDrone" <notifications@github.com>:

**Comment by MototechRyan** [comment]
The only thing i can think of that changed was i was prompted to update my eprom software....i didnt know the steps to load file locally in cleanflight after right clicking and saving build 2147. So when i tried to open the build by double clicking it in windows, it prompted me to update the eeprom software i have installed for my turnigy 9xr pro tx software. May be irrelevant, but the eprom software was updated by me before figuring out how to load the new build locally in cleanflight.

**Comment by ProDrone** [comment]
Don't know. Looks like cleanflight frimware, since i have the same with
configurator master v0.65.0 8e7097c33e64bd4a16b38588caa83fc7c2c14704
and at label v0.65.0 8d39b3f8cc037cf5b7a17b274664c9118238a491

**Comment by borisbstyle** [comment]
Even 1.10 official had the same while it wasnt there like 2 weeks ago when
it was released.
I believe @tracernz mentioned something about configurator not closing
connection when disconnecting somewhere.
Op 20 okt. 2015 00:44 schreef "ProDrone" <notifications@github.com>:

**Comment by FAYDID** [comment]
When I connect with my rev. 6 I am not able to get gyro, accel or baro to connect and it was pretty unresponsive still. I am also not getting any accel movement...

**Comment by FAYDID** [comment]
I tired the dev version last night: 2147_805ee8c_travis_cleanflight_NAZE.hex 

The only issue I am seeing in this hex is: In the motor testing only 1 motor and ESC are working. Using BL20a and Cobra motors (in baseflight all work as they should). 

I woud love to switch over to cleanflight. I just need this motor functionality. I also calibrated the ESCs the same way as I did in baseflight. (clicked the motor button to allow them to work, put master to max, plugged in battery, got audio verification, put master to zero, unplugged battery. Plugged battery back in. Only one motor and ESC are working. I tried switching all motors and ESCs as well.)

**Comment by FAYDID** [comment]
Okay so very odd. I recalibrated the ESCs again without the battery. Just put the master motor all the way up, music played, put it down, confirmation music played then plugged in the battery and now all motors work.
In baseflight I always connected the battery when the master was all the way up then, all the way down, then disconnected and reconnected the battery and it has always worked.
Odd... but I will get some more props today and try it out today.

**Comment by MototechRyan** [comment]
Long story, but i got another new rev 6 in the mail today. Its from a different batch cause my first was purple and this one is red. I connected to baseflight, flashed the most recent stable firmware and its doing the same hanging in reboot when clicking save. So Im pretty sure its not caused by cleanflight cause this new rev 6 has never been connected to or flashed with any cleanflight firmware. Im gonna try reinstalling cleanflight and baseflight on my pc and try a different usb cable and see what happens.

**Comment by FAYDID** [comment]
@MototechRyan Ya I decided to just go out and buy and rev. 5 for now and keep the rev. 6 until there is a stable usable version.. The rev. 6 has really pissed me off.

**Comment by sjtrny** [comment]
I've been getting reports that it is also affecting rev5 and downgrading Chrome seems to fix the problem.

**Comment by MototechRyan** [comment]
Me too, i thought i was ordering a rev 5 and got another rev 6, doh! Ordered a rev 5 for real today. The rev 5's are getting hard to find for a reasonable price online nowadays.

Gonna go see if this new rev 6 has the same missing diode setup that allows 5v to back feed through the 1 thru 6 + pins to the PDB when connected to usb power only

**Comment by FAYDID** [comment]
@sjtrny I already tried downgrading chrome didn't fix anything...

**Comment by FAYDID** [comment]
@MototechRyan Ya I eneded up just paying a bit more and getting one on Amazon Same Day shipping so I could install today.

**Comment by andymac4182** [comment]
@MototechRyan That might be deliberate. I know some of the boards will allow your receiver to be powered up via the USB port so you can configure without requiring the motors to be powered up.

**Comment by JasonB91** [comment]
@FAYDID Can you share the Amazon URL? I can't seem to find them myself.

**Comment by FAYDID** [comment]
@JasonB91 sure: http://www.amazon.com/gp/product/B014M7XEZO?psc=1&redirect=true&ref_=oh_aui_detailpage_o00_s00

**Comment by JasonB91** [comment]
@FAYDID Thanks. I saw that, but assumed it was a "6DOF" Clone of the naze.

**Comment by FAYDID** [comment]
I can verify for you. I don't have it yet but should be here soon. How can
I check?

@FAYDID <https://github.com/FAYDID> Thanks. I saw that, but assumed it was
a "6DOF" Clone of the naze.

—
Reply to this email directly or view it on GitHub
<https://github.com/cleanflight/cleanflight/issues/1321#issuecomment-150730072>
.

**Comment by FAYDID** [comment]
@JasonB91 It is a "6DOF" Clone of the naze... just FYI...

**Comment by mattyra** [comment]
Hey Lads,

Im a little bit wet around the ears on this one, but I'm now running a Naze Rev6 don't care much for the baro... Im have a few issues and was wondering if this is something you are still looking at..

Issue 1 - The angle mode is sloppy and the rates don't affect the speed on pitch and roll (don't care much for this but though i would point this out...

Issue 2 - Cant get black box to work on the built in memory on matter what i do i pick on the Data screen that is there but theres no recording of data present...

Issue 3- time i need more time and good weather to fly

**Comment by hydra** [comment]
@mattyra 
1) unrelated. please stay on topic.
2) probably you configured it wrong.
3) unrelated please stay on topic :smile:

**Comment by hydra** [comment]
Issues regarding 'waiting for data' have been fixed in latest master.

**Comment by MiguelFAlvarez** [comment]
@hydra @MJ666 @JasonB91 Spektrum sat binding doesnt seem possible on the rev6 without a hardware modification. This is  due to the included SBUS inverter which only allows signal going in and not  out (the spektrum port signal trace shouldve bypassed the inverter imo).
This means firmware wont fix this unless the sat is connected to another gpio just for binding, and then reconnected to the uart2 port. Or you could desolder the SBUS inverter and jump the pins like I did (marked in the image below).
Sorry if this seems off topic, but it didn't seem clear that this was a hardware issue rather than firmware when it was previously mentioned.
![naze32-rev6-2](https://cloud.githubusercontent.com/assets/6414790/10971178/8986dfda-8398-11e5-843a-73119ea45780.jpg)

**Comment by gotnull** [comment]
I have a Rev 6 that doesn't respond to accelerometer movements in Cleanflight. Betaflight works fine and haven't tried Baseflight.

**Comment by MJ666** [comment]
@MiguelFAlvarez good catch. Looks to be not much we can do about this. This will also affect the Rev6 with BF.

**Comment by MototechRyan** [comment]
@Miguelfalvarez
Im wondering why cleanflight and betaflight will not work with my Orangerx sat. I used my alienwii fc to bind it to my tx module. But when i click the spektrum satellite box in cleanflight or betaflight and click save, the box becomes unchecked and tx inputs are not recognized. Works in baseflight, but wondering why not in cleanflight or baseflight.

**Comment by Josrau** [comment]
Hydra,

 I have a problem with my Naze32 Rev5 FC which was originally set up a few months ago in my ZMR250 quad with Clean Flight 1.8, everything went well, had it up and flying in no time. Did a bit of PID tuning and 3-4 weeks ago started noticing some problems. At first, no beeps out of the FC so a week ago decided to update the firmware to 1.9.0, plugged it in to the PC via USB port and had the green light constantly flickering, went through and upgraded the firmware, said this was successful, all green and rebooted, then the next issue started, just sat there and would not complete the reboot cycle. So unplugged the USB cable and re-plugged the USB, now the Blue, Green and Red led are on. Connect to the board and it looks like it has loaded the 1.9.0 firmware. Go to the settings tab, go through the accelerometer calibration on flat surface, again hung up in reboot cycle. Disconnect, re-connect, Blue, Green and Red Led's on, Green flickering still, go to the settings tab with the image of the quad and notice that the image of the quad is jumping on the yaw axis even though I am not touching or moving the quad.

Do I have a faulty FC? I have since purchased 2 Naze32 Rev6 FC's and read that Cleanflight does not talk to them properly. Can anyone offer some suggestions on getting the Rev5 FC back working or should I throw it in the bin?

I appreciate any help you can give.Thank you...Joseph.

**Comment by YFZ450MANNY** [comment]
Josrau, FC hanging upon reboot was a known issue in Cleanflight configurator ver 0.65. Upgrade to 0.66 if you haven't already. It has since been resolved.

**Comment by Jasco34** [comment]
I tried to update my naze32 board with the current configurator (0.66) complete with newest software.
I received a message stating that "Bootloader programing failed".  Any suggestions?

**Comment by Josrau** [comment]
Hello YFZ450MANNY, when you say upgrade to Cleanflight  configurator 0.66, what is that? are you talking about the Cleanflight program on Google? or another piece of software? If so where do I find it/
Thank you,

**Comment by stylewarz** [comment]
Hi There. I'm new to this and have been searching for quite a while to find a solution to my problem. After installing the UART Driver on my Windows 7 I don't get a COM Port in my Device Manager.
I know that this is not a Clearflight issue but I've run out of search terms on the matter. You guys here seemed to be very knowledgeable in this field.
Would be very grateful if someone could help me.

**Comment by Josrau** [comment]
Hello YFZ450MANNY, I have update to Cleanflight configurator 0.66 and does not make any difference, still having the reboot issue with my version 5 board and a blinking green light. Does anyone know the error code sequence for the green blinking LED on the Naze32?

**Comment by Josrau** [comment]
Does anyone have an idea of when the next version of Cleanflight will come out, I think it may be ver 1.11?

**Comment by FAYDID** [comment]
I've been using Betaflight and it has been working phanomally. The defult values produce zero oscilations for me while I had quite a bit with Cleanflight.

**Comment by YFZ450MANNY** [comment]
Some people are still experiencing the "reboot" issue with 0.66. I am also. Just disconnect and reconnect afterwards. There are lots of very experienced people working on these issues. Give it some time. And yes, Betafilight is what seems to be working best on Rev 6 Naze32 as of now.

**Comment by MototechRyan** [comment]
Scratch my above comment. I'm an idiot. I needed to check the serial rx box for uart2 under the ports tab.

Lol, I think Travis has given up on keeping comments on topic. Thanks again for your and the other devs hard work. Thanks to you guys I am now in FPV nirvana rocking betaflight...at least till the winter hits in my part of the world.

**Comment by ExtraTicks** [comment]
Hi All,

Today i tried to calibrate motors and ESC on my first NAZE R6 board, so as usual I maxed the motor tab in Cleanflight and plugged my battery in and the motors ran on full and then poooof, magic smoke. 

How are you supposed to calibrate motors and ESC with NAZE R6? Can i replace the electronic components to save the board? 

Thx.

**Comment by ExtraTicks** [comment]
Also, does anyone know what pinout on NAZE R6 do I use for Smartport wire? (I used UART2TX single wire to Smartport on X4R-SB) 

On cleanflight on Telemetry tab when i select Smartport, and click on Save & reboot, keeps on un-selecting itself and SERIAL RX.  

Thx

**Comment by hydra** [comment]
General comments regarding unrelated issues have been deleted, again.  PLEASE only comment if you are a) using a Naze Rev6 and b) the issues is a Naze6 SPECIFIC PROBLEM or report.

This is NOT the place to ask for help for other issues!

**Comment by hydra** [comment]
@MiguelFAlvarez Thanks for the details regarding spektrum sat binding.

Clearly the F3 processor is superior in this regard :smile:

**Comment by JasonB91** [comment]
For those struggling with ESC calibration due to 5V being sent to ESC's during power up (ESC's with internal BECs), I simply just removed the power wire from throttle cable on all ESC's with BEC's. I gave away my Rev 6 board to a co-worker, and this was the workaround I came up with.  

Once the BEC's are removed, typical motor tab calibration works like a charm when you connect the flight pack!

**Comment by BasdeBeer** [comment]
Does LuxFloat work reliable on rev6? Would a filter be needed if so?
(I tried controller 1 but thats not really good on beta flight for me, how would you thing luxfloat does?)

**Comment by ExtraTicks** [comment]
just tested naze R6 on luxfloat on betaflight 2.1.3, perfect! I had issues
earlier becuase accelerometer didnt activate on earlier betaflights and
reflashed

still cant calibrate motors but flys fine. motors seem to go to full ball
each time i try, fried tornado, a Naze r6, Led board trying.

attached is the hex

**Comment by ExtraTicks** [comment]
anyone able to successfully connect telemetry from NAZE R6 to Smartport?

**Comment by BasdeBeer** [comment]
I just flew 3 packs with the luxfloat controller on my r6, extremely stable and way better on stocks than controller 1. I just wondered whether the code was stable enough to rely on as a lot of people say its still in the experimental phase.

**Comment by gotnull** [comment]
ExtraTicks yup, works for me. What's the problem?

**Comment by ExtraTicks** [comment]
Gotnull, How did you hook up the cable? and how did u setup the cleanflight
to get it to run?

i ran cable from UART2TX on naze R6 to Smartport wwire on X4R SB. In
Cleanflight on UART2 I tried to select Smartport telemetry column and
Serial RX, with both selected, when save and reboot it unchecked both. End
up only can run SERIAL RX on UART2.

Please advise how you got Telemetry on Taranis with NAZE R6 and X4R-SB.

Cheers.

**Comment by ExtraTicks** [comment]
@Jason, I removed the black cable from ESC and leaving 1 white signal wire
in the NAZE R6, motors keep going full ball when I plug in battery. Is
there something else i need to do?

Thx

**Comment by hydra** [comment]
Done

**Comment by headspindle** [comment]
switched from baseflight to cleanflight and motor 3 and 4 esc will not calibrate an motors will not run motor 1 and 2 run only

**Comment by tavila71** [comment]
Miguel, Is there any chance you could take a picture of the Naze32 Rev6 board with the modifications needed to use a Spektrum satellite. After you remove the Sbus chip and jump the connection, do you flash the same as Rev5? Thanks

**Comment by MiguelFAlvarez** [comment]
@tavila71 I think its best to go off the picture I already posted. The pictures of the actual mod dont look as clear as just marking which pins to connect. Just to be clear, this modification isn't necessary to "use" a spektrum remote rx. It's only necessary if you want to use the naze to bind the remote rx. If you have a spektrum receiver that supports remote receivers, you can use that to bind  the remote receiver and then plug it into the naze.The firmware is the same as rev 5.

**Comment by tavila71** [comment]
Thanks for the response Mike. So all I need to do is bind it to my regular reciever and then follow the setup steps like a Rev 5? 

Sent from Yahoo Mail on Android 
 
  On Thu, Feb 18, 2016 at 9:58 PM, MiguelFAlvarez<notifications@github.com> wrote:   
@tavila71 I think its best to go off the picture I already posted. The pictures of the actual mod dont look as clear as just marking which pins to connect. Just to be clear, this modification isn't necessary to "use" a spektrum remote rx. It's only necessary if you want to use the naze to bind the remote rx. If you have a spektrum receiver that supports remote receivers, you can use that to bind the remote receiver and then plug it into the naze.The firmware is the same as rev 5.

**Comment by treken** [comment]
@MiguelFAlvarez will you please post a picture of the FC modification you did? I don't want to desolder the wrong thing.
