### ISSUE TITLE
CF 1.10 RC1, no mag detected on Sparky (mpu9150)

### ISSUE THREAD

**Issue by KipK** [cleanflight/cleanflight#1325]
Ugrading to 1.10 RC1 disable mag on sparky. 
MPU9150 aka AK8975  for mag is not detected neither work if I force it in CLI
Works ok on 1.9

**Comment by SteveAmor** [comment]
Most likely a duplicate of #1314

**Comment by KipK** [comment]
I've saw it but not sure it's related. 

AK8975 read function doesn't has the same typo :+1: 

bool ak8975Read(int16_t *magData)
{
    bool ack;
    UNUSED(ack);
    uint8_t status;
    uint8_t buf[6];

    ack = i2cRead(AK8975_MAG_I2C_ADDRESS, AK8975_MAG_REG_STATUS1, 1, &status);
    if (!ack || (status & BIT_STATUS1_REG_DATA_READY) == 0) {
        return false;
    }

**Comment by hydra** [comment]
@KipK Where are you looking?

**Comment by KipK** [comment]
Hi Dom,

 

What are you talking about ?

 

 

De : Dominic Clifton [mailto:notifications@github.com] 
Envoyé : samedi 26 septembre 2015 02:38
À : cleanflight/cleanflight
Cc : Guillaume S
Objet : Re: [cleanflight] CF 1.10 RC1, no mag detected on Sparky (mpu9150) (#1325)

 

@KipK <https://github.com/KipK>  Where are you looking?

**Comment by KipK** [comment]
issue closed, fixed by e0f4ddeccd344c14e896497b73d7f71ecabad26b
