### ISSUE TITLE
CF 1.10 RC2  Serial RX Failsafe issue

### ISSUE THREAD

**Issue by Tabsy123** [cleanflight/cleanflight#1327]
Edit: See Comment bellow as i have figured out how to get it as i want now :)

If you want the motors to all stop but still have a few seconds chance at regaining control it seems you can not do this like you could on 1.8.1

When radio is turned off ( out of range)  and failsafe is set to 1000  (esc calibrated low point on my build is 1050)   The motors all stop for about a second then the craft will bring on the front or back etc as if its trying to level it self even tho the other 2 motors are off (as they are asked to at a value of 1000)  
Would be good if all motors turned off when failsafe is set to a value bellow your esc low point value   
Eg:  1000 failsafe    ,  1050 low point esc ,  motors should all stop and stay stopped unless radio signal has come back before the failsafe time out etc.

**Comment by Tabsy123** [comment]
All good I figured out how to get what i wanted,  i just disable failsafe ( untick it)  then it behaves exactly as i want  :)

**Comment by hydra** [comment]
great, closing, thanks for feedback!

**Comment by ducktaperules** [comment]
This issue sounds like some weirdness i experienced with the fail-safe.
IIRC when fail safe is triggered the armed but low throttle period that happens before the copter disarms does not seem to respect min_throttle, causing motors to go below min_throttle and stall out.
