### ISSUE TITLE
SPracingF3 softserial not working

### ISSUE THREAD

**Issue by bevibes** [cleanflight/cleanflight#1336]
Hi, 

When i'm activate "feature softserial" in CLI or with configuration tab,  cleanflight doesn't activate new port in the port tab . In CLI , I've a parse error when I try to configure serial 3.
Tested on CF 1.9 and 1.10rc2: same issue. After a reset to default, and only activate softserial, same issue...
Bug or misconfiguration?

**Comment by hydra** [comment]
probably you have parallel PWM on still.  just flashed and tsted, enabling PPM and SOFTSERIAL works fine for me using latest rc2.
