### ISSUE TITLE
GUI Buttons for Esc Calibration

### ISSUE THREAD

**Issue by w4Rd3n** [cleanflight/cleanflight#1344]
I would like to see a button in cleanflight gui for esc max min throttle calibration. i am mostly configuring my quads in the field with a tablet. but it's hard to calibrate with the sliders when having no cursor.
thanks.

**Comment by andymac4182** [comment]
I think this should be in the configurator issues list :) https://github.com/cleanflight/cleanflight-configurator/issues

**Comment by borisbstyle** [comment]
Use HOME and END button on keyboard for that.

**Comment by w4Rd3n** [comment]
@borisbstyle thanks for the hint:+1:

**Comment by hydra** [comment]
Yes, I will close this, this issue tracker is for the FIRMWARE.
