### ISSUE TITLE
On naze32 with Lux Float PID controller SERVO tilt doesen't work

### ISSUE THREAD

**Issue by spacebubi** [cleanflight/cleanflight#1350]
if i use PID controller 3 servo Tilt  ìfor my cam works perfectly, unless in the PID controller Lux Float doesent any effects , settings are the same of pid profile 3, but nothin.  try to set via CLI set gimbal_flag = 1 but run error phase. Also from TAB panel SERVO changes value from GUI cant save when click butotn "save" nothig appear on the feed on the top. Via CLI i try to set same servo settings from PID controller 3, but nothing ...some ideas?

**Comment by hydra** [comment]
use latest development configurator for latest firmware configuration via servos tab.  reset to defaults, configure servos and read up on new servo mixer configuration in 1.10 (see docuentation).

Not really seeing how this is related to the pid controller.

for example, the servo tilt works on the output from the pid controller and the same output is used to drive the motors.  so if the output was wrong it would't fly either..

https://github.com/cleanflight/cleanflight/blob/master/src/main/flight/mixer.c#L844-L858

Looks like misconfiguration to me. Closing.  Open a new bug with exact steps to repeat if and reference this if there's really an issue.
