### ISSUE TITLE
On naze32 with Lux Float PID controller SERVO tilt doesen't work

### ISSUE THREAD

**Issue by spacebubi** [cleanflight/cleanflight#1352]
if i use PID controller 3 servo Tilt for my cam works perfectly, unless in the PID controller Lux Float doesent any effects , settings are the same of pid profile 3, but nothing . I try to set via CLI with command set gimbal_flag = 1 but run error phase. Also from TAB panel SERVO changes value from GUI cant save when click button "save" nothig appear on the feed on the top. Via CLI i try to set same servo settings from PID controller 3, but nothing ...some ideas?

**Comment by hydra** [comment]
duplicate of #1352
