### ISSUE TITLE
Interesting stabilization issue

### ISSUE THREAD

**Issue by PaulHilgeman** [cleanflight/cleanflight#1355]
I have had this happen 2-3 times now and finally got it on tape WITH flight recorder data!  I can not re-create this.  It happened once while windy (recorded here) and has happened at least one other time when not windy.  It has happened with pitch both times and always was pitching rearward.  The quad is in Angle mode, and I have not had the wherewithall to switch to Acro or Angle while this is happening yet, I usually just throttle down and crash.

Here is the flight recorder data:

https://www.youtube.com/watch?v=sgMjPXwMlR4

Here is the on-board camera video:

https://www.youtube.com/watch?v=LCsyurlJGQI&feature=youtu.be

I can dump my flight settings when I get home, so stay tuned.

**Comment by digitalentity** [comment]
Can you upload your blackbox log instead of a video?

**Comment by PaulHilgeman** [comment]
Hmmm, I probably could, but it seems like I cant drag and drop it here, can you reccomend a service?

**Comment by digitalentity** [comment]
@PaulHilgeman you can rename a LOG from txt to, say, jpg and upload it here. Or you can use any file sharing service you like - Dropbox, Google Drive.

**Comment by PaulHilgeman** [comment]
![blackbox_log_2015-09-25_140324](https://cloud.githubusercontent.com/assets/14878907/10159857/7ddbd212-6660-11e5-9359-c31147122b6e.jpg)

**Comment by digitalentity** [comment]
What version of Cleanflight is this? Also can you share some details about your setup (flight controller, additional sensors)?

**Comment by PaulHilgeman** [comment]
It is a basic 250mm CF kit, Blade 250 by diatone
Emax 1806 motors with 6045 props
12A Spider ESCs – SimonK Firmware
3S battery
CC3D controller running 1.9.0 and Configuaretor 0.65
No additional sensors
500g or so

**Comment by ledvinap** [comment]
@PaulHilgeman : the loq is unusable at this rate. Is there any reason to set blackbox_rate_denom higher than 1?

**Comment by PaulHilgeman** [comment]
It was for space concerns.  I will try to recapture with a lower denom, I only have 2MB internal flash

This e-mail may contain privileged or confidential information. If you are not the intended recipient: (1) you may not disclose, use, distribute, copy or rely upon this message or attachment(s); and (2) please notify the sender by reply e-mail, and then delete this message and its attachment(s). Underwriters Laboratories Inc. and its affiliates disclaim all liability for any errors, omissions, corruption or virus in this message or any attachments.

**Comment by ledvinap** [comment]
Just guessing, but at least 5x quad natural frequency of quad will be necessary. That is about 50Hz, blackbox_rate_denom = 5 for 3500us loop time.
