### ISSUE TITLE
Inverted P gain on PID controller 0

### ISSUE THREAD

**Issue by egzumer** [cleanflight/cleanflight#1357]
My quad is 450 class. I have newest firmware flashed on flip32 board.
I tried to TX tune my quadcopter. I set "I" and "D" to 0, "P" was 4. It's been said that one should increase P until a quad starts to oscillate fast and then decrease the P little bit, or to increase the P until a quad gets responsive. But when I add P on PID controller 0 my quad gets less and less responsive, and when I decrease it gets more responsive. I ended up with P=2. Also when I turned on autotune it didn't work correctly. I stopped it manually at some point and the P was 12. So it looks like it increases P infinitely because of the mentioned problem.

**Comment by hydra** [comment]
read tuning guide

http://www.rcgroups.com/forums/showthread.php?t=2439428
