### ISSUE TITLE
Comms - Date format in MSP_BUILD_INFO

### ISSUE THREAD

**Issue by stronnag** [cleanflight/cleanflight#136]
Currently API_VERSION uses MMM DD YYYY date format, which is non-intuitive to non-English speakers.

Using ISO8601 is unambiguous for non-English speakers and USians.

Please consider using ISO 8601.

**Comment by hydra** [comment]
It would be nice, yes.

After a quick bit of googling it appears __DATE__ is in a fixed format and you have to do something else instead.

http://www.avrfreaks.net/forum/convert-date-string-during-pre-processor-or-comile-time

Solutions appear to involve mucking around make file and automatically generating files based on the output of some shell command.

I would accept a PR to fix this as long as the file didn't get regenerated when it didn't need to be.  i.e. if typing in 'make cleal && make && make'

It must also be cross-platform (osx, linux, cygwin).

**Comment by hydra** [comment]
Updated the title to reflect that `buildDate` is now used in MSP_BUILD_INFO and not MSP_API_VERSION
