### ISSUE TITLE
Enable baro and mag on Flip32 DOF10

### ISSUE THREAD

**Issue by ludiga** [cleanflight/cleanflight#1362]
I have a flip32 dof10 with the boris firmware,
I would, however, enable in the CLI the baro and magnetometer, how should I do?

Thanks a lot
Luca

**Comment by hydra** [comment]
please use forums for support.  issue tracker is for bug reports.  please read this - a link was on the form you filled in.

https://github.com/cleanflight/cleanflight/blob/master/CONTRIBUTING.md
