### ISSUE TITLE
Smartport telemetry?

### ISSUE THREAD

**Issue by borisbstyle** [cleanflight/cleanflight#1363]
I am trying to setup smartport telemetry ij my x4rsb and just cant get it working.

Using spracingf3 SBUS on uart2 and smartport on uart3 with telemetry inversion enabled.

Really lacking some clear manuals

**Comment by hydra** [comment]
Painless360 has videos on youtube.

https://www.youtube.com/playlist?list=PLYsWjANuAm4ro1vHztauuHFaelUDCOwqw
