### ISSUE TITLE
Altitude Hold Problem

### ISSUE THREAD

**Issue by mehmetyldz87** [cleanflight/cleanflight#1364]
I am having problems regarding fixing height  in altitude+angle mode , when I want to raise the altitude of the system, first system is falling, rising later. I just tuning the Altitude P value. Where can I find a set of documents related to altitude mode and tuning?  Thank you for your suggestion .

I would like to give a brief information about the system
->System weight (~2.4 kg)
->Rotor-rotor dimension (70 cm) (Quad Plus Mixer Configuration )
->MT2814-750 KV brushless motor
->12x5 Wood propeller
->Naze 32 Acro Full rev5
->Transmitter Graupner MX16 - PPMsum (Mod2)
->Software v1.90

ALT PID Values 

ALT -> P= 3 /  I=0 / D=0
VEL -> P=12 / I=0.045 / D=1

**Comment by hydra** [comment]
please use the forums and irc for support.
