### ISSUE TITLE
Afromini Amaze rev3 (Mini Naze32) Cleanflight Support

### ISSUE THREAD

**Issue by AustinSaintAubin** [cleanflight/cleanflight#1368]
Can we work towards getting full clean flight support for [Afromini Amaze rev3 (Mini Naze32)](http://www.getfpv.com/afromini-amaze-rev3-mini-naze32.html).
The small forum factor of the Afromini makes it perfect for small aircraft that cannot fill a full size board.
- ~~Barometer is not working, see #1232 & PR #975~~, (FIXED with #1326)
- Buzzer pin does not seem to work
- ~~Channel order mapping seems to be confused as of Cleanflight v1.10.0~~ (Its not a channel mapping issue, it is a issue with how servo pins are setup in mixes. Need at least 7 pins with default servo mix to work. Fixed with Custom Airplane for 6 pin boards #1370)
  - ~~Channel mapping was working fine with Cleanflight v1.9.0.~~
  - ~~Tested with Airplane Mixer, all defaults.~~

**Comment by jcowgar** [comment]
Does the include the beeper or does the board have an error on it preventing the beeper from working?

**Comment by lazd** [comment]
Looks like #1326 included support for the BMP280 barometer, so you can scratch that off the list.

**Comment by xoxota99** [comment]
From the [discussion on RCGroups](http://www.rcgroups.com/forums/showthread.php?t=2163400&page=65), it seems like even Baseflight doesn't properly support the buzzer on Afro Mini.
