### ISSUE TITLE
Feature request: Blackbox download via cleanflight.

### ISSUE THREAD

**Issue by jaimevisser** [cleanflight/cleanflight#1369]
If the Openlogger is connected to uart2 on a Naze with both TX and RX it becomes possible to dump a file to serial. With a small change in cleanflight it should be possible to redirect this dump to the CLI, allowing you to dump logging.

Rationale: not every OpenLogger is easily accessible inside the quad frame, the USB port on the FC usually is.

Possible snag: is serial fast enough to allow logging download at a reasonable pace?

**Comment by MJ666** [comment]
Reading the 16MByte SPI flash already takes ages. don't ting this is a valid option for the OpenLog and is really worth the effort. much better to take the easy access to the SDCard into account during the build phase.

**Comment by joshuabardwell** [comment]
>Possible snag: is serial fast enough to allow logging download at a reasonable pace?

In short: no.

**Comment by MJ666** [comment]
At least it will not be faster as OpenLog can write. Even for this additional action need to be taken to use an higher baudrate for downloading.
