### ISSUE TITLE
CC3D Betaflight won't boot

### ISSUE THREAD

**Issue by dkraft** [cleanflight/cleanflight#1378]
CC3D would not respond.
I tried two different boards, each could be flashed back and forth to cleanflight, but betaflight would not respond. seems it's not initiating. one light solid only.

naze works! so I changed the brain.

**Comment by Cwix** [comment]
I can confirm this too. Just a solid light. Windows reports as malfunctioned device. Betaflight 1.10

**Comment by hydra** [comment]
this is the cleanflight issue tracker.

**Comment by hydra** [comment]
http://www.rcgroups.com/forums/showthread.php?t=2464844

**Comment by borisbstyle** [comment]
Lol

**Comment by Cwix** [comment]
My bad...
