### ISSUE TITLE
Feature Request: LED Strip support GPS # of satellites found

### ISSUE THREAD

**Issue by Ravid824** [cleanflight/cleanflight#1384]
The LED Strip feature is very cool, but it is missing one of the most important indication which is the GPS #of satellites found. 
Currently when the GPS find 3D fix and there are more than 5 the buzzer beep shortly (not always you can hear it).
I would like to assign a LED that will turn on based on the #of satellites found (1- SAT one bleep, 2 SAT's 2 bleeps, etc). .
This option is available with Multiwii code.

Thank you

**Comment by dalgibbard** [comment]
Related to #709 and #896.

**Comment by skaman82** [comment]
Done in https://github.com/cleanflight/cleanflight/pull/2101. Please close this
