### ISSUE TITLE
In TriCopter configuration, Servo Values Not Saved on Naze FC

### ISSUE THREAD

**Issue by mrduncan626** [cleanflight/cleanflight#1392]
In TriCopter configuration, Yaw Servo Direction, MIN, MID, and MAX are not being saved.  This problem also existed in v1.9.  Still having to configuration TriCopter in V1.8.1.

**Comment by stronnag** [comment]
You can use the CLI, where configuration works for tri on current (and previous) versions.

**Comment by mrduncan626** [comment]
Ok, is the following correct:
Yaw Servo MID: servo_center_pulse = 1500.
Servo direction:  yaw_direction = 0  or yaw_control_direction = 1.
It's not obvious what parameters to change for Yaw Servo MIN and MAX.

**Comment by stronnag** [comment]
To change the servo direction, for 1.9, 
```
servo 5 1020 2000 1500 101 -1
````
The 101 sets reversed, for some 1.9 iterations there are some extra parameters, but the 100 / 101 defines servo direction.
````
servo 5 1000 2000 1500 90 90 101 -1
````
For 1.10 / 1.11 use the smix command set (as Mixed.md), thusly:
````
# mixer
mixer TRI
mmix reset
smix reset

# then per profile
smix reverse 5 2 r
````
min /max are probably the 1020 / 2000 values, but you'd have to check the code, as servos have not been well supported in the UI as FC code improvements have somewhat out-paced UI developer time.

**Comment by mrduncan626** [comment]
Wow.....setting up tricopter servos used to be easily done directly through Servo Tab in the CleanFlight GUI.  Thanks for the information.  I'll have to study up on the Mixer.md.

**Comment by mrduncan626** [comment]
It also looks like any configuration which requires servos will require the method above to setup the servos.

**Comment by stronnag** [comment]
smix is much more flexible than the older methods, just needs the UI to catch up.
