### ISSUE TITLE
Feature Request: Real Time Stick Marks in the Rate Graphs

### ISSUE THREAD

**Issue by nwenkel** [cleanflight/cleanflight#1397]
I could imagine that a some realtime marks or indicators of the stick position at the receiver tab indicating the influence of Throttle Mid, Expo and Rc Rate, Expo are benefical for users. Would like to see this.
![marks](https://cloud.githubusercontent.com/assets/13793203/10539582/c57e4e4e-7400-11e5-904d-92018bf8c77a.JPG)

**Comment by andymac4182** [comment]
This would probably be better in the configurator issues. 
https://github.com/cleanflight/cleanflight-configurator/issues

**Comment by nwenkel** [comment]
You are right. Sorry, my fault. Moved it allready
