### ISSUE TITLE
Board documentation- STM32F3Discovery

### ISSUE THREAD

**Issue by varoudis** [cleanflight/cleanflight#1400]
Any documentation for STM32F3Discovery with pins and basic setup?
Thanks

**Comment by nathantsoi** [comment]
I use the data sheet and https://github.com/cleanflight/cleanflight/blob/master/src/main/target/STM32F3DISCOVERY/target.h

**Comment by varoudis** [comment]
another important questions that needs documentation is about the USB VCP driver that is needed in order to connect to a flushed stm32f3disc.

I managed to flush it but I can't get the user-usb to link.

**Comment by tannewt** [comment]
I can't connect to a STM32F3Discovery either over USB. I'm on a Mac but I also tried on Linux. dmesg shows some enumeration errors but then on Mac is shows up as a tty. However, it can't load the configuration through the configurator.

**Comment by tannewt** [comment]
I take this back. The VCP driver works for me on Cleanflight but not Betaflight.

**Comment by nathantsoi** [comment]
stm32f3discovery isnt supported by betaflight: https://github.com/borisbstyle/betaflight/issues/95

this issue can pry be closed & moved to betaflight
