### ISSUE TITLE
disable disarm for Plane

### ISSUE THREAD

**Issue by Basti77** [cleanflight/cleanflight#1401]
How can i deactivate the function "disarm"?

Background: If the aircraft flies a left turn, (low throttel)  the Motor is turned off (arm) after the maneuver.
Very bad constellation.

**Comment by add1ct3dd** [comment]
Disarm via switch rather than sticks.

**Comment by joshuabardwell** [comment]
You can also use an idle-up switch to prevent the throttle from going below min_check while you are flying.
