### ISSUE TITLE
In accro mode Flight performance are better if acc_hardware==1 (disable)

### ISSUE THREAD

**Issue by Sil20** [cleanflight/cleanflight#1410]
Version 1.9.0 Board Naze32 full.

The accro mode does not include Acceleromettre data  so the flight performance should not get bad whatever the parameter acc_hardware is .

I did not read the code but accro

**Comment by joshuabardwell** [comment]
Angle mode cannot be enabled if acc_hardware=1. Self-level requires the accelerometer. This issue is really confusing.

**Comment by Sil20** [comment]
Sorry I was confused about Angle mode. I edited the Issue. only Accro mode is concerned by the issue.

**Comment by andymac4182** [comment]
With some of the latest changes from Boris this won't be required yet. This is really a question for the forums or IRC. Disabling the acc just allows lower loop times on older firmwares. If you are looking for faster loop times check out Betaflight as it includes changes that are on their way or being tested.

**Comment by Sil20** [comment]
OK , Great, 
Would BetaFlight enhancement be merge into cleanfliht when validated and tested on ist too much of a change of approach?

**Comment by andymac4182** [comment]
There are various Pull Requests for some of the features already that are being discussed :) There is still a lot of testing going into the latest stuff.

**Comment by thenickdude** [comment]
The IMU needs to run all the time (even in acro modes) so that an initial attitude is available if you decide to switch to a self-levelling mode mid-flight.
