### ISSUE TITLE
Configurator/FC crashes after a few minutes with JR DMSS satellite plugged in

### ISSUE THREAD

**Issue by andypnz** [cleanflight/cleanflight#1424]
When using a JR DMSS satellite, the configurator/FC crashes (after a few minutes) during configuration. Resolved by unplugging the DMSS satellite for most of the configuration. Just plug the satellite in briefly to check the receiver tab.

Could this be some sort of over current issue? The satellite is running from the 3.3V contact.

Seems to be no issues in flight. Solid RF link.

Plan: Must test using a satellite power feed independent of the FC/USB.

**Comment by Redshifft** [comment]
No, Satellite is pulling less than 60MA so unlikely power related.

Some other issue with Cleanflight Configurator for sure, seems to stutter in the RX screen for me and not update Radio channel positions ?
