### ISSUE TITLE
Size of pointer 'colors' used instead of size of its data (ledstrip.c)

### ISSUE THREAD

**Issue by Echelon9** [cleanflight/cleanflight#1430]
Warning from cppcheck.
```
[src/main/io/ledstrip.c:1020]: (warning) Size of pointer 'colors' used instead of size of its data.
```
The specific section of code that triggers this warning is:
```
void applyDefaultColors(hsvColor_t *colors, uint8_t colorCount)
{
    memset(colors, 0, colorCount * sizeof(colors));
    ...
}
```
The use of a size of a pointer instead of the size of its first data element is a common oversight.
This should be trivial to fix. I am preparing a PR.

This code was introduced in 545980c14a291ce9a87e3372748c0127756e34d5 @hydra

**Comment by hydra** [comment]
good spot and that for the fix.
