### ISSUE TITLE
Windows10 issue ?

### ISSUE THREAD

**Issue by Fvk1960** [cleanflight/cleanflight#1438]
I lately use Windows10 operating system.
Now the sensor tab does not display any data trends and application gets stuck . Cannot change tab any more.
Need to disconnect and reconnect.
Has anyone same issue ?

**Comment by joshuabardwell** [comment]
https://github.com/cleanflight/cleanflight/pull/1436#issuecomment-151240388

**Comment by seattleite09** [comment]
I don't think it's a Win10 problem. It seems to be an issue with the latest Chrome runtime. As Joshua pointed out, this is being addressed.

**Comment by 1477** [comment]
I figured I had problems with the software but I did not know where to look.  I seems others have similar problems.  Hopefully, this issue can be addressed and we can move on with our projects

**Comment by borisbstyle** [comment]
it is addressed.....just download manually the development version of configurator

**Comment by Skidaddle23** [comment]
I'm tagging on to the end of this with a similar issue. Has anyone else had problems since the Aniversary Update of Windows 10 a couple of days ago? Cleanflight is laggy and it claims the battery is 1.4V without a battery plugged in and the BlHeli passthrough no longer works.
