### ISSUE TITLE
SERVO_TILT not moving motors to 3-6 output on SPRacingF3 Board

### ISSUE THREAD

**Issue by EurigJones** [cleanflight/cleanflight#1444]
I've used the SERVO_TILT setting in the past to use outputs 1 or 2 for other things like a loud lost model buzzer. On my Naze it worked with cleanflight 1.10 and 1.9.

I'm doing the same with an SPRacingF3Board (Tried using 1.10 and 1.9)
- Connecting 4 motors to outputs 3 to 6.
- setting SERVO_TILT feature enabled.
- But only 2 motors are powering up (motors 1 and 2 as pictured in the motor configuration diagram)

I tried for testing purposes using the HEX configuration and all 4 motors span (so no issue with connections).

**Comment by Amorgos** [comment]
Apparently on this board SERVO_TILT results in pins 7 and 8 being used as the servos (Not tested this yet personally). So if this is not desired behaviour then it's a bug.
