### ISSUE TITLE
Naze32 will not reboot after save

### ISSUE THREAD

**Issue by noamsmadja** [cleanflight/cleanflight#1448]
Naze32 with cleanflight 1.10 does not reboot after clicking save in cli or on any tab that requires a reboot. Clicking disconnect and reconnect makes it work again. (happens on 3 naze32 board rev5 marked with abusemark and bought from hobbyking, maybe thats the reason)

connected only to usb, no battery.

how can i help debug this?

**Comment by joshuabardwell** [comment]
Is this the same issue?

https://github.com/cleanflight/cleanflight/pull/1436

**Comment by noamsmadja** [comment]
Yes, sorry, searched and didnt find it, im new :)

**Comment by SteveAmor** [comment]
@noamsmadja any chance you can close this issue if it is the same as #1436
