### ISSUE TITLE
channels 1-4 not working in cleanflight

### ISSUE THREAD

**Issue by ferdagio** [cleanflight/cleanflight#1449]
I am also  having an issue where the throttle, rudder, ail, elev channels not working,  but the Aux switches do. I've tried everything to figure this out including, switching rx's, triple checking the wire harness from the naze to the rx, erasing the Naze32 board and re-loading the firmware, calibrating the accelerometer etc. I'm all out of ideas. Can someone please help sort this out?

Regards
Karl

**Comment by qfather** [comment]
This is the bug tracker for Cleanflight, not a general support platform.  Besides that, your post lacks crucial information for anyone to actually help you, not to mention demonstration that it's actually a Cleanflight issue.
