### ISSUE TITLE
Data on buzzer pins? (SeriouslyProF3)

### ISSUE THREAD

**Issue by sjobbe** [cleanflight/cleanflight#1459]
I'm unable to use softserial and I'm gettin music out from my buzzer. I'm assuming softserial data is being transmitted to the buzzer. Is this possible? Hardware or software issue?

Made video to illustrate what I'm talking about: https://www.youtube.com/watch?v=Fv8aFk1QttI

**Comment by hydra** [comment]
If you buy a clone board you take your chance and this is what you get...
