### ISSUE TITLE
Wrong speed on HoTT telemetry

### ISSUE THREAD

**Issue by Basti77** [cleanflight/cleanflight#1461]
The GPS speed is incorrectly transmitted or interpreted from my Graupner transmitter (MC20).
My copter flies no 800km / h fast, but 80 km / h could well agree.
If the speed is sent with a decimal point? I mean 80.0 is converted t0 800?
The announcements for distance and voltage was correct.
In CF alone versions have the same problem. Hardware: Flip32 and CC3D

**Comment by Pierre-A** [comment]
**@Basti77**, thanks for your finding.
You're right, there a wrong coefficient for the ground speed before sending the Hott frame.
I'm gone open a PR to fix that.

**Comment by Pierre-A** [comment]
This should be closed.
