### ISSUE TITLE
Feature request: Alternative output pin for RGB LEDs?

### ISSUE THREAD

**Issue by martgadget** [cleanflight/cleanflight#1462]
Many boards have other output pins that could be used for addressable LED strips - e.g NAZE32 has FRSky telemetry pin.

Can you consider making it possible to configure RGB led support on to say the telemetry pin instead of requiring PPM mode for example? or is this feature dependent on PPM mode for other reasons?

Thanks again for such a stable, easy to use platform - you have no idea how many happy boys enjoy their toys because of the work you folks have done 8-) - Thanks.

**Comment by DaEmpty** [comment]
Being able to use one softserial port and the led strip at the same time, would be amazing. I'd like to use SBus (UART), USB (UART), MinimOSD (Softserial) and a led strip. The naze has still a lot of unused pins but the combination is not possible with cleanflight atm.

**Comment by Lanzi2307** [comment]
Or maybe it's possible to use one of the motoroutputs. GPIO Pin is defined in the target.h file of the target. An idea would be to let the user select a port in gui which should be used.

**Comment by ledvinap** [comment]
It's not simple. RGB output needs exclusive use of whole timer and associated DMA channel. It's quite hard to make this generic.

**Comment by Lanzi2307** [comment]
Okay, thank you very much for clarifying this. I haven't seen that till now. Maybe something comes in my mind while studying the Cleanflight Code further.
