### ISSUE TITLE
IMU level errors caused by gyro saturation

### ISSUE THREAD

**Issue by digitalentity** [cleanflight/cleanflight#1467]
I've been reported several cases or machines crashing after switching to ANGLE more from rate mode. Some said the machines "forgot" about what level is. I believe I've found the source of the problem.

Gyro on our flight controller is hard limited to 2000 degress per second. However, RC rates might be configured to request rotation rate of more than 2000 dps and PID controller will try to push the actual rotation rate above this hardcoded limit.

IMU works by integrating data from gyro and slowly correcting it using accelerometer.

Imagine the quad rotating at 3600 degrees per second for 200 ms (doung a 720 deg rotation - double flip) starting from level and ending up level. That's what actually happend.
And this is what IMU calculated: gyro is reading 2000 dps for 200ms, IMU would calculate rotation or only 400 degrees and calculated attitude will be 40 degrees off.

**Comment by lostcontrol** [comment]
@digitalentity Just for my information, could you quickly explain why you closed this issue? Thank you.

**Comment by digitalentity** [comment]
@lostcontrol 
I figured that the issue is caused not by gyro saturation and was able to solve most cases of level errors or at least make them much less evident. PR #1411 has the related changes.

**Comment by ledvinap** [comment]
@digitalentity : Can you briefly explain the changes? It is not apparent when all commits are squashed ...

**Comment by lostcontrol** [comment]
@ledvinap Probably no something that should be done here but in PR #1411

**Comment by ledvinap** [comment]
@lostcontrol : Gyro overflow is not IMU specific. And there are some reports related to CF IMU, it may be related

**Comment by joshuabardwell** [comment]
With a cap of 2000 dps, it's hard to imagine that the gyro is ever saturating. That's 5.5. flips per second.

**Comment by ledvinap** [comment]
@joshuabardwell: 5 flips/s here: https://www.youtube.com/watch?v=wk0QbFjuz00
10 seems possible (but I cant find video now)

**Comment by joshuabardwell** [comment]
I can honestly say I've never seen anyone flip that fast before. Are the people who are experiencing autolevel drift on Cleanflight running rates that high?

**Comment by ledvinap** [comment]
From my point of view, 2000deg/s problem is interesting when using level mode as failsafe (or auto-failsafe). It is reasonable to depend on switching to level mode to work no matter what ...

**Comment by joshuabardwell** [comment]
I agree. I just don't think we're solving the problem people are actually currently having, if we're focused on saturation.

**Comment by digitalentity** [comment]
I've renamed and re-opened this issue. Gyro saturation issue is not solved.

**Comment by hydra** [comment]
@digitalentity what's next to do with this issue?
