### ISSUE TITLE
Support for more than 32 WS2812 LEDs

### ISSUE THREAD

**Issue by opiswahn** [cleanflight/cleanflight#1476]
Currently, Cleanflight supports up to 32 LEDs. Since there is no physical limit(besides computation time) to the number of supported WS2812 leds it would be nice to have a max of 48 or 64 led's.

**Comment by hydra** [comment]
actually there is a constraint, RAM usage.  Current implementation is RAM heavy due to use of DMA buffer to remove CPU/ISR load.
