### ISSUE TITLE
Smart Port Telemetry

### ISSUE THREAD

**Issue by frank26080115** [cleanflight/cleanflight#148]
I've implemented Smart Port telemetry and tested it

https://github.com/frank26080115/cleanflight/tree/smartport

It's a branch in a fork of cleanflight but I don't know how to issue a pull request between the two (sorry! I'm also a bit of a git noob)

If you like my implementation, consider adding it to master

https://github.com/frank26080115/cleanflight/wiki/Using-Smart-Port

I am working on a "hack-free" implementation as well, it might involve a custom bidirectional inverter cable

**Comment by avoid3d** [comment]
I'm up for this, was just wandering if sparkys uart could be inverted... Sweet :)

**Comment by hydra** [comment]
@avoid3d cool, do you have a sparky?

**Comment by avoid3d** [comment]
Just ordered one :)

![screenshot 2015-01-23 11 32 51](https://cloud.githubusercontent.com/assets/2152709/5881184/9e26f802-a2f3-11e4-860a-3413eaafa1bb.png)

**Comment by bhuism** [comment]
@avoid3d, are you still working on this issue? I'd love to help

**Comment by avoid3d** [comment]
I would love to, but alas I am very busy :(

On Fri, Mar 27, 2015 at 2:28 PM, Bas Huisman <notifications@github.com>
wrote:

> @avoid3d <https://github.com/avoid3d>, are you still working on this
> issue? I'd love to help
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cleanflight/cleanflight/issues/148#issuecomment-86926657>
> .
>



-- 
Pierre Hugo
Founder, MyNames <http://mynames.co.za/#/?ref=email>: Painless Domain
Management
Check if your brand is still available? <http://mynames.co.za/#/?ref=email>

**Comment by dkisselev** [comment]
@bhuism, some code was merged a few days ago that should theoretically make s-port telemetry work with the hardware inversion on F3 boards (like the sparky): #628, that might be a good place to see what's going on with it and try discuss the changes

**Comment by thenickdude** [comment]
#628 didn't change the situation with F3 inversion, though @ledvinap's potential fix on top of that might do once he tests it out.

**Comment by bhuism** [comment]
@dkisselev, thanks, I've got it connected to pwm6 now (tx of USART2) but haven't tested it yet (don't even know if that will work) I also wait for #635 to be merged, so that we have something to send over telemetry, awesome!
