### ISSUE TITLE
Eliminate RSSI smoothing, or option to eliminate it

### ISSUE THREAD

**Issue by packocrayons** [cleanflight/cleanflight#1481]
I want to receive new RSSI updates immediately, at the 50Hz measurement rate. If it is not already an option, can it be made that RSSI smoothing can be removed?

**Comment by readerror67** [comment]
wats the point? I don't thing MWOSD even updates RSSI dat quik

**Comment by dkisselev** [comment]
I imagine the effect would be compounding, so even though mwosd might be slow, the data it gets will be more accurate/timely.

**Comment by readerror67** [comment]
If your RSSI drops that fast that you need 50Hz real time updates, chances are your up the turd creek already...

**Comment by packocrayons** [comment]
I need to log RSSI delta with GPS position
