### ISSUE TITLE
Controls - Allow independent pitch and roll in-flight PID adjustment.

### ISSUE THREAD

**Issue by xxlegacyxx** [cleanflight/cleanflight#149]
Can the in flight pid adj for pitch and roll be separated? It currently adjusts both at once which is not very useful as most setups have different pid settings for pitch and roll

**Comment by maralcbr** [comment]
Would be very nice to have this feature.

**Comment by vadav** [comment]
As commented in the related configurator issue, there is few multis that dont need different PIDs on pitch and roll..   So this would be very usefull.

**Comment by Ozzy33** [comment]
Would be nice to have the option to be linked or not.

**Comment by thenickdude** [comment]
This was implemented in https://github.com/cleanflight/cleanflight/commit/e4a68862661a97acf35e16adbac9d5592bdebd23, closing.

**Comment by hydra** [comment]
@thenickdude no, it wasn't!

the requester wanted *PID* adjustment, e4a6886 was pitch and roll _RATE_ adjustment.

**Comment by thenickdude** [comment]
Whoops, sorry!!
