### ISSUE TITLE
Documentation Request: Cleanflight 1.10 PID's explanation

### ISSUE THREAD

**Issue by Ravid824** [cleanflight/cleanflight#1493]
Cleanflight team
Searching all the forums and couldn't find good explanations about what each of the PID setting (ROLL/PITCH/YAW, ALT/VEL, POS/POSr etc) is doing and what is the affect of each.
Need also a clear explanation of the PID's within each of the PID controllers available.

Cleanflight 1.10 is great and has huge improvements. The defaults are OK but requires some fine tuning. We are all strangling with understating what the new code is doing.
Please, please please, find some time to update the documents  

Thank you

**Comment by borisbstyle** [comment]
https://github.com/cleanflight/cleanflight/blob/master/docs/PID%20tuning.md
