### ISSUE TITLE
naze32 wont save settings

### ISSUE THREAD

**Issue by spudym** [cleanflight/cleanflight#1497]
Just after cleanflight updated to 1.0.0 and updated firmware for the naze32 nothing will save when i am on the configuration page of cleanflight.it only gives a rebooting message and nothing changes.
So not shore if its the cleanflight or the firmware update
I would appreciate any suggestions.

**Comment by SteveAmor** [comment]
Sorry for your problem but this is a support question, not an issue. Please consider asking such questions in a support environment such as RC Groups or #cleanflight, rather than diverting developer time. 

Please close this issue.
