### ISSUE TITLE
battery discharge compensation

### ISSUE THREAD

**Issue by aerretechnology** [cleanflight/cleanflight#1499]
It's possible to auto calibrate the hovering middle position of the throttle stick when the battery discharge.
This features are good for example if use 4s or 6s battery indifferent.
Sorry for my english.

**Comment by digitalentity** [comment]
Do I understand correctly - you want to have a copter hovering at 50% throttle regardless of battery discharge?

**Comment by aerretechnology** [comment]
Yes this is my idea.
For example the hovering value is 1400 ppm at 14v if the battery discharge
the ppm to mantein the hovering is to higher.
Then to replace 4s battery to an 6s the hovering value is to small and the
naze compensates the throttle value.

Inviato da AERRETECHNOLOGY mobile.
Il 17/Nov/2015 14:27, "Konstantin Sharlaimov" <notifications@github.com> ha
scritto:

**Comment by digitalentity** [comment]
It's not possible to do without altitude sensor (baro). And even with baro it will be tricky.

**Comment by lostcontrol** [comment]
While not exactly what requested here, APM:Copter has something in this spirit to compensate for voltage drop: http://copter.ardupilot.com/wiki/current-limiting-and-voltage-scaling/#voltage_scaling

**Comment by joshuabardwell** [comment]
Setting the ESCs to closed-loop mode may have a similar effect.

**Comment by aerretechnology** [comment]
Ok testing the esc mode

**Comment by jcowgar** [comment]
Maybe I am misunderstanding the original request, but isn't it a throttle curve? The way I understand the original request is not for voltage drop across a single battery, but is for when one uses a 3s for some flights and a 4s for other flights. For example, take an extreme case of flying with a 2s, The throttle may be 75% to hover then moving to a 6s may be at 5% to hover.

With PID banks, couldn't you configure the throttle curve and and throttle mid? Likely the PIDs would need adjusting for the various battery types anyway.

**Comment by joshuabardwell** [comment]
I don't think Cleanflight currently has the ability to adjust the throttle curve like you are describing. You can adjust the amount of throttle expo and the mid-point of the expo curve. But you can't slide the entire throttle curve up and down like this.

**Comment by bdoiron74** [comment]
My battery compensation code could be modified to do this. You'd probably
need hover voltage and hover throttle % parameters and then scale the
throttle input automatically based on battery voltage. Either by expo or
two-piece linear. I linearly scaled the whole thing, which just increased
the amount of dead space at the top as the battery depleted, but I don't
think that would be appropriate for cell count changes.

For the PIDs, you just need a base voltage and apply scaling accordingly. I
used the battery warning voltage and reduced the gain proportionally if the
battery was above that. You could run into resolution issues if you want to
handle huge voltage differences, but the floating point PIDs should be ok.
https://github.com/cleanflight/cleanflight/pull/1152

**Comment by universam1** [comment]
+1
Eagerly waiting on PID scaled to voltage. Keep on good work!

**Comment by bdoiron74** [comment]
@universam1  Keep an eye on this pull : https://github.com/cleanflight/cleanflight/pull/1805

It won't handle switching batteries, but I can see further development allowing it to. It would be pretty cool to not only adjust to battery drain, but also battery maxVoltage*cellcount. As-is, the top side of stick ends up being a dead zone as the battery drains, so it probably isn't the right way to handle different battery types. Remapping the stick throttle curve based on battery type might be a simple way around it though.
