### ISSUE TITLE
Issue with RX_MSP on UART2

### ISSUE THREAD

**Issue by lotelx** [cleanflight/cleanflight#1507]
Hi,
I'm tying to have Bluetooth connected in UART2 without success.

I can easily connect the module in UART1 and it works perfect with ez-gui.
But if I connect the Bluetooth to UART2 I have no packets received message.

I want to control by MSP messages by bluetooth/wifi on UART2

If I try this:
# feature RX_MSP
Enabled RX_MSP

# set serial_port_2_scenario = 8
Invalid name

Why I can't change the scenario for UART2?

**Comment by stronnag** [comment]
The command you quote is obsolete. Please follow the instructions in https://github.com/cleanflight/cleanflight/blob/master/docs/Serial.md and then close the issue. This is not a support forum (please use rcgroups or IRC for support).
