### ISSUE TITLE
Debug[x] from cli ?

### ISSUE THREAD

**Issue by Fvk1960** [cleanflight/cleanflight#151]
Is it a good idea to enable the several debug[x] variables from cli. Like dbg=Autotune or dbg =altitudehold and replace the 
if 0 
debug[0]=xxx;
....
by
if dbg=Altitudehold
debug[0]=xxx;
.......

So each user can easily see related debug values from GUI without need of changing and recompiling
ps altitudehold.c is missing declaration for debug[x]

Forgive me if this is not the right way to do request or suggestions

**Comment by hydra** [comment]
Closing. previous comment still applies and there have been no other requests for this.
