### ISSUE TITLE
Invalid S.BUS decoding on PC

### ISSUE THREAD

**Issue by DreamNik** [cleanflight/cleanflight#1510]
Hi!
I've attached hardware S.BUS receiver to PC and tried to decode it.
(https://github.com/DreamNik/cleanflight/tree/x_plane)
(https://github.com/cleanflight/cleanflight/pull/1496)

The channel values were invalid. I've checked and looks like bit fields https://github.com/DreamNik/cleanflight/blob/master/src/main/rx/sbus.c#L108-L123 behave differently on different platforms.

I've created simple platform-independent decoder instead:
https://github.com/DreamNik/cleanflight/tree/fix_sbus_1

P.S. should I create new pull request for this?

**Comment by ledvinap** [comment]
The struct bitfield  generates very fast code, notably on ARM with bitfield instructions. It will be probably better to fix structure declaration to make it work on PC.

Maybe just `unsigned syncByte:8`?

As for programatical bit extraction - on 32 bit machine it will be faster to read whole 32bit words and then handle bit extracting as mask / shift, refilling or joining or word boundaries.

**Comment by DreamNik** [comment]
Well, the problem is that this bitfield IS platform dependent anyway.
C99 standard:
"If enough space remains, a bit-field that immediately follows another bit-field in a
structure shall be packed into adjacent bits of the same unit. If insufficient space remains,
whether a bit-field that does not fit is put into the next unit or overlaps adjacent units is
implementation-defined"

For example, on PC (MinGW,gcc) bits are packed this way:
11 bit field 1 ; 11 bit field 2 ; 10 bit padding ; 11 bit field 1 ; 11 bit field 2 ; 10 bit padding ; etc..

C/C++  tries to pack as many bitfields into "unsigned int" structure. It packs 2 of them, and adds 10 bit padding.

> Maybe just unsigned syncByte:8?
"unsigned" = "unsigned int" on 32 bit cpu, the same thing. Maybe you meant "unsigned short"?
I've tried that - packing becomes:
11 bit field 1 ; 5 padding ; 11 bit field 2 ; 5 bit padding ; etc..

All stuff like "__atribute((packed))__" , "#pagra pack..." doesn't affect this.

So I don't know current platform independent way to do this with bitfields.

**Comment by DreamNik** [comment]
I'll setup toolchain for ARM target and check what code generated with bitfields and other methods. Then I'll choose fastest and/or smallest version.

**Comment by ledvinap** [comment]
@DreamNik : The idea was to make syncByte bitfield too.

What compiler are  you using?

**Comment by DreamNik** [comment]
> The idea was to make syncByte bitfield too.
Oh, I understood.
But this won't resolve issue.

> What compiler are you using?
gcc (i686-posix-dwarf-rev1, Built by MinGW-W64 project) 4.9.2

**Comment by ledvinap** [comment]
maybe use attribute ((gcc_struct)) on windows?
https://gcc.gnu.org/onlinedocs/gcc/x86-Type-Attributes.html#x86-Type-Attributes

**Comment by DreamNik** [comment]
This one did the trick!

**Comment by DreamNik** [comment]
But I've already noticed that new version takes less size in code. Is it worth to analyze performance?

**Comment by DreamNik** [comment]
Old one:
   text    data     bss     dec     hex filename
 118804     208   14144  133156   20824 ./obj/main/cleanflight_NAZE.elf
arm-none-eabi-objcopy -O ihex --set-start 0x8000000 obj/main/cleanflight_NAZE.elf obj/cleanflight_NAZE.hex

./obj/main/NAZE/rx/sbus.o:     file format elf32-littlearm

Sections:
Idx Name          Size      VMA       LMA       File off  Algn
 65 .text.sbusFrameStatus 00000138  00000000  00000000  00002434  2**2
                  CONTENTS, ALLOC, LOAD, RELOC, READONLY, CODE

**Comment by DreamNik** [comment]
New one:
   text    data     bss     dec     hex filename
 118668     204   14144  133016   20798 ./obj/main/cleanflight_NAZE.elf
arm-none-eabi-objcopy -O ihex --set-start 0x8000000 obj/main/cleanflight_NAZE.elf obj/cleanflight_NAZE.hex

./obj/main/NAZE/rx/sbus.o:     file format elf32-littlearm

Sections:
Idx Name          Size      VMA       LMA       File off  Algn
 65 .text.sbusFrameStatus 00000080  00000000  00000000  000025d8  2**2
                  CONTENTS, ALLOC, LOAD, RELOC, READONLY, CODE

**Comment by DreamNik** [comment]
Well, maybe the speed is more important with new scheduler on the way.

**Comment by ledvinap** [comment]
Personally I would prefer generic bitstream decoder (it may be used in other places eventually).
Using 32bit buffer and assuming that at most 32 bits may be extracted , it should be quite easy to implement..
That way frame decoding will be quite easy to read ..

**Comment by DreamNik** [comment]
But at expense of cpu cycles...
Or it isn't as critical as I imagine?

**Comment by ledvinap** [comment]
something like: 
```
typedef struct bitstream_s {
  unsigned *dptr;
  unsigned acc;
  unsigned acc_bits;
} bitstream_t;


uint32_t bitstream_extract(bitstream_t *bs, unsigned bits)
{
  uint32_t ret = 0;
  while(bits > 0) {
    if(!(bs->acc_bits)) {
      bs->acc = *bs->dptr++;
      bs->acc_bits = 8 * sizeof(*bs->dptr);
    }
    unsigned chunk = MIN(bits, bs->acc_bits);
    ret <<= chunk;
    ret |= bs->acc & ((1LL << chunk) - 1);
    bs->acc >>= chunk;
    bs->acc_bits -= chunk;
    bits -= chunk;
  }
  return ret;
}
```
It may optimize quite nicely ...

BTW: 32bit extraction should be special-cased on Intel, instead of 64bit shift trick; on ARM `(1 << 32) -1` will work correctly..

Little-endian is assumed.

**Comment by DreamNik** [comment]
Won't this "caching" of 32-bit data cause any unwanted out-of-array reads?
It sounds unlikely, but just to be sure.

**Comment by ledvinap** [comment]
Yes, it may read after array. Caller is expected to stop reading when actual buffer is exhausted, so stray data will be ignored. Padding bytes will be usually in this area ... 

Another problem is that aligned buffer start is assumed. It may be fixed with improved bitstream_t initialization (preload unaligned part into acc and set number of bits accordingly)

**Comment by DreamNik** [comment]
WIP - Right now  I'm writing 4-byte aligned bitstream reader :)

**Comment by DreamNik** [comment]
Should I create new branch and pull request for bitstream?

**Comment by DreamNik** [comment]
Ok, introduced myself to unit testing.
Here's code:
https://github.com/DreamNik/cleanflight/tree/add_bitstream
