### ISSUE TITLE
Ex.Bus (Jeti) support för cleanflight? 

### ISSUE THREAD

**Issue by kajakmannen** [cleanflight/cleanflight#1513]
Ex.Bus (Jeti) support för cleanflight? 
Any code wizard that can make it happen? :D pretty please with suger on top.

Here is the documentation for Ex.bus protocol which maybe makes it easier to determine if it is possible or not.

http://www.jetimodel.com/en/show-file/642/

Thanks in advance for someone to reply on this issue, Kajaken

**Comment by hydra** [comment]
There was a PR for this here: https://github.com/cleanflight/cleanflight/pull/1563

**Comment by marv-t** [comment]
This is the new PR: #1709
