### ISSUE TITLE
Led strip issue

### ISSUE THREAD

**Issue by joeynuggetz** [cleanflight/cleanflight#1516]
I have been experiencing some issues with mapping the indicator function on certain leds in a strip. Using a 6 led strip I have been experiencing intermittent problems where the leds on the ends of the strip fail to light up. Not sure if this is related to my strip or not. I ordered a strip of assignable leds and cut off a section of 5 or 6 and once I added them to the chain the assignments were more reliable and was able to get the intended LEDs to function as indicators. Here is the original strip and the set I got to test adding more to the chain. 
http://amzn.com/B0140W5AEE    Im not using the buzzer
http://amzn.com/B00JR0MJIU     These suck by the way.

**Comment by add1ct3dd** [comment]
Sounds like a hardware issue?

**Comment by joeynuggetz** [comment]
Not sure. I don't recall having any issue setting led color. Just the indicator function at times. Will do more testing tonight.

**Comment by hydra** [comment]
hardware issue, please post on forums first for support.
