### ISSUE TITLE
 Crash Sense Feature

### ISSUE THREAD

**Issue by Ozzy33** [cleanflight/cleanflight#1522]
What about a feature that could detect a crash and immediately stop motors and or disarm to prevent motor/ESC damage? Blackbox data should give good feedback on crashes data. Of course it should be an option to enable it and set motor stop or disarm. Priority = ultra low.

**Comment by digitalentity** [comment]
That would be a super cool thing to have, however this should have zero false positives if you don't want your quad to disarm inflight on its own.

**Comment by borisbstyle** [comment]
Good configured failsafe or manual disarming does the same thing

**Comment by ProDrone** [comment]
I had the same idea in my mind for about a year, then i saw the discussion about it here: http://www.rcgroups.com/forums/showthread.php?t=2464844&page=310#post32853731

When it is implemented it should be as reliable as our airbag systems, maybe requiring dedicated sensors. I think it will turn out to be the one feature that is always turned off.. Or it will be used as a scapegoat for unexplained crashes (well, that may come in handy ;-)

**Comment by Yamaford** [comment]
Looking at my blackbox logs its pretty easy to see a crash. All 3 Gyro's go completely nuts. That would be pretty hard to duplicate on purpose while doing acro maneuvers.
![crash](https://cloud.githubusercontent.com/assets/13566044/11911218/8b9246ce-a5c2-11e5-9c43-f037678752f1.JPG)

Attached you can see a lot of gyro action, throttle is below min check and there are no RC commands on any axis. That would be a good time to stop the motors.
