### ISSUE TITLE
Modes/aux channels are not working on naze32 with spektrum RX

### ISSUE THREAD

**Issue by Austinthemighty** [cleanflight/cleanflight#1542]
Just flashed the latest version of cleanflight to my naze32 v6 with spektrum RX and TX, went into the receiver tab changed the channel map to TAER1234 and then went into modes and set my aux 2 switch to arm and my aux 1 to angle, and horizon mode, saved, turned on the TX and my new versacopter from flitetest which is running a naze32 v6 and it would not receive a signal from the aux channels, only way to arm it is throttle low and right yaw

**Comment by jtp755** [comment]
Double-check your receiver setting on the Configuration page as well as this in the CLI: serialrx_provider

**Comment by Austinthemighty** [comment]
i already did that, 3-4 times

**Comment by SteveAmor** [comment]
Assuming you are using PWM, does the Aux channel work if configured as AETR?
