### ISSUE TITLE
ESC Programing mode enhanchment

### ISSUE THREAD

**Issue by Austinthemighty** [cleanflight/cleanflight#1549]
It would be nice if there was a way to program your esc from your flight controler, like if there was a tab that you went to and you could use your arrow keys to control the values of the output. it would be something similar to testing the motors where you set the output speed of the motors.
something simmilar to this.
https://www.youtube.com/embed/AjLJZlG2TnU
and this
https://www.youtube.com/watch?v=E6epG5E8gAQ

**Comment by joshuabardwell** [comment]
You mean like this?

https://www.youtube.com/watch?v=YWLk4qcQcvw

**Comment by dkisselev** [comment]
I think he's asking to add a full BlHeli configuration UI into CF configurator?

BLHeli and Cleanflight are totally independent projects so BLHeli might add/change features or commands to their serial protocol at any point. I don't think it's worth the Cleanflight team's time to track these changes and constantly update the cleanflight configurator to make sure it can still configure BlHeli devices, so the above video is the best way to do it anyway.

**Comment by joshuabardwell** [comment]
I agree. Passthrough allows the projects to remain in separate development cycles, which is ideal.

**Comment by Austinthemighty** [comment]
Something like where I plug in the battery to the quad and then I hit the up and down arrow keys to simulate the throttle from my transmiter, it is really annoying programing each individual esc one by one.

Also I was not able to watch the video at the time of writing this as it is currently block at my location.

**Comment by dkisselev** [comment]
Why not just use the motor output tab to do that like you linked above? It does exactly that (simulates transmitter outputs to the esc's).

**Comment by joshuabardwell** [comment]
Ahh, yeah. The Motors tab totally already does this.

ISSUE CLOSED!

**Comment by Austinthemighty** [comment]
I had a hard time doing that way, even when using a mouse or a touchscreen computer, how about a switch in the motors tab that you can slide and it will jump all the way to the top or to the bottom when you press the up and down arrows

**Comment by joshuabardwell** [comment]
Left-click on the motor slider, then use up/down arrows to make fine adjustments or Page Up/Page Down to make broad adjustments.

ISSUE CLOSED! (LOL)

**Comment by fftunes** [comment]
Or just click the very top and very bottom of the motor slider. It will jump to endpoints.

**Comment by Austinthemighty** [comment]
that was what i was doing until now, now i am pressing home and end.
