### ISSUE TITLE
Arm Disarm Arm locks FC requires power cycle

### ISSUE THREAD

**Issue by Exidouce** [cleanflight/cleanflight#155]
As stated in the title using the most recent revision (30 Oct 14) when the FC is Armed then disarmed, the FC will not Arm again. FC is completely locked up and required the power be removed. Using a Naze32 full board currently.

This was not an issue with build date 18 Oct 14.

**Comment by sher1ock** [comment]
I'm having the same problem with a flip 32. telemetry isn't even turned on...
