### ISSUE TITLE
v1.11.0-RC1 - G-Tune - no option to enable?

### ISSUE THREAD

**Issue by jaffadog** [cleanflight/cleanflight#1550]
I am experimenting with the v1.11.0-RC1 firmware, which lists G-tune as one of the changes introduced.  Configurator v1.1.0 is prescribed for this firware version, but I'm not seeing any option to eable G-Tune in the "Modes" tab.  I tried to assign it int he CLI with "aux 2 26 0 1600 2100", but now in the "Modes" tab it claims "Failsave" is enabled by that aux button.

**Comment by paulwas** [comment]
I too am experimenting with v1.11.0-RC1 on a Naze32 FC with Baro & Mag but can't find an option to Enable G-Tune. I'm also using 1.1.0 the CFG. It's not listed on the Modes tab in the GUI and I can't find any mention of it or any of the "gtune_.." parameters in the CLI. Is there something else we need to do?

**Comment by chasers** [comment]
It's in the inflight adjustments tab ... seems to be working pretty well for me at least.

**Comment by jaffadog** [comment]
g-tune is in the "adjustments" tab?  I'm not seeing it there either (in CFG 1.1.0)...

**Comment by paulwas** [comment]
Thanks for the tip, I hadn't looked there. Unfortunately, my adjustments list (see .jpg) doesn't show anything for G-Tune. Is there anything else I need to do to enable it? I've verified that I do actually have the right FC flashed (Flight controller info, identifier: CLFL, version: 1.11.0) and I'm running the right CFG (OS: Windows, Chrome: 47.0.2526.73, Configurator: 1.1.0). I've also looked thru all the CLI variables and don't see anything having to do with gtune. I'm guessing there's just something dumb I'm missing..

![adjustments](https://cloud.githubusercontent.com/assets/7895210/11671815/b55ff40c-9dbf-11e5-8e1f-6eddbb50a6eb.jpg)

**Comment by chasers** [comment]
Oh derp I think I meant the receiver tab, wherever you set your ranges for
your flight mode. It's where Autotune used to be.

Here's a good video: https://youtu.be/_16hyAnJJTY

On Tue, Dec 8, 2015, 16:31 Paul Waszkiewicz <notifications@github.com>
wrote:

> Thanks for the tip, I hadn't looked there. Unfortunately, my adjustments
> list (see .jpg) doesn't show anything for G-Tune. Is there anything else I
> need to do to enable it? I've verified that I do actually have the right FC
> flashed (Flight controller info, identifier: CLFL, version: 1.11.0) and I'm
> running the right CFG (OS: Windows, Chrome: 47.0.2526.73, Configurator:
> 1.1.0). I've also looked thru all the CLI variables and don't see anything
> having to do with gtune. I'm guessing there's just something dumb I'm
> missing..
>
> [image: adjustments]
> <https://cloud.githubusercontent.com/assets/7895210/11671815/b55ff40c-9dbf-11e5-8e1f-6eddbb50a6eb.jpg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cleanflight/cleanflight/issues/1550#issuecomment-163056251>
> .
>
-- 
Chase Granberry
Founder @ AuthorityLabs
602-626-0922

**Comment by chasers** [comment]
Yeah what I really meant was the Modes tab!
![screenshot 2015-12-08 20 29 05](https://cloud.githubusercontent.com/assets/1019814/11675856/80287c7a-9dea-11e5-8f92-e8c08be31cba.png)

**Comment by paulwas** [comment]
Thanks for your help and the video link. That is what I thought you meant but GTUNE isn't showing up for me. I see you're on a MAC and I'm on Windows so that might be it. Otherwise there may be something else I need to do to get it to show up. I'll keep digging to see if I can figure it out..

![modes](https://cloud.githubusercontent.com/assets/7895210/11693745/7100dc9e-9e5b-11e5-9e9b-fbf02a5f43e1.jpg)

**Comment by jaffadog** [comment]
Chasers, can you confirm what firmware version you are running?

**Comment by paulwas** [comment]
Sure. It's 1.11.0, the RC version. And the CFG version is 1.1.0. I've flashed it several times back and forth from 1.10 and 1.11 and re-configured it manually each time. And my FC is a Naze32 with Baro and Mag (10DOF). Don't know how much this matters but I don't have a receiver connected to it. So far I'm just testing the FC stand-alone. I have tried powering it with a BEC before plugging the USB port in but that made no difference.

**Comment by chasers** [comment]
<img width="491" alt="screenshot 2015-12-09 17 24 39" src="https://cloud.githubusercontent.com/assets/1019814/11703168/f1a8056e-9e99-11e5-9028-d2e46f776265.png">

**Comment by jaffadog** [comment]
Humm... @chasers has a SRF3 board, whereas @paulwas and i have a AFNA.  The problem seems to be that GTUNE is not enabled for the AFNA:
 https://github.com/cleanflight/cleanflight/blob/master/src/main/target/NAZE/target.h

**Comment by jaffadog** [comment]
https://github.com/cleanflight/cleanflight/pull/1557

**Comment by flounderscore** [comment]
Same issue with RMRC Dodo. Pull request #1566

**Comment by GeertMeyer** [comment]
Same issue With Skyline32

**Comment by hydra** [comment]
some changes have been made which allow gtune to fit on the naze board now.  merged.
