### ISSUE TITLE
v1.11.0-RC1 - setting gps_sbas_mode to "Disabled" causes CLI dump to fail

### ISSUE THREAD

**Issue by jaffadog** [cleanflight/cleanflight#1551]
I am using v1.11.0-RC1 fw / v1.1.0 configurator.  When I set GPS "ground assistance type" to "Disabled" in the "Configuration" tab (i.e. gps_sbas_mode), CLI dump no longer works properly and chokes when trying to dump the gps_sbas_mode value.

**Comment by hydra** [comment]
this is an error in the configurator. there is no 'disabled' setting in the firmware.

**Comment by hydra** [comment]
please test latest development configurator where a fix has been applied.  If there's still an issue please open an issue in the configurator issue tracker.
