### ISSUE TITLE
Help to set up the Quanum Pico (AFNA Board) with Cleanflight

### ISSUE THREAD

**Issue by mottex** [cleanflight/cleanflight#1571]
Hi there,

I have some problems with the board, i can connect to cleanfligt (installed the actual Naze32 firmware).
But i can´t bind to my dx6i transmitter... I tried various modes. DSM2 standard and DSM2 Highspeed.

The board has an integrated receiver for DSM2, which points must be set in cleanflight?

Thanks for your help.

regards andreas

**Comment by hydra** [comment]
the issue tracker is not for support. please use rcgroups forums or irc.
