### ISSUE TITLE
suggestion: better layout for small screens please!

### ISSUE THREAD

**Issue by huibuuh** [cleanflight/cleanflight#1610]
I noticed today after my cleanflight updated itself, that it is now almost unusable on my small screen. In the pre 1.x versions I could easily use cleanflight on my small screen in the field. Now I can hardly see things anymore.

please change the layout so that it is possible to use the program on small devices outside in the field again!
![2015-12-21 1](https://cloud.githubusercontent.com/assets/16387467/11935098/34b6acb4-a806-11e5-8454-d462ff66137a.png)

**Comment by joshuabardwell** [comment]
The configurator is a separate project, and is where this issue should be raised.

https://github.com/cleanflight/cleanflight-configurator

**Comment by SteveAmor** [comment]
Please can you close this issue and open one under the cleanflight configurator repo.
