### ISSUE TITLE
Drop "OpenPilot" compatible mode from CC3D board documentation

### ISSUE THREAD

**Issue by huston007** [cleanflight/cleanflight#1617]

**Comment by stronnag** [comment]
Good plan. It would also be helpful to provide more detailed documentation about how to get CF hex into CC3D in the first instance, and the subsequent need not to short boot pins. Emphasise the use of the main port. For bonus points, describe stm32flash as the answer to everything CC3D flashing related.

**Comment by hydra** [comment]
done
