### ISSUE TITLE
IO - Support camstab on Tricopters

### ISSUE THREAD

**Issue by add1ct3dd** [cleanflight/cleanflight#162]
Hey guys,

I realise the tricopter takes up a servo as it is, but could we not use the other servo for pan or tilt?

I know a couple of people (myself included), who would love nothing more than to move their tricopters over from the KK2.0 to a Cleanflight board :)

Cheers.

**Comment by chilternflyer** [comment]
+1 
I can see why it's not working in MultiWii and I could fix it there (using the Arduino IDE)  but I've got no idea how to change it on this platform.
All we need is the tilt servo enabled (forget the roll).
Can someone help us please.

**Comment by Elo319** [comment]
+1
tilt servo would be nice

**Comment by hydra** [comment]
Blocked by #357 and #884

**Comment by chilternflyer** [comment]
It looks like we are getting some movement on this. (fingers crossed).

**Comment by hydra** [comment]
Works now.

Please test this: https://github.com/cleanflight/cleanflight/pull/1066
