### ISSUE TITLE
Failsafe - FAILSAFE box mode does not actually trigger failsafe

### ISSUE THREAD

**Issue by digitalentity** [cleanflight/cleanflight#1633]
I was looking at this part of code: https://github.com/cleanflight/cleanflight/blob/master/src/main/flight/failsafe.c#L187-L207

It occured to me that FAILSAFE mode won't actually trigger failsafe procedure. To be able to safely and reliable test failsafe procedure this must be fixed.

@ProDrone you probably know ins and outs of the code better than anyone here. Can you assist in fixing this?

**Comment by digitalentity** [comment]
@ProDrone 
See 90e9297 for a possible fix.

**Comment by ProDrone** [comment]
@digitalentity Triggering is indirectly done from RX here: https://github.com/cleanflight/cleanflight/blob/master/src/main/rx/rx.c#L526

I did that on purpose to test/simulate a loss of signal. What do you think?

**Comment by digitalentity** [comment]
Ah, I see. Perfect! Means that we still can signal a failafe to the FC even if our receiver continues to send valid signals on link loss.
