### ISSUE TITLE
CC3D No softserial

### ISSUE THREAD

**Issue by Butzi250nighrhawk** [cleanflight/cleanflight#1634]
I flashed CF v 1.9 on my CC3D over OP GCS. Everything fine, motors and esc work. But in Ports tab there are only USBVCP UART1 and UART3, no Softserial. When i choose  RX_Serial or RX_PARALLEL_PWM and reboot no rx mode is ticked. RX_PPM and RX_MSP stay when rebooting, but no softserial shows up. Before I flashed my FC with OP, I once did the Wizard of OP and the rx worked.
(Using Spektrum AR6210 rx, for RX_PARALLEL_PWM)

**Comment by Flugsicherung** [comment]
You must use Cleanflight Configurator for the settings. On the Configuration Tab you can switch on the Soft Serials and make the settings for your Reciever. OP GCS is only for flashing the Firmware to the CC3D Board.

**Comment by SteveAmor** [comment]
@Butzi250nighrhawk if this has answered your support question, can you please close this issue.

**Comment by hydra** [comment]
Please use forums for support.
