### ISSUE TITLE
makefile cleaning

### ISSUE THREAD

**Issue by MauroMombelli** [cleanflight/cleanflight#1635]
in makefile, EUSTM32F103RC PORT103R (line 121) execute the same identical code than the else branch (generic f10x board like NAZE etc..) witch basically translate the if at line 75 instead to board-based, to MCU based (F3 or F1, and hopefully soon the F4)

more to come..

**Comment by hydra** [comment]
it's not the same. the main difference is the inclusion of the device flags but I agree that it could be cleaner.

If you want to have a go just submit a PR and reference this issue.
