### ISSUE TITLE
ITerm no longer scaling by PIDweight in pidMultiWiiRewrite

### ISSUE THREAD

**Issue by martinbudden** [cleanflight/cleanflight#1639]
Currently the code is:

    errorGyroI[axis] = errorGyroI[axis] + ((RateError * cycleTime) >> 11) * pidProfile->I8[axis];

in version 1.10 the code was:

    errorGyroI[axis] = errorGyroI[axis] + ((RateError * cycleTime) >> 11) * pidProfile->I8[axis] * PIDweight[axis] / 100;

Is this a deliberate or accidental change?

**Comment by SteveAmor** [comment]
I'd say deliberate:

https://github.com/cleanflight/cleanflight/commit/bc0a30780fa6bd2dbc61fd3d6a43d27ff680615a

**Comment by martinbudden** [comment]
Closing. It was a deliberat change.
