### ISSUE TITLE
Add GUI support to bind dsm2/dsmx satellite receiver to transmitter

### ISSUE THREAD

**Issue by akcom** [cleanflight/cleanflight#164]
It would fantastic if CF GUI supported the ability to bind a satellite receiver to a transmitter so that we don't have to hook up a main receiver to bind the two the first time.

**Comment by hydra** [comment]
Working on cleaning up the serial port scenario stuff.  See 5163bef0b2ff8e1f863c4c66d54b4c5ee8b287dc

**Comment by hydra** [comment]
Firmware has support for spektrum bind, See MSP_RX_CONFIG.

Open a new issue in the GUI issue tracker that requests adding a button to bind the RX instead of via CLI.   Please reference this issue.

Nothing left to do for the firmware as I understand it.
