### ISSUE TITLE
contankt between radio and quad

### ISSUE THREAD

**Issue by ACETOPPER** [cleanflight/cleanflight#1644]
i hooked up my srd 250 with openpilot, and the radio disconnekted. now there is no contakt between quad and radio. i tried to reset the reciever and trebind but still no connektion. does anybody hawe an idea?

**Comment by SteveAmor** [comment]
Sorry for your problem but this is a support question, not an issue. Please consider asking such questions in a support environment such as RC Groups or #cleanflight, rather than diverting developer time. 
Please can you close this issue. Thank you.

**Comment by hydra** [comment]
Please use forums for support.
