### ISSUE TITLE
Naze32 CLI states invalid value (FRSKY Telemetry)

### ISSUE THREAD

**Issue by Sanguine7** [cleanflight/cleanflight#1656]
I followed Painless360'S vid on how to setup the naze 32 with frsrky telemetry but the cli only allows me to enable softserial and telemetry when i want to set the baud rate or do more the cli shatters every comand as "invalid value".
I hope this is just me having overseen something and someone can help

**Comment by readerror67** [comment]
Maybe you should like, paste the input/output instead of referencing a video.

**Comment by Sanguine7** [comment]
Sorry my bad,
D4R-II is in PPM mode connected to naze32, RX cable is soldered to pad 6
then i followed the guidelines in option 2
http://www.netraam.eu/nazewiki/pmwiki.php?n=Howto.FrskyTelemetry

feature SOFTSERIAL
feature TELEMETRY

those two where accepted

set softserial_baudrate=9600
set softserial_1_inverted=1
set telemetry_port=1
set telemetry_provider=0

for those 4 the CLI states "invalid value"

**Comment by SteveAmor** [comment]
Just read the release notes

NOTE: CLI get/set commands have changed. some variables are now set using OFF/ON instead of 0/1.

This applies to telemetry.

**Comment by Sanguine7** [comment]
Doesn't work either and this does not explain why i can't set baud rate
![cli test](https://cloud.githubusercontent.com/assets/16558440/12116281/f3e62f0c-b3b8-11e5-8a6e-5910e972d910.jpg)

**Comment by lostcontrol** [comment]
*softserial* does not exist (anymore I guess) as CLI command in Cleanflight. Look at https://github.com/cleanflight/cleanflight/blob/master/docs/Serial.md

**Comment by SteveAmor** [comment]
The instructions you are following were last updated on July 02 2014. Lots has happened since then.  Those commands no longer exist. Have a look at:

https://github.com/cleanflight/cleanflight/blob/master/docs/Cli.md
https://github.com/cleanflight/cleanflight/blob/master/docs/Telemetry.md

Failing that, please ask support questions at RC Groups or IRC #cleanflight.

**Comment by Sanguine7** [comment]
OK so i get that a lot has changed
@SteveAmor the comands given in your links don't work either
same problem that he does not know the command telem inversion given in link 2

So can anybody give me a link or commandline which enables me to use my frsky d4r-ii via softserial port 6? without external inverter?

i've seen that i can activate softserial and telemetry in the setup and set my softserial to frsky telemetry with baud 9600 in the config but my taranis still shows me no telem data

**Comment by hydra** [comment]
Please use forums for support.
