### ISSUE TITLE
Use buzzer to match blackbox log to video

### ISSUE THREAD

**Issue by ipburbank** [cleanflight/cleanflight#1669]
It would be great if the buzzer could optionally indicate what blackbox index it is recording to when the device is armed (e.g. buzz five times for index 5) to make matching logs to videos easier.

**Comment by readerror67** [comment]
That could be a mess when you get up to the double digits...

A more usable implementation would be to utilize the alarm system that @dustin implemented in MWOSD:
https://github.com/ShikOfTheRa/scarab-osd/commit/32c6a453c965f275576e34b3fc20902d3299fecf

**Comment by ipburbank** [comment]
Perhaps long beeps could be tens, so *long short short* is log id 12.
