### ISSUE TITLE
TAER1234 receiver Tab Missing all AUX channels 

### ISSUE THREAD

**Issue by solaris3000** [cleanflight/cleanflight#1671]
Dragonfly32, Cleanflight ver 1.11 
radio-Taranis X9D
rec-D4R-II

under the receiver tab the TAER channels are working. 
All AUX channels unresponsive. (no GUI slider movement when switches are moved)
Flashed to older ver of Cleanflight firmware with same result....

Attempted same setup with Walkera F12E and RX703 receiver and able to see AUX channels along with AETR mapping selected.

Thanks for looking into this issue..
B.

**Comment by joshuabardwell** [comment]
This is almost certainly a support issue, not a development issue.

https://github.com/cleanflight/cleanflight/blob/master/CONTRIBUTING.md

>Please remember the issue tracker on github is not for user support. Please also do not email developers directly for support. Instead please use IRC or the forums first, then if the problem is confirmed create an issue that details how to repeat the problem so it can be investigated.
