### ISSUE TITLE
little documentation problem

### ISSUE THREAD

**Issue by latomgo** [cleanflight/cleanflight#1679]
Hi,
the heading of the "Board - CC3D" section is wrong formatted in the documentation:
![image](https://cloud.githubusercontent.com/assets/16700832/12321139/e034fda8-baac-11e5-9237-d431747b28de.png)
It's hard to see that a new section starts.
Thomas

**Comment by SteveAmor** [comment]
Did you want to have a go at raising a pull request to fix? 

https://github.com/cleanflight/cleanflight/blob/master/docs/development/Development.md#using-git-and-github

**Comment by latomgo** [comment]
this is just a hint, do whatever is necessary to correct the documentation.
I'm a user, no developer, no github knowledge at all. sorry, if this is the wrong place for my issue.

**Comment by SteveAmor** [comment]
That's cool. It's a documentation issue that needs fixing. I'll take a look later :)

**Comment by SteveAmor** [comment]
@latomgo PR raised.  Could you close this issue please (to keep things tidy).

**Comment by latomgo** [comment]
ok, thank you
