### ISSUE TITLE
Option to allow arming regardless of current attitude

### ISSUE THREAD

**Issue by iforce2d** [cleanflight/cleanflight#1680]
Unless I'm mistaken the default behavior is not to allow arming when the frame is not reasonably level. My quad is spending the night at the top of a very tall tree with a hard-to-climb lower section, and I'm 98.4% certain it could have thrashed its way loose if could just have armed it... but it was facing downward.

**Comment by ledvinap** [comment]
just set 'small_angle' to 180 ..

But you may end up spending night at hospital ...

**Comment by iforce2d** [comment]
aha... that's great, thankyou.

**Comment by joshuabardwell** [comment]
You can use stick commands to re-calibrate the accelerometer, then the copter will believe it's level and you can spin the motors.

**Comment by iforce2d** [comment]
oh yeah, that's even better, wish I had realized that before the battery died. Oh well, I'm sure the next big storm will bring it down.
