### ISSUE TITLE
with mixer CUSTOM servos not working at all

### ISSUE THREAD

**Issue by universam1** [cleanflight/cleanflight#1699]
I have a Tricopter with 2 servos for tilt, unfortunately CUSTOMTRI is not applicable since I can configure 2nd servo but the output is not activated.
So I want to choose CUSTOM mixer, but there even though I configure cli servo and smix no servo output is on any port. I'm using a Naze32 board.

When looking through the code in mixer.c on line 455 you can see that loadCustomServoMixer() is not called for MIXER_CUSTOM. The same problem I find on line 832 where no servoMixer() is called for case MIXER_CUSTOM.

According to the documentation all custom mixer should have SMIX enabled. Is this true or not? Any hint how to solve that?

**Comment by hydra** [comment]
what board?

**Comment by universam1** [comment]
Naze32 F1 acro

**Comment by badfrogg** [comment]
I have verified this in Naze and SPRF3 while experimenting this airplane builds that have glow engines with servos for throttle. mixer "custom" has no smix.

I would like to see mixer "Custom" to be flexible for motors or servos in any combination including all servos or all motors.

**Comment by hydra** [comment]
Use CUSTOM AIRPLANE mixer.

**Comment by DzikuVx** [comment]
@hydra in iNav it was solved in inavflight#148
