### ISSUE TITLE
Google Spreadsheet Cleanflight - CLI Settings Tool

### ISSUE THREAD

**Issue by AustinSaintAubin** [cleanflight/cleanflight#1701]
I created a [Cleanflight CLI](https://github.com/cleanflight/cleanflight/blob/master/docs/Cli.md) Tool using Google Spreadsheets that will be useful for Cleanflight users & Developers dealing with CLI compairison between updates. I use it to check my settings against the defaults after flashing updates to my flight controller. Spreadsheet also pulls some of its info from this github repo, so the sheets update themselves in regard to some of the notes.

To get started with my [Spreadsheet Cleanflight - CLI Settings Tool](https://docs.google.com/spreadsheets/d/1w_oMmGCGX0DwAlVX7pBPtD-X-STbLmb4nSxLJL-hXmc/edit?usp=sharing):

1. Open Cleanflight, then dump your CLI with commands from the [DUMP_CMD](https://docs.google.com/spreadsheets/d/1w_oMmGCGX0DwAlVX7pBPtD-X-STbLmb4nSxLJL-hXmc/edit#gid=175144139) sheet.
2. Select one of the "DUMP_..." sheets from the [spreadsheet](https://docs.google.com/spreadsheets/d/1w_oMmGCGX0DwAlVX7pBPtD-X-STbLmb4nSxLJL-hXmc/edit?usp=sharing)., like the [DUMP_GENERAL](https://docs.google.com/spreadsheets/d/1w_oMmGCGX0DwAlVX7pBPtD-X-STbLmb4nSxLJL-hXmc/edit#gid=1263885617) sheet, and paste your CLI dump into that dump sheet in column B.
3. You can now go to the main sheet to see and compare your settings from your dump against your noted & default settings. Sheets might take a few seconds to update.

Hope someone else finds this tool useful.

**Comment by hydra** [comment]
Thanks for the details.  Nothing else to be done with this ticket so I will close it, people will still be able to find it via search.
