### ISSUE TITLE
Problem with set failsafe_off_delay= 200

### ISSUE THREAD

**Issue by Viosphera** [cleanflight/cleanflight#1708]
I have the latest stable version of CF for naze 32 and using the failsafe functions.

When i use the failsafe_delay it allow to set the time to recover the lost signal from the tx but when i use failsafe_off_delay= 200 it dont spin the motors that amount of time/steps.

It means that when i turn off the tx, the motors stop, but when i turn it on again, and apply the throttle. the motors spins again 

the failsafe_throttle is set to 1350 so it should be working

i don't know wich is the problem, please help

**Comment by joshuabardwell** [comment]
This is a support issue, not a bug. Please get support on the RCGroups thread. The bug tracker is not for support requests.

http://www.rcgroups.com/forums/showthread.php?t=2249574
