### ISSUE TITLE
Failsafe - Voltage-activated failsafe

### ISSUE THREAD

**Issue by digitalentity** [cleanflight/cleanflight#1711]
I have received a few requests for adding RTH functionality on a "low battery" event to iNav firmware.
This issue is opened here and not in iNav as it this it would be better to implement a more generic "failsafe on a low battery event".
@ProDrone, @hydra what do you think?

**Comment by lostcontrol** [comment]
As you probably know, Ardupilot has "do nothing", "land" and "RTH" options on battery fail-safe. I think you can now even define additional safe landing points and Ardupilot will chose the nearest one if it can't reach home again.

**Comment by digitalentity** [comment]
@lostcontrol I know what APM is capable of, but this is about Cleanflight that does nothing except beeping on low battery.

**Comment by lostcontrol** [comment]
@digitalentity Just wanted to list the available options there since Cleanflight will probably end up with similar behaviors. Also I always wondered why Cleanflight has *vbat_min_cell_voltage* and *vbat_warning_cell_voltage* since both seem to result in the exact same action (beeping)!? Or is it not possible to arm anymore if *vbat_warning_cell_voltage* is triggered?

**Comment by DL6ER** [comment]
> Or is it not possible to arm anymore if vbat_warning_cell_voltage is triggered?

I looked into the source code and (currently) that is not the case. The beeper beeps differently for warning and critical levels. That's everything that seems to happen.

**Comment by ledvinap** [comment]
Battery voltage (or remaining battery capacity) +  warning/critical level may be exposed as virtual AUX channel .. Then it will be trivial to configure it for desired action

**Comment by oleost** [comment]
@hydra Is this somehow solved since it's closed ?

**Comment by Dutchy-79** [comment]
I'd like the idea of a low voltage failsafe trigger, I'm a APM pilot and now building a new hex with the omnibus F3 and inav.

**Comment by Dutchy-79** [comment]
Can't edit the post above, but if the future isn't there yet I already had a new idea for this. 

I'll try making a logical switch on the Taranis to trigger the failsafe aux on a set voltage.

**Comment by mikeller** [comment]
@Dutchy-79: I got exactly that on my TX. It's a voice alert that tells me if my voltage drops too low, prompting me to land (unless it happens on a long punchout, when the computer between my ears uses logic to determine that this is just expected behaviour).

**Comment by Dutchy-79** [comment]
@mikeller I'm planning on making it automatically with the logical switch. 

Tho didn't think about the long punch out. Maybe I need to set a time period as well. Say <3.8v for 5 seconds triggers a logical switch on aux(failsafe channel)

**Comment by mikeller** [comment]
Up to you really. In my opinion, if you have telemetry, having the TX read out the voltage to you periodically if it's below a certain level is still best. You as the pilot know best if it's only caused by an old and sagging battery, or if it's not wise to do a failsafe landing right above a large puddle.

**Comment by Dutchy-79** [comment]
No, I was thinking of a RTH failsafe.

**Comment by mikeller** [comment]
Ah, I see. Advanced navigation features like RTH are more or less unsupported, and certainly untested in cleanflight / Betaflight. If that is what you are after, you should have a look at iNav: https://github.com/iNavFlight/inav

**Comment by Dutchy-79** [comment]
Okay thanks, I'll ask there again. I ended up here because I searched Inav RTH low battery failsafe on Google and the first 2 posts talked about inav so I didn't even look at the master branch ;) 

My bad,
