### ISSUE TITLE
servo and smix rates

### ISSUE THREAD

**Issue by universam1** [cleanflight/cleanflight#1712]
Could you please check the rates for servo and smix CLI?

Refering to 
https://github.com/cleanflight/cleanflight/blob/master/src/main/flight/mixer.h#L156
https://github.com/cleanflight/cleanflight/blob/master/src/main/flight/mixer.h#L177
the servo rates should be extensible to +/-125 - unfortunately they are limited to +/-100.

This is especially an issue with smix cli where I want a higher rate on different mixer channel.

See
https://github.com/cleanflight/cleanflight/blob/master/src/main/io/serial_cli.c#L1438
https://github.com/cleanflight/cleanflight/blob/master/src/main/io/serial_cli.c#L1305

Thank you for correcting!

**Comment by universam1** [comment]
please consider #1713

**Comment by hydra** [comment]
The links are now out of date.
