### ISSUE TITLE
Afromini Naze setup in Cleanflight

### ISSUE THREAD

**Issue by tbren100** [cleanflight/cleanflight#1719]
Hey all,

Trying to get connected to cleanflight and not having any luck. I have downloaded the CP210x driver. When I plug it in through the FTDI, I get a solid blue light and a flashing green light. Red solid light on the FTDI. I know for a fact this has betaflight flashed on it. 

If I try to connect through comm 3, it will say "No configuration received within 10 seconds, communication failed". If I try to flash new firmware, it says "Failed to open serial port". 

Running Windows 7. Any help would be HUGELY appreciated! Thanks!!

**Comment by SteveAmor** [comment]
This is a support question not an issue with cleanflight. Please ask on the cleanflight thread

http://www.rcgroups.com/forums/showthread.php?t=2249574

Please close this issue.
