### ISSUE TITLE
Installation.md does not exist

### ISSUE THREAD

**Issue by iSevenDays** [cleanflight/cleanflight#1730]
I can't open https://github.com/cleanflight/cleanflight/blob/master/Installation.md

**Comment by tigert** [comment]
Where did you see the link to this? As the correct link is https://github.com/cleanflight/cleanflight/blob/master/docs/Installation.md

But it would be good to fix the broken one if we know where it is.. :-)

**Comment by iSevenDays** [comment]
It is here https://github.com/cleanflight/cleanflight

**Comment by tigert** [comment]
Thanks!

I created a pull request for a fix #1731 - in the meanwhile see the above working link :-)

**Comment by iSevenDays** [comment]
Thank you! :)
