### ISSUE TITLE
SPRacingF3 - Softserial port mismatch?

### ISSUE THREAD

**Issue by johnlenfr** [cleanflight/cleanflight#1745]
Don't know if it is a problem in GUI or in the SP Racing F3 hex file but to have Telemetry on IO1 port I have to select Hott telemetry on Softserial 2 in the GUI.

Is there someting inverted in the code or I missed something in my hardware?

Thought config was like this:
PIN-IO1-IO2
5-SS1Rx-SS2Rx
6-SS1Tx-SS2Tx

Here is my setup:
Running - OS: Windows, Chrome: 48.0.2564.97, Configurator: 1.1.0
Flight controller info, identifier: CLFL, version: 1.11.0
2016-01-31 @ 09:40:21 -- Running firmware released on: Nov 28 2015 15:29:46
2016-01-31 @ 09:40:21 -- Board: SRF3, version: 0

Thanks

**Comment by hydra** [comment]
please provide configuration dump and wiring photo if possible

**Comment by johnlenfr** [comment]
Here you can find attach print screen of my config (since my first post I change to new CF v1.12).
![hott](https://cloud.githubusercontent.com/assets/10273794/15314543/d5fca9ae-1c12-11e6-9a5d-7dc19f9e9252.png)

You can see that I have to select Hott Telemetry on SOFTSERIAL 2 but thing is I cable my telemetry on IO_1 port as you can see on the photos.
![20160516_223946 1600x1200](https://cloud.githubusercontent.com/assets/10273794/15314555/e90895c6-1c12-11e6-9dfd-32039a9a9cb9.jpg)

![20160516_224013 1600x1200](https://cloud.githubusercontent.com/assets/10273794/15314588/264ffd84-1c13-11e6-8321-61351fec6f0e.jpg)

So is there a mismatch in GUI or Hex file?

Thanks
