### ISSUE TITLE
SP Racing F3 with Spectrum AR7700 with SLRX or Remote Receiver protocol 

### ISSUE THREAD

**Issue by sgstreet** [cleanflight/cleanflight#1749]
Has any one made this work on 1.11?  Hookup/setup hints?  Suggestions on how to debug this?  PPM works correctly....

**Comment by fporte** [comment]
Hi, I just managed to make my AR7700 (SLRX protocol) work with a SP Racing F3 flashed with betaflight 2.5.4. Just plugged to UART2 set up to serial in cleanflight configurator. I have a weird behavior though : erratic and brief uncontrolled pulses on random chanels, mainly throttle. Has someone already experienced this?
