### ISSUE TITLE
Passthrough mode missing from custom airplane mixer - Nase23 rev5

### ISSUE THREAD

**Issue by badfrogg** [cleanflight/cleanflight#1758]
Nase23 rev5 - RC 1.12.0
I noticed that if you select airplane mixer, you will have passthrough mode on the modes tab. But, if you select custom airplane, the mode "Passthrough" disappears from the modes list. Is there a command in CLI to enable this pass-through mode

And just to be clear i mean the mode "passthrough" for servos not serial passthrough.

Another odd thing is if you go back to regular airplane mixer the passthrough does not come back. EDIT: it does after a power cycle.

**Comment by hydra** [comment]
Please test new release candidates ASAP.  Raise a new bug and reference this if it's not OK.

**Comment by badfrogg** [comment]
Yes, The 1.12.0 RC2 has fixed the issue (enhancement). Passthrough Mode now avalable in Custom Airplane Mixer.

Thanks!

**Comment by hydra** [comment]
Great, thanks for the feedback and bug report.
