### ISSUE TITLE
Support for sub-32K Cleanflight build

### ISSUE THREAD

**Issue by martinbudden** [cleanflight/cleanflight#1769]
Some people have been hacking some of the toy quads. Most of these seem to have 16K ROMs, but a few have 32K ROMs. Some of these hacks are based on forks of Bradwii, for example see [Bradwii for JXD JD385, WLToys V202, Hubsan H107L and clones](https://github.com/victzh/bradwii). Others seem to be writing a flight controller from scratch, for example this [Floreon H101 port](https://github.com/silver13/H101-acro) or this [Eachine H8 port](https://github.com/silver13/h8mini-acro)

I propose we add a sub-32K ROM build variant of Cleanflight that people that can be used as a basis for putting on toy quadcopters. This means that people wishing to hack a toy copter can concentrate on the hack itself, rather than getting a flight controller working.

I've already got an experimental sub-32K build of Cleanflight, so this work is possible.

Although in some ways Cleanflight has a mess of legacy code, Cleanflight is also in some ways very well structured with good separation between components, so this means it is actually not too difficult to support a sub-32K build.

Supporting a sub-32K build also has a beneficial side effect: it adds an area of engineering discipline and so will guard against accidentally adding dependencies between components.

I've added this issue at @hydra 's request, as place to discuss this idea.

**Comment by JohnOCFII** [comment]
Very Interesting!  I know that the brushed micro-quad audience is growing for CleanFlight due to FC's like the SciSky.  If more of that audience could use CleanFlight on some of the smaller boards, that might give them a good path to move up with CleanFlight as they move to later, brushless quads.
