### ISSUE TITLE
PWM output 1 & 2 Can only be configured as Motors in custom airplane (not servo).

### ISSUE THREAD

**Issue by badfrogg** [cleanflight/cleanflight#1782]
V1.12.0 RC2 Naze32 rev5 (6 DOF)
smix has no effect on servo 0 & 1 (PWM output 1 & 2 ) These two channels can only be configured with mmix. I realize that is is likely a feature request and not a bug.

My current project is Cleanflight on a Glow airplane! The motor channel is controlled with a servo and not an ESC. This not critical but would be nice. For now throttle is directly connected on the receiver as a workaround.

**Comment by SlyMike** [comment]
#1323 raises similar issues, I'm building a wing with a 2 axis thrust mount for the motor and wanting to run an led strip but can't configure the second motor as a servo output. Would love to see some work done on the assignment of outputs in airplane mode. ;-)
