### ISSUE TITLE
Configurator doc links should link to appropriate sections

### ISSUE THREAD

**Issue by joeynuggetz** [cleanflight/cleanflight#1786]
How's about linking the documentation button that's on each page to its corresponding section in the guide? If I click help under motors, I expect to be dumped to the motors section of the docs instead of the index. Just a thought.

Also, is it possible for anyone to go in and help clean up spelling mistakes in the docs or do I have to post them as issues here? I'd like to contribute with documentation. I could probably figure out the above suggestion too.

**Comment by tigert** [comment]
You can go to the document in question and click the "edit" button. Github will guide you through creating a merge request out of it.
