### ISSUE TITLE
Flying Wing mix problem(CC3D) v1.12.0-RC2

### ISSUE THREAD

**Issue by Piradoxlanieve** [cleanflight/cleanflight#1796]
I whereas there is an issue with the flying wing , when I move the roll the elvevones are functioning as picth . and pich elevons act as roll, I'm going crazy in the GUI , move roll and roll bar will move and move the picth and picth bar moves. sorry for my English

**Comment by barneycoles** [comment]
In the servo tab play with the rate and direction values. 

Make one a positive and one a negative and try swapping them round. 

I'm flying a mini wing and have servo 3 75% and servo -75%
