### ISSUE TITLE
CC3D - Building using GCC 5.2 results in non-working VCP

### ISSUE THREAD

**Issue by digitalentity** [cleanflight/cleanflight#1799]
Building latest master with gcc-5.2-2015q4 results in "Device not recognized" message on CC3D target when plugging USB cable. gcc-4.9.3 builds are working fine.

This might be vcp library bug, similar to #452, #763

**Comment by digitalentity** [comment]
Disabling optimisation on usb_init.c fixed the issue. Also issue isn't present under debugger.

**Comment by flacjacket** [comment]
I have the same problem with gcc 5.3.
