### ISSUE TITLE
Identifiers should not be defined in serial_msp.h

### ISSUE THREAD

**Issue by martinbudden** [cleanflight/cleanflight#1801]
The identifiers `flightControllerIdentifier` and `boardIdentifier` should not be defined in `serial_msp.h`.

**Comment by borisbstyle** [comment]
It should all go into target.h IMO.

I think as much as possible stuff could best stay out of the code

**Comment by martinbudden** [comment]
When I said "definitions" I meant "C variable definitions", not the #defines. The #define for boardIdentifier is already in the `target.h` file. This issue is about the "correctness" of the C code.

**Comment by borisbstyle** [comment]
oh....yes indeed. Its already in there.....silly me.
Op 10 feb. 2016 07:50 schreef "Martin Budden" <notifications@github.com>:

**Comment by martinbudden** [comment]
No longer applicable after PR #1976 "Refactor configuration storage"
