### ISSUE TITLE
Serial Buffering broke ESC passthrough function

### ISSUE THREAD

**Issue by borisbstyle** [cleanflight/cleanflight#1803]
Just to bring it here. Perhaps bypassing buffering  just for this function would be enough

**Comment by borisbstyle** [comment]
@nathantsoi Can you have a look?

**Comment by 4712** [comment]
I can confirm that. What was changed and what for?

**Comment by borisbstyle** [comment]
It was changed to speed up the serial communication and especially for VCP
targets it was really needed as that was slow and choppy.

I just cant see why it would break the passthrough.
Op 9 feb. 2016 18:05 schreef "4712" <notifications@github.com>:

**Comment by nathantsoi** [comment]
@borisbstyle can you point me at a commit or line number?

**Comment by 4712** [comment]
done: https://github.com/cleanflight/cleanflight/pull/1808

**Comment by borisbstyle** [comment]
Cool! I felt like it should be a minor fix :D

**Comment by nathantsoi** [comment]
nice @4712
