### ISSUE TITLE
RX_Serial not working in Naze 1.12.0 RC2, works fine in RC1.

### ISSUE THREAD

**Issue by neildotwilliams** [cleanflight/cleanflight#1810]
Naze 1.12.0 RC1 was working. Naze 1.12.0 RC2 stopped working for me.
Using MX NANO OVERSKY 32
I set Port 2 to be "Serial RX"
I set Receiver Mode to be "RX_Serial"
Using RC2 the Receiver does not seem to work.

**Comment by borisbstyle** [comment]
What does not work?

**Comment by neildotwilliams** [comment]
While looking at the 'receiver' tab in cleanflight, the values change when moving my transmitter sticks around for throttle, etc. 

If I flash rc2, keeping everything else the same, the values no longer move when I move my transmitter sticks. 

This is on a hermit 145 drone kit.
