### ISSUE TITLE
Drift to the Left in Angel and Horizon 

### ISSUE THREAD

**Issue by robschii** [cleanflight/cleanflight#1816]
Hallo, i have a cc3d and i run the LibrePilot firmware, cleanflight 1.11.0 and cleanflight 1.12.0rc1 and 2

my problem ist with LP and CF1.11.0  everything is fine. The Copter makes a stable hovering.

Now with  1.12.0rc2 i noticed that i have a drift to the left. i can not say if it is also in 1.12.0rc1 becaue i do not flyi it outside, but only in my room. 

where is the problem now, coukld it be a problem with the new gyro filter??

**Comment by lostcontrol** [comment]
Why do you open a new issue since there is already #1780 and you even commented in it!!???

**Comment by robschii** [comment]
sorry

**Comment by SteveAmor** [comment]
@robschii please close this issue
