### ISSUE TITLE
Failsafe problem 

### ISSUE THREAD

**Issue by npmullins** [cleanflight/cleanflight#1830]
Setting arm to aux3 channel and then in failsafe menu setting the aux 3 channel to move to value out of range of motor arming.  Works correctly in transmitter sliders section of cf gui.  But when try with battery power to quadcopter and then turn off the taranis radio the motors do not stop spinning. (using latest Lux hex target on Lux fc)

**Comment by 3djc** [comment]
Have you made sure, in the configuration pane that "Disarm motor regardless of throttle value (when arming from AUX channel) is ENABLED (green) ?

**Comment by npmullins** [comment]
Yes this green

**Comment by npmullins** [comment]
Sorry close this i am.having this issue in betaflight
