### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by reiser4** [cleanflight/cleanflight#1832]
see pictures:

![bug1](https://cloud.githubusercontent.com/assets/2445517/13069913/8687c81c-d488-11e5-9f03-760b6761eae7.PNG)

![bug2](https://cloud.githubusercontent.com/assets/2445517/13069911/82520dde-d488-11e5-96b1-a4c9701c7f6d.PNG)

**Comment by SteveAmor** [comment]
@reiser4 could you close this issue and raise it under cleanflight/configurator

Thanks :-)

**Comment by reiser4** [comment]
ok, sorry
