### ISSUE TITLE
Uncontrollable throttle up is pressent in AfroMini 2.4.0 RC9 with airmode enabled again!

### ISSUE THREAD

**Issue by cheetah2k** [cleanflight/cleanflight#1836]
The issue experienced many versions ago that totalled my scarab knife is back again in the Afromini hex this time.  The throttle powers up on arm with airmode enabled.  Please resolve.

**Comment by joshuabardwell** [comment]
This is a Betaflight issue. Please close this issue and open an issue in the Betaflight repo. Cleanflight doesn't support airmode.
