### ISSUE TITLE
Slight drop or jump when activating alt hold mode due to mixup between rcData and rcCommand

### ISSUE THREAD

**Issue by flyinghead** [cleanflight/cleanflight#1837]
When BARO or SONAR mode is activated, the current throttle position is taken from rcData and saved. Then a correction is applied to it by the alt hold PID controller, but the result is put in rcCommand, bypassing expo and range adjustments.

This is the cause of the vertical drop or jump often seen when activating alt hold mode.

A simple solution is to use rcCommand only in altitudehold.c.

**Comment by hydra** [comment]
PR merged, thanks!

**Comment by flyinghead** [comment]
Thank you!
