### ISSUE TITLE
CC3D - PWM parralel problems

### ISSUE THREAD

**Issue by pihlerm** [cleanflight/cleanflight#1838]
Only 2 PWM inputs are working since 1.10 release on my two cc3d boards. Version 1.9 works fine. OpenPilot also works with all PWM RC channels.
Meaning, pins 4&5 (mapped to RC0&RC1) work OK, but pins 6-8 (mapped to RC2..RC4 and AUX1-AUX2) don't.

Tried enabling/disabling VBAT, all different mappings of RC channels in Configurator...

**Comment by cephyr** [comment]
Hey,

I am also experiencing problems with PWM on my Flip32 FC.
At first I thought my board could be broken but it isn't.

v1.9 is the latest firmware which works for me. 

How to post some relevant debugging info?
