### ISSUE TITLE
SP Racing F3 and FlySky i6 - Receiver mapping issues

### ISSUE THREAD

**Issue by fast240z** [cleanflight/cleanflight#1851]
Receiver mapping appears to be an issue with Cleanflight/SP Racing F3/Flysky ia6 when connected via PWM.  

Channels are mapped correctly in Cleanflight and are connected to the appropriate pins on the rx, but Yaw and Throttle indicators move at the exact same time and rate when the throttle is moved.  Applying Yaw via the sticks does nothing.  The same behavior happens with Roll and Pitch, both roll and pitch move at the same time when roll is applied.  Applying pitch does nothing via the sticks.

I've switched the pinout and found that the other channels do function, but for whatever reason the roll/pitch and yaw/throttle values are "locked" together.  

Google searches indicate this has been a problem on Naze32 boards in the past, but no one has actually provided a solution that I've seen.

**Comment by hydra** [comment]
Where did you purchase your SPRacingF3 board?  Shop and Link please.

**Comment by fast240z** [comment]
I bought the board from an Amazon seller - http://www.amazon.com/gp/product/B018VQFWU2

Wiring photos are attached.  I followed the wiring guide in Painless360's video.  The channels seem to have paired up, 1-2, 3-4, 5-6 all move at the same time.  I have no mixing set on my radio, and I've reset it back to factory settings with no luck.

<img width="858" alt="screen shot 2016-02-20 at 8 44 37 am" src="https://cloud.githubusercontent.com/assets/17327935/13197938/bbb7863c-d7b0-11e5-9fa0-ae0b08af06ee.png">
![img_0496](https://cloud.githubusercontent.com/assets/17327935/13197948/e7c4318a-d7b0-11e5-81a7-1e7808583937.JPG)
![img_0497](https://cloud.githubusercontent.com/assets/17327935/13197953/fa792c2c-d7b0-11e5-8ad7-ac93779f5a02.JPG)
<img width="727" alt="screen shot 2016-02-20 at 8 48 56 am" src="https://cloud.githubusercontent.com/assets/17327935/13197954/0281f930-d7b1-11e5-9d90-ced4711a022a.png">
![img_0500](https://cloud.githubusercontent.com/assets/17327935/13197955/087a87f8-d7b1-11e5-97a3-1cccfc9fbd9a.JPG)
<img width="721" alt="screen shot 2016-02-20 at 8 50 11 am" src="https://cloud.githubusercontent.com/assets/17327935/13197957/0b9ab1f6-d7b1-11e5-90eb-47618ef23d76.png">


# dump

# version
# Cleanflight/SPRACINGF3 1.12.0 Feb 19 2016 / 20:01:10 (aa8608a)
# dump master

# mixer
mixer QUADX
mmix reset
smix reset


# feature
feature -RX_PPM
feature -VBAT
feature -INFLIGHT_ACC_CAL
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -FAILSAFE
feature -SONAR
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DISPLAY
feature -ONESHOT125
feature -BLACKBOX
feature -CHANNEL_FORWARDING
feature -TRANSPONDER
feature VBAT
feature FAILSAFE
feature RX_PARALLEL_PWM
feature BLACKBOX


# map
map AETR1234


# serial
serial 0 1 115200 57600 0 115200
serial 1 0 115200 57600 0 115200
serial 2 0 115200 57600 0 115200


# led
led 0 15,15:ES:IA:0
led 1 15,8:E:WF:0
led 2 15,7:E:WF:0
led 3 15,0:NE:IA:0
led 4 8,0:N:F:0
led 5 7,0:N:F:0
led 6 0,0:NW:IA:0
led 7 0,7:W:WF:0
led 8 0,8:W:WF:0
led 9 0,15:SW:IA:0
led 10 7,15:S:WF:0
led 11 8,15:S:WF:0
led 12 7,7:U:WF:0
led 13 8,7:U:WF:0
led 14 7,8:D:WF:0
led 15 8,8:D:WF:0
led 16 8,9::R:3
led 17 9,10::R:3
led 18 10,11::R:3
led 19 10,12::R:3
led 20 9,13::R:3
led 21 8,14::R:3
led 22 7,14::R:3
led 23 6,13::R:3
led 24 5,12::R:3
led 25 5,11::R:3
led 26 6,10::R:3
led 27 7,9::R:3
led 28 0,0:::0
led 29 0,0:::0
led 30 0,0:::0
led 31 0,0:::0


# color
color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 0,0,0
color 15 0,0,0

set looptime = 2000
set emf_avoidance = OFF
set i2c_highspeed = ON
set gyro_sync = ON
set gyro_sync_denom = 1
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_scale = 30
set rssi_ppm_invert = OFF
set rc_smoothing = OFF
set input_filtering_mode = OFF
set min_throttle = 1150
set max_throttle = 1850
set min_command = 1000
set servo_center_pulse = 1500
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set 3d_deadband_throttle = 50
set motor_pwm_rate = 400
set servo_pwm_rate = 50
set retarded_arm = OFF
set disarm_kill_switch = ON
set auto_disarm_delay = 5
set small_angle = 25
set fixedwing_althold_dir = 1
set reboot_character = 82
set gps_provider = NMEA
set gps_sbas_mode = AUTO
set gps_auto_config = ON
set gps_auto_baud = OFF
set serialrx_provider = SPEK1024
set sbus_inversion = ON
set spektrum_sat_bind = 0
set telemetry_switch = OFF
set telemetry_inversion = ON
set frsky_default_lattitude =  0.000
set frsky_default_longitude =  0.000
set frsky_coordinates_format = 0
set frsky_unit = IMPERIAL
set frsky_vfas_precision = 0
set hott_alarm_sound_interval = 5
set battery_capacity = 0
set vbat_scale = 110
set vbat_max_cell_voltage = 43
set vbat_min_cell_voltage = 33
set vbat_warning_cell_voltage = 35
set current_meter_scale = 400
set current_meter_offset = 0
set multiwii_current_meter_output = OFF
set current_meter_type = ADC
set align_gyro = DEFAULT
set align_acc = DEFAULT
set align_mag = DEFAULT
set align_board_roll = 0
set align_board_pitch = 0
set align_board_yaw = -90
set max_angle_inclination = 500
set gyro_lpf = 188HZ
set gyro_soft_lpf =  60.000
set moron_threshold = 32
set imu_dcm_kp = 2500
set imu_dcm_ki = 0
set yaw_control_direction = 1
set pid_at_min_throttle = ON
set airmode_saturation_limit = 50
set yaw_motor_direction = 1
set yaw_jump_prevention_limit = 200
set tri_unarmed_servo = ON
set servo_lowpass_freq =  400.000
set servo_lowpass_enable = OFF
set failsafe_delay = 10
set failsafe_off_delay = 200
set failsafe_throttle = 1000
set failsafe_kill_switch = OFF
set failsafe_throttle_low_delay = 100
set failsafe_procedure = 0
set rx_min_usec = 885
set rx_max_usec = 2115
set acc_hardware = 0
set baro_hardware = 0
set mag_hardware = 0
set blackbox_rate_num = 1
set blackbox_rate_denom = 1
set blackbox_device = SPIFLASH
set magzero_x = 0
set magzero_y = 0
set magzero_z = 0

# rxfail
rxfail 0 a
rxfail 1 a
rxfail 2 a
rxfail 3 a
rxfail 4 h
rxfail 5 h
rxfail 6 h
rxfail 7 h
rxfail 8 h
rxfail 9 h
rxfail 10 h
rxfail 11 h
rxfail 12 h
rxfail 13 h
rxfail 14 h
rxfail 15 h
rxfail 16 h
rxfail 17 h

# dump profile

# profile
profile 0

# aux
aux 0 0 0 900 900
aux 1 0 0 900 900
aux 2 0 0 900 900
aux 3 0 0 900 900
aux 4 0 0 900 900
aux 5 0 0 900 900
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# adjrange
adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0

# rxrange
rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000

# servo
servo 0 1000 2000 1500 45 45 100 -1
servo 1 1000 2000 1500 45 45 100 -1
servo 2 1000 2000 1500 45 45 100 -1
servo 3 1000 2000 1500 45 45 100 -1
servo 4 1000 2000 1500 45 45 100 -1
servo 5 1000 2000 1500 45 45 100 -1
servo 6 1000 2000 1500 45 45 100 -1
servo 7 1000 2000 1500 45 45 100 -1

set gps_pos_p = 15
set gps_pos_i = 0
set gps_pos_d = 0
set gps_posr_p = 34
set gps_posr_i = 14
set gps_posr_d = 53
set gps_nav_p = 25
set gps_nav_i = 33
set gps_nav_d = 83
set gps_wp_radius = 200
set nav_controls_heading = ON
set nav_speed_min = 100
set nav_speed_max = 300
set nav_slew_rate = 30
set alt_hold_deadband = 40
set alt_hold_fast_change = ON
set deadband = 0
set yaw_deadband = 0
set throttle_correction_value = 0
set throttle_correction_angle = 800
set default_rate_profile = 0
set gimbal_mode = NORMAL
set acc_cut_hz = 15
set accxy_deadband = 40
set accz_deadband = 40
set accz_lpf_cutoff =  5.000
set acc_unarmedcal = ON
set acc_trim_pitch = 0
set acc_trim_roll = 0
set baro_tab_size = 21
set baro_noise_lpf =  0.600
set baro_cf_vel =  0.985
set baro_cf_alt =  0.965
set mag_declination = 0
set pid_delta_method = MEASUREMENT
set pid_controller = MWREWRITE
set p_pitch = 40
set i_pitch = 30
set d_pitch = 23
set p_roll = 40
set i_roll = 30
set d_roll = 23
set p_yaw = 85
set i_yaw = 45
set d_yaw = 0
set p_pitchf =  1.400
set i_pitchf =  0.400
set d_pitchf =  0.030
set p_rollf =  1.400
set i_rollf =  0.400
set d_rollf =  0.030
set p_yawf =  3.500
set i_yawf =  0.400
set d_yawf =  0.010
set level_horizon =  3.000
set level_angle =  5.000
set sensitivity_horizon = 75
set p_alt = 50
set i_alt = 0
set d_alt = 0
set p_level = 20
set i_level = 10
set d_level = 100
set p_vel = 120
set i_vel = 45
set d_vel = 1
set yaw_p_limit = 500
set dterm_cut_hz =  0.000
set gtune_loP_rll = 10
set gtune_loP_ptch = 10
set gtune_loP_yw = 10
set gtune_hiP_rll = 100
set gtune_hiP_ptch = 100
set gtune_hiP_yw = 100
set gtune_pwr = 0
set gtune_settle_time = 450
set gtune_average_cycles = 16

# dump rates

# rateprofile
rateprofile 0

set rc_rate = 90
set rc_expo = 65
set rc_yaw_expo = 0
set thr_mid = 50
set thr_expo = 0
set roll_rate = 0
set pitch_rate = 0
set yaw_rate = 0
set tpa_rate = 0
set tpa_breakpoint = 1500

#

**Comment by jlj0425** [comment]
i have the same issue. before i use 1.11.0 all is working well. when i flash it with the fucking new 1.12.0 Yaw and Throttle indicators move at the exact same time and rate when the throttle is moved. Applying Yaw via the sticks does nothing. The same behavior happens with Roll and Pitch, both roll and pitch move at the same time when roll is applied. Applying pitch does nothing via the sticks. tried to re-flash using 1.10.0 and 1.11.0 again to 1.12.0 again and again still it does not work. i also tried to brick my F3 and boot again but still not fucking working.  cant use my quad anymore. shit

**Comment by sammykumson** [comment]
i am having the EXACT same problem ...PWM NOT WORKING ON SP F3 DELUXE. AR610 RECIEVER DX6 all works fine on a Naze32... and others ... i know its not wired wrong or mapping ... i setup many of the Naze32 ... Cleanflight 1.2.1 ...... I will Not go to ppm as i have all Spektrum gear. can some one please fix or tell me how to as i would really like to use this Flight Controller as it all wired up ..... bought it from ReadytoFlyQuads.com  ...

**Comment by StraTech** [comment]
I am having a similar problem on SP RacingF3 & FS-IA6 I can't get any input on CH1-CH4, but AUX CH5-CH8 working something is mapped wrong have tried v1.10.0 v1.11.0 v1.12.0 all the same. I can get ppm working with another FS-IA6B RX but I still need PWM working!

**Comment by jlj0425** [comment]
Good news Ihave just found the solution. it doesn't give me any more head ache.. i just smash my fucking F3 with a hammer. after then no more head ache. LOL.

**Comment by hydra** [comment]
use v2.0.0, if the problem persists open a new issue and reference this one.
