### ISSUE TITLE
Develoment board

### ISSUE THREAD

**Issue by mvturnho** [cleanflight/cleanflight#1864]
I am getting the development env ready with use of the ATM32F3discovery. What are the pins used for i2c OLed. I scanned the code and came up with pb6 and pb7 but the display is not working yet. Is there a pin layout for the ATM32f3 and cleanflight?  
Thanx .

**Comment by SteveAmor** [comment]
This is very clearly a support question and not an issue. Please discuss such support on forums such as RC Groups or IRC #cleanflight 
Please close this issue.

**Comment by SteveAmor** [comment]
Thank you @mvturnho
