### ISSUE TITLE
Failed to open serial port

### ISSUE THREAD

**Issue by olaf2273** [cleanflight/cleanflight#1865]
hello
i cant connect any more  to clean flight.
now I have this in menu:
2016-02-21 @ 17:10:11 -- Failed to open serial port
2016-02-21 @ 17:10:22 -- Serial port successfully closed
2016-02-21 @ 17:10:25 -- Serial port successfully opened with ID: 2
2016-02-21 @ 17:10:35 -- No configuration received within 10 seconds, communication failed
I booed the naze32 but no response  what to do.
it workt before

**Comment by SteveAmor** [comment]
Suggest you look for support on forums such as RC Groups and IRC #cleanflight. 
Please close this issue. It is not a bug

**Comment by olaf2273** [comment]
before the old clean flight program it works. and now clean flight is updated its doesn't works ?

**Comment by Arti3DPlayer** [comment]
have same problem. how to solve it? Write guide please...

**Comment by olaf2273** [comment]
I bought a new One,
At banggood. A new one naze32 V6
This wan js wurking good !!

http://m.banggood.com/CK-REV6-NAZE32-10DF-Flight-Controller-For-RC-Multirotors-Baseflight-Configurator-p-1030040.html

**Comment by olaf2273** [comment]
And its surk with glean flight

**Comment by SteveAmor** [comment]
Hi @olaf2273 good to hear you fixed the problem. Please can you close this issue. Thanks.
