### ISSUE TITLE
Issues with Servo Mixing & PASSTHRU

### ISSUE THREAD

**Issue by AustinSaintAubin** [cleanflight/cleanflight#1869]
I have found this very confusing, there is also a lack of documentation on how to use server angles. There really isn't any good documentation on servo mixing at all. Seems like some of the setting have no effect, (like [IO - Estimated servo angles #925](https://github.com/cleanflight/cleanflight/issues/925))

I have also found that PASSTHRU mode does not map to MID, MIN, MAX ranges. Seems like servo mapping should be applied to PASSTHRU mode. This would allow you to configure your servo ranges in the flight controller, and have them apply to the model during passthrough. Currently MIN, MAX servo mixes are limiting the servos range during passthrough, but not mapping to MIN, MAX. This mean that PASSTHRU mode does get the full range of the servo's, thereby damping the control surface.

**Comment by Elmeerkat** [comment]
The servos also don't seem get mapped in stabilize modes.

Just reported that
