### ISSUE TITLE
Beeper off flags

### ISSUE THREAD

**Issue by RC-Slater** [cleanflight/cleanflight#1875]
Since CF 1.12 came out, I thought about switching back from betaflight. However, I was disappointed To find that the beeper off flags feature is missing.  Any reason why it hasn't made it into cleanflight?

It's a deal breaker for me.

**Comment by hydra** [comment]
the PR has not been merged. please comment on the PR itself instead of raising new issues to indicate that you want the feature.  This is how we decide what to work on.

See #1309

**Comment by hydra** [comment]
And see #1098 and #1271 

Please search first!
