### ISSUE TITLE
Jeti duplex

### ISSUE THREAD

**Issue by divenet** [cleanflight/cleanflight#1885]
I am a fan of the work that went into Cleanflight
Here is a quick question, i have a Jeti 2.4 duplex that use EX Bus, any chance of seeing that being supported, as i am sure i am not the only one with love for an exquisitely made radio. currently works great in ppm but would love to step it up.

**Comment by dkisselev** [comment]
Jeti EX has been implemented by another contributor and is just awaiting final review/merge, so you should see it in the next few releases: https://github.com/cleanflight/cleanflight/pull/1709

**Comment by divenet** [comment]
God I am so looking forward to that,  have my cake and eat it too. Thank for all the hard work that goes into the marriage of the awesome Jeti and great CleanFlight there kid the SPRacing Pro F 3 mini, the best flight platform I have ever toyed with.. You are the best.

**Comment by SnipeXR** [comment]
I have tried it in betaflight works great! Telemetry works too Voltage and Current!

**Comment by divenet** [comment]
thank you thank you so much for the update, in you got any input, trick or learning curve you can share, ill bring it up to all my Jeti brothers here in Canada

**Comment by SnipeXR** [comment]
Just make sure to install a resistor to brige Uart tx and rx together.  2.4k ohm 
See 
https://imgur.com/a/kGn0M
Enable telemetry and select exbus as serial provider on CLI and good to go.

**Comment by divenet** [comment]
"Just make sure to install a resistor to brige Uart tx and rx together. 2.4k ohm
See
https://imgur.com/a/kGn0M
Enable telemetry and select exbus as serial provider on CLI and good to go. "

wait, do i see Grd and 5V. on pin 1 and 2 but signal on pin 6(4) with 2.4k bridge to pin 5 (3), did i get that right? and enable ex bus in serial provider? all of this will work on a naze 32? 

all this on port uart1?

and with any luck, same thing on a SPRacing F3 board?

you the Man thanks for your time

**Comment by SnipeXR** [comment]
Yeah you got it except for its Uart 2 I had hooked up to. 
All works on Naze 32. Here's another pick from radio. 
https://imgur.com/a/boawA

**Comment by SnipeXR** [comment]
I hope hydra merges the #1709 pull request. Works great.

**Comment by divenet** [comment]
you are the man.

yup sorry, my bad, it would be Uart 2  at pin 3 and pin 4, guess i am going to bed late to give this a go.

so Uart 1 can remain free for usb or ODS when Armed.

i am so please to hear this, you have just made my day, now i feel good to have gone against the grain and got a jeti just because it is so well made.

i am indebted to your superior knowledge.

JL

**Comment by marv-t** [comment]
Hi!
Currently, the following sensors are supported :

### exBusSensor_t jetiExSensors[] = {
    { "Cleanflight D1", "",     0,      0,             0 },                     // device description
    { "Voltage",        "V",    0,      EX_TYPE_14b,   DECIMAL_MASK(1) },
    { "Current",        "A",    0,      EX_TYPE_14b,   DECIMAL_MASK(2) },
    { "Altitude",       "m",    0,      EX_TYPE_14b,   DECIMAL_MASK(2) },
    { "Capacity",       "mAh",  0,      EX_TYPE_22b,   DECIMAL_MASK(0) }}; 

For implementation other values just ask.

**Comment by divenet** [comment]
HI marv-t
you would make my system complete if there is any changes to have GPS coordinates?
i don't know if it possible but that would rock

JL

**Comment by marv-t** [comment]
I do not have GPS, but have just ordered one for testing. However, it is possible in principle.

**Comment by divenet** [comment]
> I do not have GPS, but have just ordered one for testing. However, it is possible in principle.

I have a Neo 8 and Neo 6 using Ublox provider on a Naze 32 and on my OSD, the data from the FC is to the minute accurate. Just a little hard of long to get a signal indoors as you would know for testing but outside it locks on as soon as you power up.

I would guess that you would test the location in the string of data and the length of the string to fit the Jeti protocol? Is that how it works in general and then translat to EX Bus before pumping the data into telemetry back to the RX?

Thank you so much marv-t for doing this for the Jeti Community but it kinda makes me feel like i had a hand in it if i were smarter.
JL

**Comment by divenet** [comment]
thanks to all of you for the work done for the Jeti community .
JL aka Heliox

**Comment by schaetj** [comment]
Thank you for implementing this.  What wattage for the resistor?  Is 1/8 watt sufficient?  5.0V / 2400ohm = 0.002083amps.  0.002083 ^ 2 * 2400 = 0.0104watts.  Well within 1/8 watt.

**Comment by SnipeXR** [comment]
1/8 watt works that's what I use.

**Comment by divenet** [comment]
Can one of you explain what is the purpose of the resistance and will it be the same implementation on other board Uart port? 
I mean this will work on a naze32 type flight controller but will it be the same setup  on a Seriously Pro Evo or the Kiss FC?

**Comment by marv-t** [comment]
@divenet 
The resistor protects the IOs. It is transmitted and received via one line, so both ports are connected to each other (half duplex).
This works with any board that runs cleanflight, betaflight or raceflight. ;-)

**Comment by divenet** [comment]
thanks marv-t

**Comment by divenet** [comment]
Ok i am so sorry but i have to ask, in this sting of message, there is two values for the resister for the hardware setup. one place states 2.4k and another states 2.7k, i know its not much difference, ie 300 ohms. is one more accurate than the other for the application.  

Input Please @SnipeXR and @marv-t 

PS. for everybody's info, i will install this resister on a SPR f3 evo, ill be using a surface mount that fits just perfectly between Tx an Rx

**Comment by SnipeXR** [comment]
Ethier one will work that you mentioned. There is not a tight tolarance needed it's just used to help protect the devices on a half duplex wire comms.

**Comment by divenet** [comment]
> Ethier one will work that you mentioned. There is not a tight tolarance needed it's just used to help protect the devices on a half duplex wire comms. 

thanks @SnipeXR

**Comment by marv-t** [comment]
@divenet 
I've used Mini Melf (MMA). Fits very well to the pins in 2,54 mm pitch.

![img_20160427_094623](https://cloud.githubusercontent.com/assets/13554558/14845588/604abfce-0c5f-11e6-8ce2-91f8da89e7bc.jpg)

**Comment by divenet** [comment]
> I've used Mini Melf (MMA). Fits very well to the pins in 2,54 mm pitch.

Tanks @marv-t , very nice work and great idea

**Comment by martinbudden** [comment]
@divenet , can you close this issue please?

**Comment by divenet** [comment]
@martinbudden sure can, thanks to all.
