### ISSUE TITLE
Sparky 1 wire passthrough.

### ISSUE THREAD

**Issue by Jahnkeanater** [cleanflight/cleanflight#1888]
Cleanflight 1.12.0 1wire pass through still causes FC to get stunk in a loop.
When attempting to connect the sparky ends up in a loop telling esc#1 to reset every second.
The FC board is then unresponsive and a reset is required to resume normal operation.
Same behavior as 1.11.0.
escs tested and connect with naze32.
BlHeli 14.4.0.1

**Comment by Thor368** [comment]
I can confirm the behaviour with CF 1.12. Flight control hangs up when trying to "check" motor controlers in BLheliSuit in multi mode.
