### ISSUE TITLE
naze32 v1.12 , gps 3D fix + arming problem

### ISSUE THREAD

**Issue by emski0** [cleanflight/cleanflight#1895]
Once the GPS find a 3D fix, the naze32 stops arming.
Reverted back to 1.11, no problem there, once  it get 3d Fix , i can still arm the naze32

**Comment by OleEngr** [comment]
That sounds exactly like the problem I ran into in V12 released.  I didn't equate it to the GPS, but I knew it was something in my configuration, and that if I deleted enough from the config it eventually armed.  I quit trying to figure it out and went back to V11.  The GPS modes in V11 don't work correctly, but maybe that is a PID problem in my config.

**Comment by 3djc** [comment]
1.12 is very demanding for F1 processor with the default settings. It does work, but if you add enough work on top of default config, it will break. I think this is what is happening here. Try setting in CLI : 
set gyro_sync_denom = 2

**Comment by OleEngr** [comment]
Setting gyro_sync_denom = 2 allowed the quad to arm again.  Thanks for the tip.  There were a few times when it did arm with V12 and the GPS enabled, but maybe there wasn't a fix to raise the processor load the point where it wouldn't arm.  Now, if I could just get the GPS and ALT to work as well as they did in V12-RC1.

**Comment by borisbstyle** [comment]
There should be some kind of auto configuration when some features enabled

**Comment by yedey** [comment]
I had the same issue, but I couldn't arm even if gps wasn't fixed. The "set gyro_sync_denom = 2" workaround fixed it. I agree with borisbstyle, this should be configured automatically. It took me a whole day to realize that it wasn't a fault of my cleanflight/GPS/TX setup.

**Comment by hydra** [comment]
fixed in ee6b0df418498d9252b2a507f93f7aa1430dcde6

gyro sync denom forced to 2 when gyro sync and gp enabled at the same time.

**Comment by dyter** [comment]
check your cpu load with status command

**Comment by martinbudden** [comment]
@hydra, I think this can be closed now.
