### ISSUE TITLE
gyro_lpf CLI options mismatch

### ISSUE THREAD

**Issue by flounderscore** [cleanflight/cleanflight#1896]
It seems that the options for 'gyro_lpf'  in the documentation don't agree with the source code. Cli.md talks about 256HZ, but the actual enum item is OFF. @hydra  I'm happy to fix it, but what is the preferred convention? I'd say replace OFF with 256HZ in the source code.

**Comment by borisbstyle** [comment]
Yes I did that. OFF is more suitable to this option as it is different than other modes and does actually remove the lpf at the highest level
