### ISSUE TITLE
Motor output pins changed in master?

### ISSUE THREAD

**Issue by marv-t** [cleanflight/cleanflight#1899]
Here is the output from M1-M6. The M3 changed to M5 and M4 to M6

Target is NAZE (Flip32) - configuration QuadX

![act_master](https://cloud.githubusercontent.com/assets/13554558/13372701/c1b108d4-dd4f-11e5-9d6f-64f915852dfa.png)

In 1.12.0 NAZE 2016-2-20 14:55(stable) is it correct.

![1 12 0 naze 2016-2-20 14 55 stable](https://cloud.githubusercontent.com/assets/13554558/13372700/c1aefe2c-dd4f-11e5-8b0d-b057a750b4f4.png)

**Comment by marv-t** [comment]
It seems Y6 is also not working...

![act_master-y6](https://cloud.githubusercontent.com/assets/13554558/13372800/20743734-dd54-11e5-8769-1e34b1c31a1d.png)

**Comment by tricopterY** [comment]
In CLI do a dump and see if  'feature SERVO_TILT'  is disabled i.e displayed with a minus sign:
feature -SERVO_TILT

**Comment by marv-t** [comment]
@tricopterY The feature SERVO_TILT is disabled. Only in master is the pin mapping wrong.

**Comment by SteveAmor** [comment]
@marv-t can you do a git bisect to see which commit introduced this issue?

**Comment by marv-t** [comment]
Is solved by ledvinap.
