### ISSUE TITLE
v1.12 New message MSP_STATUS_EX has invalid length

### ISSUE THREAD

**Issue by flyinghead** [cleanflight/cleanflight#1901]
The new message MSP_STATUS_EX is invalid: its reported length should be 13 bytes, not 14.

**Comment by martinbudden** [comment]
Well spotted.

I've raised a PR to fix this, along with test code to check all the MSP out message lengths.

**Comment by flyinghead** [comment]
Thanks.

Great job with automated testing by the way!

**Comment by martinbudden** [comment]
@flyinghead , can you close this, since it has now been fixed?

Thanks
