### ISSUE TITLE
SP-F3 Mini: SBUS and Telemetry both on UART1, not working

### ISSUE THREAD

**Issue by StefanFeederle** [cleanflight/cleanflight#1906]
Hey guys,

SBUS and smartport-telemetry settings don't stick in the configurator on the same port (UART1).
Is this not implemented yet or somehow not possible? Each one on its own is working just fine.

cleanflight v1.12.0
SPRacing F3 Mini

Greetings Stefan

**Comment by 3djc** [comment]
This : https://github.com/cleanflight/cleanflight/issues/782 explains why it cannot be done.

Regards, 3djc

**Comment by StefanFeederle** [comment]
Thanks, this made it clear. What a pity
