### ISSUE TITLE
CC3D Revolution Support

### ISSUE THREAD

**Issue by proggod** [cleanflight/cleanflight#1908]
Is there any chance of getting support for the Revolution, what is involved in getting this support?  I'll glad buy one for someone who wants to do it :)

**Comment by martinbudden** [comment]
This is a duplicate of issue https://github.com/cleanflight/cleanflight/issues/46

Revolution is an F4 based board and support will be added as part of achieving the [F4 targets](https://github.com/cleanflight/cleanflight/milestones/STM%20F4%20Targets) milestone.

**Comment by proggod** [comment]
Sorry I did a search but didn't come up
