### ISSUE TITLE
Can't use emf_avoidance and led strip at same time

### ISSUE THREAD

**Issue by m3us** [cleanflight/cleanflight#1913]
Emf avoidance and led strip cant be used at same time as of build 1.12.
I think the overclock to avoid harmonics ruins the data signal sent to led strip.
Will take a look at it ,just putting it out here for others to know.
Cheers

**Comment by borisbstyle** [comment]
emf avoidance also breaks oneshot timing

**Comment by borisbstyle** [comment]
I opened a seperate issue
https://github.com/cleanflight/cleanflight/issues/1917

**Comment by hydra** [comment]
lets close this and keep the discussion in #1917
