### ISSUE TITLE
Unable to set airmode in CLI

### ISSUE THREAD

**Issue by kgrammatis** [cleanflight/cleanflight#1925]
According to the ['Modes' documentation](https://github.com/cleanflight/cleanflight/blob/master/docs/Modes.md) AirMode is available to use by manually assigning it to an AUX channel in the CLI. 

I used the following command in the CLI but there was no effect.
aux 4 27 4 1400 2100

The results:
# aux
aux 0 0 0 1300 2100
aux 1 2 1 1300 2100
aux 2 25 0 1600 2100
aux 3 20 3 1300 2100
aux 4 0 0 900 900
aux 5 0 0 900 900
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# 

Additionally the documentation for the ID's of Modes seems to be wrong.

**Comment by hydra** [comment]
I tested this, worked fine.
```
# aux
aux 0 0 0 900 900
aux 1 0 0 900 900
aux 2 0 0 900 900
aux 3 0 0 900 900
aux 4 0 0 900 900
aux 5 0 0 900 900
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# aux 4 27 4 1400 2100

# aux
aux 0 0 0 900 900
aux 1 0 0 900 900
aux 2 0 0 900 900
aux 3 0 0 900 900
aux 4 27 4 1400 2100
aux 5 0 0 900 900
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

save
```
<img width="1084" alt="screen shot 2016-03-09 at 11 51 22" src="https://cloud.githubusercontent.com/assets/57075/13628654/473f54f6-e5ed-11e5-8e5e-a06384d73942.png">

I will update the documentation now if needed.

**Comment by hydra** [comment]
i couldn't spot any of the mode ids being wrong.  make sure you look at the right column

**Comment by hydra** [comment]
Modes documentation updated in d96123d8f78309018542c834f4ade11716ec8b55

Thanks for the report.
