### ISSUE TITLE
Looptime does not affect cycletime

### ISSUE THREAD

**Issue by robjahnke** [cleanflight/cleanflight#1928]
Changing the looptime does not seem to affect cycle time on NAZE32. I have set looptime=1500 and also  set looptime=2500 with a save each time. The cycle time continues to report 990 - 1005 microseconds in the GUI. This has been verified with a Blackbox recording as well. It is acting as though looptime = 0 which would mean "run as fast as you can".

# version
# Cleanflight/NAZE 1.12.0 Feb 19 2016 / 20:01:21 (aa8608a)
# 
![image](https://cloud.githubusercontent.com/assets/17134989/13551803/320b0294-e30c-11e5-8453-100313286cb6.png)

![image](https://cloud.githubusercontent.com/assets/17134989/13551805/434b15b2-e30c-11e5-8275-725480ff8dda.png)

Thanks, robjahnke

**Comment by borisbstyle** [comment]
read manuals......looptime doesnt work when gyro_sync is enabled
Op 6 mrt. 2016 02:57 schreef "robjahnke" <notifications@github.com>:

**Comment by robjahnke** [comment]
Thanks. I've been reading the manuals a lot, but I missed that point. Issue Closed :-)  Rob
