### ISSUE TITLE
Can't connect with Mac OS X 10.11 (El Capitan)

### ISSUE THREAD

**Issue by edasque** [cleanflight/cleanflight#1931]
I installed and re-installed the drivers, rebooted, etc. It seems they don't work on 10.11. Happy to help debug.

**Comment by AustinSaintAubin** [comment]
Reinstall the chrome app after clearing the browser cache. Had that issue before, so I reset chrome and reinstalled the configurator app.

**Comment by hydra** [comment]
unrelated to firmware.  if there's a configurator issue raise it in the configurator issue tracker please.
