### ISSUE TITLE
throttle too low, won't arm

### ISSUE THREAD

**Issue by proggod** [cleanflight/cleanflight#1932]
Throttle was showing 885 in configurator, so the quad would never arm.

**Comment by proggod** [comment]
Range logic should be anything below a minimum number should allow the arm switch to arm the motors, there is some arbitrary range that is used to allow arming.  Is there a reason its not just under a certain number?  If no on agrees with my logic, then remove this ticket.  Yes I know how to fix it with rxrange command, and no idea why all of a sudden radio switched to a lower number.  But I don't understand the logic here..

**Comment by proggod** [comment]
Line 115 of rc_controls.c looks like logic works like I said, any idea WHY it wouldn't arm?  Am I missing something?

**Comment by HaukeRa** [comment]
It's probably failsafe.

-------- Ursprüngliche Nachricht --------
Von: proggod <notifications@github.com> 
Datum: 06.03.2016  23:46  (GMT+01:00) 
An: cleanflight/cleanflight <cleanflight@noreply.github.com> 
Betreff: Re: [cleanflight] throttle too low, won't arm (#1932) 

Line 115 of rc_controls.c looks like logic works like I said, any idea WHY it wouldn't arm?  Am I missing something?

**Comment by proggod** [comment]
http://prntscr.com/ac3sy0
http://prntscr.com/ac3t5f
wont arm right now, why?

**Comment by proggod** [comment]
It is failsafe causing problem, i think its because switches are at 999, this is after rxrange tuning on all of them, there needs to be some tolerance put in on these values, it can easily be +-5

**Comment by proggod** [comment]
Although flicking arm back and forth a few times, it eventually will arm.

**Comment by proggod** [comment]
Also in config for failsafe valid range is 885-2115 so failsafe should not be triggering

**Comment by tozes** [comment]
Same problem here, sometimes I have to switch back and forth 10+ times until it arms.

**Comment by hydra** [comment]
see #1895

**Comment by proggod** [comment]
Does this fix non-GPS problems ?    I have this arming problem on 5 different quads, w/ multiple boards, CC3D/Cleanflight, Sparky/Cleanflight, Revolution/Raceflight.   Looks to me like that changes the loop time, which shouldn't be an issue on those other boards.

**Comment by tozes** [comment]
You could always try it and see if it helps. In my case I think the F1 on the naze32 couldn't cope with all the features and maintain 1000 looptime.

You're right, changing `gyro_sync_denom = 2` changes the looptime to 2000. I tried to set 1.5 but it didn't work, the command seems to accept only integers.

**Comment by borisbstyle** [comment]
You cannot use denom of 1.5

gyro_sync_denom is the amount of gyro samples you want to have compared to
the max amount of samples.

denom 1 means 1:1 samples
denom 2 means 1:2 samples
denom 3 means 1:3 samples

you cant get 1.5 sample
Op 10 mrt. 2016 08:20 schreef "Antonio Lourenco" <notifications@github.com>:

**Comment by proggod** [comment]
So your telling me my sparkys and revolutions with nothing activated other then horizon mode can't handle the default loop times?   Even if it is the loop time, shouldn't it eventually see switch is armed if you leave it on?  Sometimes it never even arms, but by the time I plug it into a PC, it arms..

**Comment by borisbstyle** [comment]
than there is somethint else on yours....check basic stuff like endpoints
min_check etc.

It works on all other targets just fine
Op 10 mrt. 2016 17:09 schreef "proggod" <notifications@github.com>:

**Comment by proggod** [comment]
Endpoints are all between 999 and 2001, this is with multiple versions as, raceflight & cleanflight, and multiple build versions, and I have talked to others with same issues.   I am not sure why this ticket was closed..

**Comment by proggod** [comment]
Will black box logs show what is going on?

**Comment by borisbstyle** [comment]
It sounds like a config issue to me.

What board are you using?
Op 10 mrt. 2016 17:14 schreef "proggod" <notifications@github.com>:

**Comment by borisbstyle** [comment]
check receiver tab what its doing....check leds on the board....check cpu
usuage with status command. Check if your sticks are nicely centered.

Also try arming on a switvh as well
Op 10 mrt. 2016 17:16 schreef "Boris B." <dreambb1982@gmail.com>:

**Comment by proggod** [comment]
On raceflight its an Revolution, in cleanflight they are sparkys and cc3ds.  The only thing in common is we always use spektrum radios.   But I personally witnessed it not arming in the config.  Look at my screenshots, everything is perfect, the throttle was perfect, and yet it didn't glow green in cleanflight when arm switch was depressed.   You can see in the configurator the arm switch was in the right position too.

This is with switch arming, refer to the screen shots at the top.

**Comment by hydra** [comment]
Blackbox logging will not help as logs are not made when disarmed.

Post a config dump please.

**Comment by proggod** [comment]
[cc3d_dump.txt](https://github.com/cleanflight/cleanflight/files/167888/cc3d_dump.txt)
[Sparky_dump.txt](https://github.com/cleanflight/cleanflight/files/167887/Sparky_dump.txt)
[CC3D_revo_dump.txt](https://github.com/cleanflight/cleanflight/files/167889/CC3D_revo_dump.txt)

Here you go, 3 different boards all seem to have same issue.

**Comment by CanEHdian101** [comment]
i am having a similar issue but the led is showing green on my name 32 but in the config it doesn't light up

**Comment by mikeller** [comment]
@CanEHdian101: Check CPU load (should be well below 100%).

**Comment by CanEHdian101** [comment]
@mikeller it it at like 7%

**Comment by mikeller** [comment]
Ok, that's not it then. Some more things to check: Throttle at 0, gyro init finished (3 beeps).

**Comment by CanEHdian101** [comment]
So get no beeps what so ever unless I unplug receiver they plug in the battery and reconnect the receiver. I know but it's weird but it tells me all the hardware works

**Comment by mikeller** [comment]
That's a weird one. Can you post a config `diff` please?

**Comment by CanEHdian101** [comment]
I am kinda new so I don't know what a config  diff is so could you please tell me and now after a re flash it shows in the config but still no tones at all

**Comment by mikeller** [comment]
You should probably read up here then: https://www.rcgroups.com/forums/showthread.php?2249574-Cleanflight-firmware-for-STM32F3-based-FCBs-Check-First-Post-Please%21%21
