### ISSUE TITLE
Cleanflight should support Crazepony MINI flight controller

### ISSUE THREAD

**Issue by martinbudden** [cleanflight/cleanflight#1935]
See http://www.crazepony.com/en/index.html

**Comment by hydra** [comment]
Yes

**Comment by mintisan** [comment]
hi, @hydra which board type should I choose, if I use Crazepony?

I don't see Crazepony board on the board list.

**Comment by mikeller** [comment]
@mintisan: You'll have to ask your supplier or the manufacturer for this information.
