### ISSUE TITLE
SPracingF3mini sending random motor inputs with airmode enabled.

### ISSUE THREAD

**Issue by Surgikill** [cleanflight/cleanflight#1938]
When using airmode during flips and rolls sometimes a random motor input is sent to one motor causing it to jump above 65 percent throttle and causing crashes. All other motors will be near 10 percent throttle or less. Here is a video showing the blackbox logs before the crash. https://www.youtube.com/watch?v=jw9cxFpPopA

**Comment by cruisetheblues** [comment]
Had the same problem with naze rev6. Blackbox shows two motors running at half throttle when the stick input was at min throttle.
