### ISSUE TITLE
cleanflight can fit 64kb?

### ISSUE THREAD

**Issue by lrusnac** [cleanflight/cleanflight#1939]
What is the final size of the firmware, (not the debug mode)? I was thinking to load it on a STM32F103C8T6 and attach the sensors to the board, but unfortunately the STM32F103C8T6 has only 64kb.

**Comment by martinbudden** [comment]
There are a number of build flags for Cleanflight. The size of the firmware depends on which build flags are set. There is a build for the [CJMCJ](https://github.com/cleanflight/cleanflight/blob/master/docs/Board%20-%20CJMCU.md) board which fits in 64K, you might like to look at that as a starting point.

This is really more of a forum question though, so can you close this issue.

**Comment by lrusnac** [comment]
thanks
