### ISSUE TITLE
Flight - Smoother switching from horizon to acro.

### ISSUE THREAD

**Issue by mirko91** [cleanflight/cleanflight#194]
I think it will be nice to have a smoother change between flight modes, because now when switching from horizon to acro the copter can change even 20° of pitch/roll because probably the gyro drift is not been reset when the accelerometer is not taken in account any more.

**Comment by hydra** [comment]
yes, switching from acro to horizon is fine. switching from horizon back to acro could be better.

Implementation suggestions anyone?
