### ISSUE TITLE
CC3D motor channel config wrong 

### ISSUE THREAD

**Issue by 4712** [cleanflight/cleanflight#1942]
CC3D using 1-wire passthrough with BLHeliSuite: 
counts only 3 of 4 ESC channels for X-quad and the board hangs (at HardFault_Handler) when rebooting with msp or configurator. 
Release 1.12 does not have this issue.

**Comment by SteveAmor** [comment]
Which version do you have this issue with?  Can you perform a bit bisect to determine the commit that causes this issue.

**Comment by 4712** [comment]
I downloaded code at 11.3.2016.
