### ISSUE TITLE
BMP085 barometer is no longer recognized

### ISSUE THREAD

**Issue by dyter** [cleanflight/cleanflight#1945]
Cleanflight 1.12.0 no longer recognizes the BMP085, but betaflight 2.5.3 yes, why !?

So Barometer of BEEROTOR F3 isn't supported by cleanflight

**Comment by SteveAmor** [comment]
May be due to #1052

**Comment by dyter** [comment]
ok thanks, but how can I activate my BMP085 ?
I try set baro_hardware = 0,1,2 ... but no success

**Comment by dyter** [comment]
I found drivers BMP085 is missing in SPRACINGF3

**Comment by hydra** [comment]
BMP085 is not 'missing' from SPRACINGF3 - The board never had it to begin with.

**Comment by skaman82** [comment]
Having the same problem, tried to connect an external bmp baro to the SPRacing via i2c and it doesn't work.

**Comment by pilotdna** [comment]
Confirmed that external BMP180 or BMP085 on i2c pins with NAZE32 ACRO works in 1.11.0, but is not recognized in 1.12.0 and up.
