### ISSUE TITLE
Add TBS Powercube current sensor (INA230) support?

### ISSUE THREAD

**Issue by DaTwo** [cleanflight/cleanflight#1950]
Any chance we could get support for the ina230 current monitor on the tbs powercube (COLIBRI RACE flight control)? Its connected to the i2c bus via the BST pins on the stacking header.

I am more than willing to test. 

Here is the datasheet.
http://www.ti.com/lit/ds/symlink/ina230.pdf

**Comment by hydra** [comment]
sounds perfectly reasonable.  who wants to have a go?
