### ISSUE TITLE
needs documentation/clarification on PWM/Motor/Servo naming/mapping/ordering and more...

### ISSUE THREAD

**Issue by Jimmy-Z** [cleanflight/cleanflight#1954]
I'm new to cleanflight, trying to build a fixed wing with cleanflight, and was almost completely confused in the process. for the typical application - electrical fixed pitch multi rotors without any servo - there's plenty documentation, but not with airplanes and/or servos. thankfully with some help from oleost in IRC, I think I have some basic understandings now, but still can't confirm I've put all the pieces together.
- according to [`src/main/flight/mixer.c`](https://github.com/cleanflight/cleanflight/blob/master/src/main/flight/mixer.c), AIRPLANE mixers are defined like this:

``` C
/* ... */
static const motorMixer_t mixerSingleProp[] = {
    { 1.0f,  0.0f,  0.0f, 0.0f },
};
/* ... */
const mixer_t mixers[] = {
    // motors, use servo, motor mixer
/* ... */
    { 1, true,  mixerSingleProp },     // * MIXER_AIRPLANE
/* ... */
};
/* ... */
static const servoMixer_t servoMixerAirplane[] = {
    { SERVO_FLAPPERON_1, INPUT_STABILIZED_ROLL,  100, 0, 0, 100, 0 },
    { SERVO_FLAPPERON_2, INPUT_STABILIZED_ROLL,  100, 0, 0, 100, 0 },
    { SERVO_RUDDER, INPUT_STABILIZED_YAW,   100, 0, 0, 100, 0 },
    { SERVO_ELEVATOR, INPUT_STABILIZED_PITCH, 100, 0, 0, 100, 0 },
    { SERVO_THROTTLE, INPUT_STABILIZED_THROTTLE, 100, 0, 0, 100, 0 },
};
/* ... */
const mixerRules_t servoMixers[] = {
/* ... */
    { COUNT_SERVO_RULES(servoMixerAirplane), servoMixerAirplane },  // * MULTITYPE_AIRPLANE
/* ... */
};
```

couldn't figure out how motor/servos map to PWM pins from this, there is a function named `void mixerUsePWMIOConfiguration()` but it seems just do some specific port setting based on the output is motor or servo. `SERVO_*` names are hard coded in [`src/main/flight/mixer.h`](https://github.com/cleanflight/cleanflight/blob/master/src/main/flight/mixer.h)

``` C
// target servo channels
typedef enum {
/* ... */
    SERVO_ELEVATOR = 2,
    SERVO_FLAPPERON_1 = 3,
    SERVO_FLAPPERON_2 = 4,
    SERVO_RUDDER = 5,
    SERVO_THROTTLE = 6, // for internal combustion (IC) planes
    SERVO_FLAPS = 7,
/* ... */
} servoIndex_e; // FIXME rename to servoChannel_e
```

this order does comply with the motor and servo page(let's just let alone that one of them starts from 0 and the other starts from 1) in the configurator and that `FIXME` does give me a clue. as of my current understanding, motor ordering number in the mmix command and the servo parameter in the smix command are directly mapped to PWM pins, except sometimes they are 0 based and some other times they are 1 based, is this correct? I can understand hard coded servo slot names are useful with internal mixes, but custom mix CAN give them completely different purposes. shouldn't we at least document this?
- [`motor_order/airplane.svg`](https://github.com/cleanflight/cleanflight-configurator/blob/development/resources/motor_order/airplane.svg) actually this is about configurator but still mentioned here since it adds to the confusion. Pin 2 is actually empty. and we have a throttle servo for fuel engine on Pin 7.
- motors page of the configurator shows 8 motors and 8 servos. at start they really confuses my a lot, I really didn't know they are actually mapped to the same 8 PWM Pins, since obviously the output readings are not identical. should that be just 8 bars instead of 16 and labeled motor and servo respectively?
- actually there are more confusions introduced by anti-intuitive designs of the configurator. I think I should stop now and just fire another issue there.
- @kressir posted [his flapperon airplane mix](https://github.com/cleanflight/cleanflight/issues/1323#issuecomment-172731743) in #1323 

```
mixer CUSTOMAIRPLANE
mmix reset
mmix 0 1.000 0.000 0.000 0.000
smix reset
smix 0 2 0 100 0 0 100 0  #Left Aileron
smix 1 3 0 100 0 0 100 0  #Right Aileron
smix 2 4 2 100 0 0 100 0  #Rudder
smix 3 5 1 100 0 0 100 0  #Elevator
smix 4 2 9 -30 0 0 100 0  #Left Flapperon
smix 5 3 9 30 0 0 100 0  #Right Flapperon
```

this one doesn't comply with the hard coded servo slot names.
- [`docs/Mixer.md$supported-mixer-types`](https://github.com/cleanflight/cleanflight/blob/master/docs/Mixer.md#supported-mixer-types)

| Name | Description | Motors | Servos |
| --- | --- | --- | --- |
| AIRPLANE | Fixed wing; Ax2, R, E | M1 | S1, S2, S3, S4 |

the AIRPLANE line, "S1, S2, S3, S4", that index makes no sense and only leads to confusion. the motors and servos column should be just 1 and 4, respectively.
- [`docs/Mixer.md#example-4-custom-airplane-with-differential-thrust`](https://github.com/cleanflight/cleanflight/blob/master/docs/Mixer.md#example-4-custom-airplane-with-differential-thrust)

``` bash
mixer CUSTOMAIRPLANE
mmix reset
mmix 0 1.0 0.0 0.0 0.3  # Left Engine
mmix 1 1.0 0.0 0.0 -0.3  # Right Engine

smix reset
# Rule  Servo   Source  Rate    Speed   Min Max Box
smix 0 3 0 100 0 0 100 0  # Roll / Aileron
smix 1 4 0 100 0 0 100 0  # Roll / Aileron
smix 3 5 2 100 0 0 100 0  # Yaw / Rudder
smix 2 2 1 100 0 0 100 0  # Pitch / Elevator
```

servo mixes actually complies with the hard coded servo slot names, but, let's look at the Pin outputs chart in the document:

| Pins | Outputs |
| --- | --- |
| 1 | Left Engine |
| 2 | Right Engine |
| 3 | [EMPTY] |
| 4 | Roll / Aileron |
| 5 | Roll / Aileron |
| 6 | Yaw / Rudder |
| 7 | Pitch / Elevator |
| 8 | [EMPTY] |

why elevator is on Pin 7 instead of 3? is this document incorrect or my understandings/assumptions are wrong?
- when I find out CUSTOM AIRPLANE is hard coded to use 2 motors, I thought someone with particular needs might consort to CUSTOM instead, that sure sounds more versatile, but then I found out that CUSTOM is hard coded with no servo, shouldn't that be named CUSTOM FIXED PITCH MULTI ROTORS WITHOUT TILT? by naming it just CUSTOM makes me think it's more versatile than CUSTOM AIRPLANE. or at least document this in Mixer.md. on the other hand it seems mmix reset CAN be used to override hard coded mmixes, is that correct?
- look at the AIRPLANE mixer, doesn't that throttle smix look ugly to you? what exactly is different between motor pin and servo pin? I think just eliminate that smix 7 and set motor_pwm_frequency to 50 is a cleaner solution to me, and of cause do not enable ONE SHOT. let's say, if some one built an 4*fuel engine quad rotor, or more practically a pitch controlled quad rotor, we can't use smix to do that right?
- more deeply thinking, we should call them motor mix and control surface mix instead. and esc_pwm_frequency and servo_pwm_frequency should be independent from mix type. make more sense and much more flexible.
- [`docs/Mixer.md#example-5-use-motor-output-0124-because-your-output-3-is-broken`](https://github.com/cleanflight/cleanflight/blob/master/docs/Mixer.md#example-5-use-motor-output-0124-because-your-output-3-is-broken)

``` bash
# For this to work you have to make a dummy mmix for motor 3. We do this by just saying it has 0 impact on yaw,roll and pitch.
mixer custom
mmix reset
mmix 0 1.0, -1.0, 1.0, -1.0
mmix 1 1.0, -1.0, -1.0,  1.0
mmix 2 1.0, 1.0, 1.0, 1.0
mmix 3 1.0, 0.0, 0.0, 0.0
mmix 4 1.0, 1.0, -1.0, -1.0
save
```

why not just mmix 0 1 2 4 and skip 3? if we can't skip, what is the motor ordering number parameter in the mmix commands used for?
- why is there a separate feature named motor_stop, in my understanding ESC should be calibrated from min_command to max_throttle, and setting min_throttle = min_command is equivalent to enable motor_stop, is that correct? if positive, this is not clean design in my opinion.
- Angel mode is simply marked "Legacy auto-level flight mode", while Horizon mode is labed "auto-level flight mode", that confuses me a lot since I see lots of people have them both available on switches, why would anyone do that if their difference is one of them is supposedly better than the other? Answer to this shouldn't be hard to find on the Internet, but I really think we need more documentation on this.
- [`docs/PID%20tuning.md#pid-controllers`](https://github.com/cleanflight/cleanflight/blob/master/docs/PID%20tuning.md#pid-controllers) say we used to have 6 PID controllers but now we only have 3, when I'm climbing that huge post on rcgroups I see people talking about PID 6, I don't know what they are talking about, actually when I read PID 3 in older posts, I don't know what they are talking about, we should at least keep  some short explanations of those modes in document for historical reasons.

I hope these won't sound like whining, from a developer/multi rotor side of view, you guys might think these things are too explicit and too simple to need any explanation. but as a newcomer/airplane side of view, things do look different.

look at this [HOWTO-setup-iNAV-for-fixed-wing](https://github.com/iNavFlight/inav/wiki/HOWTO-setup-iNAV-for-fixed-wing), people have to trial and error to find out which pin to connect.

I can help with documentation and simpler coding but not before someone can confirm that my understandings are correct.

Thank you all for your wonderful work and your time spent on this long post.

**Comment by Ralf-W** [comment]
@Twilight - I think everything you write here is correct. Some things are even worse. Have a look here: https://github.com/iNavFlight/inav/issues/141#issuecomment-206941412
