### ISSUE TITLE
IR LED/VTX Integration

### ISSUE THREAD

**Issue by martinbudden** [cleanflight/cleanflight#1958]
Just an idea, but @jflyper 's SPI VTX module support got me thinking. If the VTX channel is set by software, then it could also be output on the IR transponder.

This could give race organisers a handy way of checking the VTX channel of each competitor - they could have an IR scanner which reads it from the transponder. Indeed I could envisage a scenario where an IR scanner on the start line checks that all the aircraft are on different VTX channels.

OK, this is all a bit pie is the sky at the moment, and would require a suitable protocol and increased take-up of VTXs that can communicate with the flight controller. But I don't think it is totally unrealistic.

I haven't actually done any FPV racing, so this idea may be totally stupid - if so, feel free to shoot it down in flames.

**Comment by hydra** [comment]
yes, there are loads you can do with a transponder IR led when it's not armed :smile:

**Comment by jflyper** [comment]
We can also have a VTX display page.

**Comment by hydra** [comment]
i've been long since also thinking about changing vtx channels via cleanflight.

**Comment by hydra** [comment]
See #1948

**Comment by hydra** [comment]
Also see #2210.

**Comment by hydra** [comment]
With regards to the original idea, well orgianized races I've attended use frequency scanners.
