### ISSUE TITLE
Configurator should check board type before flashing

### ISSUE THREAD

**Issue by MasterZap** [cleanflight/cleanflight#1959]
When you flash, the configurator sends boot command to the board and proceeds to flash it.

What if it first sent a "version" command to check what board it was, and proceed to issue a warning if you were trying to - for example - by mistake flash the RMDO firmware to a Naze32 mini. :)

That would be awesome, wouldn't it?

(And yes, I confess, I did exactly that mistake last night :) )

/Z

**Comment by Twilight** [comment]
+1

BTW you should post [there](https://github.com/cleanflight/cleanflight-configurator/issues)

**Comment by MasterZap** [comment]
Good point - will do!

Shall I nuke this?

**Comment by MasterZap** [comment]
Made an issue over in the configurator. Closing.
