### ISSUE TITLE
RGB LED strip timing change

### ISSUE THREAD

**Issue by drumbum961** [cleanflight/cleanflight#196]
Hey there,

I just bought these LED's from polulu 
 http://www.pololu.com/product/2549

I read in the documentation about configuring these strips that the timing for this particular type will need a simple timing adjustment via the CLI if requested by the user.  I'm not sure if this is the place to get that request in or not but I'll try here first and see what happens :)  

Thanks ahead of time!
KFM

**Comment by hydra** [comment]
Closing.
