### ISSUE TITLE
Documentation for current_meter_type value seems to be wrong

### ISSUE THREAD

**Issue by XDA-Bam** [cleanflight/cleanflight#1968]
The documentation lists the values [0, 1, 2] for current_meter_type, corresponding to no sensor/hardware sensor/virtual sensor. Trying to set current_meter_type to one of those values in the CLI results in "invalid value" error with Cleanflight 1.12. The correct values are 'ADC' and 'VIRTUAL' instead of '1' and '2' (tested). '0' most likely will be 'NONE', but I didn't test this one, yet.

Tested on SP Racing F3 clone with Cleanflight 1.12. If necessary, 'dump' can be provided.

**Comment by Pierre-A** [comment]
**@XDA-BAM**, good catch , thanks. Values are "NONE", "ADC", "VIRTUAL". Can you open a PR for updating the _battery.md_ file ?

**Comment by XDA-Bam** [comment]
No, sorry. I don't have GIT set up right now :|

**Comment by Pierre-A** [comment]
OK done, see PR #1969 so you can close this issue.
Thanks.

**Comment by XDA-Bam** [comment]
That was FAST. Thanks! :)
