### ISSUE TITLE
Inconsistent use of axis indices

### ISSUE THREAD

**Issue by martinbudden** [cleanflight/cleanflight#1973]
Cleanflight uses a variety of axis indices, these are:

1. the flight dynamics indices, `FD_ROLL`, `FD_PITCH` etc
2. the angle indices, `AI_ROLL`, `AI_PITCH`
3. the radio control indices, `ROLL`, `PITCH` etc
4. the PID indices, `PIDROLL`, `PIDPITCH` etc

Although, by design, these have the same values, they are not semantically the same. In a number of places the wrong index is used. This works, but it can make the code a little unclear.

**Comment by hydra** [comment]
pr merged.
