### ISSUE TITLE
Cleanup proposal - split mixer.c into two files, mixer.c and servos.c

### ISSUE THREAD

**Issue by martinbudden** [cleanflight/cleanflight#1978]
`mixer.c` is unwieldy and difficult to read, especially since it is full of `#ifdef USE_SERVOS` directives.

I propose to split the servo code into a new file `servos.c` to make things more readable.

@hydra , if you like this proposal reply to that effect and in due course I will submit a PR.

**Comment by Ralf-W** [comment]
@martinbudden A lot is already done here https://github.com/iNavFlight/inav/pull/148

**Comment by hydra** [comment]
yes, we'll use that work when we merge the inav changes soon.

perhaps, if their code is finished, start a PR to merge the updated mixer code?

**Comment by martinbudden** [comment]
Fixed in PR https://github.com/cleanflight/cleanflight/pull/2125
