### ISSUE TITLE
Alt-hold Sonar problem

### ISSUE THREAD

**Issue by Ahrovan** [cleanflight/cleanflight#1983]
Hi

if we enable rx-msp input, sonar no receive any data and we can not use alt-hold.

Board : naze32
sonar : srf04 -> Motor 5 and 6
Msp : usart1 or 2
baro : MS5611 -> I2C

thx, Ahrovan

**Comment by Flugsicherung** [comment]
You connect the sonar to the wrong pins.
Please read documents sonar.md and Board- Naze32.md for correct informations.
Close this issue please.
