### ISSUE TITLE
IO - Support PWM Buzzers for audible battery warnings.

### ISSUE THREAD

**Issue by maximan** [cleanflight/cleanflight#199]
For boards that have no buzzer output (like CC3D) or for users who want to drive 12V loads using something like a Receiver Controlled Switch (http://www.hobbyking.co.uk/hobbyking/store/__46040__Turnigy_Receiver_Controlled_Switch.html) it would be useful to have a CLI option (e.g. **buzzer_on_pwm_ch**) that would set that PWM channel to a value specified in **buzzer_on_pwm_high** when active and **buzzer_on_pwm_low** when inactive. This would override whatever value was on that channel, so the channel number must be above 4 to avoid interfering with regular RC control. Validation code would clear the **buzzer_on_pwm_ch** variable on boot if a value of 4 or below is set.

Clearing **buzzer_on_pwm_ch** would disable the rediect to PWM channel and revert to the buzzer pin on the FC, if supported.

**Comment by andymac4182** [comment]
Pass through PWM would be great. :+1:

**Comment by hydra** [comment]
There are two discussions here which has prevented this from being discussed or worked on.
1. Passthough
2. PWM buzzer

Lets keep this focussed on PWM buzzer support please everyone.
