### ISSUE TITLE
Cleanup proposal - review default settings

### ISSUE THREAD

**Issue by blckmn** [cleanflight/cleanflight#1999]
The current 'in code' method of default settings results in a lot of ifdef statements, and increases the overall code base. This problem will only increase as more targets come onto the market.

This issue is to discuss ways in which this could be improved. Perhaps relying on the Configurator more for defaults rather than have the defaults on the device itself.

**Comment by fftunes** [comment]
"Perhaps relying on the Configurator more for defaults rather than have the defaults on the device itself."

Absolutely, why not? I don't see a single reason to keep a "backup" on my FC.
