### ISSUE TITLE
Sonar functionality improvement

### ISSUE THREAD

**Issue by l2smith2** [cleanflight/cleanflight#201]
It would be great to see the sonar range used to control things other than altitude. Similar to the aux setup of a low to high range. 
ie. once sonar distance is above a certain range it can trigger rectractable legs automatically. or landing lights when near ground.
Perhaps when it is in altitude hold with sonar and it exceeds the high range for a set time you can set the baro to turn on. 
Maybe even limit the tilt angle or rc rate or throttle curve when near the ground so you can have a super aggressive flying machine but super smooth to land.

**Comment by hydra** [comment]
This issue is far too vague to be worked on. Closing.  Please check to see if the ideas are not elsewhere.  I have found issues today that cover most of the things mentioned here.

See #234
