### ISSUE TITLE
Battery.md is out of date

### ISSUE THREAD

**Issue by mapaolini** [cleanflight/cleanflight#2010]
Battery.md is out of date. Specifically for Virtual Sensor it says the following:
"
Enable current monitoring using the CLI command:

feature CURRENT_METER
Configure the current meter type using the current_meter_type settings here:

Value	Sensor Type
0	None
1	ADC/hardware sensor
2	Virtual sensor
"

If you set current_meter_type=2
it returns
Invalid value

However if you use 
set current_meter_type=VIRTUAL
 instead of 2, it works.

I also suspect the docs on the math are very wrong as following the steps using measured current yielded wildly wrong results.

**Comment by gaelj** [comment]
I just published a PR with updated documentation.
I didn't find anything wrong with the maths, though. I did add a mention that Ampers should be used as a unit in the first method. I used the second method with very good results. I didn't test the first method but the example results in a reasonable-looking value.
