### ISSUE TITLE
Board hangs when entering Configurator pages

### ISSUE THREAD

**Issue by DzikuVx** [cleanflight/cleanflight#2028]
Build based on 4706dead22023c1284f65991160fdb73f5e5317d
Target: NAZE

Board hangs when Configurator enters _Configuration_ or _Motos_ tab.
After entering those pages, content is not displayed, unable to change pages. "Packet error" goes up by 1 every second .

**Comment by martinbudden** [comment]
This is fixed in the latest version of the configurator, i.e.: https://github.com/cleanflight/cleanflight-configurator

I don't think it's been released yet, but you can clone it locally and use it that way.

**Comment by martinbudden** [comment]
@DzikuVx , I presume this is no longer a problem for you, so I'm closing this issue.
