### ISSUE TITLE
Throttle middle value in config tab

### ISSUE THREAD

**Issue by waltr1** [cleanflight/cleanflight#2032]
The throttle middle value in the config tab is incorrectly labeled.
This is the MID_RC value applied to ALL stick input values. I checked this by changing it in the GUI then checking in the CLI.

This has caused much confusion to beginners and experts alike.

The label in the GUI should be changed,

**Comment by SteveAmor** [comment]
@waltr1 could you please raise this issue under Cleanflight configurator and close here. Thanks.
