### ISSUE TITLE
I-BUS on some other pin?

### ISSUE THREAD

**Issue by Arise** [cleanflight/cleanflight#2039]
The documentation is mentioning I should connect my I-BUS TGY-i10 receiver to the pin 4 (UART2RX) on Naze32 Board (I have a rev.6). 

Already did that and my receiver/transmitter works just fine now in cleanflight configurator, after I enabled Serial RX switch in RX column in the Ports Tab and then I've set Receiver Mode = RX_SERIAL and Serial Receiver Provider = IBUS in Configuration Tab.

But still, I would like to know if is possible to use Pin1 (PPM) on the Naze32 board for the receiver or eventually the Spektrum pins, I don't like the idea to block UART2 pins with the wire from I-BUS.

This kinda blocks me for adding GPS connection or other serial devices to the UART2. :(

Thanks!

**Comment by Arakon** [comment]
Spektrum pin is still UART2 RX. It's a serial protocol, so it needs to use a serial port. If you need more ports, either use softserial or get an F3-based FC with more serial ports.
