### ISSUE TITLE
Cleanflight FW not updating GPS flight modes to OSD

### ISSUE THREAD

**Issue by SupremeFPV** [cleanflight/cleanflight#204]
Having a issue with my OSD not showing GPS fix, GPS hold and GPS home.
The osd is a witespy minumOSD running KV osd FW. The G icon blinks when it is searching for sattelites but does not update to the FIX icon when lock is achived. it also does not show the gps hold or gps home icon when i enable those modes. 

Tested it with baseflight FW and it worked fine with that. Is there something that might have been changed in the code that prevents the naze from sending the status of theese modes over MSP?

**Comment by hydra** [comment]
Can you please re-test with latest firmware?

**Comment by SupremeFPV** [comment]
Moved over to MW OSD, but ill flash back to KV and give it a try.

**Comment by SupremeFPV** [comment]
Alright, flashed KV osd today and took it outside to get gps lock. It works like a charm now, so the problem might have been with my KV osd flash(downloaded a new file from team-KV) or it got fixed with the update to cleanflight. 

Anyhow, problem solved.

**Comment by fiveangle** [comment]
Good that it's working. BTW- you might check into MWOSD. 

Feel free to close this issue. 

-=dave

**Comment by dimitrov-b** [comment]
Flip32+ with 1.7.2 and minimosd with kv osd 2.3 and i can't solve the problem :(

**Comment by SupremeFPV** [comment]
Try downloading the KV osd firmware again and see if that helps.

**Comment by hydra** [comment]
Use MWOSD, not KV Team OSD.  Please re-open if there's still an issue after verifying that your MWOSD configuration is correct.
