### ISSUE TITLE
SPRacing evo sd card issue

### ISSUE THREAD

**Issue by dal75** [cleanflight/cleanflight#2040]
When an sd card (empty and formatted) is put into the sd card slot on the board a file called FREESPAC.E is created which is 10.8gb in size, leaving very little room for flight logging.
File can be deleted but is re-written once placed back in the board.

**Comment by hydra** [comment]
read the documentation please

**Comment by hydra** [comment]
https://github.com/cleanflight/cleanflight/blob/master/docs/Blackbox.md#onboard-sd-card-socket

**Comment by dal75** [comment]
My bad. Looks like I really need to catch up on how much Cleanflight has progressed since I last used it!
