### ISSUE TITLE
CLI Problem on latest evo cf fw

### ISSUE THREAD

**Issue by dal75** [cleanflight/cleanflight#2041]
When exiting the cli, instead of putting you back in the gui, it disconnects the board from the software.
It does save whatever changes you have made, but its very annoying having to reconnect every time you leave the cli.

**Comment by hydra** [comment]
configurator needs updating, won't be long till this is released.  btw you raised this bug in the wrong place - it should be on the configurator issue tracker.

**Comment by dal75** [comment]
Great, thanks. Sorry for misposting, I'm new to this github stuff. Only ever used it for fw downloads before.
