### ISSUE TITLE
BSOD - WIN 10 - SP Racing F3 (clone) ...

### ISSUE THREAD

**Issue by M151514K** [cleanflight/cleanflight#2044]
Hi Guys, 

My unnoficial version of SP Racing F3 has seriously problem with my PC running on WIN 10, i think that is problem only in drivers, because on other computers with Win 7  its everything fine (i think...). I tried it on Clean and Base Flight configurators...but all the same in both programs.

Connection is ok - from start, but after few minutes using... crash - BSOD with the name: "Kernel Security Check failure"

Has anybody same issue ?

**Comment by SteveAmor** [comment]
Hi @M151514K Please can you ask such support questions on a forum such as RCGroups.  Issues are for reporting bugs which developers can fix. Please close this issue. Thank you.
