### ISSUE TITLE
Feature request - choose LED Color for "armed" and "disarmed" 

### ISSUE THREAD

**Issue by ps915** [cleanflight/cleanflight#2047]
Would it be possible that the user can change the hardcoded LED colors for "armed" and "disarmed" state in Cleanflight and Betaflight?
Right now, the disarmed Color is blue and everytime there is a new releases, i have to change it manuell an compile it again.

Its not nessesary to configure it via the GUI. two cli variables would be awesome.

Cheers,
Phil

**Comment by ps915** [comment]
https://github.com/MaxWinterstein/cleanflight/releases/

A fried did this for some time, but it's anoying to do this on every Release or even when switching the an other Color.

**Comment by derdanu** [comment]
+1

**Comment by GlobalhawkDE** [comment]
Definitely a must! +1

**Comment by gaelj** [comment]
PR #2050 (only the last commit) will enable you to user-define the armed color with minimal code change (1 line). Disarmed color is still static green however.
I don't see an easy way to adapt the existing code into assigning 2 custom colors to a given mode.
On the other hand  it could be part of a broader project enabling customization of all static colors.

**Comment by JohnOCFII** [comment]
It seems this request could become a support problem.  If people start changing their colors to whatever pleases them, and then there is a support issue, and someone trying to help them asks "is the LED red?" for example but the user has changed their LED scheme, it could lead to confusion.

**Comment by NightHawk32** [comment]
I don't think that will happen, you can always access the configurator. There are hundreds of copters without LEDs and those people also managed to get it running.

**Comment by ps915** [comment]
Where is the problem to get the hardcoded colors into cli variables. 
Everything will be as before but if you want, you can change the color via CLI?

**Comment by 19Gerhard85** [comment]
+1

**Comment by hydra** [comment]
deffo think there's no support issue.  support issues come from the FIXED leds.  plus support staff could always ask users to reset to defaults and retry.

**Comment by hydra** [comment]
@gaelj see review of PR #2050

**Comment by ps915** [comment]
Hey Dominic,
thanks you and all for the smooth communication. So whats the way my feature request will be come along?
Do i need to deliver more information on this and will it be implemented in Cleanflight? And whats about Betaflight? 
Will it also implelemted in Betaflight?

Cheers,
Phil

**Comment by gaelj** [comment]
Hi, it's currently going through the build server.
Please give me your feedaback on 
https://github.com/cleanflight/cleanflight/pull/2053/commits/d2dd5260975482b3b43aa14683535c533adc75f2

**Comment by skaman82** [comment]
Hi Philipp, this issue tracker ist cleanflight only. And yes this feature request will almost likely make it into CF. 

Von meinem iPhone gesendet

**Comment by JohnOCFII** [comment]
> It seems this request could become a support problem. If people start changing their colors to whatever pleases them, and then there is a support issue, and someone trying to help them asks "is the LED red?" for example but the user has changed their LED scheme, it could lead to confusion.

My Bad.  Sorry.  Too early. Not enough coffee. I was thinking someone wanted to change the colors of the fixed LEDs.

**Comment by gaelj** [comment]
https://github.com/cleanflight/cleanflight/pull/2053

**Comment by skaman82** [comment]
Done, ps915 please close this issue

**Comment by ps915** [comment]
Thanks guys. :)
