### ISSUE TITLE
Cleanflight on an STM32F103C8T6 Dev-Board

### ISSUE THREAD

**Issue by iMattmax** [cleanflight/cleanflight#205]
Hello, I wanna build an quadcopter that has an STM32F103C8T6 Dev-Board as a flight control an I wanan use cleanflight. 
But I'm not quiet sure which pin connectors I have to use. In the www I found some DIY-FC based on an STM32F103-board. So, I wanna connect GPS, Bluetooth, Telemetry and the LED-Stripe to the FC, but I need a little help. 
So does anybody has an idea which connectors to I have to use?

**Comment by Lalbabu2001** [comment]
> Can you explain me, what I have to do an what you mean with "you'll have to make a new target and add the features you want - check the makefile and thar src/main/target/* directories."
> 
> I'm totally new in this, so I need some help to understand what you mean and what is to do.
> 
> I flashed my STM32-board with the cleanflight-configurator, but then I get no connection?
> 
> I solved the problem. I flashed the board the wrong way, so now I did it again with the right Boot-pin connections and everything is allright till now.

Hey did you got that what you want? Please asssit me i am on same way..

**Comment by iMattmax** [comment]
My question is 9 years old. I can‘t remember, sorry!
