### ISSUE TITLE
cc3d not reading receiver pwm outputs

### ISSUE THREAD

**Issue by gegtor** [cleanflight/cleanflight#2051]
When i move sticks nothing moves on screen

and only throttle channel show 885 rest 1500

here is my config:

Receiver mode : rx_parallel_pwm
Channel map: aetr1234
Rssi channel: Disabled
Cleanflight version: 1.12

**Comment by gegtor** [comment]
And i tested my receiver with servo all channels are working fine

**Comment by gegtor** [comment]
Solved i need to disable ws2812 leds :( any one know how have leds and pwm receiver at one?

**Comment by Arakon** [comment]
The CC3D runs out of timers, chances are that your only option is a different FC.

**Comment by gegtor** [comment]
Ok thx

**Comment by gegtor** [comment]
is there a way to free up timers?

**Comment by Arakon** [comment]
Not without removing other features.

**Comment by gegtor** [comment]
but i have only leds turned on

**Comment by Arakon** [comment]
I mean actually removing them from the code.

**Comment by gegtor** [comment]
can someone remove them for me if its not big deal :3?

**Comment by martinbudden** [comment]
@gegtor , Cleanflight does not support PWM receivers and WS2812 LEDs at the same time. There is no real way to do this.

I suggest you get a PPM receiver, they are reasonably cheap and it also much easier to wire.

Can you please close this issue?

**Comment by gegtor** [comment]
Ok thx

**Comment by gegtor** [comment]
Ok Thanks
