### ISSUE TITLE
Disarm by RC channel may be dangerous

### ISSUE THREAD

**Issue by ledvinap** [cleanflight/cleanflight#207]
Disarming logic (https://github.com/cleanflight/cleanflight/blob/master/src/main/io/rc_controls.c#L101) is problematic if invalid data on channel used for arming are received (and disarm_kill_switch is enabled). Cleanflight will immediately disarm and prevent rearming because throttle is not LOW. Not a nice thing to happen few meters above ground ...

This is mainly problem with softserial/rx testing, but noise on PWM/PPM rx will have similar results.

One possible fix is to disarm immediately, but ignore throttle check for a short time to allow rearming if disarm was caused by glitch ...

**Comment by hydra** [comment]
This should be addressed in the recent RX loss detection and failsafe rework in 1.9.x.

Please test current master and if the problem remains then re-open this.

**Comment by ledvinap** [comment]
I did not check too deeply, by the issue is probably still there ...
