### ISSUE TITLE
So f3 and micro minim

### ISSUE THREAD

**Issue by jeffwhu** [cleanflight/cleanflight#2073]
Hi
Can a micro minim osd be used on uart2 by configuring port to msp ?
The build I am doing has limited space an d I didn't want or have to deconstruct the quad to unplug minim on uart1 to gain access to usb port.
Have x4rsb on uart3 set as serial.
Which leaves uart2 clear, if I set uart2 to msp will this give micro minim the telemetry it needs?

**Comment by Arakon** [comment]
Yes.

**Comment by jeffwhu** [comment]
That's is a straight enough answer.....thanks

**Comment by martinbudden** [comment]
@jeffwhu , can you close this issue?

**Comment by jeffwhu** [comment]
Done

On 23 Apr 2016, at 09:42, Martin Budden <notifications@github.com<mailto:notifications@github.com>> wrote:


@jeffwhu<https://github.com/jeffwhu> , can you close this issue?

-
