### ISSUE TITLE
updateGtuneState no longer called in taskMainPidLoop

### ISSUE THREAD

**Issue by martinbudden** [cleanflight/cleanflight#2074]
At some point the call to `updateGtuneState()` in `taskMainPidLoop()` in `mw.c` seems to have been lost.

The function `updateGtuneState` is still there, but it is no longer called.

**Comment by SteveAmor** [comment]
Git bisect is telling me it was removed here:  cb941a7041a7ddcb70e6a3f1859399dd25a6c5b8

**Comment by martinbudden** [comment]
@SteveAmor , thanks for doing the git bisect. It looks like this was a genuine mistake when the new scheduler was incorporated. @digitalentity , would you care to comment?

**Comment by SteveAmor** [comment]
Some of the PRs have waaaaaaassy tooooooo much going on.............

**Comment by digitalentity** [comment]
Martin, this is high probability. I probably missed gtune in the first
place.

**Comment by SteveAmor** [comment]
Guys, you are doing fantastic work :-)

**Comment by hydra** [comment]
fix merged.
