### ISSUE TITLE
RX - RSSI On PWM while using serial RX or PPM Sum

### ISSUE THREAD

**Issue by sevet** [cleanflight/cleanflight#208]
Hi,

Using the Frsky X4R-SB with SBUS using serial rx, there is a PWM output on it for serial RSSI,
Can you please allow the RSSI_Channel to work in parallel with serial_rx?

Guess RSSI_ADC will also work but will need a fliter made,
This will also be a good feature for D4F-II which had SPPM and PWM RSSI and probably some more RX's.

Thanks,

**Comment by zdar** [comment]
Let me expand this according to closed #574 

Could the input code be altered in away to allow both serial/ppm and PWM at same time?
 E.g. to take channel 1-8 from PPM (or other serial format) and channels 9+ from remaining input (PWM) pins. This way more than 8 channels could be possible (e.g. two receivers connected) and it would also solve PWM RSSI problem.

**Comment by leothehuman** [comment]
Can someone coach me a bit on the best way to approach this? I'd like to take on this, but can use some insight.

**Comment by tracernz** [comment]
@leothehuman https://github.com/TauLabs/TauLabs/blob/f81a193f00f62c601761c8e653d829b3bca49d6f/flight/PiOS/STM32F4xx/pios_frsky_rssi.c
