### ISSUE TITLE
Can't get pwm working on cc3d atom

### ISSUE THREAD

**Issue by acdi01** [cleanflight/cleanflight#2096]
Hi,
I see that there are other posts about pwm and the cc3d, but I can't seem to get my fifth channel to work. I disabled vbat and I am not using the white wire(channel three). I know my receiver works and that I have continuity throughout the wire. Any suggestions?
Thanks,
Alex

**Comment by hydra** [comment]
This sounds like a support question, please use rcgroups.com for support.  If you can confirm the problem then please supply steps to repeat and we can try to replicate here.  Suggest showing people photos of your wiring when you ask for support.
