### ISSUE TITLE
I2C implementation on f1 chips

### ISSUE THREAD

**Issue by gvuyk** [cleanflight/cleanflight#2097]
No problem, just a question
Is there a particular reason why the I2C implementation for stm32f1 chips is interrupt based even though the read/write functions wait on a loop for the operation to finish?

**Comment by ledvinap** [comment]
IMO working code was used and simplified to fit Multiwii i2c interface.

It would be great to have interrupt-driven I2C .. But without RTOS it's not that easy to do right

**Comment by jflyper** [comment]
I was also looking at the I2C code in conjunction with #2075 & #2062.

I was wondering if 125KHz interrupt is too much to handle, and started to dream about DMA'ing once the funky arbitration is over.

**Comment by martinbudden** [comment]
@gvuyk , can you close this issue now?
