### ISSUE TITLE
LED - Add mode where LED strip shows heading in headfree mode

### ISSUE THREAD

**Issue by hydra** [cleanflight/cleanflight#21]
Suggested by CurtisBeef on IRC.

**Comment by xtrmtrk** [comment]
I'm not sure if this is the same thing or just related, but I'd love a mode where an LED can be assigned to change color based on the compass direction of the craft.

**Comment by hydra** [comment]
@xtrmtrk no, the idea here is that given a ring of LEDs one could indicate north, and the other could indicate the heading used by HEADFREE.

Specifically, this heading: https://github.com/cleanflight/cleanflight/blob/master/src/main/mw.c#L661
