### ISSUE TITLE
Flight - Improve YAW performance

### ISSUE THREAD

**Issue by FinalGlide** [cleanflight/cleanflight#210]
The Naze 32 yaw seems to be rather poor compared to Multiwii 2.3 and Nanowii and CC3D especially when using pid_controller= 1 since the PID's are decoupled from the RCrate. This is probably the most common gripe I hear from people about the Naze 32.  Possibly there is an issue with the code but I also have another idea.  

What about making a separate RCrate for Yaw?  So then you would have the following parameters you could adjust:
Roll/Pitch rate
Yaw rate
Roll/Pitch RCrate
Yaw RCrate

This would give you a lot more tuning options which would help as the amount of yaw varies depending on the type of multicopter you are flying and how you are flying it.

**Comment by MJ666** [comment]
You may try the port of the MultiWii 2.3 PID controller.
#321

**Comment by dave-pitman** [comment]
How about aiming for:

Eliminate RC Rate and Expo

Use instead:

Pitch:  Rate / Expo / Curve
Roll:    Rate / Expo / Curve
Yaw:   Rate / Expo / Curve

**Comment by anthonycake** [comment]
Another vote here for adding Expo on Yaw.
The 'expert tunes' in the Vortex (or any other product for that matter) should ideally require no expos to be set on the radio, so that loading a 'tune' gets you exactly what the pilot intended. 
We can set expos for everything but the Yaw (unless I am missing something).

**Comment by hydra** [comment]
Yaw Expo has been added, please test current master branch (1.9.x)

**Comment by hydra** [comment]
With reference to #489.

I think we need to tackle this one at a time.

I think the best solution is to close this issue and #489, get people to re-test 1.9.x and then create new issues that
a) reference this comment
b) describe what you want
c) don't ask for more than one thing
