### ISSUE TITLE
Buying SP Racing F3 Deluxe

### ISSUE THREAD

**Issue by gaelj** [cleanflight/cleanflight#2115]
@hydra, I would like to support and get an excellent FC, so I'm looking into buying the SP F3 deluxe.
The only place I can find it available is hobbyking international warehouse, therefore China, at 27€50.
It seems really cheap. Photos look genuine (CF logo is present, but is that worth anything ?)
Could you please confirm these are indeed genuine ? And if not, any idea as to where I can get hold of one ? All suppliers in EUR seem to be out of stock.

**Comment by hydra** [comment]
hobbyking ones are fake.  they do have the MINI though, not fake.  you've reminded me to kick their ass again, thanks.

btw, this is not the place for such discussion.  github is reserved for software development discussion.  rcgroups, twitter or facebook is better.

https://twitter.com/SPRacingFCs

https://www.facebook.com/SPRacingFCs/

The ACRO/DELUXE is currently out of stock, the current focus is on the EVO and MINI right now.
