### ISSUE TITLE
Swapped values in the graphs under sensors

### ISSUE THREAD

**Issue by LeonFedotov** [cleanflight/cleanflight#2119]
On naze rev6, something strange iv'e noticed in cleanflight for the sensors tab the gyro and acc graphs are swapped meaning the acc graph shows gyro values and the gyro graph shows acc values.

**Comment by SteveAmor** [comment]
@LeonFedotov could you raise this issue under the Configurator and close this one. Thanks.

**Comment by LeonFedotov** [comment]
@SteveAmor oh sorry 😿
