### ISSUE TITLE
Autoland

### ISSUE THREAD

**Issue by CradyCopter** [cleanflight/cleanflight#212]
An autoland feature similar to Arducopter's 'Land Mode' (also in latest rel. of Multiwii?) would be awesome -- especially for those people who have sonar installed.
I have an APM 2.6 on my larger multi and use the Land Mode whenever it gets too windy for me to set it down gracefully.

http://copter.ardupilot.com/wiki/land-mode/

**Comment by hydra** [comment]
Duplicate of #234
