### ISSUE TITLE
For discussion - filters are not consistently named in the CLI

### ISSUE THREAD

**Issue by martinbudden** [cleanflight/cleanflight#2127]
Cleanflight has a number of filters and they are not consistently named in the CLI. Currently we have (at least):
`gyro_lpf`
`gyro_soft_lpf`
`dterm_cut_hz`
`servo_lowpass_freq`
`servo_lowpass_enable`
`acc_cut_hz`
`accz_lpf_cutoff`
`baro_noise_lpf`

They should be consistently named. Personally I favour just using lpf, e.g.:
`gyro_lpf`
`gyro_soft_lpf`
`dterm_lpf`
`servo_lpf`
`servo_lpf_enable` (actually, probably ditch this, use convention lpf is disabled if zero)
`acc_lpf`
`accz_lpf`
`baro_lpf`
but I don't really mind what convention we decide on as long as it is consistent.

**Comment by blckmn** [comment]
@martinbudden I second your suggestion above.
