### ISSUE TITLE
Damped light and naze32 rev6

### ISSUE THREAD

**Issue by WoooSaaaW** [cleanflight/cleanflight#2129]
I recently upgraded from naze32 rev5 to a rev6 board and noticed an issue with damped light on the rev6 board that i never had with rev5. There is a glitch or rubbing when damped light is on. its audible, plus i can both feel the difference in how my quad flys as well as the fact that the motor run much warmer. I'm new to the hobby so i might be wrong but it seems like the rev6 board is constantly triggering damped light when the stick inputs aren't doing anything for it to actually be triggered (down throttle). When damped light is off (set to low) it runs about the same.

Here is a video of the issue in flight: https://www.youtube.com/watch?v=DXchjJjFeMo

Here is another video with no props: https://www.youtube.com/watch?v=xDz9cJTVZAQ

**Comment by Arakon** [comment]
The v6 is much more prone to vibrations. It may simply be your d-term being overactive cause of that.
Damped light is done by the ESCs, it's not "triggered" by the FC at all.

**Comment by hydra** [comment]
closing, known issue, isolate fc from vibrations.  it's not specific to the naze32 rev6 either.  the lux also suffers from it.  it's a combination of fc sensor, esc settings, motors and frame.  in all reported cases i've seen isolating the FC using foam on the FC standoffs fixes the problem.  this has been true of my own quad builds here too.
