### ISSUE TITLE
naze32

### ISSUE THREAD

**Issue by vobbi** [cleanflight/cleanflight#2130]
configuration does not work in configurator 1.2.1
the motors tab causes crash too

**Comment by emski0** [comment]
yeh i confirm, configuration tab, does not work on v1.13.0-RC1 (stuck on waiting for data)

**Comment by jflyper** [comment]
Confirmed.
It only happens for configuration and motor tab.
Stuck on waiting for data, "Packet error" counts up.

**Comment by sreichholf** [comment]
You'll need configurator 1.2.2. Which is already available!

https://chrome.google.com/webstore/detail/cleanflight-configurator/enacoimjcgeinfnnnpajinjgmkahmfgb

**Comment by jflyper** [comment]
Cool. That did it.

**Comment by SteveAmor** [comment]
Hi @vobbi now this issue is fixed, can you please close. Thanks.
