### ISSUE TITLE
SPR F3 dlx clone Baro problem (cf1.13.0-rc1)

### ISSUE THREAD

**Issue by mrzed72** [cleanflight/cleanflight#2134]
I installed cf1.13.0-rc1 release.
Angle mode work correctly.
Enabled baro mode It holds the given altitude... I'm trying to change the altitude then it starts up at full throttle... baro mode disabled again operating normally.

**Comment by hydra** [comment]
no support for clones to be found here!  thanks for trying the release candidate though.
