### ISSUE TITLE
 Can't get pmm working on spracingf3 with fs-th9x

### ISSUE THREAD

**Issue by marcoberri** [cleanflight/cleanflight#2137]
On cleanfight plug-in i only see ,throrrle on  aux1 and ,aux2... can help me?

**Comment by SteveAmor** [comment]
Please see #2132 This is a support question. Please use spport forums like rcgroups as this is not a bug. Please close this issue.  Thanks.

**Comment by marcoberri** [comment]
Hello.


the problem is widespread and no one finds a solution . 

You can help us?

please!

http://www.rcgroups.com/forums/showthread.php?t=2479093
http://www.rcgroups.com/forums/showthread.php?t=2596297
http://www.rcgroups.com/forums/showthread.php?t=2607319

**Comment by hydra** [comment]
Please configure your FC correctly.
