### ISSUE TITLE
CC3D PPM no RX signal 

### ISSUE THREAD

**Issue by Wolus666** [cleanflight/cleanflight#2138]
HI Guys. I flashed today the CF 1.13 on my CC3D running 1.12 and result is no stick movement/no RX signal detected. Re-flashed back to 1.12 and everything working. Tried second time 1.13 and same issue so it is confirmed. The Blheli pass though is great so would like to use 1.13. Any fix to this issue yet?

**Comment by sreichholf** [comment]
Om the CC3D PPM has been moved from pin 3 to pin 8 in 1.13. That's probably your issue.

**Comment by Wolus666** [comment]
Oh great. Thanks. I din't see that in the docs.
