### ISSUE TITLE
spedix s250q drone 

### ISSUE THREAD

**Issue by finga7** [cleanflight/cleanflight#2145]
hello I just got this brand new drone spedix s250q and wen I go to take off it gets about 1/2" foot off the ground and starts a speed wobble and flips over dose anyone know how to fix this ? thanks

**Comment by SteveAmor** [comment]
Hi @finga7 please can you use support forums like RCGroups for such support.  Cleanflight issues are not for support but reporting bugs for developers to fix and requesting features.  Please can you close this issue.
