### ISSUE TITLE
motor twitching after 1.13 update, random gyro glitch on pitch axis

### ISSUE THREAD

**Issue by CreeT6** [cleanflight/cleanflight#2146]
dys xm20a, spracing f3, luxfloat, 1khz, 100hz lpf, motors randomly twitches
[blackbox_log_2016-05-17_165313.TXT](https://github.com/cleanflight/cleanflight/files/269411/blackbox_log_2016-05-17_165313.TXT)

![2016-05-17 17_19_46-cleanflight - blackbox explorer](https://cloud.githubusercontent.com/assets/14284294/15343668/98f5a95c-1c53-11e6-8821-df0951fc3b18.png)

**Comment by bmordan** [comment]
I am having the same issue.

| |P|I|D|
|:-- |:--:|:---:|:---:|
Roll|4.0|0.015|0|
Pitch|4.0|0.015|0|
Yaw|5.5|0.015|0|

![screenshot 2016-08-14 at 12 58 06](https://cloud.githubusercontent.com/assets/4499581/17648942/d903d7ec-621e-11e6-8b45-a675c4391b33.png)
