### ISSUE TITLE
Fake Travis Build files are not Cygwin-compatible

### ISSUE THREAD

**Issue by gaelj** [cleanflight/cleanflight#2152]
I have to change line endings from windows style to unix style in the configuration files, in order to be able to run the fake travis build in Cygwin.
I believe it could be fixed easily : 

> One way to fix this is to create .gitattributes file in repo's root and add lines like the following:
> `*.txt text eol=lf`

Thoughts ?

**Comment by hydra** [comment]
how about defining git attributes for just the affected `*.sh` files?  Seems a bit more sensible to me. PR please.
