### ISSUE TITLE
air mode not showing as active via MSP

### ISSUE THREAD

**Issue by divenet** [cleanflight/cleanflight#2156]
Is it my wrong doing somewhere in my settings or is there an issue with SPRACINGF3MINI air mode not lighting up green in Mode in v1.13.0-RC1?

My modes are all set to aux 2, they light up green when activated in all other modes but not air mode during my test.

Thanks for any feedback

**Comment by divenet** [comment]
@JamesHarrison,  shoud i close this issue if you have this in hand?

**Comment by martinbudden** [comment]
@divenet , don't close this yet - issues are closed when the fix gets merged in.

**Comment by divenet** [comment]
@martinbudden thanks, just let me know when its a good time to do so as i am a new user of github and still learning my way around and trying hard to become a valuable contributor.

Trying my best to help.  JL

**Comment by hydra** [comment]
fix in #2159 merged.
