### ISSUE TITLE
Motor buzzer 

### ISSUE THREAD

**Issue by flynet** [cleanflight/cleanflight#2172]
Hi, I know buzzer can do this, but I'm just curios is it posible to have mottor beepeng turned on via some switcher? I would like to have ability to turn on mottor beepeng like when battery plugs without having beeper on my board.

**Comment by flounderscore** [comment]
No, typically the FC just communicates the throttle % to the escs (unless in programming mode). Unless someone changes the BLHeli Firmware (e.g. Beep when throttle < 900ms, e.g.), it is not possible.

**Comment by flynet** [comment]
Thank you
