### ISSUE TITLE
flash cleanflight to cc3d

### ISSUE THREAD

**Issue by nitro20** [cleanflight/cleanflight#2180]
i can get the cleanflight firmware to flash onto the cc3d from libre pilot and then when i open CF and click connect it says "serial port failed to open". tried to flash latest firmware from CF and it pops up that read warning page..i can get it too go back to libre pilot. but i cant get it to connect to CF??

**Comment by lechak** [comment]
This is not issue. Please read the docs:
https://github.com/cleanflight/cleanflight/blob/master/docs/Board%20-%20CC3D.md
Section 'Flashing'.
And close issue here.

**Comment by stanleykuenzle** [comment]
Follow this instructions how to flash the Cleanflight to your CC3D. I've done it yesterday and it worked great.

[``](http://www.southquay3d.com/index.php?route=news/article&news_id=9)
