### ISSUE TITLE
Sonar support on SPR F3 EVO

### ISSUE THREAD

**Issue by gaelj** [cleanflight/cleanflight#2187]
Sonar is not supported on SPR F3 Evo.
Is it due to a hardware limitation ? Or a compromise ?
Or does it "only" require a development effort ?

**Comment by ledvinap** [comment]
@gaelj : It will be much easier to implement when #1984 (and rest of IO code) is merged..

**Comment by martinbudden** [comment]
@gaelj , you could try implementing it yourself. I think all you need to do is define the pins etc in the `target.h` file. Easiest thing is just to copy the values from SPRACINGF3MINI (check with the documentation that the pins etc haven't changed).

Let us know how you get on.

**Comment by kitchung** [comment]
I'm interested in this as well.
