### ISSUE TITLE
Cannot connect CC3D via USB-Port.

### ISSUE THREAD

**Issue by ReinhardSinger** [cleanflight/cleanflight#2189]
Connected FC via USB. Green LED is on, blue is flashing.
No Connection: auto / Manual / all baud rates -> nothing worked.
Installed STM USB VPC Driver: same !
Deinstallt STM Driver,  installed  CP210x -> same!

What do  I have to do to get the CC3D connected ?

**Comment by gibbyshane** [comment]
Sometimes flight battery must be plugged in than connect board......take off props
