### ISSUE TITLE
Move LED Strip on Sparky to PA0 or PA5

### ISSUE THREAD

**Issue by x0054** [cleanflight/cleanflight#2197]
I am making a version of Sparky board, but with PA0 and PA5 also broken out as pads for a project I am working on, Tanky Drone. How difficult would it be to move LED strip output on Sparky from current pin, PA6, to PA5 or PA0? Sorry to post here, not sure where else to ask.

**Comment by SteveAmor** [comment]
You'll possibly get a quicker response on IRC #cleanflight

**Comment by x0054** [comment]
I figured it out by moving LED Strip to PB8, the pin used for the CAN port that no one uses anyway. Works perfect. I'll merge and submit pull request later on this week.
