### ISSUE TITLE
Support CJMCU board

### ISSUE THREAD

**Issue by hydra** [cleanflight/cleanflight#22]
Support new CJMCU micro quad target.

Boards can be purchased from here:

http://www.goodluckbuy.com/micro-quadcopter-flight-driver-controller-9dof-9-axis-altitude-sensor-stm32f103.html

![schematic](https://cloud.githubusercontent.com/assets/57075/3529343/94b146f2-0798-11e4-85c6-0ecbc33ce7c6.PNG)

![1](https://cloud.githubusercontent.com/assets/57075/3529297/513aa076-0798-11e4-87dc-4c8d40f10aff.jpg)
![2](https://cloud.githubusercontent.com/assets/57075/3529298/513bc7bc-0798-11e4-8e72-9e3b154d60c5.jpg)
![3](https://cloud.githubusercontent.com/assets/57075/3529299/513d3f48-0798-11e4-8794-e6fc609a50cb.jpg)
![4](https://cloud.githubusercontent.com/assets/57075/3529301/51400c96-0798-11e4-9fb2-0db85896178d.jpg)
![5](https://cloud.githubusercontent.com/assets/57075/3529300/513e5efa-0798-11e4-8997-b4fb99181b96.jpg)
![6](https://cloud.githubusercontent.com/assets/57075/3529302/51414c28-0798-11e4-9124-8fc7ee292d4e.jpg)
![7](https://cloud.githubusercontent.com/assets/57075/3529303/514d2d7c-0798-11e4-8660-26752fe6462e.jpg)

Led1: Pin2 PC13
Led2: Pin3 PC14
Led3: Pin4 PC15
Motor1 Pin45 PB8 TIM4_CH3
Motor2 Pin46 PB9 TIM4_CH4
Motor3 Pin18 PB0 TIM3_CH3
Motor4 Pin19 PB1 TIM3_CH4
TX1 Pin30 PA9 USART1_TX
RX1 Pin31 PA10 USART1_RX
SCL Pin42 PB6 I2C1_SCL using external pullup
SDA Pin43 PB7 I2C1_SDA using external pullup

Discussion and source - http://www.multiwii.com/forum/viewtopic.php?p=53157#p53157

**Comment by yuan0226** [comment]
You then can compile for Crazepony of cleanflight it?
