### ISSUE TITLE
Diatone Naze32 Rev 6 Mode Saving Issues

### ISSUE THREAD

**Issue by screamingtiger** [cleanflight/cleanflight#2200]
I have two of these with the same issue.  I set the mode so I can have ARM on a switch (AUX 1).  I hit save and sometimes it saves sometimes it does not.  

Once it saves, later it will revert back to missing randomly.

PIDS and configuration saves ok just the "mode" screen does not.

Anyone else ever experienced this?

**Comment by gaelj** [comment]
What versions of Cleanflight and Cleanflight configurator are you running ?

**Comment by SteveAmor** [comment]
@screamingtiger did you resolve this?  If so, please close this issue. If not, please provide above information.
