### ISSUE TITLE
mode_color CLI command is not recognized

### ISSUE THREAD

**Issue by rigo3t** [cleanflight/cleanflight#2205]
Hi there, 

I have been trying to change the LED color for different modes, for armed and for disarmed. According to the instruction PDF the way to do this is using the command mode_color and 3 arguments. When I insert this "mode_color 6 0 4" I get this: 

# mode_color 6 0 4
Unknown command, try 'help'

Is there something else I should do? I have the LED strip enabled, everything else is working.

**Comment by rigo3t** [comment]
Sorry, I realize I probably should have stated what I'm using. This is on a Afroflight Naze 32 Rev 6. I'm using an addressable LED panel with 6 LEDs. 

Here are examples: According to the manual, if I just type mode_color it should list the modes and their corresponding colors.

![image](https://cloud.githubusercontent.com/assets/5488393/15769324/aedefc3c-298c-11e6-80bb-8c42045de143.png)

set mode_color gives me an "Invalid name"

![image](https://cloud.githubusercontent.com/assets/5488393/15769341/d4cfcc14-298c-11e6-9b3d-c3b124da9934.png)

**Comment by gaelj** [comment]
Hi, it's a new feature. Try the unstable release 1.13 RC2.

**Comment by rigo3t** [comment]
Ohh! I didn't realize that, my bad. Thanks for the headsup. Quick question... In terms of flight characteristics, how stable is this release? I have a brand new build and I want to be able to fly it this weekend without major issues. Any thoughts?

**Comment by gaelj** [comment]
1.13 RC2 flies good for me, better than 1.12 in my opinion. Lots of bug fixes & some new features as well (check the release notes & git diff). The bugs reported in RC1 have been fixed.
So I don't think you are taking a big risk using RC2.
Additionally, if you do find any bug, report it and you will have contributed in making 1.13.0 even better.

**Comment by rigo3t** [comment]
Fair enough, I'll give it a spin. Thanks Gael!

**Comment by gaelj** [comment]
Can you close the issue please ?

**Comment by rigo3t** [comment]
Absolutely. Thanks!
