### ISSUE TITLE
LED - LED Strip doesn't work when emf_avoidance=1

### ISSUE THREAD

**Issue by HFMan** [cleanflight/cleanflight#221]
Was testing the led strip functionality, and all I got was random barely blinking LEDs.  I went back to defaults, and it started working.  Tracked it down to having emf_avoidance=1.  Understandably a timing issue, but this is a deal breaker for me.

**Comment by hydra** [comment]
@HFMan Can you confirm if this is still an issue?  Perhaps you just needed an in-line diode?

**Comment by hydra** [comment]
With reference to 'new information' in https://github.com/cleanflight/cleanflight/issues/221#issuecomment-67181645 see http://wp.josh.com/2014/05/13/ws2812-neopixels-are-not-so-finicky-once-you-get-to-know-them/

**Comment by hydra** [comment]
Additionally the USB VCP doesn't work when the system clock is increased due to incorrect USB clock initialisation.
