### ISSUE TITLE
Revolution

### ISSUE THREAD

**Issue by Tomcatt** [cleanflight/cleanflight#2212]
Hello.  I'm running the REVO board and would like to know will you guys support it along with the OPLM GCS card?

Thanks.

**Comment by proggod** [comment]
You want to use raceflight for your revo board, https://github.com/rs2k/raceflight

**Comment by hydra** [comment]
please search before asking.

See #46

**Comment by Tomcatt** [comment]
Huh, Beta and CleanFlight has some things race do not  plus I just want to play around with all different types of software. I like watching the development- some really good stuff.

Race has held me over for now.  Thought there was no harm in asking.
