### ISSUE TITLE
Betaflight mergebacks

### ISSUE THREAD

**Issue by martinbudden** [cleanflight/cleanflight#2213]
Merge selected betaflight improvements into cleanflight

- [x] Use PT1 filters rather than biQuad filters for PIDs. Improve filter defaults.
- [x] Move RC lookup out of `mw.c` into `rc_curves.c`
- [ ] Support calculation of PID delta from measurement and error
- [ ] Use calculation rather than lookup for RC curves
- [ ] Add super expo feature
- [ ] Improved anti-windup protection

**Comment by martinbudden** [comment]
@borisbstyle , @hydra has asked me to look into betaflight "pilot feel" improvements with a view to merging them back into Cleanflight. I've listed the main ones I'm aware of above - are there any others you think should be merged into Cleanflight.

My plan is to submit a series of PRs (rather than one big PR) to get these merged back in.

**Comment by borisbstyle** [comment]
Cool @martinbudden. I told that to dominic. I dont have much time to merge back a lot as I still hope to make some progress.
I will help you out.

Dont merge dynamic P yet. I am not yet happy with it in some scenarios.

**Comment by martinbudden** [comment]
@borisbstyle thanks.

**Comment by lkaino** [comment]
I would add VCP blheli passthrough to the list.

**Comment by ledvinap** [comment]
@lkaino BLHeli 4-way is supported in CF ...

**Comment by lkaino** [comment]
Ah, sorry for my ignorance. Couldn't connect 4-way with the VCP passthrough. All good then :).

**Comment by hydra** [comment]
unrelated comments deleted.

**Comment by martinbudden** [comment]
Dynaminc P removed from todo list.

**Comment by hydra** [comment]
@martinbudden thanks for the PRs.

I've been having a nightmare time the last couple of weeks, my schedule is clearing up now so I can get back to coding, finally!  Thanks for your patience, sorry things have been moving a little slowly.

I will merge the OSD code in, after which I will continue to work on the OSD code and I'm quite happy for you to continue working on and merging the betaflight mergebacks when they are ready as they are important for the 1.14 release.

**Comment by martinbudden** [comment]
No worries. Good to hear that you've got everything sorted and are back to coding.

In the meantime I've been working on the new build system in betaflight - that's pretty well done now. Something to merge back into Cleanflight at some time in the future.

**Comment by hydra** [comment]
yes i saw some comments regarding it but have not looked at it.  could you create an issue for that with a couple of links to some betaflight commits so we can track it.

**Comment by hydra** [comment]
@martinbudden Any chance you can look at porting the more stable betaflight changes back in now that things have had a chance to settle?  Also should we create a ticket for the build system changes?

**Comment by martinbudden** [comment]
@hydra , for quite a while now I've been focusing on some quite low-level stuff: changing the 'make' system in betaflight and then iNav and then converting iNav to the new IO. So I've lost sight a bit about what has been happening in the higher layers - PIDs and RC control. I think there have been some quite radical changes to both these things, but I'm not sure about the detail of those changes.

So I'm happy to help do this in the next release, but it will take be a bit of time to get back up to speed in those areas. One other thing is you need to decide what approach you want to take: take the betaflight changes wholesale (eg replace pidluxfloat with the betalfight PID), or just port over some of the changes.

There have also been quite a few changes to the ESC handling, ie oneshot,multishot etc, but again I haven't really followed those changes in detail.

There's also the F4 port, but that comes almost "for free" once all the new IO changes have been completed.

And yes, there should certainly be a ticket for the build system changes.

One thing I'd like to see is some reconvergence of the the betaflight, iNav and Cleanflight code bases. I see no reason, for example, why the `drivers`, `io` `rx` , `sensors` and `telemetry` directories should not be identical for all three forks (of course for this to happen Cleanflight needs to adopt the new IO and betaflight and iNav need to adopt parameter groups - but both those changes are on the roadmap). Indeed I can see a future where the changes are concentrated in the `fc` `flight` and `target` directories.

This convergence would reduce everyone's workload in the common areas, and so allow faster innovation by each fork in its area of speciality.

@borisbstyle , @digitalentity do you have any views on convergence?

**Comment by hydra** [comment]
@martinbudden yes, we need convergence.  And I totally agree regarding the drivers/telemetry/rx/etc.  Perhaps the key to this is better modularisation to allow re-use of modules in other forks as required.

Dare I say it but perhaps repos for the modules are required?  I'm very wary of the overhead that might be introduced doing that but I feel the overhead would be LESS than the current overhead of continual merging and PR/code rot that we have in the 3 projects right now.

**Comment by martinbudden** [comment]
I've also been thinking of a separate repo for the common parts. I think it is certainly feasible.

A prerequisite for this is that Cleanflight convert to the new IO. iNav has now done this and there is  (I estimate) >85% commonality between the drivers for iNav and betaflight.

There will probably always be some divergence, since betaflight experiments quite a bit in the driver area, but that can be accommodated.

**Comment by hydra** [comment]
yup, agreed.  we need the new IO stuff ASAP.

**Comment by hydra** [comment]
With regards to this issue, I will close it now. I want to get 1.14.0 out before some other changes are coming, i feel this issue is already out of date anyway.

**Comment by digitalentity** [comment]
@hydra please note that INAV is suffering from odd random glitches after IO has been merged. It's likely not related to the IO itself, but still, new IO might reveal long lurking bugs with stack and memory corruption - https://github.com/iNavFlight/inav/issues/431

**Comment by martinbudden** [comment]
Yes, this issue is out of date. We can discuss betaflight mergebacks again once 1.14 is out.
