### ISSUE TITLE
Motors spinning up when calibrating escs via cleanflight

### ISSUE THREAD

**Issue by jeffwhu** [cleanflight/cleanflight#2215]
New build ZMR with Diatone v2 pdb,Naze 32 10 dof flashed with latest version of cleanflight, x4rsb receiver, micro minim osd (removed to use msp on usb) rotorgeeks rg20 escs.
Question......
When trying to calibrate escs via cleanflight without battery plugged in, I slide the master tab fully up and two motors start spinning with only the usb connected to pc.
https://youtu.be/jGPJBmQJJjM
could somebody help me to find out what happening.
Ceers
Jeff

**Comment by Arakon** [comment]
If it's a naze rev. 6, that's the cause. Not related to cleanflight, but a hardware design issue.
https://hilo90mhz.com/naze-v6-reverse-voltage-feedback-issue-schottky-diode-fix/

**Comment by jeffwhu** [comment]
Thanks Arakon, fitted the diode and working perfect now.
