### ISSUE TITLE
How can I use Telemetry(only TX), Serial_RX(only RX) at UART3 same time?

### ISSUE THREAD

**Issue by enuke** [cleanflight/cleanflight#2216]
I used FrSky X4RSB that is support SmartPort and S.BUS with Spracing F3 deluxe FC.

SmartPort Telemety use only one TX and S.Bus use only one RX Channel.
It's working good set Telemtry at UART2 and Serial_RX(S.BUS) at UART3.

But It can't set up at Same Uart-Port(2 or 3) It's disappered.
Could I set up at same UART(UART3) Telemetry and Serial_RX?

**Comment by ledvinap** [comment]
SBus and SmartPort baudrates are different. This was disused in the past, see https://github.com/cleanflight/cleanflight/issues/782 ..
