### ISSUE TITLE
Immersion Vortex 285 Altitude and GPS Hold

### ISSUE THREAD

**Issue by sag007** [cleanflight/cleanflight#2238]
Hi,

I have purchased the Vortex 285 and whilst the unit is good to fly, it would be awesome if it had altitude hold using the onboard barometer and an adon board for GPS hold.

I couldnt justify having two copters, one for photography and another for racing and would like to be able to use the Vortex for evreything because when the legs are folded in it very compact. 

Is any one working on adding these feature to the Vortex series of copters?

sag...

**Comment by martinbudden** [comment]
You should look at iNav, the navigation-enabled fork of Cleanflight.

I'm not sure what flight controller is on the Vortex, so it might not be supported by iNav. However, support for more flight controllers is being added to iNav.

Eventually the navigation features in iNav will make it back into Cleanflight.

**Comment by martinbudden** [comment]
Closing, since no further response from originator.
