### ISSUE TITLE
GITHUB Query Failed

### ISSUE THREAD

**Issue by lucasyeung** [cleanflight/cleanflight#2240]
Received this msg today when I tried to flash my FC

GITHUB Query Failed: API rate limit exceeded form (MY IP) (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

not sure how to tackle this, appreciate any help available

**Comment by skaman82** [comment]
This is a github restriction. This happens if you load the firmware to often in a short time. It will work again 24h later. Nothing we can do about that. Please close this issue.
