### ISSUE TITLE
Not arming when telemetry enabled on softserial

### ISSUE THREAD

**Issue by daJuels** [cleanflight/cleanflight#2257]
When I enable telemetry on Sofserial then arming is not possible..
I tried with connecting X4R SmartPort to Tx, to Tx&Rx, w/o Tx&Rx.

Please let me know if you need further information..
# Cleanflight Log

Running - OS: Windows, Chrome: 49.0.2623.112, Configurator: 1.2.2
Serial port successfully opened with ID: 1
MultiWii API version received - 1.19.0
Flight controller info, identifier: CLFL, version: 1.13.0
Running firmware released on: Jun 6 2016 00:03:48
Board: AFNA, version: 2
# dump
## mixer

mixer QUADX
mmix reset
smix reset
## feature

feature -RX_PPM
feature -VBAT
feature -INFLIGHT_ACC_CAL
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -FAILSAFE
feature -SONAR
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DISPLAY
feature -ONESHOT125
feature -BLACKBOX
feature -CHANNEL_FORWARDING
feature -TRANSPONDER
feature RX_PPM
feature VBAT
feature SOFTSERIAL
feature FAILSAFE
feature TELEMETRY
feature ONESHOT125
## map

map AETR1234
## serial

serial 0 1 115200 57600 0 115200
serial 1 0 115200 57600 0 115200
serial 30 0 115200 57600 0 115200
serial 31 32 115200 57600 9600 115200
## led

led 0 15,15:ES:IA:0
led 1 15,8:E:WF:0
led 2 15,7:E:WF:0
led 3 15,0:NE:IA:0
led 4 8,0:N:F:0
led 5 7,0:N:F:0
led 6 0,0:NW:IA:0
led 7 0,7:W:WF:0
led 8 0,8:W:WF:0
led 9 0,15:SW:IA:0
led 10 7,15:S:WF:0
led 11 8,15:S:WF:0
led 12 7,7:U:WF:0
led 13 8,7:U:WF:0
led 14 7,8:D:WF:0
led 15 8,8:D:WF:0
led 16 8,9::R:3
led 17 9,10::R:3
led 18 10,11::R:3
led 19 10,12::R:3
led 20 9,13::R:3
led 21 8,14::R:3
led 22 7,14::R:3
led 23 6,13::R:3
led 24 5,12::R:3
led 25 5,11::R:3
led 26 6,10::R:3
led 27 7,9::R:3
led 28 0,0:::0
led 29 0,0:::0
led 30 0,0:::0
led 31 0,0:::0
## color

color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 0,0,0
color 15 0,0,0
## mode_color

mode_color 0 0 1
mode_color 0 1 11
mode_color 0 2 2
mode_color 0 3 13
mode_color 0 4 10
mode_color 0 5 3
mode_color 1 0 5
mode_color 1 1 11
mode_color 1 2 3
mode_color 1 3 13
mode_color 1 4 10
mode_color 1 5 3
mode_color 2 0 10
mode_color 2 1 11
mode_color 2 2 4
mode_color 2 3 13
mode_color 2 4 10
mode_color 2 5 3
mode_color 3 0 8
mode_color 3 1 11
mode_color 3 2 4
mode_color 3 3 13
mode_color 3 4 10
mode_color 3 5 3
mode_color 4 0 7
mode_color 4 1 11
mode_color 4 2 3
mode_color 4 3 13
mode_color 4 4 10
mode_color 4 5 3
mode_color 5 0 9
mode_color 5 1 11
mode_color 5 2 2
mode_color 5 3 13
mode_color 5 4 10
mode_color 5 5 3
mode_color 6 0 6
mode_color 6 1 10
mode_color 6 2 1
mode_color 6 3 0
mode_color 6 4 0
mode_color 6 5 2
mode_color 6 6 3
mode_color 6 7 6

set looptime = 4000
set emf_avoidance = OFF
set i2c_highspeed = ON
set gyro_sync = ON
set gyro_sync_denom = 1
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_scale = 30
set rssi_ppm_invert = OFF
set rc_smoothing = OFF
set rx_min_usec = 885
set rx_max_usec = 2120
set serialrx_provider = SPEK1024
set sbus_inversion = ON
set spektrum_sat_bind = 0
set input_filtering_mode = OFF
set min_throttle = 1150
set max_throttle = 1850
set min_command = 1000
set servo_center_pulse = 1500
set motor_pwm_rate = 400
set servo_pwm_rate = 50
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set retarded_arm = OFF
set disarm_kill_switch = ON
set auto_disarm_delay = 5
set max_arm_angle = 25
set small_angle = 25
set fixedwing_althold_dir = 1
set reboot_character = 82
set gps_provider = NMEA
set gps_sbas_mode = AUTO
set gps_auto_config = ON
set gps_auto_baud = OFF
set telemetry_switch = OFF
set telemetry_inversion = ON
set frsky_default_lattitude =  0.000
set frsky_default_longitude =  0.000
set frsky_coordinates_format = 0
set frsky_unit = IMPERIAL
set frsky_vfas_precision = 0
set hott_alarm_sound_interval = 5
set battery_capacity = 0
set vbat_scale = 110
set vbat_max_cell_voltage = 43
set vbat_min_cell_voltage = 33
set vbat_warning_cell_voltage = 35
set current_meter_scale = 400
set current_meter_offset = 0
set multiwii_current_meter_output = OFF
set current_meter_type = ADC
set align_gyro = DEFAULT
set align_acc = DEFAULT
set align_mag = DEFAULT
set align_board_roll = 0
set align_board_pitch = 0
set align_board_yaw = 90
set max_angle_inclination = 500
set gyro_lpf = 188HZ
set gyro_soft_lpf = 60
set moron_threshold = 32
set imu_dcm_kp = 2500
set imu_dcm_ki = 0
set pid_at_min_throttle = ON
set yaw_motor_direction = 1
set yaw_jump_prevention_limit = 200
set tri_unarmed_servo = ON
set servo_lowpass_freq =  400.000
set servo_lowpass_enable = OFF
set failsafe_delay = 10
set failsafe_off_delay = 200
set failsafe_throttle = 1000
set failsafe_kill_switch = OFF
set failsafe_throttle_low_delay = 100
set failsafe_procedure = 1
set acc_hardware = 0
set baro_hardware = 0
set mag_hardware = 0
set blackbox_rate_num = 1
set blackbox_rate_denom = 5
set blackbox_device = SERIAL
set magzero_x = -540
set magzero_y = 429
set magzero_z = 94
## rxfail

rxfail 0 a
rxfail 1 a
rxfail 2 a
rxfail 3 a
rxfail 4 h
rxfail 5 h
rxfail 6 h
rxfail 7 h
rxfail 8 h
rxfail 9 h
rxfail 10 h
rxfail 11 h
rxfail 12 h
rxfail 13 h
rxfail 14 h
rxfail 15 h
rxfail 16 h
rxfail 17 h
## profile

profile 0
## aux

aux 0 0 1 1700 2100
aux 1 2 0 900 1700
aux 2 3 0 900 1300
aux 3 4 0 900 1300
aux 4 27 3 900 1300
aux 5 0 0 900 900
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900
## adjrange

adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0
## rxrange

rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000
## servo

servo 0 1000 2000 1500 45 45 100 -1
servo 1 1000 2000 1500 45 45 100 -1
servo 2 1000 2000 1500 45 45 100 -1
servo 3 1000 2000 1500 45 45 100 -1
servo 4 1000 2000 1500 45 45 100 -1
servo 5 1000 2000 1500 45 45 100 -1
servo 6 1000 2000 1500 45 45 100 -1
servo 7 1000 2000 1500 45 45 100 -1

set gps_pos_p = 15
set gps_pos_i = 0
set gps_pos_d = 0
set gps_posr_p = 34
set gps_posr_i = 14
set gps_posr_d = 53
set gps_nav_p = 25
set gps_nav_i = 33
set gps_nav_d = 83
set gps_wp_radius = 200
set nav_controls_heading = ON
set nav_speed_min = 100
set nav_speed_max = 300
set nav_slew_rate = 30
set alt_hold_deadband = 40
set alt_hold_fast_change = ON
set deadband = 0
set yaw_deadband = 0
set yaw_control_direction = 1
set 3d_deadband_throttle = 50
set throttle_correction_value = 0
set throttle_correction_angle = 800
set default_rate_profile = 0
set gimbal_mode = NORMAL
set acc_cut_hz = 15
set accxy_deadband = 40
set accz_deadband = 40
set accz_lpf_cutoff =  5.000
set acc_unarmedcal = ON
set acc_trim_pitch = 0
set acc_trim_roll = 0
set baro_tab_size = 21
set baro_noise_lpf =  0.600
set baro_cf_vel =  0.985
set baro_cf_alt =  0.965
set mag_declination = 2400
set pid_controller = MWREWRITE
set p_pitch = 40
set i_pitch = 30
set d_pitch = 23
set p_roll = 40
set i_roll = 30
set d_roll = 23
set p_yaw = 85
set i_yaw = 45
set d_yaw = 0
set p_alt = 50
set i_alt = 0
set d_alt = 0
set p_level = 20
set i_level = 10
set d_level = 100
set p_vel = 120
set i_vel = 45
set d_vel = 1
set yaw_p_limit = 500
set dterm_cut_hz = 0
set gtune_loP_rll = 10
set gtune_loP_ptch = 10
set gtune_loP_yw = 10
set gtune_hiP_rll = 100
set gtune_hiP_ptch = 100
set gtune_hiP_yw = 100
set gtune_pwr = 0
set gtune_settle_time = 450
set gtune_average_cycles = 16
## rateprofile

rateprofile 0

set rc_rate = 90
set rc_expo = 65
set rc_yaw_expo = 0
set thr_mid = 50
set thr_expo = 0
set roll_rate = 0
set pitch_rate = 0
set yaw_rate = 0
set tpa_rate = 0
set tpa_breakpoint = 1500
# cleanflight_data_log

Not sure if this helps..

Arm switch is set to AUX2 (RC5)

timestamp,RC0,RC1,RC2,RC3,RC4,RC5,RC6,RC7,RC8,RC9,RC10,RC11,Debug0,Debug1,Debug2,Debug3
1466864902394,1500,1500,1500,885,1500,1675,1500,1500,1500,1500,1500,1500,992,-5,0,0
1466864902894,1500,1500,1500,885,1500,1675,1500,1500,1500,1500,1500,1500,1002,3,0,0
1466864903394,1500,1500,1500,885,1500,1675,1500,1500,1500,1500,1500,1500,994,-6,0,0
1466864903898,1500,1500,1500,885,1500,1675,1500,1500,1500,1500,1500,1500,999,1,0,0
1466864904394,1500,1500,1500,885,1500,1675,1500,1500,1500,1500,1500,1500,1001,4,0,0
1466864904894,1500,1500,1500,885,1500,1675,1500,1500,1500,1500,1500,1500,1009,11,0,0
1466864905394,1500,1500,1500,885,1500,1675,1500,1500,1500,1500,1500,1500,1000,1,0,0
1466864905894,1500,1500,1500,885,1500,1675,1500,1500,1500,1500,1500,1500,991,-6,0,0
1466864906394,1500,1500,1500,885,1500,1675,1500,1500,1500,1500,1500,1500,992,-7,0,0
1466864906894,1500,1500,1500,885,1500,1675,1500,1500,1500,1500,1500,1500,991,-6,0,0
1466864907394,1500,1500,1500,885,1500,1675,1500,1500,1500,1500,1500,1500,993,-7,0,0
1466864907894,1500,1500,1500,885,1500,1675,1500,1500,1500,1500,1500,1500,1000,3,0,0
1466864908394,1500,1500,1500,885,1500,1675,1500,1500,1500,1500,1500,1500,1007,9,0,0
1466864908894,1500,1500,1500,885,1500,1675,1500,1500,1500,1500,1500,1500,1050,51,0,0
1466864909394,1500,1500,1500,885,1500,1675,1500,1500,1500,1500,1500,1500,997,-2,0,0
1466864909894,1503,1499,1500,988,1996,1500,1995,1996,1500,1500,1500,1500,998,-1,0,0
1466864910398,1503,1500,1500,988,1995,1500,1996,1996,1500,1500,1500,1500,1004,6,0,0
1466864910894,1503,1500,1500,988,1995,1500,1996,1996,1500,1500,1500,1500,992,-5,0,0
1466864911394,1503,1499,1500,987,1996,1500,1996,1995,1500,1500,1500,1500,995,-2,0,0
1466864911894,1503,1500,1501,987,1996,1500,1996,1995,1500,1500,1500,1500,1001,4,0,0
1466864912394,1502,1500,1500,988,1996,1500,1995,1996,1500,1500,1500,1500,992,-5,0,0
1466864912894,1502,1500,1500,988,1996,1499,1996,1996,1500,1500,1500,1500,996,-1,0,0
1466864913394,1504,1499,1500,988,1995,1500,1996,1996,1500,1500,1500,1500,993,-4,0,0
1466864913894,1503,1499,1501,988,1996,1500,1995,1996,1500,1500,1500,1500,995,-3,0,0
1466864914394,1503,1500,1500,988,1995,1500,1995,1996,1500,1500,1500,1500,997,0,0,0
1466864914894,1503,1500,1500,988,1996,1500,1995,1996,1500,1500,1500,1500,1009,12,0,0
1466864915394,1502,1500,1500,988,1996,1499,1996,1996,1500,1500,1500,1500,993,-4,0,0
1466864915898,1503,1500,1500,988,1996,1004,1996,1996,1500,1500,1500,1500,990,-8,0,0
1466864916394,1503,1500,1501,987,1996,1004,1995,1995,1500,1500,1500,1500,995,-2,0,0
1466864916894,1502,1500,1501,988,1995,1996,1995,1996,1500,1500,1500,1500,994,-3,0,0
1466864917394,1502,1500,1500,988,1995,1996,1996,1996,1500,1500,1500,1500,994,-3,0,0
1466864917894,1503,1500,1500,988,1996,1996,1995,1996,1500,1500,1500,1500,999,2,0,0
1466864918394,1503,1500,1500,988,1995,1996,1996,1996,1500,1500,1500,1500,993,-4,0,0
1466864918894,1503,1500,1500,987,1996,1996,1996,1996,1500,1500,1500,1500,995,-2,0,0
1466864919394,1503,1500,1499,988,1996,1996,1996,1996,1500,1500,1500,1500,991,-6,0,0
1466864919894,1503,1499,1501,988,1996,1996,1995,1995,1500,1500,1500,1500,990,-7,0,0
1466864920394,1502,1500,1500,988,1996,1995,1995,1996,1500,1500,1500,1500,1003,6,0,0
1466864920898,1503,1500,1500,988,1995,1499,1996,1996,1500,1500,1500,1500,992,-5,0,0
1466864921394,1502,1500,1500,988,1995,1499,1996,1996,1500,1500,1500,1500,1002,4,0,0
1466864921894,1503,1499,1501,988,1995,1500,1996,1996,1500,1500,1500,1500,996,-1,0,0
1466864922394,1503,1499,1500,988,1996,1499,1996,1996,1500,1500,1500,1500,1003,6,0,0
1466864922894,1503,1500,1500,987,1996,1996,1996,1996,1500,1500,1500,1500,999,2,0,0
1466864923394,1503,1500,1500,987,1996,1996,1996,1996,1500,1500,1500,1500,996,-1,0,0
1466864923894,1503,1500,1500,987,1996,1996,1995,1996,1500,1500,1500,1500,993,-4,0,0
1466864924394,1503,1499,1500,988,1996,1996,1996,1996,1500,1500,1500,1500,995,-2,0,0
1466864924894,1503,1499,1500,987,1996,1996,1996,1995,1500,1500,1500,1500,1002,4,0,0
1466864925394,1503,1499,1500,988,1996,1499,1996,1996,1500,1500,1500,1500,995,-2,0,0
1466864925894,1503,1500,1501,988,1995,1499,1996,1996,1500,1500,1500,1500,1000,2,0,0
1466864926394,1503,1499,1500,988,1996,1500,1996,1996,1500,1500,1500,1500,995,-2,0,0
1466864926894,1503,1500,1500,988,1995,1499,1996,1996,1500,1500,1500,1500,994,-4,0,0
1466864927394,1503,1499,1500,988,1996,1500,1996,1996,1500,1500,1500,1500,1004,7,0,0
1466864927894,1503,1499,1500,988,1995,1499,1996,1996,1500,1500,1500,1500,998,0,0,0
1466864928394,1503,1499,1500,988,1995,1500,1996,1995,1500,1500,1500,1500,995,-2,0,0
1466864928894,1502,1500,1500,988,1996,1500,1996,1996,1500,1500,1500,1500,990,-7,0,0
1466864929394,1502,1499,1500,988,1996,1500,1995,1996,1500,1500,1500,1500,1000,3,0,0
1466864929894,1502,1499,1501,988,1996,1500,1995,1996,1500,1500,1500,1500,994,-3,0,0
1466864930394,1503,1500,1500,988,1995,1499,1996,1996,1500,1500,1500,1500,990,-8,0,0
1466864930894,1503,1499,1500,988,1996,1499,1996,1996,1500,1500,1500,1500,996,-1,0,0
1466864931394,1503,1500,1500,988,1995,1500,1996,1996,1500,1500,1500,1500,1002,5,0,0
1466864931894,1503,1499,1506,988,1995,1500,1995,1996,1500,1500,1500,1500,1000,3,0,0
1466864932394,1502,1499,1505,1053,1996,1500,1996,1996,1500,1500,1500,1500,997,0,0,0
1466864932894,1503,1499,1505,1052,1995,1500,1995,1995,1500,1500,1500,1500,994,-3,0,0
1466864933394,1503,1499,1505,1053,1996,1500,1996,1996,1500,1500,1500,1500,994,-3,0,0
1466864933894,1503,1499,1505,1053,1996,1996,1996,1996,1500,1500,1500,1500,1004,7,0,0
1466864934394,1503,1499,1505,1053,1996,1996,1996,1996,1500,1500,1500,1500,995,-2,0,0
1466864934894,1503,1500,1505,1052,1996,1995,1996,1996,1500,1500,1500,1500,993,-6,0,0
1466864935394,1503,1499,1505,1052,1995,1996,1996,1996,1500,1500,1500,1500,993,-5,0,0
1466864935894,1503,1500,1505,1052,1996,1500,1996,1996,1500,1500,1500,1500,1008,10,0,0
1466864936394,1503,1499,1651,2011,1996,1500,1996,1995,1500,1500,1500,1500,998,1,0,0
1466864936894,1453,1060,1579,988,1995,1500,1995,1996,1500,1500,1500,1500,990,-7,0,0
1466864937394,2011,1631,998,1883,1996,1500,1995,1996,1500,1500,1500,1500,992,-6,0,0
1466864937914,1065,993,2008,988,1996,1500,1995,1996,1500,1500,1500,1500,998,0,0,0
1466864938394,2006,1887,1385,2012,1996,1500,1995,1996,1500,1500,1500,1500,1003,6,0,0
1466864938894,1503,1498,1502,1086,1996,1500,1996,1996,1500,1500,1500,1500,994,-3,0,0
1466864939394,1503,1498,1501,988,1996,1500,1996,1996,1500,1500,1500,1500,1002,5,0,0
1466864939894,1503,1498,1501,988,1996,1500,1995,1996,1500,1500,1500,1500,999,2,0,0
1466864940394,1503,1499,1501,988,1995,1500,1995,1996,1500,1500,1500,1500,1003,5,0,0
1466864940894,1503,1498,1501,988,1996,1500,1995,1996,1500,1500,1500,1500,995,-2,0,0
1466864941394,1503,1498,1501,988,1996,1500,1996,1996,1500,1500,1500,1500,994,-3,0,0

**Comment by Ede2016** [comment]
I can confirm this problem.
FC: AfroMini (MiniNaze32)
When I used CleanFlight 12.x I could use Telemetry on SoftSerial with SBus and arming worked in the way it should work.
When I try to do the same with CleanFlight 13.0 I can't arm my quad.
I did some more troubleshooting:
a) If I disable Telemetry arming works, SoftSerial is enabled with SBus but because Telemetry is off it is not really used
b) Disabling SoftSerial  does not make a difference. Just Telemetry ON, even if SoftSerial is OFF makes it impossible to arm
c) Arming with stick commands or with switch does not make a difference
d) Changing the loop time (I tried 1000 up to 4000) does not make a difference
e) Telemetry with SoftSerial works, I see all the values in my Taranis, I just can't arm the quad
f) Looking at the Modes Section in CleanFlight Configurator: I set a range for AUX2 to arm the quad. I can see in CleanFlight Configurator in the Modes section that the received signal is in the correct range but the ARM stays grey. If I switch off telemetry ARM is green when I use the correct switch position.
g) I tried other things to check exactly when the problem happens. Arming is not possible with Telemetry switched on. Nothing else makes a difference.

**Comment by andre92** [comment]
Try cli commands 'tasks' and 'status' with said features enabled.
Maybe your cpu load is too high to arm.
It is a safety feature that should prevent bad things to happen in the air.
If your cpu load is too high, set gyro_sync_denom to 2, that will set looptime to 2000 and will fix cpu load

**Comment by Ede2016** [comment]
@andre92 thanks for your info.
First: I set gyro_sync_denom = 2 and now it works.

I read about gyro_sync but somehow I did not realize that this automatically disables the looptime. In the Configurator it is still possible to set the looptime - the field is not disabled. I guess this is what confused me. I tried the 4000 just as a sample to have a very high value to verify if this makes a difference. But being disabled it obviously does not make a difference ;)

I had a look at the commands status and task list and I am a little confused. The task list shows me that baro uses about 36% and telemetry uses about 1%. With default gyro_sync_denom = 1 I disabled the baro and it does not show in the task list anymore but I still can't arm the quad. But if I disable telemetry which uses only 1% then I can arm it. Strange!

Last question: I tried to use the CLI commands status and tasks after I successfully armed the quad but it did not work. Is this normal? Is there any way to see the status and task list of the armed quad?

**Comment by andre92** [comment]
Correct, telemetry itself uses only 1%. I believe that Softserial is responsible for a lot of cpu load since it uses so many interrupts, especially at high baud rates.
As for the baro, do you have a BMP280? Even though it shows a high percentage in tasks, I do not notice a difference in system load when I disable it. 
You are correct at CLI, it doesn't work when armed, but all tasks (except MSP) keep running in the background, so the load should not differ between armed and disarmed.

**Comment by Ede2016** [comment]
Thanks @andre92 
Here is the info from my status and tasks:
This is with SoftSerial and Telemetry enabled, can't arm the quad (I understand why)

```
# status
System Uptime: 222 seconds, Voltage: 83 * 0.1V (2S battery - OK), System load: 1.87
CPU Clock=72MHz, GYRO=MPU6050, ACC=MPU6050.n, BARO=BMP280
Cycle Time: 991, I2C Errors: 0, registry size: 46

# tasks
Task list          max/us  avg/us rate/hz maxload avgload     total/ms
 0 -       SYSTEM      10       0       9    0.5%    0.5%        11
 1 -     GYRO/PID     934     732     897   84.2%   66.1%    169502
 2 -        ACCEL     178     144     450    8.5%    6.9%     17203
 3 -       SERIAL   44951       2      84  378.0%    0.5%       458
 4 -       BEEPER      15       0      62    0.5%    0.5%        31
 5 -      BATTERY   40099       1      43  172.9%    0.5%       147
 6 -           RX     281     171     111    3.6%    2.3%      4637
 9 -         BARO     143      75    4901   70.5%   37.2%      1061
11 -     ALTITUDE     350     177      38    1.8%    1.1%      1006
13 -    TELEMETRY      53       4     208    1.6%    0.5%       405
```

And here are the details after I set gyro_sync_denom = 2
```
# status
System Uptime: 18 seconds, Voltage: 81 * 0.1V (2S battery - OK), System load: 0.15
CPU Clock=72MHz, GYRO=MPU6050, ACC=MPU6050.n, BARO=BMP280
Cycle Time: 2005, I2C Errors: 0, registry size: 46

# tasks
Task list          max/us  avg/us rate/hz maxload avgload     total/ms
 0 -       SYSTEM      11       0       9    0.5%    0.5%         1
 1 -     GYRO/PID     899     726     499   45.3%   36.7%      7374
 2 -        ACCEL     181     144     847   15.8%   12.6%      1981
 3 -       SERIAL     754       2      99    7.9%    0.5%        85
 4 -       BEEPER      13       0      99    0.6%    0.5%         3
 5 -      BATTERY   40089       1      49  196.9%    0.5%        49
 6 -           RX     227     167     109    2.9%    2.3%       369
 9 -         BARO     151      75    6802  103.2%   51.5%       143
11 -     ALTITUDE     358     180      38    1.8%    1.1%       156
13 -    TELEMETRY      35       4     229    1.3%    0.5%        62
```
I am surprised about the day and night difference in the system load (1.87 vs 0.15) and I am surprised about the high values for baro.
This is now just a theoretical discussion. I am happy if someone explains these things to me and anybody else who reads this. But the original problem is found and solved already.

**Comment by ledvinap** [comment]
The statistics for baro are incorrect- BMP280 does not use separate temperature measurement, so ut_delay = 0 (https://github.com/cleanflight/cleanflight/blob/058eb5c6f938fc6707a1814e75c5f91d098ee50d/src/main/drivers/barometer_bmp280.c#L123).
Baro UT is scheduled after 100us (sanity limit in scheduler), UP is scheduled after tens of ms (measurement interval).
This is confusing scheduler statistics .

**Comment by andre92** [comment]
One thing I notice here is the total task load is about 100% when using BMP280. Maybe when the scheduler has nothing to do it will just check the baro. That is possible since the BMP280 collects all data at once instead of seperate intervals for temperature and pressure. Maybe one interval is not set or zero.

It looks like he BMP280 on the naze rev6 runs as fast as possible, taking the remaining scheduler time. I just tested the BMP085 (on the same board as my external compass) and it did 166Hz with summed avgload of 57.1% and system load of 0.23. 
On my naze full with MS5611 and same settings the baro runs at 99Hz, with summed avgload of 51.9% and system load of 0.27

**Comment by Ede2016** [comment]
@ledvinap @andre92 
Would this "incorrect statistic" explain why telemetry and gyro_sync_denom = 1 worked just fine in CleanFlight 12.x but it does not allow me to arm in 13.0?
I have no experience if gyro_sync_denom = 2 is as good as gyro_sync_denom = 1 on my 120mm micro quad (with OneShot KISS ESCs). But it seems with 12.1 it worked and with 13.0 not anymore so I think if it would make sense to go back to 12.1?

**Comment by ledvinap** [comment]
@Ede2016 : Only the statistics is incorrect, baro code is working as designed. It is only misleading, baro has minor influence on system load (about 0.5%, 1.061s out of 222s uptime)

System load is average number of tasks waiting during scheduler call. When no task is selected, scheduler is called again immediately (adding 'zero tasks waiting' to average), so 'system load' decreases quickly.

Calculating 'system uptime' / 'total task time' is more reliable way to get actual system load / task cpu percentage.

I'am not sure about difference between 12.x and 13.0, even quite minor change can cause this. Can you try both versions and post task statistics?

**Comment by Ede2016** [comment]
@ledvinap 
> I'am not sure about difference between 12.x and 13.0, even quite minor change can cause this. Can you try both versions and post task statistics?

Thanks for the info. Probably I will try this with version 12 and 13 - but probably in a few days. I will publish the information here after I did this.

**Comment by Ede2016** [comment]
@ledvinap @andre92 

I changed back to 1.12.1 and here are the status and task details for my AfroMini (Mini Naze32):

All default after flashing 1.12.1
```
# status
System Uptime: 65 seconds, Voltage: 76 * 0.1V (2S battery - OK), System load: 0.15
CPU Clock=72MHz, GYRO=MPU6050, ACC=MPU6050.n, BARO=BMP280
Cycle Time: 1006, I2C Errors: 0, config size: 2072

# tasks
Task list:
0 - SYSTEM, max = 8 us, avg = 0 us, total = 4 ms
1 - GYRO/PID, max = 736 us, avg = 642 us, total = 45280 ms
2 - ACCEL, max = 125 us, avg = 93 us, total = 794 ms
3 - SERIAL, max = 635647 us, avg = 2 us, total = 684 ms
4 - BEEPER, max = 8 us, avg = 0 us, total = 12 ms
5 - BATTERY, max = 40079 us, avg = 1 us, total = 67 ms
6 - RX, max = 65 us, avg = 31 us, total = 186 ms
9 - BARO, max = 128 us, avg = 65 us, total = 480 ms
11 - ALTITUDE, max = 270 us, avg = 156 us, total = 441 ms
```
With SBus receiver and SPort Telemetry on SoftSerial:
```
# status
System Uptime: 61 seconds, Voltage: 76 * 0.1V (2S battery - OK), System load: 0.57
CPU Clock=72MHz, GYRO=MPU6050, ACC=MPU6050.n, BARO=BMP280
Cycle Time: 1020, I2C Errors: 0, config size: 2072

# tasks
Task list:
0 - SYSTEM, max = 15 us, avg = 0 us, total = 4 ms
1 - GYRO/PID, max = 929 us, avg = 726 us, total = 49503 ms
2 - ACCEL, max = 173 us, avg = 138 us, total = 828 ms
3 - SERIAL, max = 758 us, avg = 2 us, total = 407 ms
4 - BEEPER, max = 12 us, avg = 0 us, total = 12 ms
5 - BATTERY, max = 40081 us, avg = 1 us, total = 74 ms
6 - RX, max = 231 us, avg = 161 us, total = 1120 ms
9 - BARO, max = 145 us, avg = 75 us, total = 427 ms
11 - ALTITUDE, max = 342 us, avg = 180 us, total = 441 ms
13 - TELEMETRY, max = 50 us, avg = 3 us, total = 159 ms
```
Same after set gyro_sync_denom = 2
```
# status
System Uptime: 11 seconds, Voltage: 75 * 0.1V (2S battery - OK), System load: 0.05
CPU Clock=72MHz, GYRO=MPU6050, ACC=MPU6050.n, BARO=BMP280
Cycle Time: 1994, I2C Errors: 0, config size: 2072

# tasks
Task list:
0 - SYSTEM, max = 10 us, avg = 0 us, total = 1 ms
1 - GYRO/PID, max = 925 us, avg = 740 us, total = 5170 ms
2 - ACCEL, max = 166 us, avg = 134 us, total = 199 ms
3 - SERIAL, max = 736 us, avg = 2 us, total = 52 ms
4 - BEEPER, max = 10 us, avg = 0 us, total = 2 ms
5 - BATTERY, max = 40088 us, avg = 1 us, total = 46 ms
6 - RX, max = 255 us, avg = 187 us, total = 129 ms
9 - BARO, max = 145 us, avg = 75 us, total = 99 ms
11 - ALTITUDE, max = 360 us, avg = 183 us, total = 116 ms
13 - TELEMETRY, max = 32 us, avg = 1 us, total = 34 ms
```
Change back to gyro_sync_denom = 1, I noticed that system load varies a lot. Here are some lines which I created within 30s:
```
System Uptime: 7 seconds, Voltage: 75 * 0.1V (2S battery - OK), System load: 3.98
System Uptime: 20 seconds, Voltage: 75 * 0.1V (2S battery - OK), System load: 0.84
System Uptime: 24 seconds, Voltage: 75 * 0.1V (2S battery - OK), System load: 0.77
System Uptime: 25 seconds, Voltage: 76 * 0.1V (2S battery - OK), System load: 0.73
System Uptime: 26 seconds, Voltage: 75 * 0.1V (2S battery - OK), System load: 0.77
System Uptime: 27 seconds, Voltage: 75 * 0.1V (2S battery - OK), System load: 0.82
System Uptime: 28 seconds, Voltage: 75 * 0.1V (2S battery - OK), System load: 0.55
System Uptime: 29 seconds, Voltage: 76 * 0.1V (2S battery - OK), System load: 0.71
System Uptime: 30 seconds, Voltage: 75 * 0.1V (2S battery - OK), System load: 0.79

```
I will stay with CF 1.12.1 for the moment and look what the future will bring.
Here is some more info about the same issue with some more details:
http://www.rcgroups.com/forums/showthread.php?t=2678624
