### ISSUE TITLE
Sensors - ADC speed is too high

### ISSUE THREAD

**Issue by ledvinap** [cleanflight/cleanflight#226]
There is minor problem with ADC when using apm-power-module.

STM32F103 ADC has sampling capacitor of 8pF. This capacitor is charged to Vref/2 before each conversion and must be charged to input voltage during sampling.

This charging current is normally quite negligible, but is is causing undesirable offset with APM power module.

When only 2 channels are in use, ADC conversion frequency is about 27kHz and input capacitance can be seen as 9MOhm resitor to 1.65V. (My)  APM uses 100kOhm current-to-voltage conversion resistor, additional current from ADC causes 20mV offset when current measured by APM is zero. This translates to 0.4A error in calculated current. This theoretical result does match measurement.

This error is much larger than measurement noise and is hard to compensate (it is voltage dependent. It may be possible to compensate it if equivalent circuit is annalyzed). This error is also dependent on number of used ADC channels, complicating things further ...  

Decreasing measuring frequency to 1kHz does greatly decrease this error. Patch will follow soon ...

**Comment by hydra** [comment]
@ledvinap did you do a PR for this?  I would also like to see progress on ADC conversion triggered from systick to give better readings when using multiple ADC channels.
