### ISSUE TITLE
Issues with Flight Modes not being picked up

### ISSUE THREAD

**Issue by robthomson** [cleanflight/cleanflight#2262]
Had an issue on multiple different Quanum Illuminati controllers (naze32)

When running as a 'flying wing' mode; the controller seems to get confused and loose the ability to change flight modes.

The desktop app shows everything correctly - the flight controller just stays on one mode only.  Never changing to the settings indicated on the desktop app.

**Comment by AmiSMB** [comment]
To see what is happening whilst flying you may need to try using a black box recorder, but I am not sure if this data is logged. Also if you have a buzzer on the FC you should hear a beep when you alter flight modes which could help.
