### ISSUE TITLE
Possible motor output bug

### ISSUE THREAD

**Issue by Kalveo** [cleanflight/cleanflight#2269]
I am using the latest naze32 firmware on a quadcopter. After adding a sonar sensor to my config two motors did no longer arm (the ESCs only made a single beep instead of the normal initiation tune). Flipping the motors around showed there was no problem with motors or ESCs, it was only motors connected to output 1 and 2 that had a problem. I tried both the motorpanel and my transmitter while conducting the tests. Using my transmitter I could not get the board to arm at all, while the motorpanel seemed to spin the wrong motor, as the slider for motor one spun the motor connected to output 3.

I am fairly certain I did not change anything except adding the sonar between the board working normally and the described error, but I could have missed something.

Afraid that I might have a hardware issue I decided to try to eliminate that by reflashing and erasing the board. After the reflash all the motors worked normally again, which gives the conclusion that there might be some software error.

**Comment by andre92** [comment]
Maybe some feature shifted motor outputs internally, from 1234 to 3456 (servo_tilt is known to do that). If you can unplug your motors, moving them all 2 pins higher might solve the issue.
