### ISSUE TITLE
Buzzer beep

### ISSUE THREAD

**Issue by usab** [cleanflight/cleanflight#229]
Hi Hydra, I would like to submit a short feature request for your cleanflight firmware. At first, I would like to say that I am very satisfied with your software and I prefer it over baseflight. Thank you. :)

I am flying a warpquad230 with vbat set to 3.5v. Unfortunately, I sometimes can't hear the beeps from the voltage warning since these tiny buzzer aren't loud enough and the beeps are very short. One thing I would like to ask for, is to implement an option like "buzzer_fullbeep = 1" into CLI which does activate the buzzer unter vbat value and deactivate the buzzer when over vbat value. So, basically just changing the current "beep-----beep-----beep" to one long "beeeeeeeeeeeeeeeeeeeep" without interruption (or at least a short interruption every few seconds) and easily changable via CLI command. 

Please give me a short reply if this is possible or not. :) Thank you very much for your great work! Greetings from Germany

**Comment by usab** [comment]
Hi hydra,
Sorry for writing you again. ;-)

I would like to (still) ask for a little change in the buzzer code sound. Isn't it possible to just turn on the buzzer when 
actual_voltage < alarm_volt
and turn off when
actual_voltage > alarm_volt?

I don't think it requires a new or more complexity. I really only want to change the melody from:
"beep ___ beep ___ beep ___ beep ..."
to a constant:
"beeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee......eeeep".
(Seems to be easier or am I wrong?)

In my opinion, the beeps are to short and can't be heard sometimes (especially when you are flying with friends).

A louder buzzer isn't possbile since I am using it on a warpquad and have almost no space for extra parts. :)

A little cli-command like "vbat_constantbeep = 1" would be great. :+1:

**Comment by dkisselev** [comment]
@usab When 1.9 is released it will come with the new beeper code: #669. It'll be easy to implement the feature then, but someone would need to do the work and I don't think there's much demand for it right now..

The new beeper code will also change some of the sounds, so it might work better for you without any changes anyway. (ethomas mentions that the critical battery beep is now longer in that PR thread)

**Comment by thenickdude** [comment]
>A louder buzzer isn't possbile since I am using it on a warpquad and have almost no space for extra parts. :)

It wouldn't be extra parts though, you would remove the original buzzer and replace it with a louder one?
