### ISSUE TITLE
bug report: possible magnetometer bug

### ISSUE THREAD

**Issue by samerhay** [cleanflight/cleanflight#2290]
NAZE32 with 10DOF and GPS.
Magnetometer declination is -6.5.
everything was working fine.
I modified the arrangement of the receiver and the GPS inside the quadcopter, which forced me to rotate the flight controller 90 degrees. I compensated for that in the "configuration - board and sensor alignment". the configuration is working fine as  determined by looking at the virtual drone on my screen in the "setup" tab (what i mean, if you lift the nose, the right movement is detected and if you roll left, it roll left, and if yaw right, it yaws the right direction). But now comes the problem: my true north is pointing east. I recalibrated the magnetometer. it was still wrong. the only thing that fixed it, is when i deleted the magnetometer declination value, rebooted, put it back, and reboot again.

**Comment by hydra** [comment]
thanks for the bug report, we'll look at the potential fix.

**Comment by hydra** [comment]
fix merged, please test any development build from tomorrow.

Download one from here:

http://cleanflight.memoryleaks.org/builds/
