### ISSUE TITLE
Roll issues 

### ISSUE THREAD

**Issue by mateostyle** [cleanflight/cleanflight#2304]
When stick input is given to yaw, the quad yaws that direction but also rolls in opposite direction. 
Any info on Cleanflight settings is appreciated.

**Comment by andre92** [comment]
Do you have a video or blackbox log? And may I see your cli dump please? I'm not sure which flight mode you are using here. With self level disabled (default out of the box) this would be normal behaviour.

**Comment by hydra** [comment]
please use rcgroups.com for support
