### ISSUE TITLE
PWM Receiver AR610: channels 1-4 not working for vers>1.9 with sp f3

### ISSUE THREAD

**Issue by wzr1337** [cleanflight/cleanflight#2320]
I set up a brand new SP F3 (seriously pro) with my old AR610 spectrum receiver. The AUX channels work perfectly fine, while Aileron, Elevators, Throttle and Rudder won't work with software versions greater than 1.9 . 

If I downgrade to 1.9 the regular channels work perfectly fine. 

I assume there is an issue with the PWM signal processing in the software.

**Comment by SteveAmor** [comment]
This will most likely be the failsafe changes.  Please check your end points.

**Comment by hydra** [comment]
closing, please use rcgroups for support.
