### ISSUE TITLE
Flight - Alt Hold enchancement proposal

### ISSUE THREAD

**Issue by xRadx** [cleanflight/cleanflight#2325]
Hi,

I am not an expert, on the subject, however I just have a thought about the topic. Not sure how would it work, but I have just a thought:
maybe better performance of Alt Hold would be achieved by ACC readings for flight/THR adjustments and BARO readings only for ALT/height estimation?

Read the values of accZ (make for example a moving average of X samples) and keep the average of 0 by controlling the flight/THR.

Another point for ALT estimation based on the ACC readings:
while a copter is leaning in pitch/roll, accZ is not real ATL/height change. I believe this should be taken into aact (by tg/ctg of accZ value and pitch/roll angle).

**Comment by martinbudden** [comment]
[iNav](https://github.com/iNavFlight/inav) does a much better job of Alt Hold than Cleanflight. This code will eventually be ported to Cleanflight, so there is no real point in improving the Cleanflight Alt Hold code.
