### ISSUE TITLE
Add GUI support for changing the failsafe settings on dsm2/dsmx satellite receivers

### ISSUE THREAD

**Issue by NullVoxPopuli** [cleanflight/cleanflight#233]
Same reason as #164 (not having to use a main receiver). But also for lessening weight and size - the bind plug on satellite receivers is rather large, and it would be great to be able to just solder directly to the rx.

**Comment by hydra** [comment]
Closing, if you can provide details on what needs to happen then please re-open this.

This issue is not at all clear and because of it's lack of clarity will not ever be worked on.

e.g.  what can't you do that you want to do and how do you want it to work?

**Comment by NullVoxPopuli** [comment]
on the lemon rx, there are a couple failsafe settings,
 - maintain last signal on all channels, 
 - or send nothing to the FC (allowing the FC's failsafe to trigger).

Being able to change the failsafe mode on the satellite without the main receiver would be helpful.

how would it work?
I think all the lemonRX receivers have the same failsafe options, so maybe if there was a Receiver Failsafe area in the UI with a couple radio buttons for the different failsafe options?
