### ISSUE TITLE
PARIS Sirius AirHero 32 r2 BetaFlight - Suddenly not connecting to CleanFlight

### ISSUE THREAD

**Issue by PilotPatch** [cleanflight/cleanflight#2331]
Hi,
I have been working on this setup and calibration for two days, moved over to PPM from sBus and got the radio receiver working and calibrated. Motors 1 & 3 kept increasing with the application of >0% throttle. AIRMODE was disabled. Then suddenly the board wont connect to CF, nor will it recognise bootloader. After a period of time the blue light blinks rapidly... tried changing USB ports and restarting computer and CF application.
Any thoughts on why CF would suddenly stop recognising the board?

**Comment by hydra** [comment]
no.  sounds like corrupt flash or faulty hardware/cable/usb socket/etc.  try another fc/usb cable/computer/reflashing.

for further non-code related support please use rcgroups or irc.
