### ISSUE TITLE
(Done) Eclipse + GDB openOCD debuging fail : I can't access FC by SWD, but I can burn the hex file.

### ISSUE THREAD

**Issue by qwedsazxc78** [cleanflight/cleanflight#2333]
## Hi guys, I want to develop the our compass into SPRacingF3, but I meet below problem.

**problem:**
- Eclipse openOCD can't connect the flight control board by SWD correctly, the window message show 
- I can burn the hex file by SWD, STLINK utlity, and USB burnner, so I believe the HW is ok. all setting picture in goolge driver: https://goo.gl/awIz7E
- I think I have to configure something to let the OpenOCD can connect the stm32f303CC MCU. Therefore, I try to modify the reset_config option of OpenOCD cfg file as below

> 1. reset_config srst_nogate 
> 2. reset_config srst_only
> 3. reset_config srst_only srst_nogate
> 4. reset_config none

0 Setting stm32f4 + SPRacing F3
![0 stlink utility check ok](https://cloud.githubusercontent.com/assets/13078460/17208965/82bc100e-54ed-11e6-954e-3c022c2f30ce.png)
0 error msg
![0 error msg](https://cloud.githubusercontent.com/assets/13078460/17208964/82ba7320-54ed-11e6-8ef3-cfc75c537d0e.png)
0 STLINK utility check ok
![0 setting stm32f4 spracing f3](https://cloud.githubusercontent.com/assets/13078460/17208966/82bc5e74-54ed-11e6-8cfb-5abca78f63c2.jpeg)

GDB OpenOCD  setting 
![1 gdb openocd setting 1](https://cloud.githubusercontent.com/assets/13078460/17209021/b5e3915a-54ed-11e6-9e23-b2b7a2dddaf8.png)
![1 gdb openocd setting 2](https://cloud.githubusercontent.com/assets/13078460/17209024/b5ea1250-54ed-11e6-80db-7d8dc80c4aec.png)
![1 gdb openocd setting 3](https://cloud.githubusercontent.com/assets/13078460/17209023/b5e7b078-54ed-11e6-914c-c80775abd323.png)
![1 gdb openocd setting 4](https://cloud.githubusercontent.com/assets/13078460/17209022/b5e584a6-54ed-11e6-96b7-dc8b15b8c8bf.png)

gdb console
![2 gdb console](https://cloud.githubusercontent.com/assets/13078460/17209043/c6b782a2-54ed-11e6-9d93-47ddd72631d6.png)
gdb trace
![2 gdb trace](https://cloud.githubusercontent.com/assets/13078460/17209044/c6b8e44e-54ed-11e6-86e4-fd720606f05f.png)
openocd console
![2 openocd console](https://cloud.githubusercontent.com/assets/13078460/17209045/c6bf487a-54ed-11e6-9f5d-bc1002f1dd1a.png)

I try it about 2 week, so I need some nice boy help me fix it.
Also, all I follow this tutorial to configure my environment. 
https://github.com/CraigJPerry/cleanflight/blob/dev-docs/docs/development/Building%20in%20Eclipse.md#install-eclipse

**environment**

- win10
- eclipse-cpp-luna-SR2-win32-x86_64
- gcc-arm-none-eabi-4_9-2015q3-20150921-win32
- gnuarmeclipse-build-tools-win64-2.6-201507152002-setup
- gnuarmeclipse-openocd-win64-0.10.0-201601101000-dev-setup
- gnuarmeclipse-qemu-win64-2.4.50-201510290935-dev-setup
- STM32 ST-LINK Utility v3.9.0
- STM32F4 USB dongle + SPRacing F3 10DOF board

**Comment by qwedsazxc78** [comment]
hello guys,
I resolve this issue, and the solution is that I change the setting back to default, so I find the problem is from below two diagram.

The context of run and reset commend should be empty, and in the debugger setting, I use the stm32f3discovery setting. then, everything go back to perfect status. 
![image 001](https://cloud.githubusercontent.com/assets/13078460/17277603/98ba7bf0-5779-11e6-8309-2381eee50bf8.png)
![image 002](https://cloud.githubusercontent.com/assets/13078460/17277604/98c16546-5779-11e6-8f11-42c9ba6e3ffe.png)

**Comment by SteveAmor** [comment]
Good to hear you resolved the problem. Can you please close this issue.

**Comment by qwedsazxc78** [comment]
I try the below method and fix the problem. close issue
