### ISSUE TITLE
processRx calls mspSerialAllocatePorts repeatedly while un-armed.

### ISSUE THREAD

**Issue by jflyper** [cleanflight/cleanflight#2335]
Not a big deal, a little cycle waster.
`telemetryCheckState` should return a boolean value indicating if port usage was changed, and `mspSerialAllocatePorts` should be called based on this information.

[https://github.com/cleanflight/cleanflight/blob/master/src/main/fc/cleanflight_fc.c#L601-L612](https://github.com/cleanflight/cleanflight/blob/master/src/main/fc/cleanflight_fc.c#L601-L612)
```
#ifdef TELEMETRY
    if (feature(FEATURE_TELEMETRY)) {
        if ((!telemetryConfig()->telemetry_switch && ARMING_FLAG(ARMED))
            || (telemetryConfig()->telemetry_switch && rcModeIsActive(BOXTELEMETRY))) {
            releaseSharedTelemetryPorts();
        } else {
            // the telemetry state must be checked immediately so that shared serial ports are released.
            telemetryCheckState();
            mspSerialAllocatePorts();
        }
    }
#endif
```

**Comment by hydra** [comment]
@jflyper thanks, fixed!
