### ISSUE TITLE
Naze32 compass autodetection problem

### ISSUE THREAD

**Issue by xdigyx** [cleanflight/cleanflight#2336]
As in the post:
I have a Naze32 rev6 10DOF (with compass). Athough CF sees that it is present (an icon in Conf-tool) however it seems that it does not autodetect the correct hardware. setting hw type in CLI: "set mag_hardware = 2" helps.

FW 1.13

**Comment by hydra** [comment]
Can anyone else replicate this? I don't have a rev6 with a mag.

**Comment by hydra** [comment]
@xdigyx please can you find someone else that can confirm the issue you're having.  If we can't reproduce it or confirm it then it'll be hard for us to spend time on this issue.

**Comment by urlu75** [comment]
flashing CF 1.13 on Naze rev 6 with full chip erase.
# status
System Uptime: 9 seconds, Voltage: 0 * 0.1V (1S battery - NOT PRESENT), System load: 0.39
CPU Clock=72MHz, GYRO=MPU6500, ACC=MPU6500, BARO=MS5611, MAG=HMC5883
Cycle Time: 996, I2C Errors: 0, registry size: 46

# 
seems ok.

**Comment by xdigyx** [comment]
Please calibrate it and check if the directions are correct.

**Comment by Fossdal** [comment]
Cleanflight/NAZE 1.13.0 Jun  6 2016 / 00:03:48 (a77bc76)

System Uptime: 385 seconds, Voltage: 0 * 0.1V (3S battery - OK), System load: 0.06
CPU Clock=72MHz, GYRO=MPU6500, ACC=MPU6500, BARO=MS5611, MAG=HMC5883
Cycle Time: 1990, I2C Errors: 0, registry size: 46

The Orientation of the compass was 180 degrees wrong

**Comment by xdigyx** [comment]
try to change set mag_hardware = 2, recalibrate and check directions again

**Comment by Fossdal** [comment]
cli => set_ mag_hardware=2
configuration=> set mag aligment to default 
hit save and reboot
then mag orientation is right

try to recalibrate mag, orientation still ok

**Comment by Fossdal** [comment]
No no problem if do a calibration of mag
TEST done 

1.  flash 1.13 with full chip erase
2. connect and check orientation of mag
result 180 degree wrong

3 calibrate mag
result orientation ok

**Comment by urlu75** [comment]
flash 1.13 with full erase. After calibration, orientation is ok

**Comment by SteveAmor** [comment]
@urlu75 @Fossdal can you confirm if this issue has been resolved.

**Comment by urlu75** [comment]
mag detection and calibration ok. D'ont see any issue here with the test done.

**Comment by Fossdal** [comment]
mag detection an calibration ok. no problem

**Comment by guidojones** [comment]
I have 2 Rev 5 10DOF and both intermittently don't detect the compass. When they don't detect it, the calibrate function is not available. Both boards flashed 14.2 with full chip erase. Configurator 1.2.4 running under Win 10 64bit. Heading on setup screen shows active compass that moves with board/drone.

I tried:
set_ mag_hardware=2
save

that didn't make any difference

**Comment by guidojones** [comment]
Using status, when it isn't detected, the mag is missing from the status. When it's present, it shows: MAG=HMC5883

Even when it is missing, Heading starts at 0 and follows the movement of the drone.
