### ISSUE TITLE
would it be possible to add support for mavros?

### ISSUE THREAD

**Issue by MohmadAyman** [cleanflight/cleanflight#2337]
mavros is becoming more and more important with ros growing community, 
This is the answer i got from mavros devs about supporting clean flight, i wonder if it would be possible to add these features to the current mavlink?

```
In current state cleanflight support of mavlink is useless. They do not handle any message. You simply can't send any command to control drone.

To be usable they should support at least:
1. Settable system and maybe component ID. 0:200 - broadcast:200
2. Own AUTOPILOT_TYPE, not GENERIC - else you can't detect AP type
3. COMMAND_LONG and/or COMMAND_INT message handler. At least you should be able to ARM
4. Some types of setpoint messages. Else it useless for automatic control from mavros

Also good to implement parameter and mission protocols if possible.
```
Here is the link of their answer:
https://github.com/mavlink/mavros/issues/584

**Comment by martinbudden** [comment]
@MohmadAyman , development of the mavlink protocol is occurring in the iNav fork of Cleanflight. This work will eventually be merged back into Cleanflight.
