### ISSUE TITLE
3d_deadband_throttle gets incorrect value when saving RX config in GUI

### ISSUE THREAD

**Issue by andre92** [cleanflight/cleanflight#2347]
After changing Receiver settings in the GUI (things as RC deadband, expo, throttle expo), the 3d_deadband_throttle setting in CLI is 30212. With this setting, arm switch will immediately start motors when using 3d mode (should only start at mid stick)

**Comment by KiteAnton** [comment]
This seems very similar to the same issue in betaflight, it was fixed with [this PR](https://github.com/betaflight/betaflight/pull/929). And then [this PR ](https://github.com/betaflight/betaflight-configurator/pull/194)for the configurator.

**Comment by hydra** [comment]
Fixed in latest development configurator.  Please test and report any issues in configurator firmware.

3D Throttle Deadband setting moved to receiver page where it belongs.  3D ESC settings remain on configuration page and the '3D' title has been updated to '3D ESC' to clarify.
