### ISSUE TITLE
IO SP Racing F3 Evo

### ISSUE THREAD

**Issue by urlu75** [cleanflight/cleanflight#2354]
Hi,

Just got an official SP Racing F3 Evo flight controller and contribute to this great project.
I will use the board with : 
- OSD (UART1)
- GPS (UART2)
- SBUS RX (UART3)

but where to plug Smart Port telemetry ? What are the plan for SoftSerial with this board ?

thanks,
lulu

**Comment by andre92** [comment]
I have same issue with this board. If not all 8 motor outputs are on one timer, maybe some motor pins could be used for it? At least with quadcopters.

**Comment by gaelj** [comment]
Try this https://github.com/cleanflight/cleanflight/pull/2362

**Comment by hydra** [comment]
@urlu75 Please provide feedback on #2362 when you have tried it.

I will close this so we can keep discussion in on the PR.
