### ISSUE TITLE
modes doc needs clarification

### ISSUE THREAD

**Issue by Fossdal** [cleanflight/cleanflight#2356]
The modes documentation needs to clarify what acro mode is
no mode is called acro, but you find references to is on a lot of other documentation documents. and on the web

**Comment by rb1205** [comment]
I checked and in fact acro (or rate) mode is not covered anywhere in the modes documentation page. I made a pull request #2374 with a brief explanation of what it is and the differences with the auto-leveled modes.

**Comment by Fossdal** [comment]
Closing this as the modes doc now explains a little bit about manual/Acro
