### ISSUE TITLE
Where to place questions on custom boards?

### ISSUE THREAD

**Issue by edogaldo** [cleanflight/cleanflight#2365]
Hello, I'm trying to build a custom F1 board with hw I own.
Where should I place details questions to get support in building the board?
Is there a forum?

Thanks in advance and best, E.

**Comment by hydra** [comment]
There is not a forum, perhaps try the `#Cleanflight` IRC channel on FreeNet (see docs).

**Comment by edogaldo** [comment]
I tried the IRC channel but it's not very practical: you have to stay connected and hope the right people is connected as well.
Why not setting up a forum? I think it would be very useful..
