### ISSUE TITLE
 Failed to open serial port

### ISSUE THREAD

**Issue by DengkeDu** [cleanflight/cleanflight#2369]
I connect my board based on stm32f103 with ubuntu 16.04, and runing `dmesg` that show the board had connect to ttyUSB0, but on my cleanflight configurator, it show ` Failed to open serial port` , do I need the sudo? If so how can I let it work?

**Comment by roskoant** [comment]
You will need to add yourself to the dialout group and reboot.
usermod -a -G dialout MY_USER_NAME

**Comment by DengkeDu** [comment]
Great! Thank you very much!
