### ISSUE TITLE
Feature Request: Set Color of LED Strip based on Radio AUX Channel

### ISSUE THREAD

**Issue by Red13x3** [cleanflight/cleanflight#2377]
Synopsis: Link an AUX channel to a MODE that modifies the color of an attached programmable LED strip in at least 4 color stages: Red, Yellow, Green, Blue.

Requirement: One of the things that seems to be a real issue is identifying where the quads are on the track, so the race-caller can call who's passing who and to make it easier for spectators to see the quads rather than seeing black specks.

But as we all know, the VTX channel you are allocated in the early heats could well change. So, we need to be able to change the color of those LED strips to indicate what VTX channel we are on. Currently I think this can be done by connecting to CF... But not everyone carries a laptop to race-day.

Being able to change the colors from your radio, using either a rotating knob, or maybe a "digital lever" to step though the colors of a minimum: Red, Yellow, Green then Blue. (Feel free to implement more color stops if you get creative, like white, all off, and colors in-between the main 4.)

PS. Yes, the LaForge VTX have an optional LED module which I think is neat, but I don't like to use the remote they supply, as I bet I would lose it. Wish they would make it listen to an AUX channel instead.)

**Comment by hydra** [comment]
Good idea. Thanks.
