### ISSUE TITLE
IRCFUSIONF3 does not work with CF v1.13.0

### ISSUE THREAD

**Issue by dexX7** [cleanflight/cleanflight#2383]
When trying to connect a Vortex Pro, flashed with Cleanflight v1.13.0, via the CF configurator, then the connection times out and can't be established.

I assume it's the same issue as https://github.com/betaflight/betaflight/issues/1056, which was fixed via https://github.com/betaflight/betaflight/pull/1062.

**Comment by hydra** [comment]
@dexX7 thanks for the bug report.  I've added the config to CF now, please test v1.14.0-RC2 when the binaries are created.  If it doesn't work still please create a new issue.
