### ISSUE TITLE
Active suspension

### ISSUE THREAD

**Issue by inoxas78** [cleanflight/cleanflight#2384]
Hello all,

I plan to use CC3D or NAZE32 to do an active suspension on a crawler.
I'll only user Roll and pitch but i have to manage 4 servos (1 per suspension).
Someone can tell me how to set up this?
In my mind, this is the same problem as maintaining roll and pich for a quadcopter (drone) but in place of rotors, i have servos.
Any idea?

**Comment by jflyper** [comment]
I think there's different kind of physic involved, and it's much easier.

[https://www.youtube.com/watch?v=HaMM3opNrpY](url)
