### ISSUE TITLE
Please support external (GPS) mag on EVO

### ISSUE THREAD

**Issue by stronnag** [cleanflight/cleanflight#2392]
Currently the EVO target has
````
//#define USE_MAG_HMC5883 // External
````
Not withstanding that nav mode (PH, RTH) users may prefer iNav, this negates a selling point of the EVO (replaceable mag).  Please consider removing the comment characters.

Examples of good GPS / mag options include:

http://www.banggood.com/Ublox-NEO-M8N-Flight-Controller-GPS-with-Protective-Shell-for-PIX-PX4-Pixhawk-p-1005394.html and http://www.banggood.com/UBLOX-NEO-M8N-BN-880-Flight-Control-GPS-Module-Dual-Module-Compass-p-971082.html. Both work well with CF compatible flight controllers on EVO.

**Comment by kitchung** [comment]
I also have the same GPS and confirm it works fine on my SP Racing F3 Evo board running inav. So getting the compass working in CleanFlight would be a good thing.

**Comment by hydra** [comment]
done
