### ISSUE TITLE
motors 5 and 6 dont spin CC3D

### ISSUE THREAD

**Issue by kopterimies** [cleanflight/cleanflight#2397]
motors 5 and 6 dont spin CC3D and CC3D atom. why? and what can I do? both worked when they were open pilot software

**Comment by hydra** [comment]
this isn't enough information to help you.    the github issue tracker is for reporting confirmed bugs.  probably you have a configuration issue or other feature clash.  please post details of your configuration to a post on rcgroups.com and ask there for support.   if you confirm there is a bug then please report here.

**Comment by hydra** [comment]
please also refer to this:

https://github.com/cleanflight/cleanflight/blob/master/CONTRIBUTING.md
