### ISSUE TITLE
Add new LED mode

### ISSUE THREAD

**Issue by mixMugz** [cleanflight/cleanflight#2409]
Hi there.

If possible, please add new LED stripe mode. Calling something like "Flight Beacon"

Mode is based by led direction.

So, lets me explain:

four location NORTH/SOUTH/WEST/EAST
color for each led location can changed in configurator (default: N: white, S: yellow, E: red, W: blue)
one numeric option from '1' to '5' (or other not more '9'), named "BPS (blink per second)"
So. Logic for this mode (for test we have 4 led for each location with assigned mode, 1-N, 1-S, 1-E, 1-W)
Mode is looped for 4 second.

Led for NORTH and SOUTH alway ON (no blinks or something) just always on.

For first we are use BPS option and blink WEST led for one second (if BPS is equal 1 - then LED 1 sec just ON, if 2 or more - blink 2 or more time in one second), EAST led is off.
WEST and EAST led off for one second.
EAST led blink with same logic, like step 1. (WEST LED is OFF)
Same logic like step 2.
Goto 1.
So, If you liked the idea that is ready to answer your questions.

**Comment by Floyer007** [comment]
Do you mean there should be an implementation of "Navigation lights"?
And doesn't it blink a lot?

I prefer the international light-color:
https://en.wikipedia.org/wiki/Navigation_light
