### ISSUE TITLE
Naze32 Board wont connect to Cleanflight with error Failed to open serial port

### ISSUE THREAD

**Issue by nielas0608** [cleanflight/cleanflight#2410]
Hello,

I am new to drone's and i ran into this problem. Failed to open serial port. When i connect my drone with the computer and try to flash. I get this error message. I have tried things like hercules and stuff but nothing works.

Please help.
niels

**Comment by SteveAmor** [comment]
@nielas0608 sorry for your problems.  Can you please use forums like rcgroups for support.  Issues are to report bugs which developers need to fix or to request enhancements.  It would be appreciated if you closed this issue and ask for support on rcgroups.
