### ISSUE TITLE
Incorrect scheduling of BMP280 barometer

### ISSUE THREAD

**Issue by martinbudden** [cleanflight/cleanflight#2413]
Caused because driver reads temperature and pressure together, rather than on alternate calls like the other baros. This means `baro->ut_delay` is set to zero which causes a problem with the scheduling, see PR https://github.com/iNavFlight/inav/pull/612 for a possible fix.

**Comment by hydra** [comment]
cherry-picked dd2a122ae644ca6cfbac24cc3b1559f7a2a56f05

thanks
