### ISSUE TITLE
MAG is alway disabled after reset

### ISSUE THREAD

**Issue by jrtph** [cleanflight/cleanflight#242]
Hi Dominic, I just noticed that every time I power cycle my board the MAG is alway disabled. It will only goes to enable after I connect to CLI and exit, after soft reset the MAG will goes to enable. Is this normal? Or is there any setting that I need to set to keep my board MAG stay enabled?

**Comment by jrtph** [comment]
After installing the latest firmware (v1.4.0), MAG seams to be working fine now.

**Comment by LupinIII** [comment]
Whatever it was, the MAG is on immediately now (1.4.0). I also tried 1.3.0 and it was already working with it I found. For good measure I flashed 1.2.0 where the problem appeared again (just to make sure it was not some weird electrical glitch). 

Btw. is there any way to get a previous version of cleanflight configurator? Not that I really want to go back, but 0.59 can't connect to any firmware before 1.4.0. But if I hadn't tested in the order 1.2 then 1.3 then 1.2 then 1.4 with updating configurator (I'm always doing that manually), I couldn't even know if it already worked on 1.3.

**Comment by hydra** [comment]
yes, configurator releases are archived on the github releases page for the project.

please re-open this ticket if you get the problem again.  There were changes, iirc to support the mag on the sparky which may have also fixed this problem, i was never able to replicate it here.
