### ISSUE TITLE
io/motor_and_servo.* should be split

### ISSUE THREAD

**Issue by martinbudden** [cleanflight/cleanflight#2420]
There are `io/motor_and_servo.h` and `io/motor_and_servo.c` which should be split into `io/motor.*` and `io/servos.*`

Similarly for `motorAndServoConfig_t` which should be split into `motorConfig_t` and `servoConfig_t`.

**Comment by hydra** [comment]
agreed, seems like an easy PR to get into 1.14.0 if you fancy it?

**Comment by hydra** [comment]
I think it will also help with the 64K quad-only targets a little too.

**Comment by hydra** [comment]
done
