### ISSUE TITLE
Cleanflight doesn't recognize channel 1

### ISSUE THREAD

**Issue by Abdaaf444** [cleanflight/cleanflight#2424]
Hi. I have a CC3D and flashed cleanflight on it. Transmitter: Turnigy 9x

So i now have this mapping: ETRA1234.
But it looks like it doesnt recognize channel 1. And thinks that my channel 1 is AUX ch. 5.
So if i switch my gear button on my transmitter, it thinks that i want to roll the quad.

Before all this I had openpilot, and there everything worked fine. I have checked the wires and everything is ok.

Any help would be apprectiated.

Abdaaf

**Comment by hydra** [comment]
please see documentation, please use forums for support.
