### ISSUE TITLE
Failsafe - Allow RSSI to trigger failsafe

### ISSUE THREAD

**Issue by Infinity553** [cleanflight/cleanflight#243]
Would be cool to have a Failsafe that kicks in if the RSSI percentage goes under a given value, like 0%.

**Comment by hydra** [comment]
@Infinity553 I agree, i'm sure @ProDrone would too.

**Comment by ProDrone** [comment]
YES! anything that takes the control away from the pilot (except drinking & flying) should be handled by failsafe. I won't go as far as an (almost) empty battery, but who knows -someone may like it-.
