### ISSUE TITLE
Custom Naze32 USART3 (STM32F103C8T6)

### ISSUE THREAD

**Issue by giacomo892** [cleanflight/cleanflight#2435]
Since STM32F103 can deliver up to 3 hardware USART interfaces could be nice if they are all available to use.

That could be very good in situations like:

USART1) MSP telemetry 
USART2) Serial GPS
USART3) Serial Receiver (IBUS) (115200)

Avoiding the use of software serial for one of the previuous to enhance global performance and deliver realiable baudrates > 57600 on all serials.

To enable the third hw serial wil require:

1)Not having more than 4 motors since motor 5 and 6 will go on PB8 and PB9 or at least move motor 5 and 6 to PA6-7 used by motors 7-8 and limiting to 6 engines. 

2)The ability to use HW I2C1 bus on pins (PB8,PB9) instead of using HW I2C2 bus on pins (PB10,PB11) so one of the HW serial ports is not used by the I2C bus

pinout reference: https://developer.mbed.org/media/uploads/hudakz/stm32f103c8t6_pinout03.png

**Comment by hydra** [comment]
not something we're interested in, Naze32 is an F1 based I2C target that is End-Of-Life for Cleanflight, there are far more pressing things that users want right now.
