### ISSUE TITLE
Quadcopter issue

### ISSUE THREAD

**Issue by bakke37** [cleanflight/cleanflight#2438]
Hi guys. I'm really hoping someone can help me out with this issue I've got. I recently crashed and one of the power leads arced. Since I've repaired this, I've had quite a strange problem. After a few seconds of just hovering, the quad drops out the sky and always falls from the front left. Immediately, I figured it must be an issue with the motor or esc but after replacing both, I still have the same issue. Another problem that arose is whenever I plug in my flight controller, which is a lumenier lux, it doesn't make those sounds it usually made before. Although the fc still connects and i can make changes, I'm starting to think my flight controller is causing the issue. I would really appreciate some help. Just bought this flight controller and don't want to waste money if I don't have to.

**Comment by SteveAmor** [comment]
@bakke37 sorry for your problem. Please look for help on the likes of RCGroups.  The Cleanflight issues log if for reporting code bugs for developers to fix. Thanks.
