### ISSUE TITLE
Autonomous flying

### ISSUE THREAD

**Issue by liutairan** [cleanflight/cleanflight#2443]
Is there any intention to have autonomous flying or way point flying functions recently? Or does it already exist? Thanks.

**Comment by digitalentity** [comment]
Please have a look at INAV project:
https://github.com/iNavFlight/inav
http://www.rcgroups.com/forums/showthread.php?t=2495732

**Comment by liutairan** [comment]
Well, thanks. But the INAV just looks so similar to the cleanflight. I can see there are some changes, but any big differences?

**Comment by digitalentity** [comment]
@liutairan what did you expect? Pixhawk or Wookong :smile:? You asked for navigation support in Cleanflight - INAV **is** a fork of Cleanflight - no surprise it looks similar. 

But appearances can be deceiving. INAV has completely new navigation core and very different flight control logic.

**Comment by liutairan** [comment]
@digitalentity Yeah, I see. But as I wrote in my original post and the subject, what I am looking for is autonomous flight. Cleanflight and INAV have plenty attractive features, and I was asking if there is any intention to have autonomous flying features like Pixhawk or Wookong in the future. Anyway, thank you. I will read the wiki for INAV carefully. Thanks.

**Comment by digitalentity** [comment]
Please define "autonomous flight". INAV already has support of waypoint
flight.

**Comment by hydra** [comment]
Closing, see INAV for now.
