### ISSUE TITLE
SP Racing F3 error

### ISSUE THREAD

**Issue by gtboost** [cleanflight/cleanflight#2444]
OSD is fried but I can't connect to CleanFlight or BaseFlight. Controller is SP Racing F3, CleanFlight doesn't want to find my controller! What can I do? Please help.
P.S. Drone is beeping with 1s interval and all the lights are power on.

**Comment by hydra** [comment]
this is not a developer issue. please use forum or contact your retailer.  read the Contributing.md guidelines BEFORE creating issues.  Thanks!
