### ISSUE TITLE
port acceleration filtering from Betaflight 3.0

### ISSUE THREAD

**Issue by andre92** [cleanflight/cleanflight#2445]
In current state the acceleration readings are filtered when updating the IMU. (100hz)
This means 9 out of 10 acc samples are dropped, since acc is sampled at 1000hz.
Betaflight lowpass filters the acceleration readings right after sampling it. (in TASK_ACCEL) This ensures all acc samples go through the filter instead of only the latest when the filter is called.
100hz for acc filter may be too slow, and may cause aliasing and problems with althold. I would expect same effects for althold as in 1.12.0 where it was only sampled at 100hz.

**Comment by hydra** [comment]
any chance of a PR?

**Comment by andre92** [comment]
https://github.com/cleanflight/cleanflight/pull/2447 
I can not test it until tomorrow though, I don't currently have an FC at hand
