### ISSUE TITLE
servo max pitch angle issue

### ISSUE THREAD

**Issue by geoffreybainathsah** [cleanflight/cleanflight#2453]
dear developper

first, thank you for your hard work, i love to fly cleanflight on my quads.

this request is regarding camera tilt pwm value.
I have configured my screemer (penta copter) such that the 5th motor increases its output as the pitch angle of the craft increases downward.
this is done by activating servo_tilt

The issue is, that max output is reached at a **fixed** angle of 40 degrees tilt, please make max tilt angle user selectable
My goal is to have max tilt angle at 25 degrees approx
see picture below
http://s976.photobucket.com/user/trex500GBEDITION/media/cleanflight%20servo%20issue_zpsvhtwqr7r.jpg.html

Kind regards
Geoffrey

**Comment by hydra** [comment]
you can use the servo mixer to limit the range of the servo.
