### ISSUE TITLE
Implement BMP280 baro support on CC3D

### ISSUE THREAD

**Issue by rQwor** [cleanflight/cleanflight#2455]
Although "baro_hardware" can be set for BMP280, the CC3D does not support this barometer.
It is not included in target.h.

Thanks!

**Comment by hydra** [comment]
ditch the CC3D and use an SPRACINGF3EVO 😄  

The 128K targets are already quite full, I can take a quick look and see if it fits.

**Comment by hydra** [comment]
it fits, you're in luck.

done in f92066d900dfdd3e5b416c7ed2d63184479ddce5

this makes sense too, since the CC3D does not have an onboard baro.  boards with on-board baros, unless there is a good reason, generally only have support for the baros they were shipped with.

**Comment by rQwor** [comment]
Thanks a lot!
