### ISSUE TITLE
I Don't see ibus in the GUI

### ISSUE THREAD

**Issue by assafwei** [cleanflight/cleanflight#2462]
Hi,

I downloaded the latest version and I cant find the ibus serial provider option.
I looked around and understood that this option was already added to the GUI, but for some reason I dont see it in the list under serial provider.

Thanks.

**Comment by SteveAmor** [comment]
Hi @assafwei can you please close this issue here and raise it under cleanflight/configurator if you believe it is a bug.  Alternatively, you could ask for support on a forum like RCGroups.  Thanks.

**Comment by assafwei** [comment]
Sure.  Thanks.
