### ISSUE TITLE
servo max pitch angle issue (part2)

### ISSUE THREAD

**Issue by geoffreybainathsah** [cleanflight/cleanflight#2463]
Dear Hydra

thank you for replying to my last post 2453
Unfortunately my issue is not solved.

The servo mixer is working incorrect and angle at min/max is not working (higlited in blue)
please see photo http://s976.photobucket.com/user/trex500GBEDITION/media/cleanflight%20servo%20issue_zpsvhtwqr7r.jpg.html

my goal is to achieve max pwm at 20degree, right now max pwm is locked at 40degree.
I need to muliply the servo rate by 200% and servo mixer can go to max is 100% rate (higlighted in red)
Would you be so kind to take a look at this again

Geoffrey
![cleanflight servo issue](https://cloud.githubusercontent.com/assets/17955516/19585564/4d83dd80-9756-11e6-9d69-0409e75b97be.JPG)

**Comment by hydra** [comment]
angle at min/max does nothing, it never has - it was supposed to be used by the tilt drone support which was never completed and has now been removed in latest firmware and configurator.
