### ISSUE TITLE
CF configurator 1.2.4 - Issues with serial rx configuration

### ISSUE THREAD

**Issue by joolskii** [cleanflight/cleanflight#2467]
After updating to 1.2.4 of cleanflight configurator the serial rx configuration section does not appear in the configuration. 

I have set a port for SERIAL_RX but the configuration section still does not appear.

**Comment by joolskii** [comment]
Just been told it's moved to the receiver tab, the configuration is now at the bottom, should anyone else hit this issue.

**Comment by hydra** [comment]
:smile:

**Comment by hydra** [comment]
btw, this shoud be raised in the configurator issue tracker, not here.
