### ISSUE TITLE
Graupner Hott and "Text" mode

### ISSUE THREAD

**Issue by johnlenfr** [cleanflight/cleanflight#247]
Hi Hydra.
First I would like to thank you for this very nice peace of code.

I saw that you put a link to part of my research about the Hott protocol for the Graupner Radios.

I would like to tell you that I can send to you all of my work on that if you need it.
I don't know how to program and I made a very poor code that was doing what I want 2 years ago.

All of that to request if it is possible to integrate the "text mode" in the code so that we can have a menu in the radio to manage for example: PIDs, GPS options, RC Rate, etc...

So with that we will not need a bluetooth or PC or in flight stick adjustements PID.
Everything will be on a text menu on the radio, it would look like: http://mikrocontroller.com/files/HoTT/Hott_Status_2.gif

You can view some of my work here (I start with a simply lipometer and final with GPS and Pressure sensor):
Lipometer: http://www.youtube.com/watch?v=4yqt04cG9Sk
Menu for GPS options: http://www.youtube.com/watch?v=3U9cg2b_m50
Setting pressure sensor: http://www.youtube.com/watch?v=1KIIgY8Fupc

Original code is developed for Arduino but I'm pretty sure you can transform it for Cleanflight.
I can send to you the documentation about all of this if you want to work on this?
At what email I can send it to you?
It will be very nice to have that in the Hott telemetry protocol of Cleanflight.
If I could program it, I already did.

Thanks in advance for all of your work

**Comment by johnlenfr** [comment]
Here is the code attach.
You'll find also the Graupner unofficial documentation of the Hott v4 protocol in PDF.

Documentation here: https://johnlenfr.fr

Code of my last version here: https://johnlenfr.fr

Don't hesitate to contact me if you have questions about Hard/Soft.

**Comment by CopterFail** [comment]
I cant open the links...

**Comment by johnlenfr** [comment]
This is direct links to zip files.

We're now working on it, please see #260

**Comment by hydra** [comment]
Closing this, See #792
