### ISSUE TITLE
type mistake for 'SPRACINGF3MINI' target.h

### ISSUE THREAD

**Issue by dotnfc** [cleanflight/cleanflight#2471]
In the master, cleanflight/src/main/target/SPRACINGF3MINI/target.h,  line 83-84:

83  #define USB_DETECT_GPIO_PORT             GPIOB
84  #define USB_DETECT_GPIO_CLK              RCC_AHBPeriph_GPIOC

RCC_AHBPeriph_GPIOC should be RCC_AHBPeriph_GPIOB

**Comment by hydra** [comment]
thanks!
