### ISSUE TITLE
Modify the CF parameter with Frsky LUA and the S.Port Telemetry

### ISSUE THREAD

**Issue by bbc25185** [cleanflight/cleanflight#2474]
Frsky has developed the new receiver S6R...
This receiver can be configured using a FRSKY Taranis radio and the S6R LUA code without using a PC. (To do this, the LUA use the telemetry link).
Since CF already supports the  FrSky S.PORT telemetry,  I think it is quite simple to add support for changing parameters using a specially prepared LUA code to be run on TARANIS, no ???

**Comment by jflyper** [comment]
This might be related: betaflight/betaflight#1438

**Comment by raphaelcoeffic** [comment]
The original issue with feature discussion is betaflight/betaflight#1311.

**Comment by raphaelcoeffic** [comment]
Please note that there is now a testable version for betaflight. Please let me know if I should work on a port for cleanflight.

**Comment by hydra** [comment]
yes please!

**Comment by raphaelcoeffic** [comment]
@hydra where should I place the LUA script to test the feature? In BF, this is in the test dir, but I think it would be better somewhere else, perhaps even outside the project.

**Comment by hydra** [comment]
@raphaelcoeffic create 'support\opentx' and place it there.

**Comment by floaledm** [comment]
Great work! Any reason why this hasn't been merged yet?
