### ISSUE TITLE
Cant see the "looptime" setting in the Naze (32) CLI window in cleanflight V1.14.0

### ISSUE THREAD

**Issue by G433** [cleanflight/cleanflight#2481]
Is this featrue was replaced or dropped by purpose?
If yest what is the replacement for it?

**Comment by hydra** [comment]
it's gone, no replacement yet for 1.14.  requires additional work on the configurator.

**Comment by Poitivin** [comment]
Hi, if the looptime is gone what is now the default value for the looptime?
