### ISSUE TITLE
Massive triple digit CPU load on Naze32 Rev5 when selecting MWREWRITE PID controller.

### ISSUE THREAD

**Issue by Nihilistic** [cleanflight/cleanflight#2483]
When switching to rewrite, the CPU load shows super high. Naze32 Rev5 target.

**Comment by hydra** [comment]
adjust your gyro refresh and gyro sync settings, disable unused sensors, etc.

**Comment by Nihilistic** [comment]
CPU usage was well under 50% with LUX with default settings. LUX is that much easier on the CPU even on F1 targets despite lacking the dedicated FPU of the F3 boards?
