### ISSUE TITLE
Restore to 1.2.3

### ISSUE THREAD

**Issue by romanator** [cleanflight/cleanflight#2488]
The backup feature was removed for 1.2.4.  How do I downgrade to v1.2.3 on my Mac?  I need the backup feature to restore my drone settings.

**Comment by andre92** [comment]
I assume you mean the configurator. Download the version you want as zip: https://github.com/cleanflight/cleanflight-configurator/releases
extract it, and install it manually into google chrome (load unpacked extension)

**Comment by downtown54** [comment]
Help!! How do you install manually into Chrome?

**Comment by andre92** [comment]
@downtown54 Download the Configurator from https://github.com/cleanflight/cleanflight-configurator/releases (mind the version you want) and extract the archive in a new folder.
Next, visit chrome://extentions and enable developer mode. Then there will be a button to load an unpacked extention. Then find your unpacked folder of Cleanflight Configurator. It should install itself from there.

**Comment by downtown54** [comment]
Thanks Andre 

    On Monday, November 14, 2016 2:55 AM, André <notifications@github.com> wrote:
 

 @downtown54 Download the Configurator from https://github.com/cleanflight/cleanflight-configurator/releases (mind the version you want) and extract the archive in a new folder.
Next, visit chrome://extentions and enable developer mode. Then there will be a button to load an unpacked extention. Then find your unpacked folder of Cleanflight Configurator. It should install itself from there.—
