### ISSUE TITLE
Allow disabling of configurator auto updates

### ISSUE THREAD

**Issue by Exidouce** [cleanflight/cleanflight#249]
Normally the auto update is a nice feature. However, when there is no backwards compatibility if can cause a lot of issues. The most recent update did not connect to the previous FW version. Retrieving fresh settings, after a tuning session, was not possible and the settings were lost. 

I always keep a dump copy as text file and an offline copy of CF on my laptop so in the end nothing was lost but everyone is not so cautious. 

I suggest auto update be disabled by default and there be a notification when an update is available.

**Comment by hydra** [comment]
GUI issue.  Not possible anyway, talk to google :smile:
