### ISSUE TITLE
strange Blackbox data v1.14

### ISSUE THREAD

**Issue by xuyuan** [cleanflight/cleanflight#2490]
My copter flies fine, but blackbox gives strange data (i.e. battery value less than 1v, the heading is completely wrong)
Everything was fine in 1.13.0.

PS: Tested with NAZE

**Comment by hydra** [comment]
need more information on that, e.g. steps to repeat, config dumps, logs, etc.

**Comment by xuyuan** [comment]
For example, in this log [LOG00025.TXT](https://github.com/cleanflight/cleanflight/files/600242/LOG00025.TXT)

my quad was flying ok, it was hovering most of the time, but from the log file
* the battery voltage is about 1v
* the orientation is totally wrong in the picture below:
![selection_005](https://cloud.githubusercontent.com/assets/239020/20435254/b591e140-adab-11e6-8773-59c71a05e095.png)

**Comment by DengueTim** [comment]
I haven't been able to get blackbox data over serial with versions 1.14 and 1.14.1.   Worked as expected in 1.13.

**Comment by xuyuan** [comment]
@DengueTim that's another bug, I have fixed and made pull request 26 days ago:
https://github.com/cleanflight/cleanflight/pull/2489

I wonder how many people use cleanflight 1.14 with blackbox, since the configuration breaks...
