### ISSUE TITLE
coding style; const correctness

### ISSUE THREAD

**Issue by Bengt-M** [cleanflight/cleanflight#2491]
The style guide says:
> Defining constants using pre-processor macros is not preferred. Const-correctness should be enforced.

After trying to comply I see that a const var cannot be used to initialise a static var in C. Preferred in C++ but not allowed in C.
See here: http://stackoverflow.com/questions/3025050/error-initializer-element-is-not-constant-when-trying-to-initialize-variable-w

I think static is more important so the recommendation should be changed.

**Comment by mkschreder** [comment]
IMO const correctness is most useful when passing arguments to functions. Anything that you are not changing should be passed as const ptr.
