### ISSUE TITLE
Rx will not connect unless plugged in after FC boots - SPRacing F3/OrangeRx R615X

### ISSUE THREAD

**Issue by Kettenhund** [cleanflight/cleanflight#2493]
Greetings. I have an SPRacing F3 and I am attempting to use an OrangeRx R615X receiver outputting PPM. I have everything configured correctly as far as PPM and channel mapping in betaflight, but when powering on the quad the RX does not connect to the TX. If (after powering on the quad) I unplug and replug the PPM cable to the RX, the RX will connect to my DX6i radio with no issues every time. Is there a setting in the CLI I have to change? It seems that something is happening too fast in the boot process that is not allowing the RX to establish communication with the TX.

**Comment by hydra** [comment]
this is the cleanflight issue tracker, you're using betaflight.
