### ISSUE TITLE
Buzzer and current sensor not working on Afromini boards

### ISSUE THREAD

**Issue by RBirdie001** [cleanflight/cleanflight#2496]
Hi!
I use **AfroMini 32** NAZE boards on my multicopters Rev.3 (with external I2C magnetometer) (http://www.abusemark.com/downloads/afromini_rev3.pdf) and these boards work fine with NAZE builds except the BEEPER and Current sensor.
Reason is that Rev. 3 use NPN transistor for driving buzzer so need to **output high level** for beeping and not sink output to ground as other NAZE boards.
One possible solution already is prepared here: https://github.com/cleanflight/cleanflight/pull/1482#issuecomment-165391522 but it was never merged.
Another solution would be to make another separate target board with modified definitions.
...
All versions of AfroMini also use **A5 pin for current sensor ADC input** so current sensor doesn't work with standard NAZE builds. Also this would be easy to correct with creating new AfroMini target board.
I'm not able of modify code myself. Can please someone help me with this issue?
Thanks!
Roman

**Comment by hydra** [comment]
unlikely to ever be fixed due to lack of developer time and interest, no support from hardware manufacturer and lack of user interest.
