### ISSUE TITLE
Betaflight with Revolt F4

### ISSUE THREAD

**Issue by Maxthepersonz** [cleanflight/cleanflight#2506]
Does anyone know if this is possible? Just curious to throw the Raceflight board on Betaflight and see what I think. 

What firmware do I flash? Or none available yet?

-Max

**Comment by martinbudden** [comment]
Betaflight 3.1 will ship with a Raceflight Revolt target. See:

https://github.com/betaflight/betaflight/blob/master/src/main/target/REVO/REVOLT.mk

You can build it yourself now, but remember it is pre-release with all the risks that entails.

BTW, this is the Cleanflight not the Betaflight repository.

**Comment by William3170** [comment]
I just finished flashing Betaflight 3.1.5 to my Revolt FC. Works great, you just need to use Zadig to change driver. Install revolt on CDC driver and you should be able to connect FC after flashing BF Firmware.
