### ISSUE TITLE
CC3D serial command lists UART1 twice, SOFTSERIAL missing, v1.14.1

### ISSUE THREAD

**Issue by gimx** [cleanflight/cleanflight#2507]
`#` serial
serial 20 1 115200 57600 0 115200
serial 0 64 115200 57600 0 115200
serial 2 0 115200 57600 0 115200
serial 0 0 115200 57600 0 115200

`#` feature
Enabled: VBAT RX_SERIAL SOFTSERIAL FAILSAFE BLACKBOX

**Comment by atomiclama** [comment]
Something similar was fixed in the betaflight repo in the makefile associated with the CC3D OPBL, can't recall the details but could be a starting point for investigation.

@gimx Is this with the OPBL build?

**Comment by gimx** [comment]
This issue occurs with the hex file downloaded from the repo and it was not there with v1.12. I did not compile myself.
