### ISSUE TITLE
Receiver Mode & Serial Receiver Provider not appearing in configuration tab

### ISSUE THREAD

**Issue by kjmos** [cleanflight/cleanflight#2513]
I'm hoping that someone can provide me information why I'm not seeing Receiver Mode & Serial Receiver Provider in the configuration tab. Installed a new Naze32 v6, firmware is Betaflight_3.0.1, wired for SBUS to a X4R.

**Comment by stronnag** [comment]
1. You should be using the betaflight configurator for βF.
2. Have you looked in the Receiver Tab?
3. This is neither the configurator issue tracker, nor is it a support channel.

Please close.
