### ISSUE TITLE
ONESHOT125 not working in CUSTOMAIRPLANE or CUSTOMTRI mode

### ISSUE THREAD

**Issue by starlino** [cleanflight/cleanflight#2519]
ONESHOT125 not working in CUSTOMAIRPLANE or CUSTOMTRI mode . Using CC3D board.

**Comment by CerealKiller1** [comment]
If it works in standard tri mixer then this sounds like eother a wiring issue or the wrong servo / motor mixer (both causes being user error) to me...  We'll need so much more to go on to help in any way. 

Your wiring?
All relevant version / build info 
CLI dump 
ESC's
Servo mixer that works in standard tricopter mode?
