### ISSUE TITLE
Crash: USART1 listed twice in CFC, config corruption, CF crash

### ISSUE THREAD

**Issue by emente** [cleanflight/cleanflight#2529]
Problem: 
- Cleanflight Configurator lists UART1 twice, see screenshot.

Symptoms:
- Changes on first UART1 (listed after VCP) are ignored (except data toggle).
- Changes on second UART1 are saved but seem to corrupt data. CF crashes after about 30 seconds, sometimes blinking slow and steady, mostly signaling 6 blinks, on very few occasions 2 blinks. 

Steps to reproduce: 
- freshly flash CF 1.14.1 on CC3D (F1 cpu) via main port
- disable data and enable serial_RX on second UART1, save, reboot
- observe irratic behaviour and crash

Versions:
Flight controller info, identifier: CLFL, version: 1.14.1
Running firmware released on: Nov 11 2016 11:55:21
Board: CC3D, version: 0
Configurator: 1.2.4

![cfdoubleusart](https://cloud.githubusercontent.com/assets/1915844/21058106/c85c235c-be3c-11e6-8bb9-09f2be30ca17.png)

**Comment by emente** [comment]
CF 1.12.0 (CFC 1.2.4) works correctly.

**Comment by hydra** [comment]
have you tried flashing with full chip erase?  thanks for the report, not seen this issue before.  it does feel like the config is corrupt somehow, we just need to narrow down when this is happening.

**Comment by emente** [comment]
Yes, flashed with full chip erase. It happens right after you change something on the (duplicate) UART1 and save. CLI also reports duplicate UART1.

As said above, it works with 1.12.0, no doubly detected ports.

**Comment by GEORGEPLAVSIC180** [comment]
HOW TO ON WORKING THE CLEANFLIGHT ?

**Comment by hydra** [comment]
ok, fixed. cause was this: e1ef91c0bc56b468fb2012d212a5f02524972ac2

fixed by a8ccc57445f192d104aff4e2e344228636135479
re-added support for SOFTSERIAL via 11546a1ba2261d987a6197d88f2627f98d8b3a1f

please test new release candidate RC3 when available.

**Comment by emente** [comment]
1.14.3 works correctly. thanks.
