### ISSUE TITLE
Add mixer documentation

### ISSUE THREAD

**Issue by l2smith2** [cleanflight/cleanflight#253]
After recently trying to put a naze32 onto a deadcat/tbs discovery style frame I've found no mixer for it. QuadX flies pretty good but not perfect so I set about trying to learn how to make a custom mixer.
I researched for hours to find very little clear concise information about it. Mostly what other people have interpreted from their hours of their own research, trial and error.

I would like to see documentation added that explains how to correctly calculate the values for each cmix motor so that it passes the sanity check. There is not as much info regarding the Yaw values.

A separate tab in the GUI to enter these values instead of CLI (similar to mikrokopter) perhaps even show a graphical representation of where the mix is saying the motors are.

The perfect solution would be entering your number of motors, positions and distances apart on a grid and the correct mix is calculated for you.

**Comment by hydra** [comment]
Some links to help:

http://www.multiwii.com/forum/viewtopic.php?f=23&t=5345

http://www.rcgroups.com/forums/showpost.php?p=15964797&postcount=15361

http://polakiumengineering.org/custom-multiwii-motor-mixes/

https://www.youtube.com/watch?v=il6SoU8Hnak

**Comment by hydra** [comment]
Done, if there's anything missing please create a new issue and reference this one.
