### ISSUE TITLE
Cleanflight Triflight version 1.2.4 problem...

### ISSUE THREAD

**Issue by Atorhe** [cleanflight/cleanflight#2535]
Hi,

I am currently trying to setup a tricopter using triflight.
but i cant accsess  the servo tab in cleanflight config....
from what i understand this is a problem in version 1.2.4 and i need to go back to version 1.2.3 to make it work.

does anyone know how i can get version 1.2.3 cleanflight?

**Comment by stronnag** [comment]
This is not a support channel. This is not even the configurator bug tracker. Please seek support on the triflight tracker or RCGroups.
