### ISSUE TITLE
Naze32 rev6 ESC channel 2 dead with PWM Rx

### ISSUE THREAD

**Issue by mhd-medfa** [cleanflight/cleanflight#2537]
I'm building my first drone
and I faced a problem
when I send the signals from Tx to Rx and pull up the throttle stick, the motors go crazy.Taking into consideration, the first and fourth channels on the flight controller (Naze32 rev6) work very well, but, the second and third do not.
I tried to visualize the control signals that going from Naze to the first ESC which is wired to channel1 then to visualize the ESC number three using Oscilloscope and I recorded this video(in this video Naze works on the Horizon mode).
video link: 
https://youtu.be/9Bhr5u-ZEhI

it was gone four weeks from working, searching, asking others and trying many solutions without any good result...
Notes:
1.I used homemade power distribution board and ESCs with BEC and Battery 3S 
2.I calibrate the ESCs from the cleanflight extension many many times without any progress...
3.I recorded another video from cleanflight  configurator(i this video Naze works on manual mode "no mode")

**Comment by hydra** [comment]
please use rcgroups for help/support.  github is for developers or confirmed bugs/ideas/feature requests.
