### ISSUE TITLE
firmware flasher fail

### ISSUE THREAD

**Issue by andro46** [cleanflight/cleanflight#2540]
I was trying to update my vortex pro 250 ummagawd, and when i try to flash the firmware it failed
to do the upgrade. Now i have lost the communication to my board and i dont know how to make back  how it was.. help please

Youtube link: https://youtu.be/_uQFSKn6zu0

**Comment by stronnag** [comment]
This is not a support channel. Please ask on RCG or IRC and close this non-issue.
