### ISSUE TITLE
Cleanflight firmware flasher

### ISSUE THREAD

**Issue by andro46** [cleanflight/cleanflight#2541]
I was trying to update my vortex pro 250 ummagawd, and when i try to flash the firmware it failed
to do the upgrade. Now i have lost the communication to my board and i dont know how to make back how it was.. help please
Youtube link: https://youtu.be/_uQFSKn6zu0

**Comment by stronnag** [comment]
Please stop abusing the bug tracker.

**Comment by andro46** [comment]
What mean to you issue? I was adding this because i have this problem.. i dont know what the f.... do yoi want from me

**Comment by stronnag** [comment]
This is not a support channel. You are wasting developer time. Please take support questions to IRC or RC Groups.

You have been asked politely twice now.
