### ISSUE TITLE
combine flysky ibus telemetry and serial rx on same port

### ISSUE THREAD

**Issue by unitware** [cleanflight/cleanflight#2545]
Flysky ibus telemetry is discussed here: https://github.com/cleanflight/cleanflight/issues/1125

Meanwhile, I'm working on combining serial rx and ibus telemetry on the same pin without any specific mods to the flysky equipment. I'll start this issue for that discussion to stay focused.

**Comment by stronnag** [comment]
Does #2345 help?

**Comment by unitware** [comment]
I'm combining the ibus ports of the FS-iA6B receiver with a diode and a resistor.

```
+---------+
| FS-iA6B |
|         |
| Ser RX  |---|<---\       +------------+
|         |        |       | FC         |
| Sensor  |--#==#--*-------| SerialTX   |
+---------+                +------------+
```

![2016-12-19 22 27 41](https://cloud.githubusercontent.com/assets/6065378/21365422/98982d5c-c6f5-11e6-9e36-3a51d7ca699b.jpg)

**Comment by unitware** [comment]
Prereviews are welcome:
https://github.com/unitware/cleanflight/tree/combine-ibus-serial-rx-and-telemetry

I have borrowed some snippets from https://github.com/cleanflight/cleanflight/pull/2345 to be able to combine the serial port functions.

Enable with cli:
```
serial 1 1088 1115200 57600 115200 115200
feature RX_SERIAL
set serialrx_provider = IBUS
save
```

**Comment by inode-** [comment]
@unitware can you give us more information about what kind of resistor and diode you used?

Thanks

**Comment by unitware** [comment]
10kohm and something like 1n4148 or similar. I just scrapped some stuff in my drawers. 

Skickat från min iPhone

**Comment by unitware** [comment]
Lets move further discussions to the pull request: https://github.com/cleanflight/cleanflight/pull/2554

**Comment by MotoMotoRo** [comment]
Can it be used without a flight controller?
