### ISSUE TITLE
mmix command not respected in Cleanflight/NAZE 1.14.1

### ISSUE THREAD

**Issue by asmeureanu** [cleanflight/cleanflight#2550]
In # Cleanflight/NAZE 1.14.1 Nov 11 2016 / 11:53:56 (51ae22d)

I issue mmix command and the board implements something else check CLI  conversation:

**# mixer CUSTOM**
Mixer: CUSTOM
**# mmix reset**
**# mmix 0  1.000  1.000 -1.000 -1.000**

Motor	Thr	Roll	Pitch	Yaw
#0:	 1.000	 1.000	 1.000	 1.000

**# mmix 1  1.000  1.000  1.000  1.000**
Motor	Thr	Roll	Pitch	Yaw
#0:	 1.000	 1.000	 1.000	 1.000
#1:	 1.000	 1.000	 1.000	 1.000

**# mmix 2  1.000 -1.000 -1.000  1.000**
Motor	Thr	Roll	Pitch	Yaw
#0:	 1.000	 1.000	 1.000	 1.000
#1:	 1.000	 1.000	 1.000	 1.000
#2:	 1.000	 1.000	-1.000	-1.000

**# mmix 3  1.000 -1.000  1.000 -1.000**
Motor	Thr	Roll	Pitch	Yaw
#0:	 1.000	 1.000	 1.000	 1.000
#1:	 1.000	 1.000	 1.000	 1.000
#2:	 1.000	 1.000	-1.000	-1.000
#3:	 1.000	 1.000	-1.000	 1.000

**Comment by hydra** [comment]
works fine here

```
# mixer CUSTOM
Mixer: CUSTOM

# mmix reset

# mmix 0 1.000 1.000 -1.000 -1.000
Motor	Thr	Roll	Pitch	Yaw
#0:	 1.000	 1.000	-1.000	-1.000

# mmix 1 1.000 1.000 1.000 1.000
Motor	Thr	Roll	Pitch	Yaw
#0:	 1.000	 1.000	-1.000	-1.000
#1:	 1.000	 1.000	 1.000	 1.000

# mmix 2 1.000 -1.000 -1.000 1.000
Motor	Thr	Roll	Pitch	Yaw
#0:	 1.000	 1.000	-1.000	-1.000
#1:	 1.000	 1.000	 1.000	 1.000
#2:	 1.000	-1.000	-1.000	 1.000

# mmix 3 1.000 -1.000 1.000 -1.000
Motor	Thr	Roll	Pitch	Yaw
#0:	 1.000	 1.000	-1.000	-1.000
#1:	 1.000	 1.000	 1.000	 1.000
#2:	 1.000	-1.000	-1.000	 1.000
#3:	 1.000	-1.000	 1.000	-1.000

# 
```

I suspect the '-' symbol you were pasting was a strange unicode character or something.
