### ISSUE TITLE
flip32 wont arm

### ISSUE THREAD

**Issue by outkast187** [cleanflight/cleanflight#2551]
I have no idea if this is in right place, most god awful site on earth to navigate, will never see a reply I'm sure.

did everything by the book, calibrated acc, esc, etc. 
set all radio functions, and at 996-1504-2001 on sticks

no arm, even with switch.  8 hours of attempts.

**Comment by hydra** [comment]
yes, wrong place. complain to github regarding github itself.  new release candidate v1.14.2-RC just posted, try it.  use rcgroups for user support.  github is for developers or for confirmed bugs/features/ideas.

https://www.rcgroups.com/forums/showthread.php?2249574-Cleanflight-firmware-for-STM32F3-based-FCBs-Check-First-Post-Please!!
