### ISSUE TITLE
Unable to ARM - F3 EVO

### ISSUE THREAD

**Issue by Curran3001** [cleanflight/cleanflight#2556]
Hello,

I'm attempting to build my first quad and I'm having issues arming (i think). The quad just doesn't respond to the transmitter.

The receiver seems to be receiving the signal from the transmitter ok when I look on the receiver tab and I can power up the motors in CF.

Any ideas to get it working?

Thanks

**Comment by HomeY** [comment]
You probably already check this, but have you checked the correct Channel Map setting on the receiver map?

**Comment by hydra** [comment]
please use rcgroups.com for support.
