### ISSUE TITLE
CC3D Warning LED 6x "the system is overloaded"

### ISSUE THREAD

**Issue by ckusnierek** [cleanflight/cleanflight#2558]
I have a clean flashed CC3D. 
Setup serial Rx SBUS to my Taranis. Inputs are all good. 
Even in the default (reset all) state I get 6 flashes from blue LED indicating a system overload:
[http://shipow.github.io/cleanflight-web/docs/controls.html](http://shipow.github.io/cleanflight-web/docs/controls.html)
ESCs are calibrated and giving ready tones. 
after power on the LED sequence goes something like this:
Fast flash for about 2 seconds
5 flashes (calibrating gyros)
"heart beat" ready flashes for about 3 seconds
then constant 6x flashes indicating a overloaded system
occasionally it will go back to ready pulses for just a few seconds then back to 6x

**Comment by hydra** [comment]
try v1.14.2-RC3 please.

**Comment by ccpyle** [comment]
Same problem here, even on RC3.
