### ISSUE TITLE
SPRacing F3 amperage_meter_source=ADC CPU at 500%

### ISSUE THREAD

**Issue by jelinj8** [cleanflight/cleanflight#2565]
After clean flashing with full chip erase, setting amperage_meter_source=ADC and saving makes CPU overloaded. (CF 1.14.2)

**Comment by willanth** [comment]
I can also demonstrate this bug.. 

CF configurator 1.2.4
SP Racing F3, CF firmware 1.14.2

If I enable current monitoring, reported CPU load goes from 20-30% (sitting on the bench with no other activity) to 500+%.
