### ISSUE TITLE
can not arm quad unless plugged into clean flight 

### ISSUE THREAD

**Issue by buzznlush** [cleanflight/cleanflight#2572]
hi.
i recently purchased a rotorx rx122 jr and a taranis x9d plus transmitter, everything seemed to set up well. plugged into clean flight with bat plugged into quad and transmitter on after saving and rebooting the quad will arm (switch g) for arming . i can unplug and all stick inputs work well. as soon as i unplug batt and plug back in quad wont arm unless i repeat the steps above.
taranis stick end points are min 1000 max 2000
in cleanflight min throttle is 1050 max is 2000
min command is 1000.
when i do have everything plugged into clean flight and hit save and reboot i notice in the log screen everything works except rebooting comes up in red writing. so perhaps a rebooting problem. 
any help would be much appreciated, ive been stuck here for days

**Comment by andre92** [comment]
please post the output of following CLI commands:
dump
status

**Comment by buzznlush** [comment]
Hi Andre
Thanks for responding.  I will do what you've asked very soon. I'm beat for
what is happening but it is something to do with the arming switch and
software. it doesn't seem to be hardware related ... well i don't think so
anyways

Darren

**Comment by buzznlush** [comment]
[#dump.txt](https://github.com/cleanflight/cleanflight/files/698460/dump.txt)


# dump

# version
# BetaFlight/COLIBRI_RACE 3.0.0 Oct  6 2016 / 09:00:01 (f408ed9)

# name
name -

# mixer
mixer QUADX

mmix reset


# servo
servo 0 1000 2000 1500 90 90 100 -1
servo 1 1000 2000 1500 90 90 100 -1
servo 2 1000 2000 1500 90 90 100 -1
servo 3 1000 2000 1500 90 90 100 -1
servo 4 1000 2000 1500 90 90 100 -1
servo 5 1000 2000 1500 90 90 100 -1
servo 6 1000 2000 1500 90 90 100 -1
servo 7 1000 2000 1500 90 90 100 -1

# servo mix
smix reset



# feature
feature -RX_PPM
feature -VBAT
feature -INFLIGHT_ACC_CAL
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -FAILSAFE
feature -SONAR
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DISPLAY
feature -OSD
feature -BLACKBOX
feature -CHANNEL_FORWARDING
feature -TRANSPONDER
feature -AIRMODE
feature VBAT
feature INFLIGHT_ACC_CAL
feature RX_SERIAL
feature FAILSAFE
feature LED_STRIP
feature OSD
feature AIRMODE

# beeper
beeper GYRO_CALIBRATED
beeper RX_LOST
beeper RX_LOST_LANDING
beeper DISARMING
beeper ARMING
beeper ARMING_GPS_FIX
beeper BAT_CRIT_LOW
beeper BAT_LOW
beeper GPS_STATUS
beeper RX_SET
beeper ACC_CALIBRATION
beeper ACC_CALIBRATION_FAIL
beeper READY_BEEP
beeper MULTI_BEEPS
beeper DISARM_REPEAT
beeper ARMED
beeper SYSTEM_INIT
beeper ON_USB

# map
map TAER1234

# serial
serial 20 1 115200 57600 0 115200
serial 0 1 115200 57600 0 115200
serial 1 64 115200 57600 0 115200
serial 2 0 115200 57600 0 115200

# led
led 0 0,0:W:CW:6
led 1 0,1:W:CW:6
led 2 0,8:W:CW:6
led 3 7,15::C:6
led 4 8,15::C:6
led 5 7,14::C:6
led 6 8,14::C:6
led 7 15,8:E:CW:6
led 8 15,1:E:CW:6
led 9 15,0:E:CW:6
led 10 0,0::C:0
led 11 0,0::C:0
led 12 0,0::C:0
led 13 0,0::C:0
led 14 0,0::C:0
led 15 0,0::C:0
led 16 0,0::C:0
led 17 0,0::C:0
led 18 0,0::C:0
led 19 0,0::C:0
led 20 0,0::C:0
led 21 0,0::C:0
led 22 0,0::C:0
led 23 0,0::C:0
led 24 0,0::C:0
led 25 0,0::C:0
led 26 0,0::C:0
led 27 0,0::C:0
led 28 0,0::C:0
led 29 0,0::C:0
led 30 0,0::C:0
led 31 0,0::C:0

# color
color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 0,0,0
color 15 0,0,0

# mode_color
mode_color 0 0 1
mode_color 0 1 11
mode_color 0 2 2
mode_color 0 3 13
mode_color 0 4 10
mode_color 0 5 3
mode_color 1 0 5
mode_color 1 1 11
mode_color 1 2 3
mode_color 1 3 13
mode_color 1 4 10
mode_color 1 5 3
mode_color 2 0 10
mode_color 2 1 11
mode_color 2 2 4
mode_color 2 3 13
mode_color 2 4 10
mode_color 2 5 3
mode_color 3 0 8
mode_color 3 1 11
mode_color 3 2 4
mode_color 3 3 13
mode_color 3 4 10
mode_color 3 5 3
mode_color 4 0 7
mode_color 4 1 11
mode_color 4 2 3
mode_color 4 3 13
mode_color 4 4 10
mode_color 4 5 3
mode_color 5 0 9
mode_color 5 1 11
mode_color 5 2 2
mode_color 5 3 13
mode_color 5 4 10
mode_color 5 5 3
mode_color 6 0 6
mode_color 6 1 10
mode_color 6 2 1
mode_color 6 3 0
mode_color 6 4 0
mode_color 6 5 2
mode_color 6 6 3
mode_color 6 7 6
mode_color 6 8 0
mode_color 6 9 0
mode_color 6 10 0

# aux
aux 0 0 0 1800 2100
aux 1 1 1 900 1200
aux 2 2 1 1300 1700
aux 3 14 2 900 1800
aux 4 0 0 900 900
aux 5 0 0 900 900
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# adjrange
adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0
adjrange 12 0 0 900 900 0 0
adjrange 13 0 0 900 900 0 0
adjrange 14 0 0 900 900 0 0

# rxrange
rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000

# rxfail
rxfail 0 a
rxfail 1 a
rxfail 2 a
rxfail 3 a
rxfail 4 h
rxfail 5 h
rxfail 6 h
rxfail 7 h
rxfail 8 h
rxfail 9 h
rxfail 10 h
rxfail 11 h
rxfail 12 h
rxfail 13 h
rxfail 14 h
rxfail 15 h
rxfail 16 h
rxfail 17 h

# master
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_scale = 30
set rc_interpolation = AUTO
set rc_interpolation_interval = 19
set rssi_ppm_invert = OFF
set input_filtering_mode = OFF
set roll_yaw_cam_mix_degrees = 0
set max_aux_channels = 6
set debug_mode = NONE
set min_throttle = 1050
set max_throttle = 2000
set min_command = 980
set servo_center_pulse = 1500
set max_esc_throttle_jump = 0
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set 3d_deadband_throttle = 50
set use_unsynced_pwm = OFF
set motor_pwm_protocol = MULTISHOT
set motor_pwm_rate = 400
set servo_pwm_rate = 50
set disarm_kill_switch = ON
set gyro_cal_on_first_arm = OFF
set auto_disarm_delay = 5
set small_angle = 25
set fixedwing_althold_dir = 1
set reboot_character = 82
set gps_provider = NMEA
set gps_sbas_mode = AUTO
set gps_auto_config = ON
set gps_auto_baud = OFF
set gps_wp_radius = 200
set nav_controls_heading = ON
set nav_speed_min = 100
set nav_speed_max = 300
set nav_slew_rate = 30
set serialrx_provider = SBUS
set sbus_inversion = ON
set telemetry_switch = OFF
set telemetry_inversion = ON
set frsky_default_lattitude =  0.000
set frsky_default_longitude =  0.000
set frsky_coordinates_format = 0
set frsky_unit = IMPERIAL
set frsky_vfas_precision = 0
set frsky_vfas_cell_voltage = OFF
set hott_alarm_sound_interval = 5
set battery_capacity = 0
set vbat_scale = 110
set vbat_max_cell_voltage = 43
set vbat_min_cell_voltage = 33
set vbat_warning_cell_voltage = 35
set vbat_hysteresis = 1
set current_meter_scale = 400
set current_meter_offset = 0
set multiwii_current_meter_output = OFF
set current_meter_type = ADC
set align_gyro = DEFAULT
set align_acc = DEFAULT
set align_mag = DEFAULT
set align_board_roll = 0
set align_board_pitch = 0
set align_board_yaw = 180
set max_angle_inclination = 700
set gyro_lpf = OFF
set gyro_sync_denom = 1
set gyro_lowpass_level = NORMAL
set gyro_lowpass = 90
set gyro_notch_hz = 0
set gyro_notch_cutoff = 130
set moron_threshold = 32
set imu_dcm_kp = 2500
set imu_dcm_ki = 0
set alt_hold_deadband = 40
set alt_hold_fast_change = ON
set deadband = 10
set yaw_deadband = 10
set throttle_correction_value = 0
set throttle_correction_angle = 800
set yaw_control_direction = 1
set yaw_motor_direction = 1
set tri_unarmed_servo = ON
set servo_lowpass_freq = 400
set servo_lowpass_enable = OFF
set airmode_activate_throttle = 1350
set failsafe_delay = 10
set failsafe_off_delay = 10
set failsafe_throttle = 1000
set failsafe_kill_switch = OFF
set failsafe_throttle_low_delay = 10
set failsafe_procedure = DROP
set rx_min_usec = 885
set rx_max_usec = 2115
set gimbal_mode = NORMAL
set acc_hardware = AUTO
set acc_lpf_hz =  10.000
set accxy_deadband = 40
set accz_deadband = 40
set acc_unarmedcal = ON
set acc_trim_pitch = 0
set acc_trim_roll = 0
set baro_tab_size = 21
set baro_noise_lpf =  0.600
set baro_cf_vel =  0.985
set baro_cf_alt =  0.965
set baro_hardware = NONE
set mag_hardware = NONE
set mag_declination = 0
set pid_process_denom = 2
set blackbox_rate_num = 1
set blackbox_rate_denom = 1
set blackbox_device = SERIAL
set blackbox_on_motor_test = OFF
set magzero_x = 0
set magzero_y = 0
set magzero_z = 0
set ledstrip_visual_beeper = OFF

# profile
profile 0

set gps_pos_p = 15
set gps_pos_i = 0
set gps_pos_d = 0
set gps_posr_p = 34
set gps_posr_i = 14
set gps_posr_d = 53
set gps_nav_p = 25
set gps_nav_i = 33
set gps_nav_d = 83
set pid_delta_method = MEASUREMENT
set yaw_p_limit = 500
set dterm_lowpass_level = HIGH
set dterm_lowpass = 100
set dterm_notch_hz = 260
set dterm_notch_cutoff = 160
set vbat_pid_compensation = OFF
set pid_at_min_throttle = ON
set iterm_throttle_gain = 0
set pterm_srate_ratio = 100
set dterm_setpoint_weight = 50
set yaw_rate_accel_limit = 220
set rate_accel_limit = 0
set accum_threshold = 130
set yaw_accum_threshold = 32
set yaw_lowpass = 80
set pid_controller = BETAFLIGHT
set p_pitch = 52
set i_pitch = 73
set d_pitch = 24
set p_roll = 50
set i_roll = 51
set d_roll = 22
set p_yaw = 92
set i_yaw = 53
set d_yaw = 20
set p_alt = 50
set i_alt = 0
set d_alt = 0
set p_level = 50
set i_level = 50
set d_level = 100
set p_vel = 55
set i_vel = 55
set d_vel = 75
rateprofile 0

# rateprofile
rateprofile 0

set rc_rate = 70
set rc_rate_yaw = 80
set rc_expo = 15
set rc_yaw_expo = 15
set thr_mid = 50
set thr_expo = 0
set roll_srate = 72
set pitch_srate = 72
set yaw_srate = 72
set tpa_rate = 20
set tpa_breakpoint = 1650

# status
System Uptime: 24 seconds, Voltage: 0 * 0.1V (1S battery - NOT PRESENT), CPU:26%
CPU Clock=72MHz, GYRO=MPU6000, ACC=MPU6000
Cycle Time: 135, I2C Errors: 1, config size: 1476

#

**Comment by buzznlush** [comment]
done, 
i have changed to betaflight and the fc now has betaflight 3.0.0 aton v2 but the issue remains the same

**Comment by andre92** [comment]
If you still have the same issue with Betaflight, could you please also post it [in the Betaflight issue tracker](https://github.com/betaflight/betaflight/issues)?

**Comment by buzznlush** [comment]
the dump I posted was from bf. .. i swapped to bf because I thought cf may
have been the issue.
I flashed the fc with beta flight atom v2 and had the same issue..

Darren

**Comment by buzznlush** [comment]
Oh. . yes I can do that .. i get what your saying

Darren

**Comment by waynewendrone** [comment]
I have the same problem here and don't know what to do, I'm using an sp racing f3

**Comment by buzznlush** [comment]
Hi Wayne.
the problem I had (rotorx arom v2 Tbs power cube ))was solved by going
through the osd setup .. at the time I had no goggles and didn't read
anywhere I had to go through the osd set up even though now looking at
things it made sense to do so.
other than that i discovered it can also be minimum throttle settings
initially I had a min throttle of 1000 i had to reduce it to 989 before the
quad would arm (srd280 v3 cc3d fc )

Darren

**Comment by waynewendrone** [comment]
Ok that's great that we have a possible solution, could you just give me the exact things I need to look into and the steps I need to take. I'm new to drones:D!

Wayne

**Comment by waynewendrone** [comment]
About the minimum throttle, surely the quad wouldn't have armed while during clean flight of the numbers were too high?

**Comment by buzznlush** [comment]
True. I'd day you have everything right but have not completed something.

With the power cube i had to press a button on the vtx and follow the
prompts after which it armed armed and flew without issue.
I'm new to this myself so I may not be as much help as some of the other
more experienced pilots.


Darren

**Comment by buzznlush** [comment]
when you say it armed when plugged into cleanflight was that using the tx
or when testing motor outputs in a screen

Darren

**Comment by waynewendrone** [comment]
What I mean is that I can arm it using my Devo 10

**Comment by waynewendrone** [comment]
But can't while USB is unplugged

**Comment by buzznlush** [comment]
do you have a failsafe set on the fc . I had that mentioned to me before I
sorted the issue I was having.
As I said.  The issue I had was specific to the vtx board which is part of
the Tbs powercube . It had to be calibrated via osd before it would arm
without being plugged in to pc

Darren

**Comment by waynewendrone** [comment]
I'm not getting any beeps from the esc without the USB cable plugged in, but if I have the USB cable plugged in first and then the battery the motors would arm

**Comment by waynewendrone** [comment]
here is my dump

**Comment by waynewendrone** [comment]
dump

# version
# Cleanflight/SPRACINGF3 1.14.2 Dec 31 2016 / 02:11:08 (747971f)
# dump master

# mixer
mixer QUADX
mmix reset
smix reset


# feature
feature -RX_PPM
feature -VBAT
feature -INFLIGHT_ACC_CAL
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -FAILSAFE
feature -SONAR
feature -TELEMETRY
feature -AMPERAGE_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DISPLAY
feature -ONESHOT125
feature -BLACKBOX
feature -CHANNEL_FORWARDING
feature -TRANSPONDER
feature -OSD
feature VBAT
feature MOTOR_STOP
feature FAILSAFE
feature RX_PARALLEL_PWM


# map
map AETR1234


# serial
serial 0 1 115200 57600 0 115200
serial 1 0 115200 57600 0 115200
serial 2 0 115200 57600 0 115200


# led
led 0 15,15:ES:AI:0
led 1 15,8:E:FW:0
led 2 15,7:E:FW:0
led 3 15,0:NE:AI:0
led 4 8,0:N:F:0
led 5 7,0:N:F:0
led 6 0,0:NW:AI:0
led 7 0,7:W:FW:0
led 8 0,8:W:FW:0
led 9 0,15:SW:AI:0
led 10 7,15:S:FW:0
led 11 8,15:S:FW:0
led 12 7,7:U:FW:0
led 13 8,7:U:FW:0
led 14 7,8:D:FW:0
led 15 8,8:D:FW:0
led 16 8,9::R:3
led 17 9,10::R:3
led 18 10,11::R:3
led 19 10,12::R:3
led 20 9,13::R:3
led 21 8,14::R:3
led 22 7,14::R:3
led 23 6,13::R:3
led 24 5,12::R:3
led 25 5,11::R:3
led 26 6,10::R:3
led 27 7,9::R:3
led 28 0,0::C:0
led 29 0,0::C:0
led 30 0,0::C:0
led 31 0,0::C:0


# color
color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 0,0,0
color 15 0,0,0


# mode_color
mode_color 0 0 1
mode_color 0 1 11
mode_color 0 2 2
mode_color 0 3 13
mode_color 0 4 10
mode_color 0 5 3
mode_color 1 0 5
mode_color 1 1 11
mode_color 1 2 3
mode_color 1 3 13
mode_color 1 4 10
mode_color 1 5 3
mode_color 2 0 10
mode_color 2 1 11
mode_color 2 2 4
mode_color 2 3 13
mode_color 2 4 10
mode_color 2 5 3
mode_color 3 0 8
mode_color 3 1 11
mode_color 3 2 4
mode_color 3 3 13
mode_color 3 4 10
mode_color 3 5 3
mode_color 4 0 7
mode_color 4 1 11
mode_color 4 2 3
mode_color 4 3 13
mode_color 4 4 10
mode_color 4 5 3
mode_color 5 0 9
mode_color 5 1 11
mode_color 5 2 2
mode_color 5 3 13
mode_color 5 4 10
mode_color 5 5 3
mode_color 6 0 6
mode_color 6 1 10
mode_color 6 2 1
mode_color 6 3 0
mode_color 6 4 0
mode_color 6 5 2
mode_color 6 6 3
mode_color 6 7 6
mode_color 6 8 0
mode_color 6 9 0
mode_color 6 10 0

set debug_mode = NONE
set emf_avoidance = OFF
set i2c_highspeed = ON
set mid_rc = 1500
set min_check = 1150
set max_check = 1890
set rssi_channel = 0
set rssi_scale = 30
set rssi_ppm_invert = OFF
set rc_smoothing = OFF
set rx_min_usec = 885
set rx_max_usec = 2115
set serialrx_provider = SPEK1024
set sbus_inversion = ON
set spektrum_sat_bind = 0
set input_filtering_mode = OFF
set min_throttle = 1150
set max_throttle = 1850
set min_command = 1000
set motor_pwm_rate = 400
set servo_center_pulse = 1500
set servo_pwm_rate = 50
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set retarded_arm = OFF
set disarm_kill_switch = ON
set auto_disarm_delay = 5
set max_arm_angle = 25
set fixedwing_althold_dir = 1
set reboot_character = 82
set gps_provider = NMEA
set gps_sbas_mode = AUTO
set gps_auto_config = ON
set gps_auto_baud = OFF
set telemetry_switch = OFF
set telemetry_inversion = ON
set telemetry_send_cells = ON
set frsky_default_lattitude =  0.000
set frsky_default_longitude =  0.000
set frsky_coordinates_format = 0
set frsky_unit = IMPERIAL
set frsky_vfas_precision = 0
set hott_alarm_sound_interval = 5
set ibus_report_cell_voltage = OFF
set battery_capacity = 0
set vbat_scale = 110
set vbat_max_cell_voltage = 43
set vbat_min_cell_voltage = 33
set vbat_warning_cell_voltage = 35
set amperage_meter_scale = 0
set amperage_meter_offset = 0
set multiwii_amperage_meter_output = OFF
set amperage_meter_source = VIRTUAL
set vbat_hysteresis = 1
set align_gyro = DEFAULT
set align_acc = DEFAULT
set align_mag = DEFAULT
set align_board_roll = 0
set align_board_pitch = 0
set align_board_yaw = 90
set small_angle = 25
set max_angle_inclination = 500
set pid_process_denom = 1
set gyro_sync = 1
set gyro_sample_hz = 2000
set gyro_lpf = OFF
set gyro_lowpass_level = NORMAL
set gyro_lowpass_hz = 90
set gyro_notch_hz = 130
set gyro_notch_cutoff_hz = 130
set moron_threshold = 32
set imu_dcm_kp = 2500
set imu_dcm_ki = 0
set pid_at_min_throttle = ON
set yaw_motor_direction = 1
set yaw_jump_prevention_limit = 200
set tri_unarmed_servo = ON
set servo_lowpass_freq =  400.000
set servo_lowpass_enable = OFF
set failsafe_delay = 200
set failsafe_off_delay = 200
set failsafe_throttle = 1000
set failsafe_kill_switch = OFF
set failsafe_throttle_low_delay = 100
set failsafe_procedure = 0
set acc_hardware = 0
set baro_hardware = 0
set mag_hardware = 0
set blackbox_rate_num = 1
set blackbox_rate_denom = 1
set blackbox_device = SPIFLASH
set magzero_x = 0
set magzero_y = 0
set magzero_z = 0

# rxfail
rxfail 0 a
rxfail 1 a
rxfail 2 a
rxfail 3 a
rxfail 4 h
rxfail 5 h
rxfail 6 h
rxfail 7 h
rxfail 8 h
rxfail 9 h
rxfail 10 h
rxfail 11 h
rxfail 12 h
rxfail 13 h
rxfail 14 h
rxfail 15 h
rxfail 16 h
rxfail 17 h

# dump profile

# profile
profile 0

# aux
aux 0 1 0 1800 2100
aux 1 0 0 900 900
aux 2 0 0 900 900
aux 3 0 0 900 900
aux 4 0 0 900 900
aux 5 0 0 900 900
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900

# adjrange
adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0

# rxrange
rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000

# servo
servo 0 1000 2000 1500 100 -1
servo 1 1000 2000 1500 100 -1
servo 2 1000 2000 1500 100 -1
servo 3 1000 2000 1500 100 -1
servo 4 1000 2000 1500 100 -1
servo 5 1000 2000 1500 100 -1
servo 6 1000 2000 1500 100 -1
servo 7 1000 2000 1500 100 -1

set gps_pos_p = 15
set gps_pos_i = 0
set gps_pos_d = 0
set gps_posr_p = 34
set gps_posr_i = 14
set gps_posr_d = 53
set gps_nav_p = 25
set gps_nav_i = 33
set gps_nav_d = 83
set gps_wp_radius = 200
set nav_controls_heading = ON
set nav_speed_min = 100
set nav_speed_max = 300
set nav_slew_rate = 30
set alt_hold_deadband = 40
set alt_hold_fast_change = ON
set deadband = 0
set yaw_deadband = 0
set yaw_control_direction = 1
set 3d_deadband_throttle = 50
set throttle_correction_value = 0
set throttle_correction_angle = 800
set default_rate_profile = 0
set gimbal_mode = NORMAL
set acc_cut_hz = 15
set accxy_deadband = 40
set accz_deadband = 40
set accz_lpf_cutoff =  5.000
set acc_unarmedcal = ON
set acc_trim_pitch = 0
set acc_trim_roll = 0
set baro_tab_size = 21
set baro_noise_lpf =  0.600
set baro_cf_vel =  0.985
set baro_cf_alt =  0.965
set mag_declination = 0
set pid_controller = LUX
set p_pitch = 40
set i_pitch = 30
set d_pitch = 23
set p_roll = 40
set i_roll = 30
set d_roll = 23
set p_yaw = 85
set i_yaw = 45
set d_yaw = 0
set p_alt = 50
set i_alt = 0
set d_alt = 0
set p_level = 20
set i_level = 10
set d_level = 75
set p_vel = 120
set i_vel = 45
set d_vel = 1
set pid_delta_method = MEASUREMENT
set yaw_p_limit = 500
set yaw_lpf_hz = 0
set dterm_lowpass_level = HIGH
set dterm_lowpass_hz = 100
set horizon_tilt_effect = 75
set horizon_tilt_mode = SAFE
set gtune_loP_rll = 10
set gtune_loP_ptch = 10
set gtune_loP_yw = 10
set gtune_hiP_rll = 100
set gtune_hiP_ptch = 100
set gtune_hiP_yw = 100
set gtune_pwr = 0
set gtune_settle_time = 450
set gtune_average_cycles = 16

# dump rates

# rateprofile
rateprofile 0

set rc_rate = 90
set rc_expo = 65
set rc_yaw_expo = 0
set thr_mid = 50
set thr_expo = 0
set roll_rate = 0
set pitch_rate = 0
set yaw_rate = 0
set tpa_rate = 0
set tpa_breakpoint = 1500

**Comment by buzznlush** [comment]
Hi Wayne.
just wondering how you are doing with the issue at hand.
I had a look at the dump file but because I'm almost as new ass you I'm
can't see much.
I can only think of throttle settings, failsafe rx tx and fc and osd setup.
. Each of those if not set will cause your issue.

Darren

**Comment by waynewendrone** [comment]
Hi Darren, it's the same as it's always been, I can arm the motors if I plug the USB into the fc and then into a power source, I was wondering if it could be that my fc is not getting the 5v it needs but I have linear Bec in my esc so I don't see how that's the case, also I'm sure how to configure the osd since I don't have one.

Wayne

**Comment by hydra** [comment]
please use rcgroups for user-support

**Comment by jalao** [comment]
All, has anyone found a solution to BFF4 not arming unless plugged into to USB. I purchased two FC which cost me almost $90 including shipping. I purchased this FC because I trusted the teams developing the BF can be trusted. It is very frustrating after 2 separate builds  with 2 FC's and I can not arm my quad. I have increased my Moron_threshold to 120. Nothing happens. Please if there is a solution please kindly help.

**Comment by mikeller** [comment]
@jalao: This seems to be a problem with the board design, caused by the voltage regulator introducing too much noise for the gyro to work when not plugged into USB. Contact the manufacturer.

**Comment by waynewendrone** [comment]
What about turning off the accelerometer and fly in rate mode??
