### ISSUE TITLE
NAZE target, gyro with no reading in 1.14.0 

### ISSUE THREAD

**Issue by dhoulton** [cleanflight/cleanflight#2587]
NAZE32 rev 6 gets no gyro input when flashing 1.14.  Behavior seems identical to CJMCU issue #2485. I applied the fix suggested there ("define DEFAULT_GYRO_SYNC 0) and problem is resolved. I'll issue a pull request back to mainline.

**Comment by hydra** [comment]
fix merged, thanks.
