### ISSUE TITLE
Moving all relevent PID setup info onto one screen

### ISSUE THREAD

**Issue by FinalGlide** [cleanflight/cleanflight#259]
It would be really helpful to move throttle mid, throttle expo, rc rate and rc expo onto the PID tuning page from the receiver page where it currently is.  When taking screenshots of the these settings for use in forums it seems silly that they are on separate screens.  The current setup also makes it rather annoying when comparing profiles as the profile selection tab is on the PID page so there is much switching between pages needed.  

BTW: The "channel map" and "rssi on aux" tabs could go into the new configuration page.  Brilliant work so far guys!!!!!!

**Comment by therippa** [comment]
Wouldn't it make more sense to pull the profiles dropdown out of the PID tab and put it above the tabs themselves since it also affects modes, etc?

**Comment by athertop** [comment]
It would be nice to see specific selection for rate profiles too on the PID screen (separate from the main profile drop-down), also a way to copy/paste one profile to another. Only way I have found to select a specific rate profile (without affecting main profile) and display its settings in the GUI is to configure a 3 pos switch on the Tx, change the profile on the switch and refresh the PID screen to see the new values. Would be nice to be able to doi this in the GUI directly.

**Comment by hydra** [comment]
This is a GUI issue, please open GUI issues in the GUI tracker.  Closing.
