### ISSUE TITLE
Please add channel reverse in GUI

### ISSUE THREAD

**Issue by Gavin-Williams** [cleanflight/cleanflight#2599]
There doesn't seem to be any way to reverse channels, what I think should be a basic operation. As it is, I have to plug in my programming cable and invert them in the controller (TX) software just to switch between my quad and the simulator. EVERY TIME. It's so frustrating. If Cleanflight allowed reversing the channels, I wouldn't have to do that.

**Comment by stronnag** [comment]
Doesn't rxrange work for you?
https://github.com/cleanflight/cleanflight/blob/master/docs/Rx.md

**Comment by hydra** [comment]
rxrange is the solution.
