### ISSUE TITLE
'Pass-through' mode does not disable twin motor stabilization.  

### ISSUE THREAD

**Issue by wojciechwas** [cleanflight/cleanflight#2601]
Custom airplane with 2 motors stabilization is always on. 
In pass through mode it should be disabled to allow full manual control. 
At least the stabilization should not be as 'head hold'. 
(Tested on Naze32 rev6c and a custom airplane with 2 motors)

**Comment by hydra** [comment]
please provide a cli dump

**Comment by wojciechwas** [comment]
I hope this helps. For the time being I had to use Inav that has yaw stab on motors always on but on lightly damped mode. 
[CleanflightSrttings_v0.1.txt](https://github.com/cleanflight/cleanflight/files/785433/CleanflightSrttings_v0.1.txt)
