### ISSUE TITLE
MSP_SET_RAW_RC: Yaw and throttle channels swapped

### ISSUE THREAD

**Issue by christianrauch** [cleanflight/cleanflight#2603]
The original order of channels in the `MSP_SET_RAW_RC` message is defined as:

1. ROLL
2. PITCH
3. YAW 
4. THROTTLE
5. ... 8. AUX1 ... AUX4

(http://www.multiwii.com/wiki/index.php?title=Multiwii_Serial_Protocol)

According to this order, I should be able to arm via sending the array:
[1500, 1500, **2000**, **1000**, 1000, 1000, 1000, 1000]
This does work for MultiWii 2.4 but not for cleanflight 1.14.2

However, I can only arm cleanflight by swapping the yaw and throttle channels:
[1500, 1500, **1000**, **2000**, 1000, 1000, 1000, 1000]

**Comment by hydra** [comment]
likely the RC mapping you're using is wrong, did you check the CF code?

**Comment by hydra** [comment]
the default map in CF comes from this line of code:

`parseRcChannels("AETR1234", rxConfig());`

see `config.c`

use MSP_SET_RX_MAP once to set the correct mapping before using MSP_SET_RAW_RC and you'll be fine.

**Comment by christianrauch** [comment]
I am referring to the original definition of `MSP_SET_RAW_RC` at http://www.multiwii.com/wiki/index.php?title=Multiwii_Serial_Protocol. The order of channels is fixed in this definition and is independent from the physical remote control mode.

Shouldn't the MSP implementation in cleanflight follow this definition?

**Comment by hydra** [comment]
it does, but then due to the default mapping the channel order is changed.  msp rx is handled like any other rx protocol in CF and so the mapping applies in CF.

**Comment by christianrauch** [comment]
Sorry, I disagree. Compared to other RX protocols, the order of channels in `MSP_SET_RAW_RC` is very well defined.
I actually think that the channel mapping should be done in CF to assure that channels in `MSP_SET_RAW_RC` are interpreted in the defined order. Otherwise all clients need to figure out the correct mapping by themselves.

E.g. see the wrong values send by the GUI control sticks. Both images show the left stick in the lower right corner (throttle 1000, yaw 2000) which should arm the Quad. Because of the wrong mapping (`AETR1234` as well `TAER1234`) it won't arm:
![aetr1234_mapping](https://cloud.githubusercontent.com/assets/8573621/22628316/bb36ee36-ebc9-11e6-9b55-5e7708eb1c43.png) 
![taer1234_mapping](https://cloud.githubusercontent.com/assets/8573621/22628322/cc422e48-ebc9-11e6-8401-1051ba7fcc6a.png)

This issue could be fixed by interpreting the MSP channels in the defined order.

**Comment by hydra** [comment]
no, then there would be two mappings.  

MSP RX is handled like all other RX protocols.  All RX protocols allow the TRANSMITTER to define the channel order and the FC to map the channels into the appropriate functions via the RX MAP.

We do not need nor want additional code or logic to do this when clients can use the API provided.

**Comment by hydra** [comment]
see also https://github.com/cleanflight/cleanflight/issues/2359#issuecomment-241808977
