### ISSUE TITLE
Battery voltage discrepancy between Configurator and Blackbox recording

### ISSUE THREAD

**Issue by willanth** [cleanflight/cleanflight#2607]
Setup is:

SPRacing F3 10DOF 
CleanFlight 1.14.2 Stable
Configurator 1.2.4
Blackbox Explorer Standalone 1.2.1

Connecting a benchtop power supply set to 12.0VDC, the configurator GUI as well as the CLI "status" command reports accurate voltage and cell count.

When replaying blackbox data the raw values seem to be correct, but the decoded values appear to be incorrect.  

Example:
CLI status reports raw value of 119 which is reported as 3S (correctly).  However Blackbox Explorer shows a raw value of 122, but a decoded 1.08V, and 1.08V/cell which is completely wrong.

Motivation:
I am attempting to log my pack voltage so that I can adjust the warnings appropriately.  I have been discharging my packs a bit too far lately and I would like to be able to check the logs and see how far through my flights the pack starts to sag.  This is not working very well with the software currently as it is not displaying information correctly.

Attached is a blackbox log.

I am unsure if this issue resides in the recorder, or the blackbox log software.  

[blackbox_log_2017-02-04_114231.TXT](https://github.com/cleanflight/cleanflight/files/752864/blackbox_log_2017-02-04_114231.TXT)

**Comment by hydra** [comment]
@willanth please do more investigation work to pinpoint the source of the error and report back when you have time.
