### ISSUE TITLE
SPRacingF3PDB/OSD with SPRacingF3EVO -OSD boot issues (Phase look loop)

### ISSUE THREAD

**Issue by JBlocks** [cleanflight/cleanflight#2609]
With regard to the closed ticket "SPRacingF3PDB/OSD with SPRacingF3EVO - Video and OSD Overlay issues" (https://github.com/cleanflight/cleanflight/issues/2594), new insights follow with the OSD and video problem.

The main problem is not the "RunCam Eagle" video camera, but actually the PDB / OSD with the software.

In use is a SPRacingF3PDB/OSD and a SPRacingF3EVO with the "Stackable Design". It is the latest CleanFlight version 1.14.2 installed on the SPRacingF3OSD and on the SPRacingF3EVO as well.

It is important that you look at Issue #2594  again before editing.

With an oscillograph I have the video signal tapped and made visible. The video shows the boot process of the SPRACINGF3OSD and it is clearly recognizable that it fails the synchronization (PLL phase look loop). It was tested with a connected camera and without camera, in order to rule out that it s.der the RunCam Eagle camera lies. After 20-60 seconds, the overlay will be shown and the video signal is quite stable. At different intervals the video signal breaks again and the process starts again and again.

Note: 
The video track from the oscilloscope and the video track from the TV is not exactly on top of each other, but it is clear to see what happens.

The problem seems to lie in the software of the OSD and that during the boot process.
**The video is available as ZIP archive on this ticket.**
A solution to the problem is absolutely desirable! The ODB is not usable.

*Attachment*
[SPRacingF3PDB_OSD-Issue-PLL-Video-Boot.zip](https://github.com/cleanflight/cleanflight/files/759265/SPRacingF3PDB_OSD-Issue-PLL-Video-Boot.zip)

**Comment by hydra** [comment]
It's probable you have a faulty board.  We've not experienced any issues like this when no camera is created.

What documentation specifically are your referring to with regards to the PLL.  Note that the MAX7456 chip is entirely responsible for generating the video output signal.

If you don't have any issues when the USB cable is plugged in this further points to a hardware issue as the MAX7456 is quite sensitive to the input voltage being within range.

Please produce a time/voltage graph of the the 5v inputs to the MAX7456 chip when:
a) powering via USB.
b) powering via Battery.
This will shed light on the situation. 

Refer to the datasheet for 5V inputs (PVDD, AVDD, DVDD).

https://datasheets.maximintegrated.com/en/ds/MAX7456.pdf

Also you can monitor the VSYNC/HSYNC/LOS and LOS outputs on the MAX7456.  That would also be interesting.

If you think you have a hardware problem then please contact your retailer and request an RMA, if you think it can be solved in software then I'm all ears but I currently can't see any solution.
