### ISSUE TITLE
PPm reciver on inav 1.6

### ISSUE THREAD

**Issue by jratha** [cleanflight/cleanflight#2636]
Hi guys,

I was interested in seeing the new updates in inav 1.6 so I flashed my spf3 Mini fc with the new firmware.

After flashing, I noticed that my roll, pitch and yaw were not working, I'm using ppm mode with an orange R615x receiver. I tried every possible combination of receiver set up and channel map that i could think of but nothing worked. I now re-flashed version 1.5.1 back on to my fc and everything is now working again

**Comment by stronnag** [comment]
Wrong repository. Please raise iNav bugs on the iNav tracker. FYI, Orange RX PPM is working OK on my SPRF3 (not mini) on iNav 1.6.
