### ISSUE TITLE
QUAD IS NOT ARMING 

### ISSUE THREAD

**Issue by anshul7997** [cleanflight/cleanflight#2649]
Hello sir ,
I am using naze 32 rev 5 10dof FC and 12A ESC BL-heli with flysky 2.4GHz transmitter and receiver. my quad is showing corresponding values in the receiver tab of the clean flight going from 1100 to 2000 but my quadcopter is not arming or quad motor doesn't start to rotate. please help me in this.

**Comment by tigert** [comment]
These issues are not meant for technical support (use the rcgroups forum or irc channel for that).

In any case, the low endpoint should be 1000, not 1100. Make sure you adjust the endpoints from the transmitter to be as close as 1000 - 1500 (midpoint) - 2000.
