### ISSUE TITLE
Gyro LPF bug

### ISSUE THREAD

**Issue by lou270** [cleanflight/cleanflight#2651]
Hi,

I am on spracing f3 evo with cleanflight 1.14.2.
I have a problem with gyro_lpf value. With default configuration (gyro_lpf=OFF), cpu usage is about 25% and the quad run correctly. But when I assign gyro_lpf = 188Hz, cpu usage increase to 70% and I can't control pitch and roll. I tried to go back with gyro_lpf=OFF but the problem do not disappear. 
The only solution I found is to reflash cleanflight with "full erase".

**Comment by hydra** [comment]
this is unlikely to be fixed due to lack of developer time as we are now developing on CF v2.0.0.
