### ISSUE TITLE
Align board yaw from GUI issue

### ISSUE THREAD

**Issue by Tabsy123** [cleanflight/cleanflight#266]
EDIT:  I realised rather than try to go to 270 alignment which gui does not allow, can go -90 and this works.  not really sure even if that was even a GUI issue or the firmware.  up and down buttons dont always work either

**Comment by fiveangle** [comment]
I've submitted a defect against CFC for this issue with suggested simple fix (sorry no PR - still getting my dev env setup):

https://github.com/cleanflight/cleanflight-configurator/issues/84

Please review and close this one if appropriate.

-=dave

**Comment by sophana** [comment]
Hi

When I set -90 for align_board_yaw, the motor get inverted: This means that when you set angle mode, hold the quad, spin the motors, and move it, the motors move in the same direction instead of opposite.
Setting the value to 90 works ok, except that it is not what I need.
I think this is a bug.

**Comment by thenickdude** [comment]
sophana, which direction does the forward arrow of your board point? If it's pointing to the right of the craft, 90 is the correct value. (also how is a setting that makes it work correctly "not what you need"?)

**Comment by sophana** [comment]
Initialy I've set the board in the right direction, and connected the motors accordingly.
I had problems accessing the usb port so I turned the board left and have set -90. 
But there, the motors are inverted and have to reconnect them.
This does not happen if I choose 90. I didn't reconnect the motors, but fly my quad in the opposite direction.

It seems strange to me that I have to reconnect my motors if I choose -90, but not with 90.

In all 3 values (0, -90 and 90), the quad animation in cleanflight configurator is ok. It is the just the wiring of the motors that change at -90.

Would 270 fix that problem?

**Comment by thenickdude** [comment]
Just to clarify, which side of your craft did the USB port stick out of when you set it to -90? Naze32, right?

**Comment by sophana** [comment]
it is a flip32 (the same).
turning to the left, the usb port is on the right.

**Comment by sophana** [comment]
I have just tested 270, it is the same as -90, the quad crashes because of inverted motors.
I think it is a bug, the quad should fly whatever value in Align board yaw.

To test it, simply set -90, hold the quad and apply throttle, you will see the problem.

**Comment by hydra** [comment]
Closing, open a GUI issue in the other tracker if needed, there are 3 other issues that deal with board alignment issues #8 #272 #712 #290

**Comment by Archon03** [comment]
This is still a bug (both in Cleanflight and the GUI).  When "Yaw Adjustment" and "Pitch Adjustment" are both set I get different results in rate mode versus Horizon/Angle modes.  It seems as though pitch is adjusted after yaw in rate mode, but before in Angle/Horizon mode.  So in Angle/Horizon I have to apply the adjustment as "Roll Adjustment" instead of "Pitch Adjustment."  This prevents me from being able to toggle modes with angled motor mounts installed.

**Comment by hydra** [comment]
@Archon03 Please open a new issue and fully describe the symptoms since your issue is not related to a GUI issue.

**Comment by hydra** [comment]
@Archon03 The angle and horizon modes are unrelated to the sensor/board alignment settings.  The board alignment matrix is used DIRECTLY after reading each sensor.  So all flight modes will be using the same data.

See

https://github.com/cleanflight/cleanflight/blob/4fcecbd6674160bc872690f7fab2b492ada95bb1/src/main/sensors/boardalignment.c#L54

Called by 

https://github.com/cleanflight/cleanflight/blob/4fcecbd6674160bc872690f7fab2b492ada95bb1/src/main/sensors/boardalignment.c#L65

Called by

https://github.com/cleanflight/cleanflight/blob/27db9ad0fe9a4d8abc05c59db201b8944324eea4/src/main/sensors/compass.c#L75
https://github.com/cleanflight/cleanflight/blob/27db9ad0fe9a4d8abc05c59db201b8944324eea4/src/main/sensors/gyro.c#L123
https://github.com/cleanflight/cleanflight/blob/27db9ad0fe9a4d8abc05c59db201b8944324eea4/src/main/sensors/acceleration.c#L175

See

https://github.com/cleanflight/cleanflight/search?utf8=%E2%9C%93&q=alignSensors
