### ISSUE TITLE
Silabs drivers

### ISSUE THREAD

**Issue by Carlos1301** [cleanflight/cleanflight#2670]
Hello,
No matter what I do, I don't seem to be able to run Cleanflight on my laptop due to the drivers. I installed them but as soon as I try to connect I get a message saying that Windows does not recognize the driver.
I have a Lenovo E460 running Windows 7 professional. I am trying to connect a Vortex 150. It has an STM32F303 based ('F3') FC.
Any help would be really appreciated.
Thanks.

**Comment by lichtl** [comment]
Hmm I think for the vortex you will need the STM32 VCP driver

**Comment by Carlos1301** [comment]
I have tried that one too and nothing....

**Comment by SteveAmor** [comment]
@Carlos1301 Please close this issue.  The Github issue track is not for end-user support.

**Comment by Carlos1301** [comment]
Ok. I will close it. Could you tell me then where I can get some help?
Thanks.
