### ISSUE TITLE
Roll & Pitch Rate on PID 1 

### ISSUE THREAD

**Issue by Tabsy123** [cleanflight/cleanflight#268]
Unlike PId controller 0 where roll and pitch rate is only added from approx 50% or more roll and pitch stick movment.
When On pid controller 1 roll and pitch rate is basicly like adjusting rc rate but way more sensitive, changes happen even from middle stick subtle movments. this may not be a error as such but it is not ideal and is just like having 2 rc rate adjustments.

**Comment by hydra** [comment]
what do you suggest is done?  This issue isn't currently well-titled.

**Comment by hydra** [comment]
Blocked until a suggestion on what to do is provided.

**Comment by hydra** [comment]
Closing, no suggestion provided.
