### ISSUE TITLE
BLHeliSuite passthrough not working with CleanFlight 2.x

### ISSUE THREAD

**Issue by McGiverGim** [cleanflight/cleanflight#2682]
I can't connect to the ESC from BLHeliSuite version 2.x using the CleanFlight passthrough, it appears this message:

![image](https://cloud.githubusercontent.com/assets/2673520/24493801/55e0df8e-1530-11e7-9b11-cdf76a99ed54.png)

If I flash CleanFlight 1.4.2 then I can connect without problem.

My setup is a NAZE32 REV6 10DOF with Littlebee fvt Opto Pro 20A ESC.

**Comment by hydra** [comment]
@4712 can you have a look into this?

**Comment by McGiverGim** [comment]
I've tested a 2.x version from some days ago and the BLHeliSuite passthrough worked again. So some of the recents commits have breaked it.

**Comment by McGiverGim** [comment]
@hydra @4712 I think I've found the commit who introduce the problem:
https://github.com/cleanflight/cleanflight/commit/ab2b1188cfeedd38a7781dad93ae1902b0736f09

Maybe some of the commands cleaned is used by BLHeliSuite?

Regards!

**Comment by 4712** [comment]
@McGiverGim @hydra: removing MSP_MISC introduced it... I need to switch to MSP_MOTOR_CONFIG I guess.

**Comment by hydra** [comment]
@4712 yes that's likely.  we're removing all the old crufty MSP commands from CF (and BF).  Likely the change in the BlHeliSuite should be simple enough.  Are you able to do it?

**Comment by 4712** [comment]
@hydra Sure, asap.

**Comment by McGiverGim** [comment]
@4712 I will test it as soon you have the first version ;)

Regards!

**Comment by 4712** [comment]
Fixed in [BLHeliSuite 16..6.14.9.0.1](https://www.mediafire.com/folder/dx6kfaasyo24l/BLHeliSuite)

**Comment by McGiverGim** [comment]
@4712 Tested and working ;)

I close the issue.

Thanks!
