### ISSUE TITLE
Flight - GPS Assisted Mode

### ISSUE THREAD

**Issue by uk-Pedro** [cleanflight/cleanflight#270]
HI,

I tried GPS Hold today (27th December) with the 14th December firmware with GPS improvements. Much better than previous versions. Thanks to whoever took the time to make the improvements that were needed. I had 9 sats and it held position to within about 2m whereas previously this was more like 12m or not at all.

The feature does exactly what it says it will do, i.e. "hold", as in when I hover in a position and flick the GPS Hold switch it tries to maintain its position. If I then apply some pitch to force it away from it's hold position, when I release the pitch it will try to recover it's hold position. 
Is there a way to make it behave more like a helper, whereby when in "GPS Assisted" mode if all sticks are released it will hold the position where the sticks were released?

Thanks

**Comment by Exidouce** [comment]
That would be a great idea, update the stored coordinates once sticks are centered.

**Comment by andymac4182** [comment]
Are you looking for something like this @uk-Pedro ? https://www.youtube.com/watch?v=3D8BzaadYoI

**Comment by uk-Pedro** [comment]
That's awesome - YES!

**Comment by strips** [comment]
+1

This is the way it works in Harakiri. The same as Loiter in ArduCopter.

**Comment by andymac4182** [comment]
Position hold + baro = Loiter from APM. 
What is in OpenPilot is loiter when doing nothing but acro/angle/horizon mode the moment you move your sticks

**Comment by hydra** [comment]
Need better GPS PH first, see #197

**Comment by digitalentity** [comment]
I'm happy to announce a very first public beta of my navigation-rewrite for Cleanflight featuring better altitude and position hold, better RTH and GPS-assisted flight modes. Please have a look at my post at [RCG](http://www.rcgroups.com/forums/showthread.php?t=2495732)
