### ISSUE TITLE
 Failed to open serial port error 

### ISSUE THREAD

**Issue by radioflyerrick** [cleanflight/cleanflight#2712]
I am having an issue with trying to connect my QX90 and 95 - The date and  Failed to open serial port comes up, doesnt even want to try... I have tried to update the drivers, I put all three of the download suggestion drivers, I have run through most fixes.. can anyone tell me how I can get this to work, as it would seem its not a BNF as it says.. it wont fly without the programming... 
So any help would be good, suggestions, fixes or whatever, I have a specktrum DX6e controller... 
Thanks

**Comment by hydra** [comment]
please see the contributing guide before creating issues.  use rcgroups for support, the issue tracker is for issues, not for support.
