### ISSUE TITLE
Naze32 cleanflight ver.2.0 GPS not work

### ISSUE THREAD

**Issue by stanislavdimov** [cleanflight/cleanflight#2716]
After flash new ver 2.0 GPS 'U-blox NEO M8N" do not work! With cleanflight ver 1.14.2 work perfect!

**Comment by McGiverGim** [comment]
Gps has been deactivated you can activate it in your own version https://github.com/cleanflight/cleanflight/blob/master/docs/Customized%20Version.md

**Comment by stanislavdimov** [comment]
To be flight with CF on copter I must study programing? Thanks, thanks.....!

**Comment by McGiverGim** [comment]
No. In a NAZE there is no space for new features. You can continue with version 1 and have gps, or use version 2 to have new features deactivating others. You decide.

**Comment by hbouzas** [comment]
Guys, see my blog for an explanation on how to solve this issue. Step by step. 
www.horaciobouzas.com
