### ISSUE TITLE
Define of SONAR_TRIGGER_PIN_PWM not used in CF 2.0

### ISSUE THREAD

**Issue by S-Klann-DEV** [cleanflight/cleanflight#2717]
SONAR_TRIGGER_PIN_PWM-Pin is not used in the code. Sonar wont work if someone tries to use it.

**Comment by sandeeppahadi** [comment]
i have problem with sonar too. even though i turned sonar feature on its not turning into green. Oneshot125 esc is also not  working. everything was fine before upgrading. Can anyone give me solution?

**Comment by S-Klann-DEV** [comment]
To make the sonar working with pwm receiver:

Just define the motor pins M7 and M8 to the SONAR_TRIGGER_PIN and SONAR_ECHO_PIN.

`#define SONAR_TRIGGER_PIN       PB8`
`#define SONAR_ECHO_PIN          PB9`

**Comment by sandeeppahadi** [comment]
How to make sonar work on ppm mode?

**Comment by hydra** [comment]
Confusing defines removed in 690bedf11ef543b160916203cda042d9671b56dc.  If you need sonar on a naze32 you'll need to compile your own version.
