### ISSUE TITLE
Cleanflight - Configurator 2.0.0 can not use the BLHeliSuite connection problem

### ISSUE THREAD

**Issue by E120103016** [cleanflight/cleanflight#2725]
Today, the use of Configurator 2.0.0 and v2.0.0 program set up. Then BLHeliSuite set ESC. Can not use. 2.0.0 program is not set BLHeli Bootloader (cleanfight). How to solve this problem. Trouble Thank ...

**Comment by McGiverGim** [comment]
Update blheli suite to the latest version.

**Comment by stanislavdimov** [comment]
Cleanflight - Configurator new update can not use CF old ver /ver.1***/ with NAZE32 ver 6  /flash but not work/!?!?!?! Work only with new CF ver 2.0! But in new version CF do not have more GPS!
Cleanflight - Configurator old version no more work!
What we happy MrGiverGim?

**Comment by E120103016** [comment]
Today, BLHeli can be updated. Thank you very much the two predecessors. Thank you again!
