### ISSUE TITLE
feature LED_STRIP: turn on/off via TX

### ISSUE THREAD

**Issue by RandGH** [cleanflight/cleanflight#273]
It would be nice if LED_STRIP (and probably others as well) could be activated via AUX Chanel similar to Beeper et al.

**Comment by JurikRistjouw** [comment]
I think this is possible already by assigning LED_LOW to an aux channel in the modes tab? But could be I am missing your question.

**Comment by RandGH** [comment]
Well this is a possible solution;) The original request dates back from last year, not sure when LED_LOW made it in - 1.8x? ;)

**Comment by thenickdude** [comment]
Yep, this should now be supported by the LEDLOW flight mode, please reopen if that does not work for you. (Note that the "LEDMAX" and "LLIGHTS" flight modes don't currently do anything).
