### ISSUE TITLE
Link for "Documentation For 2.0.0" does not work properly.

### ISSUE THREAD

**Issue by Arbitrator** [cleanflight/cleanflight#2735]
It currently opens the browser to 'https://github.com/cleanflight/cleanflight/tree/v2.0.0/docs', with a 404 message 'This is not the web page you are looking for.'

**Comment by stanislavdimov** [comment]
Perhaps line in Documentation for Building in Eclipse.md
"Set your build and debug targets by going to project properties -> C/C++ Build and choose the Behaviour tab. Replace "all" in the build box with "TARGET=xxx DEBUG=GDB" where xxx is your platform such as NAZE"
change with
"Set your build and debug targets by going to project properties -> C/C++ Build and choose the Behaviour tab. Replace "all" in the build box with "make TARGET=xxx DEBUG=GDB" where xxx is your platform such as NAZE"
or not?

**Comment by hydra** [comment]
Thaks for the report. I will take a look.

**Comment by hydra** [comment]
fixed in latest configurator master - wait for CF configurator v2.0.1.
