### ISSUE TITLE
Reverse Motor direction

### ISSUE THREAD

**Issue by RandGH** [cleanflight/cleanflight#274]
It would be nice if there was an option to be able to reverse the required motor direction similar to Open Pilot, this would enable migration between cc3d with OP/cf without having to resolder if coming from OP.

Additionally free assignment of motor channels to motors similar to OP would be awesome as well.

**Comment by 11digits** [comment]
Hi there, is there a way to reverse just 1 channel? (like the Pitch in my case) ?  
My TX has the pitch reversed --- due to a non configurable controller

**Comment by joshuabardwell** [comment]
You're talking about inverting an input channel, not reversing a motor direction, I think.

**Comment by 11digits** [comment]
Yes, you are right... I confused myself. I want to be able to reverse the input channel.
