### ISSUE TITLE
Current sensor not working 

### ISSUE THREAD

**Issue by kcunreal** [cleanflight/cleanflight#2740]
For some reason I cannot get current telemetry on my Taranis. I am able to get VBatt telemitry, but no current info. Dump file below...

Any help would be appreciated.

CLI

# dump
# Cleanflight / NAZE 2.0.0 Apr 13 2017 / 00:49:44 (b6a7f7a)
name QAV250
resource BEEPER 1 A12
resource MOTOR 1 A08
resource MOTOR 2 A11
resource MOTOR 3 B06
resource MOTOR 4 B07
resource MOTOR 5 B08
resource MOTOR 6 B09
resource MOTOR 7 NONE
resource MOTOR 8 NONE
resource MOTOR 9 NONE
resource MOTOR 10 NONE
resource MOTOR 11 NONE
resource MOTOR 12 NONE
resource SERVO 1 NONE
resource SERVO 2 NONE
resource SERVO 3 NONE
resource SERVO 4 NONE
resource SERVO 5 NONE
resource SERVO 6 NONE
resource SERVO 7 NONE
resource SERVO 8 NONE
resource PPM 1 A00
resource PWM 1 A00
resource PWM 2 A01
resource PWM 3 A02
resource PWM 4 A03
resource PWM 5 A06
resource PWM 6 A07
resource PWM 7 B00
resource PWM 8 B01
resource LED_STRIP 1 A06
resource SERIAL_TX 1 NONE
resource SERIAL_TX 2 NONE
resource SERIAL_TX 3 NONE
resource SERIAL_TX 4 NONE
resource SERIAL_TX 5 NONE
resource SERIAL_TX 6 NONE
resource SERIAL_TX 7 NONE
resource SERIAL_TX 8 NONE
resource SERIAL_TX 9 NONE
resource SERIAL_TX 10 NONE
resource SERIAL_TX 11 A07
resource SERIAL_TX 12 B01
resource SERIAL_RX 1 NONE
resource SERIAL_RX 2 NONE
resource SERIAL_RX 3 NONE
resource SERIAL_RX 4 NONE
resource SERIAL_RX 5 NONE
resource SERIAL_RX 6 NONE
resource SERIAL_RX 7 NONE
resource SERIAL_RX 8 NONE
resource SERIAL_RX 9 NONE
resource SERIAL_RX 10 NONE
resource SERIAL_RX 11 A06
resource SERIAL_RX 12 B00
mixer QUADX

mmix reset

servo 0 1000 2000 1500 -1 0
servo 1 1000 2000 1500 -1 0
servo 2 1000 2000 1500 -1 0
servo 3 1000 2000 1500 -1 0
servo 4 1000 2000 1500 -1 0
servo 5 1000 2000 1500 -1 0
servo 6 1000 2000 1500 -1 0
servo 7 1000 2000 1500 -1 0
smix reset

feature -RX_PPM
feature -VBAT
feature -INFLIGHT_ACC_CAL
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -FAILSAFE
feature -SONAR
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DISPLAY
feature -OSD
feature -UNUSED
feature -CHANNEL_FORWARDING
feature -TRANSPONDER
feature -AIRMODE
feature -SDCARD
feature -VTX
feature -RX_SPI
feature -SOFTSPI
feature -ESC_SENSOR
feature -ANTI_GRAVITY
feature VBAT
feature RX_SERIAL
feature MOTOR_STOP
feature SOFTSERIAL
feature FAILSAFE
feature TELEMETRY
beeper GYRO_CALIBRATED
beeper RX_LOST
beeper RX_LOST_LANDING
beeper DISARMING
beeper ARMING
beeper ARMING_GPS_FIX
beeper BAT_CRIT_LOW
beeper BAT_LOW
beeper GPS_STATUS
beeper RX_SET
beeper ACC_CALIBRATION
beeper ACC_CALIBRATION_FAIL
beeper READY_BEEP
beeper MULTI_BEEPS
beeper DISARM_REPEAT
beeper ARMED
beeper SYSTEM_INIT
beeper ON_USB
beeper BLACKBOX_ERASE
map TAER1234
serial 0 1 115200 57600 0 115200
serial 1 64 115200 57600 0 115200
serial 30 32 115200 57600 0 115200
serial 31 0 115200 57600 0 115200
led 0 15,15:ES:AI:0
led 1 15,8:E:FW:0
led 2 15,7:E:FW:0
led 3 15,0:NE:AI:0
led 4 8,0:N:F:0
led 5 7,0:N:F:0
led 6 0,0:NW:AI:0
led 7 0,7:W:FW:0
led 8 0,8:W:FW:0
led 9 0,15:SW:AI:0
led 10 7,15:S:FW:0
led 11 8,15:S:FW:0
led 12 7,7:U:FW:0
led 13 8,7:U:FW:0
led 14 7,8:D:FW:0
led 15 8,8:D:FW:0
led 16 8,9::R:3
led 17 9,10::R:3
led 18 10,11::R:3
led 19 10,12::R:3
led 20 9,13::R:3
led 21 8,14::R:3
led 22 7,14::R:3
led 23 6,13::R:3
led 24 5,12::R:3
led 25 5,11::R:3
led 26 6,10::R:3
led 27 7,9::R:3
led 28 0,0::C:0
led 29 0,0::C:0
led 30 0,0::C:0
led 31 0,0::C:0
color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 0,0,0
color 15 0,0,0
mode_color 0 0 1
mode_color 0 1 11
mode_color 0 2 2
mode_color 0 3 13
mode_color 0 4 10
mode_color 0 5 3
mode_color 1 0 5
mode_color 1 1 11
mode_color 1 2 3
mode_color 1 3 13
mode_color 1 4 10
mode_color 1 5 3
mode_color 2 0 10
mode_color 2 1 11
mode_color 2 2 4
mode_color 2 3 13
mode_color 2 4 10
mode_color 2 5 3
mode_color 3 0 8
mode_color 3 1 11
mode_color 3 2 4
mode_color 3 3 13
mode_color 3 4 10
mode_color 3 5 3
mode_color 4 0 7
mode_color 4 1 11
mode_color 4 2 3
mode_color 4 3 13
mode_color 4 4 10
mode_color 4 5 3
mode_color 5 0 9
mode_color 5 1 11
mode_color 5 2 2
mode_color 5 3 13
mode_color 5 4 10
mode_color 5 5 3
mode_color 6 0 6
mode_color 6 1 10
mode_color 6 2 1
mode_color 6 3 0
mode_color 6 4 0
mode_color 6 5 2
mode_color 6 6 3
mode_color 6 7 6
mode_color 6 8 0
mode_color 6 9 0
mode_color 6 10 0
mode_color 7 0 3
aux 0 0 0 1850 2100
aux 1 28 1 1300 1700
aux 2 0 0 900 900
aux 3 0 0 900 900
aux 4 0 0 900 900
aux 5 0 0 900 900
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900
adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0
adjrange 12 0 0 900 900 0 0
adjrange 13 0 0 900 900 0 0
adjrange 14 0 0 900 900 0 0
rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000
rxfail 0 a
rxfail 1 a
rxfail 2 a
rxfail 3 a
rxfail 4 h
rxfail 5 h
rxfail 6 h
rxfail 7 h
rxfail 8 h
rxfail 9 h
rxfail 10 h
rxfail 11 h
rxfail 12 h
rxfail 13 h
rxfail 14 h
rxfail 15 h
rxfail 16 h
rxfail 17 h
set align_gyro = DEFAULT
set gyro_lpf = 188HZ
set gyro_sync_denom = 3
set gyro_lowpass_type = PT1
set gyro_lowpass = 90
set gyro_notch1_hz = 400
set gyro_notch1_cutoff = 300
set gyro_notch2_hz = 200
set gyro_notch2_cutoff = 100
set moron_threshold = 32
set gyro_use_32khz = OFF
set gyro_isr_update = OFF
set align_acc = DEFAULT
set acc_hardware = NONE
set acc_lpf_hz = 10
set acc_trim_pitch = 12
set acc_trim_roll = 56
set align_mag = DEFAULT
set mag_hardware = NONE
set mag_declination = 0
set magzero_x = 0
set magzero_y = 0
set magzero_z = 0
set baro_hardware = NONE
set baro_tab_size = 21
set baro_noise_lpf = 0
set baro_cf_vel = 0
set baro_cf_alt = 0
set mid_rc = 1500
set min_check = 1000
set max_check = 2000
set rssi_channel = 7
set rssi_scale = 30
set rssi_invert = OFF
set rc_interp = AUTO
set rc_interp_ch = RP
set rc_interp_int = 19
set fpv_mix_degrees = 0
set max_aux_channels = 6
set serialrx_provider = SBUS
set sbus_inversion = ON
set spektrum_sat_bind = 0
set spektrum_sat_bind_autoreset = 1
set airmode_start_throttle = 1350
set rx_min_usec = 885
set rx_max_usec = 2115
set input_filtering_mode = OFF
set blackbox_rate_num = 1
set blackbox_rate_denom = 1
set blackbox_device = SERIAL
set blackbox_on_motor_test = OFF
set min_throttle = 1080
set max_throttle = 2000
set min_command = 1000
set use_unsynced_pwm = OFF
set motor_pwm_protocol = ONESHOT125
set motor_pwm_rate = 400
set motor_pwm_inversion = OFF
set thr_corr_value = 0
set thr_corr_angle = 800
set failsafe_delay = 10
set failsafe_off_delay = 200
set failsafe_throttle = 1200
set failsafe_kill_switch = OFF
set failsafe_throttle_low_delay = 100
set failsafe_procedure = DROP
set align_board_roll = 0
set align_board_pitch = 0
set align_board_yaw = 0
set gimbal_mode = NORMAL
set bat_capacity = 1300
set vbat_max_cell_voltage = 42
set vbat_min_cell_voltage = 35
set vbat_warning_cell_voltage = 38
set vbat_hysteresis = 1
set current_meter = ESC
set battery_meter = ADC
set bat_detect_thresh = 55
set use_vbat_alerts = ON
set use_cbat_alerts = OFF
set cbat_alert_percent = 10
set vbat_scale = 110
set ibata_scale = 400
set ibata_offset = 0
set beeper_inversion = ON
set beeper_od = OFF
set beeper_frequency = 0
set yaw_motors_reversed = OFF
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set 3d_deadband_throttle = 50
set servo_center_pulse = 1500
set servo_pwm_rate = 50
set servo_lowpass_hz = 0
set tri_unarmed_servo = ON
set channel_forwarding_start = 4
set reboot_character = 82
set serial_update_rate_hz = 100
set accxy_deadband = 40
set accz_deadband = 40
set acc_unarmedcal = ON
set imu_dcm_kp = 2500
set imu_dcm_ki = 0
set small_angle = 25
set auto_disarm_delay = 5
set disarm_kill_switch = ON
set gyro_cal_on_first_arm = OFF
set fixedwing_althold_reversed = OFF
set alt_hold_deadband = 40
set alt_hold_fast_change = ON
set deadband = 8
set yaw_deadband = 4
set yaw_control_reversed = OFF
set pid_process_denom = 1
set tlm_switch = OFF
set tlm_inversion = ON
set sport_halfduplex = ON
set frsky_default_lat = 0
set frsky_default_long = 0
set frsky_gps_format = 0
set frsky_unit = IMPERIAL
set frsky_vfas_precision = 0
set frsky_vfas_cell_voltage = OFF
set hott_alarm_int = 5
set pid_in_tlm = OFF
set ibus_report_cell_voltage = OFF
set ledstrip_visual_beeper = OFF
set task_statistics = ON
set debug_mode = NONE
profile 0

set d_lowpass_type = BIQUAD
set d_lowpass = 100
set d_notch_hz = 260
set d_notch_cut = 160
set vbat_pid_gain = OFF
set pid_at_min_throttle = ON
set anti_gravity_thresh = 350
set anti_gravity_gain = 1000
set setpoint_relax_ratio = 100
set d_setpoint_weight = 60
set yaw_accel_limit = 100
set accel_limit = 0
set iterm_windup = 50
set yaw_lowpass = 0
set pidsum_limit = 500
set pidsum_limit_yaw = 400
set p_pitch = 54
set i_pitch = 60
set d_pitch = 27
set p_roll = 45
set i_roll = 60
set d_roll = 23
set p_yaw = 42
set i_yaw = 35
set d_yaw = 23
set p_alt = 50
set i_alt = 0
set d_alt = 0
set p_level = 30
set i_level = 40
set d_level = 60
set p_vel = 100
set i_vel = 45
set d_vel = 1
set level_sensitivity = 55
set level_limit = 55
rateprofile 0

set rc_rate = 80
set rc_rate_yaw = 100
set rc_expo = 62
set rc_yaw_expo = 0
set thr_mid = 50
set thr_expo = 0
set roll_srate = 70
set pitch_srate = 70
set yaw_srate = 70
set tpa_rate = 20
set tpa_breakpoint = 1500

#

**Comment by hydra** [comment]
please use rcgroups, slack, irc for help - raise issues when a steps to repeat or confirmed bugs are found.  probably just a misconfiguration or wiring issue.  check usual documentation sources.
