### ISSUE TITLE
Spektrum RX issue

### ISSUE THREAD

**Issue by ripley123** [cleanflight/cleanflight#2741]
I'm running a lemon rx satellite receiver and a spektrum DX6 as well as an SPF3. I was able to bind the DX6 to the satellite using the cleanflight CLI however none of my stick inputs show up under the receiver tab.

I used: set spektrum_sat_bind=7 (DSMX 1024 22ms)

![uart](https://cloud.githubusercontent.com/assets/27743053/25152912/7c34914e-243f-11e7-968a-603b1910801b.PNG)
![receiver](https://cloud.githubusercontent.com/assets/27743053/25152911/7c32e9a2-243f-11e7-9354-f1410c5c2035.PNG)

**Comment by hydra** [comment]
please use forums for support, probably a configuration issue.  we're not aware of any issues with spektrum rx.

**Comment by hydra** [comment]
another user just posted an issue (#2746) stating that they can see receiver input from a spektrum rx and an SPRacingF3 and had no issues seeing stick movements on the RX tab.  likely you just have a configuration issue.  please use forums for support, if you still have an issue please open a new issue and reference this one.
