### ISSUE TITLE
Battery status incorrect. Battery level detection does not work on SPEV (QX70)

### ISSUE THREAD

**Issue by rbekkers** [cleanflight/cleanflight#2747]
Hi,

I noticed that my low battery detection did not work. The LED strip kept blinking pink. In the configurator the battery voltage is correct but the status is not connected. In CLI the status shows:
\# status
System Uptime: 920 seconds
Voltage: 41 * 0.1V (0S battery - NOT PRESENT)
CPU Clock=72MHz, GYRO=MPU6500, ACC=MPU6500
SD card: Startup failed
Stack size: 2048, Stack address: 0x10002000
I2C Errors: 1, config size: 1923, max available config: 4096
CPU:14%, cycle time: 132, GYRO rate: 7575, RX rate: 49, System rate: 9

\# version
\# Cleanflight / SPRACINGF3EVO 2.0.1 Apr 19 2017 / 00:39:07 (229d76a)

![screenshot_2017-04-19_23-42-43s](https://cloud.githubusercontent.com/assets/27829454/25251000/16a0ed20-2618-11e7-9bfe-98ae9295fa27.png)

As you can see the voltage is correct, but for some reason the battery is 0S and NOT PRESENT. 

Any idea what can be the cause?
Please let me know if I can help with additional information.

Thanks,
Rob

**Comment by hydra** [comment]
yes. set `bat_detect_thresh` lower.  the default is 5.5v (`55`)  if you're on 1S/2S you may want to reduce this to about 2v (`20`)  From your detected voltage it looks like you're using 1S.

**Comment by hydra** [comment]
Please use rcgroups for support in future.

**Comment by rbekkers** [comment]
You were so right. Thank you very much.

2017-04-20 23:37 GMT+02:00 Dominic Clifton <notifications@github.com>:
