### ISSUE TITLE
Telemetry settings on SpracingF3neo wrong by default

### ISSUE THREAD

**Issue by dschiedsch** [cleanflight/cleanflight#2749]
A clean install of CF 2.0.1 didn't give any telemetry on my XSR receiver with S.Port connected.
I found out that the defaults for 
sport_halfduplex and
tlm_inversion are set to OFF by default
For S.Port telemetry to work these should be set to ON
Since the XSR receiver is the default receiver for the SpracingF3Neo board I would suggest setting these to ON by default

**Comment by hydra** [comment]
I'll take a look at that,  yes it makes sense due to the support for the XSR connector.

**Comment by hydra** [comment]
Done, see #2751
