### ISSUE TITLE
def_generated.pl lost

### ISSUE THREAD

**Issue by ledvinap** [cleanflight/cleanflight#2762]
I just noticed that def_generated.pl (https://github.com/cleanflight/cleanflight/blob/master_v1.x/src/utils/def_generated.pl) got removed from repository. It is IMO bad idea, it is much easier to maintain 161lines of quite simple templates instead of 1030 lines of generated code.

Should I resurrect it into `src/utils` or is there better place?

**Comment by hydra** [comment]
yes PR to resurrect it in the same place or if you have a preference for a new location that's also fine.
