### ISSUE TITLE
Add support for disabling the UART1 port on the OSD for SPRacingF3(Acro/Deluxe) + SPRacingF3OSD/PDB users

### ISSUE THREAD

**Issue by hydra** [cleanflight/cleanflight#2767]
Use cause:
user has SPRACINGF3 ACRO/DELUXE
user wants to configure motors.
user powers OSD + FC + ESCS via battery.

what happens now is that the user is unable to configure the FC because the OSD is using UART1 connected to UART1 on the FC via stacking pins which means that UART1 on the FC cannot be used by the configurator.

4 workarounds are currently possible.
a) unstack the FC from the OSD.
b) on the FC add MSP to another serial port, use a USB -> serial adapter to connect to the FC via a different serial port.
c) put the OSD in bootloader mode, then configure FC as usual - keeps the bus-switch disabled.
d) erase the firmware on the OSD so that the bus switch is never enabled, put firmware back after configuring ESCs.

suggested implementations:
a) add button to UI so the next time the OSD powers on the bus switch is not enabled - a bit like spektrum bind currently does.
b) add buttons the UI to enable/disable bus-switch.

note: this does not apply to SPRACINGF3EVO/SPRACINGF4EVO because they do not share UART1 with the USB connector on the FC.

**Comment by ratmole** [comment]
is there any update about this  enhancement?
Asking because i have a SPRACINGF3 + SP RacingF3 OSD/PDB and it's a little bit annoying to unstack the FC from the OSD...

**Comment by mikeller** [comment]
@ratmole: Have you tried option c):

> c) put the OSD in bootloader mode, then configure FC as usual - keeps the bus-switch disabled.

Just pushing the boot button on the SPRACINGF3OSD board when powering up seems to be the least involved of the options listed.

**Comment by ratmole** [comment]
FYI, there is no boot button soldered on my board.
great tip, i will add one on the board :)
thanks.

**Comment by hydra** [comment]
closing due to lack of demand.  If you want this feature please add a 👍 to the original post and comment here.
