### ISSUE TITLE
Sonar seems to be disabled for NAZE32

### ISSUE THREAD

**Issue by Fl0h0** [cleanflight/cleanflight#2772]
I switched on sonar in the configuration tab and saved it to the naze32(Firmware version 2.0.2) but it never seemed to be active. After some research it seems to be disabled because it is commented out in the file: cleanflight/src/main/target/NAZE/target.h

**Comment by McGiverGim** [comment]
Yes, it has been removed for space constraints. If you need it you must compile your own firmware.

**Comment by Fl0h0** [comment]
Ok I will do that.
Thanks for your reply.
