### ISSUE TITLE
Softserial and FrSky telemetry does'nt work anymore

### ISSUE THREAD

**Issue by m3us** [cleanflight/cleanflight#2773]
# A - Description

-- Softserial and FrSky telemetry does'nt work anymore on SPracingF3 Cf2.0.3

# B - Steps To Repeat

-- Turn on softserial, connect telemetry pin to soft serial port.Tried using telemetry_inversion in cli but didnt work.

The telemetry works on USART though. I am using that now but I thought i'd let you guys know about this issue.

**Comment by hydra** [comment]
you're using the incorrect command, it's tlm_inversion now.  please pay attention to the get/set command output.

**Comment by hydra** [comment]
also, you can use the slack group for support, see http://cleanflight.com/slack

**Comment by m3us** [comment]
I am aware of the change but tlm_inversion is on and yet there is no telemetry
