### ISSUE TITLE
Add option to change OSD preview ratio (4:3/16:9)

### ISSUE THREAD

**Issue by tonipalmgren** [cleanflight/cleanflight#2774]
OSD preview is in 4:3 without an option to change the ratio. At the moment, the top of the image is in the right place, but bottom will be cut out when using a 16:9 camera/VTX. Slider (or maybe a radio button) to change between 4:3 and 16:9 would be a nice addition. 

Cleanflight: v2.1.0, built from master branch, 30th of April
Configurator: 2.0.3

**Comment by hydra** [comment]
Note something we're likely to implement, if you want to have a go at it please submit a PR.
