### ISSUE TITLE
Tricopter Yaw Servo Configuration

### ISSUE THREAD

**Issue by bobthemac** [cleanflight/cleanflight#2775]
# A - Description

I have a tricopter and it worked before the update to 2.0.x I pluged it in to check some settings and got prompted to update so I did. Once updated the servo becomes unresponsive there is no signal sent to the servo. I am using a SPracingF3 Evo. Tested versions 2.0.0, 2.0.1, 2.0.2. It works fine in 1.14.2.

# B - Steps To Repeat

Upgrade to 2.0.x then apply yaw the tail servo will not move 

# E - Version Information

Cleanflight: 2.0.X or commit SHA
Configurator: 2.0.3 or commit SHA

# E - Other information

OS: Debian Linux

**Comment by hydra** [comment]
hi, your steps to repeat are not sufficient.  

how are you configuring the mixer?

can you provide a config dump.

it's likely you're running into a mixer configuration issue.  See also https://github.com/cleanflight/cleanflight/issues/2764

**Comment by bobthemac** [comment]
I just set the model type to tricopter in the configuration tab.  Looking at the other issue if tricopters are seen as uncommon mixers that would explain it. I will have to take some time to get a dump as I reverted to 1.4.2 firmware as I know that works, I will have to re-flash and setup again.

**Comment by lrodorigo** [comment]
Same problem here.
I also tried to remap SERVO 6 (default output for tricopter yaw) to MOTOR 4-8 but resource command seems to don't have any effect (_resource_ command show my new mapping but _dump_ command is still to **SERVO 6 NONE**).

**Comment by lunebleue** [comment]
Hello, I have the same FC and using it with a tricopter I had to type this in CLI to put servo on output 4.

resource MOTOR 4 NONE
resource SERVO 1 A03
save

It took me a while as in motor tab in GUI I see it moving on servo 6 bar but in fact it is **S1** for yaw servo...

**Comment by mikeller** [comment]
@lrodorigo: You have to remap servo 1 (and not servo 6) for a tricopter's yaw servo. (I know, tail servo is 'servo slot 6', but that gets mapped to servo 1, it _is_ confusing.)

Resources get initialised in numerical order, up to the first one that isn't assigned. So if you've got a resource mapped for servo 6 (but not 1 to 5), this will never get initialised.

**Comment by DeetAus** [comment]
I am getting the same issue on an old naze32r5 board

The entire output mix has changed.

Previously the outputs (1thru 5 were) 
S1, S1, M1, M2, M3

With 2.0.2 the mix outputs are
M1, M2, M3   but no servo output

I tried the above suggestion:
resource MOTOR 4 NONE
resource SERVO 1 A03
save

but that doesn't appear to have changed anything
Looks like I will have to ground my tricopter until this can be resolved

**Comment by victorivanovich** [comment]
Hello! Same thing happend to me. I have cc3d and I tryed configure as tricopter. Servo not moved and config where changed in servo panel not saved. Pleace check it.

**Comment by mikeller** [comment]
You will have to remap your motors / servos to get the same setup as before 2.0.

For NAZE:

resource servo 1 a08
resource servo 2 a11
resource motor 1 b06
resource motor 2 b07
resource motor 3 b08

**Comment by DeetAus** [comment]
I don't care if it isn't the same setup as before, just want the servo working, I have already re-done the ESC outputs to suit the new outputs

I'll try setting servo1 to b07 and see if that solves it

**Comment by mikeller** [comment]
@DeetAus: Sorry, I was not entirely clear in my last post. It will **not** work unless you go back to the wiring that worked for < 2.0. Motors on outputs 1 / 2 / 3 and Servo on output 4 is **not** supported.

(The reason for this is a hardware limitation: On the NAZE board, outputs 1 and 2 share the same timer, and outputs 3 - 5 share another timer. Motors and servos cannot share the same timer. As a consequence, there is no way to use 3 motors and servos, and have the motors use outputs 1 or 2.)

**Comment by DeetAus** [comment]
Thanks, will test and get back to you

**Comment by DeetAus** [comment]
OK
Thats got the servo and motors back to where they used to be, and the servo is no working BUT

Its correcting in the wrong direction and I cannot get it to reverse via the servo tab of the configurator

**Comment by mikeller** [comment]
Good to hear it's working. And yes, tricopter support in Betaflight is somewhat clumsy, there is no equivalent for the `smix reverse` CLI command in the Servos tab.

**Comment by Strommy** [comment]
I am having the same problem. Using latest CF and latest update. Aircraft set to tri copter. Connected the correct way and had to enter CLI as below to set servo and motors to correct channel:-
resource motor 1 none
resource motor 2 none
resource servo 1 a8
resource servo 2 a11
resource motor 1 b6
resource motor 2 b7
resource motor 3 b8
resource motor 4 b9
save

All motors spin up correctly now and servo is listed as servo 6 in motors page. Servo 6 graph  moves correctly when yaw is activated on screen but no reaction from servo. Running digital servo and also tried with a analog one to no avail. Naze32 rev6 acro. (Tried a second one but still same issue. Any help would be great. Even if someone has a working CLI code dump so I can load to mine.
Thankyou in advance

**Comment by mikeller** [comment]
Have you set `tri_unarmed_servo = on`?

**Comment by Strommy** [comment]
I tried that but it is an unknown command in CLI.
below is dump of CLI.
# dump
# Cleanflight / NAZE 2.0.2 Apr 22 2017 / 14:41:48 (4328b13)
name -
resource BEEPER 1 A12
resource MOTOR 1 A08
resource MOTOR 2 A11
resource MOTOR 3 B06
resource MOTOR 4 B07
resource MOTOR 5 B08
resource MOTOR 6 B09
resource MOTOR 7 NONE
resource MOTOR 8 NONE
resource MOTOR 9 NONE
resource MOTOR 10 NONE
resource MOTOR 11 NONE
resource MOTOR 12 NONE
resource SERVO 1 NONE
resource SERVO 2 NONE
resource SERVO 3 NONE
resource SERVO 4 NONE
resource SERVO 5 NONE
resource SERVO 6 NONE
resource SERVO 7 NONE
resource SERVO 8 NONE
resource PPM 1 A00
resource PWM 1 A00
resource PWM 2 A01
resource PWM 3 A02
resource PWM 4 A03
resource PWM 5 A06
resource PWM 6 A07
resource PWM 7 B00
resource PWM 8 B01
resource LED_STRIP 1 A06
resource SERIAL_TX 1 NONE
resource SERIAL_TX 2 NONE
resource SERIAL_TX 3 NONE
resource SERIAL_TX 4 NONE
resource SERIAL_TX 5 NONE
resource SERIAL_TX 6 NONE
resource SERIAL_TX 7 NONE
resource SERIAL_TX 8 NONE
resource SERIAL_TX 9 NONE
resource SERIAL_TX 10 NONE
resource SERIAL_TX 11 A07
resource SERIAL_TX 12 B01
resource SERIAL_RX 1 NONE
resource SERIAL_RX 2 NONE
resource SERIAL_RX 3 NONE
resource SERIAL_RX 4 NONE
resource SERIAL_RX 5 NONE
resource SERIAL_RX 6 NONE
resource SERIAL_RX 7 NONE
resource SERIAL_RX 8 NONE
resource SERIAL_RX 9 NONE
resource SERIAL_RX 10 NONE
resource SERIAL_RX 11 A06
resource SERIAL_RX 12 B00
mixer TRI

mmix reset

servo 0 1000 2000 1500 100 -1
servo 1 1000 2000 1500 100 -1
servo 2 1000 2000 1500 100 -1
servo 3 1000 2000 1500 100 -1
servo 4 1000 2000 1500 100 -1
servo 5 1000 2000 1500 100 -1
servo 6 1000 2000 1500 100 -1
servo 7 1000 2000 1500 100 -1
smix reset


feature -RX_PPM
feature -VBAT
feature -INFLIGHT_ACC_CAL
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -FAILSAFE
feature -SONAR
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DISPLAY
feature -OSD
feature -UNUSED
feature -CHANNEL_FORWARDING
feature -TRANSPONDER
feature -AIRMODE
feature -SDCARD
feature -VTX
feature -RX_SPI
feature -SOFTSPI
feature -ESC_SENSOR
feature -ANTI_GRAVITY
feature RX_PPM
feature SERVO_TILT
feature FAILSAFE
beeper GYRO_CALIBRATED
beeper RX_LOST
beeper RX_LOST_LANDING
beeper DISARMING
beeper ARMING
beeper ARMING_GPS_FIX
beeper BAT_CRIT_LOW
beeper BAT_LOW
beeper GPS_STATUS
beeper RX_SET
beeper ACC_CALIBRATION
beeper ACC_CALIBRATION_FAIL
beeper READY_BEEP
beeper MULTI_BEEPS
beeper DISARM_REPEAT
beeper ARMED
beeper SYSTEM_INIT
beeper ON_USB
beeper BLACKBOX_ERASE
map AETR1234
serial 0 1 115200 57600 0 115200
serial 1 0 115200 57600 0 115200
led 0 0,0::C:0
led 1 0,0::C:0
led 2 0,0::C:0
led 3 0,0::C:0
led 4 0,0::C:0
led 5 0,0::C:0
led 6 0,0::C:0
led 7 0,0::C:0
led 8 0,0::C:0
led 9 0,0::C:0
led 10 0,0::C:0
led 11 0,0::C:0
led 12 0,0::C:0
led 13 0,0::C:0
led 14 0,0::C:0
led 15 0,0::C:0
led 16 0,0::C:0
led 17 0,0::C:0
led 18 0,0::C:0
led 19 0,0::C:0
led 20 0,0::C:0
led 21 0,0::C:0
led 22 0,0::C:0
led 23 0,0::C:0
led 24 0,0::C:0
led 25 0,0::C:0
led 26 0,0::C:0
led 27 0,0::C:0
led 28 0,0::C:0
led 29 0,0::C:0
led 30 0,0::C:0
led 31 0,0::C:0
color 0 0,0,0
color 1 0,255,255
color 2 0,0,255
color 3 30,0,255
color 4 60,0,255
color 5 90,0,255
color 6 120,0,255
color 7 150,0,255
color 8 180,0,255
color 9 210,0,255
color 10 240,0,255
color 11 270,0,255
color 12 300,0,255
color 13 330,0,255
color 14 0,0,0
color 15 0,0,0
mode_color 0 0 1
mode_color 0 1 11
mode_color 0 2 2
mode_color 0 3 13
mode_color 0 4 10
mode_color 0 5 3
mode_color 1 0 5
mode_color 1 1 11
mode_color 1 2 3
mode_color 1 3 13
mode_color 1 4 10
mode_color 1 5 3
mode_color 2 0 10
mode_color 2 1 11
mode_color 2 2 4
mode_color 2 3 13
mode_color 2 4 10
mode_color 2 5 3
mode_color 3 0 8
mode_color 3 1 11
mode_color 3 2 4
mode_color 3 3 13
mode_color 3 4 10
mode_color 3 5 3
mode_color 4 0 7
mode_color 4 1 11
mode_color 4 2 3
mode_color 4 3 13
mode_color 4 4 10
mode_color 4 5 3
mode_color 5 0 9
mode_color 5 1 11
mode_color 5 2 2
mode_color 5 3 13
mode_color 5 4 10
mode_color 5 5 3
mode_color 6 0 6
mode_color 6 1 10
mode_color 6 2 1
mode_color 6 3 0
mode_color 6 4 0
mode_color 6 5 2
mode_color 6 6 3
mode_color 6 7 6
mode_color 6 8 0
mode_color 6 9 0
mode_color 6 10 0
mode_color 7 0 3
aux 0 0 0 1300 1700
aux 1 0 0 900 900
aux 2 0 0 900 900
aux 3 0 0 900 900
aux 4 0 0 900 900
aux 5 0 0 900 900
aux 6 0 0 900 900
aux 7 0 0 900 900
aux 8 0 0 900 900
aux 9 0 0 900 900
aux 10 0 0 900 900
aux 11 0 0 900 900
aux 12 0 0 900 900
aux 13 0 0 900 900
aux 14 0 0 900 900
aux 15 0 0 900 900
aux 16 0 0 900 900
aux 17 0 0 900 900
aux 18 0 0 900 900
aux 19 0 0 900 900
adjrange 0 0 0 900 900 0 0
adjrange 1 0 0 900 900 0 0
adjrange 2 0 0 900 900 0 0
adjrange 3 0 0 900 900 0 0
adjrange 4 0 0 900 900 0 0
adjrange 5 0 0 900 900 0 0
adjrange 6 0 0 900 900 0 0
adjrange 7 0 0 900 900 0 0
adjrange 8 0 0 900 900 0 0
adjrange 9 0 0 900 900 0 0
adjrange 10 0 0 900 900 0 0
adjrange 11 0 0 900 900 0 0
adjrange 12 0 0 900 900 0 0
adjrange 13 0 0 900 900 0 0
adjrange 14 0 0 900 900 0 0
rxrange 0 1000 2000
rxrange 1 1000 2000
rxrange 2 1000 2000
rxrange 3 1000 2000
rxfail 0 a
rxfail 1 a
rxfail 2 a
rxfail 3 a
rxfail 4 h
rxfail 5 h
rxfail 6 h
rxfail 7 h
rxfail 8 h
rxfail 9 h
rxfail 10 h
rxfail 11 h
rxfail 12 h
rxfail 13 h
rxfail 14 h
rxfail 15 h
rxfail 16 h
rxfail 17 h
set align_gyro = DEFAULT
set gyro_lpf = OFF
set gyro_sync_denom = 8
set gyro_lowpass_type = PT1
set gyro_lowpass = 90
set gyro_notch1_hz = 400
set gyro_notch1_cutoff = 300
set gyro_notch2_hz = 200
set gyro_notch2_cutoff = 100
set moron_threshold = 48
set gyro_use_32khz = OFF
set gyro_isr_update = OFF
set align_acc = DEFAULT
set acc_hardware = AUTO
set acc_lpf_hz = 10
set acc_trim_pitch = 0
set acc_trim_roll = 0
set align_mag = DEFAULT
set mag_hardware = NONE
set mag_declination = 0
set magzero_x = 0
set magzero_y = 0
set magzero_z = 0
set baro_hardware = NONE
set baro_tab_size = 21
set baro_noise_lpf = 600
set baro_cf_vel = 985
set baro_cf_alt = 965
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set rssi_scale = 30
set rssi_invert = OFF
set rc_interp = AUTO
set rc_interp_ch = RP
set rc_interp_int = 19
set fpv_mix_degrees = 0
set max_aux_channels = 6
set serialrx_provider = SPEK1024
set sbus_inversion = ON
set spektrum_sat_bind = 0
set spektrum_sat_bind_autoreset = 1
set airmode_start_throttle = 1350
set rx_min_usec = 885
set rx_max_usec = 2115
set input_filtering_mode = OFF
set blackbox_rate_num = 1
set blackbox_rate_denom = 1
set blackbox_device = SPIFLASH
set blackbox_on_motor_test = OFF
set min_throttle = 1070
set max_throttle = 2000
set min_command = 1000
set use_unsynced_pwm = OFF
set motor_pwm_protocol = OFF
set motor_pwm_rate = 480
set motor_pwm_inversion = OFF
set thr_corr_value = 0
set thr_corr_angle = 800
set failsafe_delay = 10
set failsafe_off_delay = 10
set failsafe_throttle = 1000
set failsafe_kill_switch = OFF
set failsafe_throttle_low_delay = 100
set failsafe_procedure = DROP
set align_board_roll = 0
set align_board_pitch = 0
set align_board_yaw = 0
set gimbal_mode = NORMAL
set bat_capacity = 0
set vbat_max_cell_voltage = 43
set vbat_min_cell_voltage = 33
set vbat_warning_cell_voltage = 35
set vbat_hysteresis = 1
set current_meter = ADC
set battery_meter = ADC
set bat_detect_thresh = 55
set use_vbat_alerts = ON
set use_cbat_alerts = OFF
set cbat_alert_percent = 10
set vbat_scale = 110
set ibata_scale = 400
set ibata_offset = 0
set beeper_inversion = ON
set beeper_od = OFF
set beeper_frequency = 0
set yaw_motors_reversed = OFF
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set 3d_deadband_throttle = 50
set servo_center_pulse = 1500
set servo_pwm_rate = 50
set servo_lowpass_hz = 0
set tri_unarmed_servo = ON
set channel_forwarding_start = 4
set reboot_character = 82
set serial_update_rate_hz = 100
set accxy_deadband = 40
set accz_deadband = 40
set acc_unarmedcal = ON
set imu_dcm_kp = 2500
set imu_dcm_ki = 0
set small_angle = 25
set auto_disarm_delay = 5
set disarm_kill_switch = ON
set gyro_cal_on_first_arm = OFF
set fixedwing_althold_reversed = OFF
set alt_hold_deadband = 40
set alt_hold_fast_change = ON
set deadband = 0
set yaw_deadband = 0
set yaw_control_reversed = OFF
set pid_process_denom = 1
set tlm_switch = OFF
set tlm_inversion = OFF
set tlm_halfduplex = ON
set frsky_default_lat = 0
set frsky_default_long = 0
set frsky_gps_format = 0
set frsky_unit = IMPERIAL
set frsky_vfas_precision = 0
set frsky_vfas_cell_voltage = OFF
set hott_alarm_int = 5
set pid_in_tlm = OFF
set ibus_report_cell_voltage = OFF
set ledstrip_visual_beeper = OFF
set task_statistics = ON
set debug_mode = NONE
profile 0

set d_lowpass_type = BIQUAD
set d_lowpass = 100
set d_notch_hz = 260
set d_notch_cut = 160
set vbat_pid_gain = OFF
set pid_at_min_throttle = ON
set anti_gravity_thresh = 350
set anti_gravity_gain = 1000
set setpoint_relax_ratio = 100
set d_setpoint_weight = 60
set yaw_accel_limit = 100
set accel_limit = 0
set iterm_windup = 50
set yaw_lowpass = 0
set pidsum_limit = 500
set pidsum_limit_yaw = 400
set p_pitch = 58
set i_pitch = 50
set d_pitch = 35
set p_roll = 44
set i_roll = 40
set d_roll = 30
set p_yaw = 70
set i_yaw = 45
set d_yaw = 20
set p_alt = 50
set i_alt = 0
set d_alt = 0
set p_level = 50
set i_level = 50
set d_level = 100
set p_vel = 55
set i_vel = 55
set d_vel = 75
set level_sensitivity = 55
set level_limit = 55
rateprofile 0

set rc_rate = 100
set rc_rate_yaw = 100
set rc_expo = 0
set rc_yaw_expo = 0
set thr_mid = 50
set thr_expo = 0
set roll_srate = 70
set pitch_srate = 70
set yaw_srate = 70
set tpa_rate = 10
set tpa_breakpoint = 1650

any help would be great.
thankyou for helping **mikeller**

**Comment by mikeller** [comment]
Looks like you did not save your resource remappings:

>resource MOTOR 1 A08
resource MOTOR 2 A11
resource MOTOR 3 B06
resource MOTOR 4 B07
resource MOTOR 5 B08
resource MOTOR 6 B09
resource MOTOR 7 NONE
resource MOTOR 8 NONE
resource MOTOR 9 NONE
resource MOTOR 10 NONE
resource MOTOR 11 NONE
resource MOTOR 12 NONE
resource SERVO 1 NONE
resource SERVO 2 NONE
resource SERVO 3 NONE
resource SERVO 4 NONE
resource SERVO 5 NONE
resource SERVO 6 NONE
resource SERVO 7 NONE
resource SERVO 8 NONE

(Also, `tri_unarmed_servo` is already on in your config.)

**Comment by Strommy** [comment]
Thats weird as i just checked resource and it states it as. after i changed settings i always save. but when i do a "dump" it comes up as posted above...

# resource
resource BEEPER 1 A12
resource MOTOR 1 B06
resource MOTOR 2 B07
resource MOTOR 3 B08
resource MOTOR 4 B09
resource SERVO 1 A08
resource SERVO 2 A11

Just to confirm power going through to the servo can go through unused channels (ie out put 2 or 6) ?? as i have tried putting power through receiver to power naze and also tried through unused channels. (just incase the bus is similar to the kk board where as 2-6 are not on same bus as output1) 
i have also tried the "triflight_0.7_Beta1_NAZE.hex" that rcexplorer recommends but still to no avail.
I have been looking for a stevis hex for naze. I just cant understand why after the hex has been loaded and the model set that you have to remap outputs.

**Comment by mikeller** [comment]
Try saving it again. Also, note that if you reset the config, the resource mappings will be reset as well.

> I just cant understand why after the hex has been loaded and the model set that you have to remap outputs.

That's because 2.0 has removed the custom resource mappings for non-quad models that existed for a dozen or so boards, and introduced user configurable resource mappings.

At a later stage there will be support for preset resource mappings for models like tricopters. But with over 100 boards now supported, and all of them requiring their own custom mapping, the effort for this (including testing) will be quite large.

**Comment by Strommy** [comment]
okI have tried now tried using Cleanflight 1.10 to 1.14 and older versions of releases to no avail. i have also tried it on betaflight 3.0 with resource remapping on all but no movement from servo. Servo works perfectly on tester and so does analogue servo. so no faults there.. tried to also load the dump from rcexplorer settings but no reaction. ensured i saved it and board rebooted and saved as it usually does with my quads. tried power on the channel 2 output and channel 6 (not at same time) and also by powering it through receiver ppm input. channel 6 on motor page of both cleanflight and beta flight register the movement through yaw channel but no out put is produced. enabled channel A8 for the servos. 
starting  to Just wonder if the NAZE32 rev6 board works with a tricopter? if not what suggestions are there except the kk which i use already.

**Comment by mikeller** [comment]
> starting to Just wonder if the NAZE32 rev6 board works with a tricopter?

Yes they do, I am using one.

Different question: Have you tried moving the servo by changing the mid point of slot 6 in the 'Servos' tab?

**Comment by Strommy** [comment]
yes. enabled expert mode. went to servo tab and adjusted servo 5 to 1800 and it changed the mid point on the motors page of servo 6 (which is my yaw channel as it moves the bar on movement of yaw. I thought servo on tri was servo 0 on servos tab.)
So i reflashed the naze, loaded current cleanflight configurator and current version 2.0.2,  changed the resourses to allocate motors and servos to which the motors work. servos tested using servo tested and even tried to power servo independantly and just use signal wire to tell servo position. no avail.
i have tried to enable servo tilt to see if that works but nothing. and just tried my other 2 boards but same thing.
using ppm input with spectrum dx6 reciever. servo is a bluebird digital 385dmax or 380 max for analogue.
when i go to cli screen and command dump it states the dump as previously posted but if i check resourse everything is correct.
if i go to the servo tab and select a checkbox and save, it will not be there next time i enter the tab but the midpoint settings stay.
you are using a tri. which cleanflight configurator and version of flash are you using? board is an acro too.

**Comment by rejo54** [comment]
Strommy , 
I had the same problem. The motors will spin up, the server control worked in Cleanflight and was listed as servo 6, but no servo movement on my tricopter. Thanks to this forum I got it working now :).  Nothing was saving when I made changes in cleanflight.


I opened Betaflight CLI  I did the following. 


resource MOTOR 4 NONE
resource SERVO 6 A03

A03 was the resource for motor 4.

On the servo tab I set servo 6 to ch 4 (ticked the box)
changed the values to -45/45 from -90/90

Hope this helps.

**Comment by Strommy** [comment]
I have tried everything possible. It all saves. And the resource listed in cli is correct. All up it just doesn't want to play might be the hk boards or something... so I bit the bullet and put the kk back in and updated to 811 software to get some of the same features of horizon mode (slmix!)
Will keep using the naze for my quads but as for tricopters I will try another day when there is more info and more data dumps on the Web so I can copy it into my cli and test that. But happy with the kk as it works first time everytime. Just wish they were 32 bit too.
Thankyou all for helping out.

**Comment by rejo54** [comment]
@mikeller: Thank you for your input. I never stated that the resources had to be the same as mine, my point was servo 6 never had resources in the CLI and I cleared the resources from motor 4 and used those for servo 6 and it worked. 
As Stormmy had posted above:
"ll motors spin up correctly now and servo is listed as servo 6 in motors page. Servo 6 graph moves correctly when yaw is activated on screen but no reaction from servo."
"resource SERVO 6 NONE"

It seems like the same problem I had. Just because you could not help him does not mean others input may not!

**Comment by mikeller** [comment]
@rejo54: I am a bit surprised by your statement that you when using servo 6. For the tricopter mixer, it is servo 1 that is used. There is some confusion between 'servo slots' as listed in the configurator, and servos, which is how resource management sees them. For a (somewhat lacking) explanation have a look at https://github.com/cleanflight/cleanflight/blob/master/docs/Mixer.md#custom-servo-mixing 

(Also, the resource for servo 6 will not be initialised unless you define resources for servos 1 - 5 too.)

**Comment by hydra** [comment]
afaikt there's no issue here other than a configuration issue.  yes we know the configurator could be more helpful in this regard and can be addressed in the future when we have time.  If this isn't the case and there's a genuine bug here then please create a new issue with exact steps to repeat and reference this one in the description.

**Comment by SteCowell** [comment]
I've been trying to setup a Quantum Illuminati 32 (essentially a NAZE 32) on a trictopter for a number of weeks without success. The tricopter motors worked fine but the YAW servo just would not cooperate. I've read numerous forums and papers but it was thanks to the comment by mikeller (May 14, 2017); which explained the timer issue and provided the mapping, that my setup has been successful. 

Illuminati 32 connections: 
- pin1 to servo
- pin3 to motor 1
- pin4 to motor 2
- pin5 to motor 3

Resource mapping (as per mikeller comments):
- resource servo 1 a08
- resource servo 2 a11 
- resource motor 1 b06
- resource motor 2 b07
- resource motor 3 b08

Many thanks mikeller and to all other contributers.
