### ISSUE TITLE
Where do you start learning cleanflight?

### ISSUE THREAD

**Issue by xdwgood** [cleanflight/cleanflight#2785]
Hello everyone！ I have read some of the content on cleanflight's official website and gitbub. But I don't know how to learn it in a planned way.

**Comment by mikeller** [comment]
A good start would be to tell us what aspect of cleanflight you are interested in learning about. :-) Also, you may want to join IRC (or slack) as listed on the cleanflight main page, to ask questions in a real time chat.

**Comment by xdwgood** [comment]
@mikeller thanks
