### ISSUE TITLE
Cleanflight code is how to solve the impact of body vibration on the acc/gyro?

### ISSUE THREAD

**Issue by xdwgood** [cleanflight/cleanflight#2793]
Low pass filtering of raw data?
Or more?

**Comment by fftunes** [comment]
Additional notch filtering in the newer versions which can be adjusted to higher frequency noise peaks.

But since more powerful motors became standard it is recommended to use softmounting on FC and/or motors as well.

**Comment by xdwgood** [comment]
@fftunes Thanks
