### ISSUE TITLE
Firmware 2.0.2 not worked on CJMCU

### ISSUE THREAD

**Issue by ErfanDL** [cleanflight/cleanflight#2796]
Hi. please fix firmware 2.0.2 on CJMCU. when uploading firmware motors run selfi

**Comment by mikeller** [comment]
Is that 'during the upload'? Please read the safety instructions, and never have a battery connected _and_ props on when flashing firmware.

**Comment by ErfanDL** [comment]
@mikeller
No. upload is successful but when I turn on cjmcu motors start by itself

**Comment by mikeller** [comment]
Ok. Looks a lot like the brushed motors are not detected properly. Can you connect it to the configurator and check what protocol is selected for 'ESC/Motor protocol' on the 'Configuration' tab? If it's not 'Brushed' switch it to 'Brushed' and you'll be fine.

**Comment by ErfanDL** [comment]
@mikeller thanks for reply. motor configuration is Brushed but not worked. I downgrade to 1.9.0
this problem is in firmware 1.9.0 and above ( 1.10 to 2.0.2 )
and a question: can I use GPS on my CJMCU micro quad for mission planner ?

**Comment by mikeller** [comment]
You probably can use GPS on firmware < 2.0. For 2.0, GPS support has had to be removed because there was no space for it.

**Comment by ErfanDL** [comment]
@mikeller thanks. Can GPS working with firmware 1.9.0 ?

**Comment by McGiverGim** [comment]
There's no firmware 1.9.0. I think remember that the latest was 1.4.2 before 2.0.

**Comment by ErfanDL** [comment]
why CJMCU cant support GPS ? my Ublox 7 not worked with CJMCU firmware1.9.0

**Comment by mikeller** [comment]
@ErfanDL: Please read my statement from 2 days ago.

**Comment by ErfanDL** [comment]
@mikeller I read. my firmware is not 2.0 or above Im in 1.9.0 :( but GPS not worked

**Comment by AleksandrNull** [comment]
Guys, I could confirm that last working version for my CJMCU is 1.14.2. Starting with 2.0.0 and later all of them cause props to start spin around 5-10 seconds after board is booted up. My initial thought was ... hmm.. looks like my mosfet's dying but reverting back to 1.14.2 fixed it. I have brushed with 16k PMW settings in configurator. Dunno what to look into and already tried to look on all commits since tag 1.14.2 but it's a huge amount and, you know, that could be anything. It looks like something initialized on the board which somehow affects PWM output for brushed motor MOSFET control pins.

**Comment by mikeller** [comment]
@AleksandrNull: What did you configure as 'ESC Protocol'?

**Comment by AleksandrNull** [comment]
Hi Michael, thanks for a reply. For ESC Protocol this board have BRUSHED. I've checked that multiple times.
![image](https://cloud.githubusercontent.com/assets/2253348/26611696/b8f2db2c-4564-11e7-9da3-d45f33245c54.png)

**Comment by Smeat** [comment]
I have the same problem.
1.14.2 is working flawlessly and with 2.0.2 my motors start spinning after a few seconds (not all just a few of them).
If I try to control the motors manually via the configurator, the connection drops and LED3 is blinking very fast. ESC is set to brushed.
CLI seems to be broken too.

**Comment by AleksandrNull** [comment]
CLI is disabled on CJMCU target. Probably because there is not enough space to fit it in.
