### ISSUE TITLE
GPS Ublox 7 not worked on CJMCU

### ISSUE THREAD

**Issue by ErfanDL** [cleanflight/cleanflight#2800]
Hi. I install Ublox 7 on CJMCU but cant worked when I set GPS to Ublox after save and reboot its jumped to NMEA !!! the firmware is version 1.9.0. (the port GPS is enabled and baud set to 57600)

please help

**Comment by McGiverGim** [comment]
The F1 CPU's have very few free space, in version 2.0 the GPS has been removed for a lot of targets, so it will not work. You have two options:
- Stay in CF1.x
- Customize your own build to remove some features that you don't need and add the GPS again.

This is not an issue, if you need more support please go to the slack chat: https://cleanflight.slack.com

I close this.

Regards!

**Comment by ErfanDL** [comment]
@McGiverGim thanks. but Im in firmware 1.9.0 not 2 or above. my question: is CJMCU microquad support Ublox 7 GPS ?

**Comment by McGiverGim** [comment]
I don't know too much about version 1.9. And here you will only find help for issues of version 2.0 or later.

Please try to find help in the slack chat.

Regards!

**Comment by ErfanDL** [comment]
@McGiverGim thanks. Can you invite me in Slack ? my email: erfan.shirzad@gmail.com

**Comment by mikeller** [comment]
@ErfanDL: You can invite yourself: http://cleanflight.com/slack/ ;-)

**Comment by ErfanDL** [comment]
@mikeller Im joined slack support chat but nobody help me ! please build a firmware for me CJMCU that support GPS I need firmware 1.9.0 with GPS
