### ISSUE TITLE
Missing "Passthrough" mode in CUSTOMAIRPLANE

### ISSUE THREAD

**Issue by supergregg** [cleanflight/cleanflight#2802]
# A - Description

I created a customairplane and had problems with the mixers. Got that sorted via the CLI and now the servors work. However, the problem I'm reporting here is that I'm now missing the "Passthrough" mode in modes. Modes like Servo 1,2,3 have appeard but no "passthrough can be found.

# B - Steps To Repeat

set mixer to CUSTOMAIRPLANE and "Passthrough"-mode is gone

# E - Version Information

Cleanflight / NAZE 2.0.2 Apr 22 2017 / 14:41:48 (4328b13)
Configurator: v2.0.3

# E - Other information

Naze 32, old one not sure

**Comment by mikeller** [comment]
Yes, not enabling passthru mode for the custom airplane mixer seems to be an oversight. We can enable this in the next release.
