### ISSUE TITLE
Cant enable Gyro 32khz sampling mode

### ISSUE THREAD

**Issue by Bardiaesm** [cleanflight/cleanflight#2803]
# A - Description

CleanFlight 2.03
SP Racing F3
Cant seem to enable Gyro 32khz sampling mode. When enabled, after rebooting it goes back to before and disable it self. Please watch the video

# B - Steps To Repeat

Watch the attached video

# C - Video Links

https://youtu.be/lcFFgdZcj3I

# D - Forum post links

https://www.rcgroups.com/forums/showthread.php?2889678-CleanFlight-Cant-enable-Gyro-32khz-sampling-mode#post37540943

# E - Version Information
Configurator: 2.0.3

**Comment by mikeller** [comment]
Try if `set gyro_lpf = off` in CLI fixes this.

**Comment by hydra** [comment]
SP Racing F3 Acro/Deluxe uses I2C, not supported.  Use a board with SPI and a sensor that can support the rate.
