### ISSUE TITLE
Bug in multiWii PID controller in Horizon mode when RC rate > 1.0

### ISSUE THREAD

**Issue by thenickdude** [cleanflight/cleanflight#281]
In Horizon mode, at full roll or pitch, the PIDs are supposed to be calculated entirely based on the gyros (like rate mode) and not at all on the accelerometers. This is achieved by mixing the gyro and accelerometer corrections together based on the "prop" variable, which is set to the highest of the absolutes of the roll and pitch rcCommand values:

```c
prop = max(abs(rcCommand[PITCH]), abs(rcCommand[ROLL])); // range [0;500]
...
PTerm = (PTermACC * (500 - prop) + PTermGYRO * prop) / 500;
ITerm = (ITermACC * (500 - prop) + ITermGYRO * prop) / 500;
```

The mixing calculation assumes that full throw on the stick is 500 (a comment indicates that the range for the abs() of rcCommand on pitch and roll is [0;500]). But actually rcCommand values are scaled by rcRate, so if your rcRate is above 1.0, your rcCommand will exceed that range (e.g. for rcRate = 1.5 the range is [-750...750]). 

This causes the mixing calculation to fail at full stick throw: It ends up adding a *negative* portion of the accelerometer correction in (when it should be zero) and an exaggerated version of the gyro correction (when it should be applied at 100%). 

During a roll, at the point where the quad is inverted, this causes it to briefly oppose the roll with a spike in "P", even though the gyroscope and RC inputs remain steady (so there is no error for it to be correcting):

https://www.youtube.com/watch?v=gjyp3CJ_6kY&feature=youtu.be

Here's the data during the sudden reverse spike:

![Point of the reverse correction](http://i.imgur.com/HUy2qYT.jpg)

You can see that the motors on the reverse side to the roll have been driven high and the others have fallen to zero, which is a very severe correction. But at this point notice that the gyro (red line in bottom graph) is still completely smooth: it is still correctly maintaining the set rotation rate so there is nothing for it to correct. And also the roll stick is still full up against the edge (650) so I haven't changed the rotation rate I'm commanding. That only leaves the accelerometer.

At full stick throw in horizon mode, the accelerometer is supposed to have no impact on the flight characteristics. But due to the bug, when rcRate > 1.0, a *negative version* of the accelerometer correction gets added in. Now, when the craft is completely inverted, the accelerometer (which tries to bring the craft level at all times) suddenly flips the sign of its correction: it always tries to roll toward the shortest angle to bring itself back upright, so instead of trying to roll back to the beginning of the flip it suddenly changes to trying to roll toward the end. But since the correction is negated, this causes it to suddenly oppose the rate of rotation, which is what causes this sudden reverse-thrust correction.

**Comment by thenickdude** [comment]
HFMan: Same bug is present in Baseflight upstream, but in MultiWii the "prop" gets clamped to 500 before being used in the calculations, so the bug doesn't exist there!

**Comment by hydra** [comment]
Perhaps for now the quick fix is to apply the same solution that was applied to the multiwii codebase.

@HFMan have you had time to study the code more yet?
