### ISSUE TITLE
Control HZ issue

### ISSUE THREAD

**Issue by xdwgood** [cleanflight/cleanflight#2813]
I have a issue about     .desiredPeriod = TASK_GYROPID_DESIRED_PERIOD
In code :
#if defined(STM32F4) || defined(STM32F7)
#define TASK_GYROPID_DESIRED_PERIOD     125
#else
#define TASK_GYROPID_DESIRED_PERIOD     1000

why F4 or F7 have lower hz than  F1?

**Comment by mikeller** [comment]
It is period, which is 1/frequency.

**Comment by xdwgood** [comment]
@mikeller Thanks, so Fi pid control is 1000hz?  Task is 1 ms ?

**Comment by xdwgood** [comment]
@mikeller Thanks,I will learn more about the code and ask more questions.
