### ISSUE TITLE
Telemetry Documentation error for telemetry inversion command

### ISSUE THREAD

**Issue by pascoea** [cleanflight/cleanflight#2815]
# A - Description

Telemetry documentation specifies an incorrect command name for telemetry inversion

# B - Steps To Repeat

In configurator command line type set telemetry_inversion = ON

# E - Version Information
Configurator: v2.0.2

# E - Other information

Proper command appears to be "set tlm_inversion=ON"

**Comment by mikeller** [comment]
Thanks for reporting this. The wiki is user editable, can you please change this to reflect the correct command?

**Comment by pascoea** [comment]
Added a pull request to update telemetry.md

Thanks for the quick response!
