### ISSUE TITLE
Same code in one function

### ISSUE THREAD

**Issue by xdwgood** [cleanflight/cleanflight#2818]
I find two same code in one function,why?
https://github.com/cleanflight/cleanflight/blob/master/src/main/scheduler/scheduler.c#L212

sorry,I can not understand "taskId == TASK_SELF".Why we need to judge this?

**Comment by martinbudden** [comment]
@xdwgood , well spotted. Second line should be:
```
cfTasks[taskId].maxExecutionTime = 0;
```

`TASK_SELF` is a special value that allows a task to reset its own statistics.

**Comment by xdwgood** [comment]
@martinbudden Thanks
