### ISSUE TITLE
Board - Support additional UART ports on STM32F3Discovery

### ISSUE THREAD

**Issue by iMattmax** [cleanflight/cleanflight#282]
The STM32F3Dicovery board support more than only two UART-ports. So, is it possible to have all of them activated in cleanflight? 
What is to change, that all supported UART's of the STM32F3Dischovery-board can be used in cleanflight? 
Other fc-fw support the available UART's of this board and somewhere I read that People are working on this thing.

**Comment by Exidouce** [comment]
Two UART's is a limitation of the STM32/board design itself not the FW. If you look at the quanton FC, it uses a beast of a STM32 chip. F405 I believe. Depending on the chip, It may have 2-5 UART's. They simply need to be addressed. Since all FC's are different, the FW necessary for each one is different due to differences in STM32 pinout changes between them.

**Comment by hydra** [comment]
Feel free to update src/main/target/target.h  and src/main/drivers/serial_uart_stm32f30x.c to add the appropriate code and raise a pull request.

There are a couple of other places you will have to change too in serial.c serial_uart.c/h etc.

**Comment by iMattmax** [comment]
If somebody can say how to start, than I can see what I can do....

**Comment by iMattmax** [comment]
If somebody can say how to start, than I can see what I can do....

**Comment by iMattmax** [comment]
If somebody can say how to start, than I can see what I can do....

**Comment by iMattmax** [comment]
If somebody can say how to start, than I can see what I can do....

**Comment by iMattmax** [comment]
If somebody can say how to start, than I can see what I can do....

**Comment by iMattmax** [comment]
If somebody can say how to start, than I can see what I can do....

**Comment by iMattmax** [comment]
If somebody can say how to start, than I can see what I can do....

**Comment by hydra** [comment]
Start by looking at the code mentioned above, you shod be able to follow the same pattern for other uarts.
