### ISSUE TITLE
acc.accSamplingInterval  issue

### ISSUE THREAD

**Issue by xdwgood** [cleanflight/cleanflight#2826]
https://github.com/cleanflight/cleanflight/blob/master/src/main/sensors/acceleration.c#L325
I can not undestand why we need judge STM32F10X.
They have the same result:    acc.accSamplingInterval = 1000;

**Comment by xdwgood** [comment]
Oh, I see, probably for future code frameworks.

**Comment by mikeller** [comment]
@xdwgood: It's probably easier if you join the Betaflight slack and ask these questions in there. Sent you an invite.

**Comment by xdwgood** [comment]
@mikeller Thanks
