### ISSUE TITLE
Acc Calibration Issue

### ISSUE THREAD

**Issue by xdwgood** [cleanflight/cleanflight#2827]
https://github.com/cleanflight/cleanflight/blob/master/src/main/sensors/acceleration.c#L382
accelerationTrims->raw[X] = (a[X] + (CALIBRATING_ACC_CYCLES / 2)) / CALIBRATING_ACC_CYCLES;

why have " + (CALIBRATING_ACC_CYCLES / 2)"?

**Comment by ledvinap** [comment]
Rounding.

Can you create one issue with your questions, please? It would be easier to track and answer
