### ISSUE TITLE
RX - Add support for OrangeRx R910 DSM2 S.Bus channel 9

### ISSUE THREAD

**Issue by RandGH** [cleanflight/cleanflight#283]
I am running a 9ch Orange RX via s.bus.
I can use 8ch fine but cannot access ch9.
I tried mapping the channel but that does not work

# map
Current assignment: TAER1234

# map TAER12345
Current assignment: TAER1234

Either this is a bug or a documentation deficiancy;)

**Comment by hydra** [comment]
The FrSky gear i have here works with 16 channels just fine.  Perhaps there is some configuration that needs to happen on the TX or RX?

Do you know for sure that the RX is sending the 9th channel to the FC?  Can you log the data it sends via an oscilloscope or logic analyzer?

Do you or anyone else use that TX/RX combination with 9 channels via SBus sucessfully on any other flight controller?

**Comment by RandGH** [comment]
Hm
 
there is another user with a similar problem on the rcgroups forum, not sure
what he uses.
 
I will check my setup again, but unfortunatly no osci or la :/ And noone i know
has that combo.

**Comment by hydra** [comment]
can you give me links to the exact TX and RX hardware you purchased?

**Comment by RandGH** [comment]
A Devo 12s with deviationX 4.01 and an Oragen R910 

http://www.hobbyking.com/hobbyking/store/__17621__OrangeRx_R910_DSM2_Compatible_9Ch_2_4Ghz_TwinPort_Rx.html
http://www.helipal.com/walkera-devo-12s-12-channel-2-4ghz-digital-radio-system.html
http://www.deviationtx.com/repository/Deviation-Releases/Deviation-4.0.1/

**Comment by hydra** [comment]
Can't do anything with this unless you can record the data that the receiver is sending to the FC somehow.

Any chance you could write some debug code in cleanflight to log the data from your RX, with the data we'd be able to analyze what the FC is receiving and then work out the problem.

If you have a spare RX that you could donate to the project we could take a look too.

**Comment by bmedici** [comment]
Same problem here: using a FrSky X4R connected with an SBUS inverter to pin4. SBUS serial mode in settings.
Only AETR and AUX 1-4 are moving according to channels sent by my transmitter. AUX 5-12 are stuck a 880 on the lelft. Anything I could have forgotten (config option or anything else) ?
I'm running v1.5.0

**Comment by ledvinap** [comment]
X4R is working for me, all 16 channels. 

You need D16 mode and channel range 1-16  set on transmitter.

**Comment by bmedici** [comment]
You're right... my transmitter was in 8-channel mode, thanks for the 
suggestion.
All 12 channels only are working, AUX 9-12 are still inactive, though 
I'm sending the exact same value on channels 8-16 from my transmitter.

Looks like channles above 12 may be ignored? An SBUS limitation?

Petr Ledvina wrote:

**Comment by ledvinap** [comment]
I'll check tomorrow, but I'am quite sure all 12 aux channels works.

**Comment by RandGH** [comment]
Hm, don't ask me why but after the latest rebuild of the quad it began to work? (1.6 rc)
I will check if it keeps working; but if it does i will say its a user error (unless something changed in the code in between)

**Comment by hydra** [comment]
Closing, please re-open if there's still an issue.
