### ISSUE TITLE
Conditions for acceleration calibration

### ISSUE THREAD

**Issue by xdwgood** [cleanflight/cleanflight#2851]
Hello everyone.
I have a question: why don't we add some judgement to the static acceleration calibration because if the UAV is tilted on the ground or not at the level of stationary conditions. Then the calibration record is not a correct value.
https://github.com/cleanflight/cleanflight/blob/master/src/main/sensors/acceleration.c#L472
If I do not understand correctly, I hope you can excuse me.

**Comment by hydra** [comment]
we could, perhaps this could be addressed when #95 is addressed.

Closing for now, thanks for sharing the idea.
