### ISSUE TITLE
cleanflight / Naze32 Rev5

### ISSUE THREAD

**Issue by bojanmanev** [cleanflight/cleanflight#2858]
Hello, 
i have a Naze32 Rev5 on mu drone u used the firmware 1.7.0 from cleanflight and was all good , so i have add sonar on mu drone and open the cleanflight to activate it, but on cleanflight i have a messege you must to update the firmware so i update it and now, everything is working good except the motor, they won't spin just beeping, i try different versions but same thing, also try with new motor and ESC but same thing, i thing the problem is on the board so can you help me.

Sorry for my bad English :)

**Comment by mikeller** [comment]
Hi @bojanmanev. GitHub is for questions and discussion around development of cleanflight. For configuration questions please have a look at RCGroups, and ask there if there isn't an answer to your problem already: https://www.rcgroups.com/forums/showthread.php?2249574-Cleanflight-firmware-for-STM32F3-based-FCBs-Check-First-Post-Please!!
