### ISSUE TITLE
LED - Configurable colors for arm state

### ISSUE THREAD

**Issue by MaxWinterstein** [cleanflight/cleanflight#286]
As discussed with hydra a few days ago on irc:

If the armed indicator is used the color is read from the hardcoded color (see https://github.com/cleanflight/cleanflight/blob/master/src/main/io/ledstrip.c#L527)
As far as i remember color 14&15 is not used anywhere and could be recycled to define the armed and disarmed color.

(Sadly i am not able to do it and create a pull request :cry: )

**Comment by JurikRistjouw** [comment]
Interesting, since i have been fooling around with ledstrip with somewhat results, i could try to look into that if it is possible.

**Comment by hydra** [comment]
PR for #667 

Please test and comment on the PR.

**Comment by JurikRistjouw** [comment]
will test this weekend.

**Comment by Raz6000** [comment]
Hi, Did this go any further? I'd like to add arm state for front and rear so when unarmed its green at both ends but when armed its blue at the front and red at the rear. Was this the idea of this thread?

Cheers,

Ray

**Comment by MaxWinterstein** [comment]
see #2047 for more on this.
