### ISSUE TITLE
FLIP32OSD Hex file appears to be corrupted V2.0.3

### ISSUE THREAD

**Issue by aowi7280** [cleanflight/cleanflight#2869]
# 3. If you answered NO to the first question.  Delete everything above this line, read the guidelines (see link above this form) and continue.

# A - Description

-- Tried to Load firmware (online) with FLIP32OSD target v2.0.3 - 20-06-2017 (stable) and got the message "Hex file appears to be corrupted".

# B - Steps To Repeat

--  Opened v2.0.2 successfully. Tried to open v2.0.3 again and it was still corrupted.

# C - Video Links

-- None

# D - Forum post links

-- None

# E - Version Information

Cleanflight: v2.0.3 or commit SHA
Configurator: v2.0.3 or commit SHA

# E - Other information

-- provide additional information such as.
-- flight controller make/model
-- config dump + diff
-- esc make/model/config
-- receiver make/model/config
-- transmitter make/model/config
-- schematics
-- diagrams
-- operating system
-- etc.

**Comment by mikeller** [comment]
Hi @aowi7280. 2.0.4 has been released: https://github.com/cleanflight/cleanflight/releases/tag/CLFL_v2.0.4  Try that.
