### ISSUE TITLE
LED - Show Battery Capacity Remaining

### ISSUE THREAD

**Issue by efespilsen03** [cleanflight/cleanflight#287]
hello, it's possible have a code to option with LED color:

lipo full green
lipo 50% orange 
lipo 20%  red

 thank you

use naze32 acro

**Comment by hydra** [comment]
yes, that would be possible, interesting idea.

**Comment by joeynuggetz** [comment]
Awesome idea. Better yet have support for the avail volts to be scaled across the number of leds specified by the user and have them turn off as battery decreases.
