### ISSUE TITLE
Gyro offset with 0.5khz  gyro_update_frequency

### ISSUE THREAD

**Issue by Cesco1** [cleanflight/cleanflight#2873]
I get a gyro error of 8 deg in X and 1 deg in Y when selecting update frequency lower than 1khz. This happens on 2 different naze32 boards. With 1khz update the gyro offset disappears.

**Comment by Cesco1** [comment]
Same thing happens on F3 boards if gyro update is set to 0.5 khz.  
On F4 boards i cant set gyro below 1khz, so its fine on F4.

**Comment by hydra** [comment]
can you provide more details on how you're testing this?  diffs, screenshots, etc would help.

**Comment by hydra** [comment]
no response, there have been some recent fixed in the latest BF 3.3 code that was just merged.  Please try a nightly build.  Re-open if problem persists.
