### ISSUE TITLE
Will Cleanflight Run On Odroid ?

### ISSUE THREAD

**Issue by hawkeyeuas** [cleanflight/cleanflight#2874]
I have a general question.  I am using Qdroid XU4 as a companion computer on my Pixhawk / Ardupilot based quadcopter platform.

Could I run your product on the Odroid and does it have API support ?

Please advise.

Abe

**Comment by mikeller** [comment]
You could probably compile a version of the SITL target (which is a designed to run in a simulator on a PC) to run on the CPU on the Qdroid under linux.
