### ISSUE TITLE
Cleanflight will not activate Sonar on SPF3 using Ver 2.0 and higher firmware. 

### ISSUE THREAD

**Issue by WA4KMA** [cleanflight/cleanflight#2877]
#

# 3. If you answered NO to the first question.  Delete everything above this line, read the guidelines (see link above this form) and continue.

# A - Description 

Sonar does not work on SPF3 using Ver 2.0 firmware and up. It works fine on Ver 1.4 , I am not using soft serial or PWM.

# B - Steps To Repeat

-- replace this line with a list of steps to repeat your problem

# C - Video Links

-- provide a link to a video showing your problem, as applicable --

# D - Forum post links

cleanflight.slack.com  Support Mike Keller

# E - Version Information

Cleanflight: v2.0.2 or commit SHA
Configurator: v2.0.3 or commit SHA

# E - Other information

-- provide additional information such as.
-- flight controller SPF3
-- config dump + diff
feature -RX_PPM
feature -VBAT
feature -INFLIGHT_ACC_CAL
feature -RX_SERIAL
feature -MOTOR_STOP
feature -SERVO_TILT
feature -SOFTSERIAL
feature -GPS
feature -FAILSAFE
feature -SONAR
feature -TELEMETRY
feature -CURRENT_METER
feature -3D
feature -RX_PARALLEL_PWM
feature -RX_MSP
feature -RSSI_ADC
feature -LED_STRIP
feature -DISPLAY
feature -OSD
feature -UNUSED
feature -CHANNEL_FORWARDING
feature -TRANSPONDER
feature -AIRMODE
feature -SDCARD
feature -VTX
feature -RX_SPI
feature -SOFTSPI
feature -ESC_SENSOR
feature -ANTI_GRAVITY
feature RX_PPM
feature FAILSAFE
feature SONAR

-- esc make/model/config BL Heli Oneshot 125
-- receiver Spektrum AR7700 PPM
-- transmitter Spektrum DX9
-- schematics
-- diagrams
-- operating system
-- etc.

**Comment by hydra** [comment]
seems fine in master, I can clearly see the sonar signals on my scope here.

if there's still an issue  please provide more information in a new issue and reference this.
