### ISSUE TITLE
Flycolor tower spf3 motor twitch

### ISSUE THREAD

**Issue by CC210** [cleanflight/cleanflight#2888]
When hooked to the computer and battery power the motors twitch and it changes to several motors but only one at a time. Could be esc attempting motor beeps but seems to start before time.

**Comment by McGiverGim** [comment]
What ESC and motor protocol are you using?

**Comment by CC210** [comment]
Raptor 20 amp vs 14.9 on the flyolor tower..using one shot 125



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by hydra** [comment]
check with esc manufacturuer, check wiring (e.g. signal ground), not really enough information to go on here.  closing.  please open a new issue with more information if this is still an issue and reference this one.
