### ISSUE TITLE
Feature Request - Split softserial

### ISSUE THREAD

**Issue by geigerg** [cleanflight/cleanflight#289]
Is there a way to split softserial code. This would be great if there is a way to use softserial 2 and ledstrip or softserial 1 and current-sensing.

**Comment by johnlenfr** [comment]
Would like to use SUMD+LED_STRIP+TELEMETRY on softserial too.

**Comment by hydra** [comment]
there are other related improvements coming to softserial but it's complicated due to timer channel allocation.

please search for existing issues/requsts before posting since this is a duplicate of #113

**Comment by geigerg** [comment]
I'm not that sure about #113 is covering using LED_Strip and softserial at the same time.
