### ISSUE TITLE
Generate PDF manual for v2.1.0

### ISSUE THREAD

**Issue by alanfj** [cleanflight/cleanflight#2891]
It's not currently available, where can I get it?

**Comment by hydra** [comment]
please don't use github for questions like this, use slack support.

answer: it's not been built yet but will be available for the final release and hopefully for the release candidates soon.

**Comment by hydra** [comment]
further to this, the manual build tools no-longer work on the OS I use.

https://github.com/cleanflight/cleanflight/blob/master/docs/development/Building%20Manual.md

I created a PR to allow the manual to be built with markdown-pdf

https://github.com/cleanflight/cleanflight/pull/2897

markdown-pdf seems to be maintained and popular, but currently the hyperlinks in the generated PDF do not work, and there needs to be some styling work.

https://github.com/alanshaw/markdown-pdf

**Comment by DanNixon** [comment]
@hydra If you want something a little more versatile you could have a look at [Pandoc](http://pandoc.org/).

**Comment by hydra** [comment]
We can take a look at this if there is some interest.  Please create a new issue and reference this one if that's the case.
