### ISSUE TITLE
CLI ibata_scale does not accept negative value

### ISSUE THREAD

**Issue by AndreasAusD** [cleanflight/cleanflight#2895]
cleanflight 2.0.5, PIKOBLX board, configurator 2.0.3 

when trying to set ibata_scale to a negative value it is not accepted but allowed range is positive and negative

`# set ibata_scale = 1000
ibata_scale set to 1000
# set ibata_scale = -1000
Invalid value
Allowed range: -16000 - 16000

# 
`

![screenshot](https://user-images.githubusercontent.com/8605512/28249888-a39146dc-6a5e-11e7-9cd3-7b97aab02375.jpg)

**Comment by matty17** [comment]
`# set ibata_scale = 1000 ibata_scale set to 1000
--


Invalid value Allowed range: -16000 - 16000
--




 
--

**Comment by hydra** [comment]
please check with CF 2.1.0-RC2 and report back, i think this might be fixed already.

**Comment by AndreasAusD** [comment]
yes, looks ok with 2.1.0-RC2

accepts the negative value and the current is displayed correctly in the configurator and by telemetrie
