### ISSUE TITLE
Cleanflight configurator V2.1.0-RC1 has problem

### ISSUE THREAD

**Issue by E120103016** [cleanflight/cleanflight#2898]
Hello there:
   The cleanflight configurator V2.1.0-RC1 has a problem. Cause After updating the firmware v2.1.0-RC1, use the cleanflight configurator V2.1.0-RC1. Can not make the settings. Jump directly to the CLI. Is there a problem.

**Comment by hydra** [comment]
seems like your firmware is out of date.  please use the forums or slack for support.  the configurator doesn't jump directly to cli - it will show you a message first, check the message and act accordingly.
