### ISSUE TITLE
Failsafe issue when spin on armed is activated spf3 

### ISSUE THREAD

**Issue by CC210** [cleanflight/cleanflight#2901]
I have the motors set to spin on armed and when I kill the transmitter after throttle up it doesn't stop completly just falls back to the armed idle speed. This is on a flycolor raptor tower.

**Comment by CC210** [comment]
I have it set to drop as well.

**Comment by CC210** [comment]
Maybe I was wrong my bf board does the same I just started experimenting with the spin motors when armed

**Comment by hydra** [comment]
I think this was related to a recent BF issue that has been addressed and merged, I can't find details of it right now though.  If this is still an issue please create a new issue and reference this one.
