### ISSUE TITLE
Why there's no fakeMagDev, while fakeGyroDev and fakeAccDev exists?

### ISSUE THREAD

**Issue by ohshout** [cleanflight/cleanflight#2903]
Looking at the SITL target.c, if I disable the SKIP_IMU_CALC macro, which is defined with such comments:
// use simulatior's attitude directly
// disable this if wants to test AHRS algorithm
#define SKIP_IMU_CALC

It does enable the internal Mahony AHRS algorithm, but at the same time, it also makes cleanflight ignore mag readings from the simulator. Instead, I have to use one of the compass drivers in cleanflight. I wonder why mag doesn't have a fake dev defined like gyro and acc (i know there's a fake mag driver file, but it seems not being used...)? Any techincal or historical reason?

Thanks a lot!

A little bit background: I'm trying to 'abuse' the SITL target to get a quick linux port of cleanflight on the Intel Aero board. I've got gyro, acc and mag drivers working in separate Linux processes and cleanflight built as SITL target. But I'm struggling getting raw mag readings through over UDP and then pumping them into the internal Mahony alg. (I was hoping there's a fakeMagDev, then everything would be just as simple as how fakeGyro and fakeAcc work...)

Any comments or suggestions are highly appreciated.

**Comment by hydra** [comment]
to answer your questions, it's likely just not been developed yet.  feel free to implement it and submit a PR.
