### ISSUE TITLE
Hack for multiwii sensor data unit still valid?

### ISSUE THREAD

**Issue by ohshout** [cleanflight/cleanflight#2914]
Looking at lines in fc/fc_msp.c:

 955     case MSP_RAW_IMU:
 956         {
 957             // Hack scale due to choice of units for sensor data in multiwii
 958             const uint8_t scale = (acc.dev.acc_1G > 512) ? 4 : 1;

Is line 958 still valid? There are accls that have acc_1G=512***8** (e.g., bmi160). Maybe we should have a switch case for acc.dev.acc_1G?

Can someone please confirm if my understanding is correct? If it is, then I'll go submit a PR. Thx!

**Comment by hydra** [comment]
probably related to this:

https://github.com/betaflight/betaflight/pull/3679

**Comment by ohshout** [comment]
@hydra Indeed. I'll wait for the merge then. Thx!
