### ISSUE TITLE
SPRACINGF3 firmware 2.1.0 - GPS settings back to default after reboot

### ISSUE THREAD

**Issue by benni26** [cleanflight/cleanflight#2916]
Hi,

since the 2.1.0 firmware update my GPS dont work anymore. Im using a Ublox GPS on UART2.
After setting the GPS setting in the PORT menu I activate the GPS feature in the configuration menu. After saving settings and reboot the GPS settings und the configuration menu shows the desired settings but GPS doesnt work. After complete power off and restart the configuration menu shows that the GPS settings are back to default means Ublox is NOT selected and the auto config and auto baud rate are also turned off.
Setting it all back to desired values (Ublox, auto config, auto baud) the config shows correct settings but GPS wont work. A reconnect shows that the settings are again back to default.

I think there are two issues:
1. The configuration menu does not show the correct data after changes are safet. Only after a reconnect the correct data is shown.
2. The gps settings are not safed to EEPROM or the settings are overwritten for some reason.

Using previous version 2.0.5 works fine. Settings are keept after reboot and GPS works fine.

**Comment by imarsv** [comment]
https://github.com/cleanflight/cleanflight/issues/2889
