### ISSUE TITLE
Second arm switch

### ISSUE THREAD

**Issue by ijustwannafly** [cleanflight/cleanflight#2920]
I use the safer arm switch logic on my taranis qx7 and it works great.

However, I use a devo7e transmitter for my micros and there is no logic programming available on the tx.

I have tried searching myself but have not been able to mimic the safer switch arm function.

I tried mapping an aux channel to set small_angle to 180 or 0 but that option does not exist in the cli of cleanflight.

Basically there is only one switch option for arming in cleanflight.

Is it possible to add a second mode for arming, say stage1 arm and then stage2 arm where I can use 2 two way switches to arm.

Both arm stages must be in the true position to actually arm.  If one switch is up and the other is down arm won't succeed.  

A check can be used to specify if 2-stage arming is used (for people/tx's that don't have enough switches) and if 2 stage is not used then the traditional one switch arm will be used.

I tested setting small_angle between 0 and 180 to test arming (or no arming) in different positions and even at 0 or 180 the arming is hit or miss on whether it will or not.  I was trying to see if I could force a no arm at all situation but there was times when it would arm when it should have been expected not to.

Thank you for reading.

**Comment by mikeller** [comment]
This is implemented in https://github.com/betaflight/betaflight/pull/3683, and will show up in cleanflight in the next release.
