### ISSUE TITLE
Lack of GPS support for 256kB boards is missing from documentation

### ISSUE THREAD

**Issue by hisalmin** [cleanflight/cleanflight#2921]
# A - Description

The fact that 2.1.0 disables GPS for all boards with 256kB flash is missing from release notes, GPS configuration docs, etc.

The release info <https://github.com/cleanflight/cleanflight/releases> only mentions NAZE32 and "older targets", which probably means F1 boards. F3 boards are not mentioned. Other docs have not been updated after commit 6a1f1f3df5ac5ec07dd9f1224f2d90c162e2db54 which disabled GPS.

**Comment by hydra** [comment]
i will update the release notes, thanks.
