### ISSUE TITLE
SPF3 6DOF external mag not connected

### ISSUE THREAD

**Issue by matevz25** [cleanflight/cleanflight#2931]
Hello my SPF3 6DOF external mag HMC5883L doesnt work. Its connected to I2c port. Cleanflight wont recognize it. CLi mag enabled HMC5883, tried 3,3V power  from FC and  5V from PDB. Same. Scl and Sda have aprox 2,2V input/ output. I have tried 2 sensors. I have tried i2c highspeed but command doesnt work. 
What else can I do? FW is 2.0.5, on latest gps doesnt work for me.Thank you !

**Comment by mikeller** [comment]
GPS has been disabled on F3 because of flash size constraints.

**Comment by matevz25** [comment]
Ok, on 2.0.5 gps works. Problem is mag. Why it doesnt work?

**Comment by hydra** [comment]
if your firmware has mag support then mag will work on the SPRacingF3 since the other sensors are also connected via I2C.   CLI commands for mag would not be available if there was no mag support in the firmware.

I don't thing we have enough information to solve your problem. Closing.
