### ISSUE TITLE
Throttle stuck at idle when motor stop on with CL Racing F4 board.

### ISSUE THREAD

**Issue by hattrickmwf** [cleanflight/cleanflight#2938]
#

# A - Description

If motor stop is enabled,  then the throttle is stuck at idle and will not advance at all.  It will arm.  The props will start and stop at idle when airmode is turned on or off.  Throttle functions normally on the receiver page.  Motor spin up normally on the motors tab.  Turning off throttle stop does not make the problem go away.  The board has to be reflashed to correct the problem.  
Quad will function normally if airmode is set as a feature.  

# B - Steps To Repeat

Turn on motor stop and have airmode on a switch.

Betaflight 3.2 RC4
Configurator: Betaflight 3.2.1

# E - Other information
CL Racing F4

**Comment by hydra** [comment]
not enough information to reproduce, probably mis-configured channel endpoints.  if this is still an issue please create a new issue with more information - perhaps include a video showing the issue and a config dump/diff.
