### ISSUE TITLE
FEATURE REQUEST - Autosearch/Autoconfig

### ISSUE THREAD

**Issue by ps915** [cleanflight/cleanflight#2960]
did not find a similar feature request, so i will publish it.
I it possible to get a auto search button for finding and configurating devices like receivers, and other uart devices. 
I get manny help requests on my blog (https://blog.seidel-philipp.de) how to configure devices like receivers and other UART stuff. For beginners, this auto config would be a big help.

Is there any plan to implement it in the future?

**Comment by mikeller** [comment]
This should rather go into https://github.com/cleanflight/cleanflight-configurator/issues .

**Comment by ps915** [comment]
oops, sure. dont know why i posted it here. ;) closed
