### ISSUE TITLE
option to set the maximum throttle on anti turtle mode

### ISSUE THREAD

**Issue by grhookgr** [cleanflight/cleanflight#2963]
sometimes we push the stick too much making the copter to jump to much, = roll 360.
it will be nice if we have the option to limit the maximum throttle on anti-turtle mode.

**Comment by Jahnkeanater** [comment]
I would rather have too much throttle than not enough. Some quads are more difficult to flip than others. If there was a limit it would need to be configurable.

**Comment by fiveangle** [comment]
Do you have expo on your TX ?

**Comment by grhookgr** [comment]
i was thinking a "set max_recover_throttle= 1750"  or the desired value it may just work to help us recover faster. 
it may be even configurable from osd

**Comment by fiveangle** [comment]
Is that a yes or a no ? 😁

**Comment by grhookgr** [comment]
:) No expo

**Comment by Quick-Flash** [comment]
this has been implemented into EmuFlight

**Comment by haslinghuis** [comment]
Cleanflight >= 4.2.0 has [new rates modes](https://github.com/cleanflight/cleanflight/wiki/4.2-Tuning-Notes#new-rates-modes) :)
I guess rates and expo are a personal preference.
