### ISSUE TITLE
failsafe method naming

### ISSUE THREAD

**Issue by Philippe-France** [cleanflight/cleanflight#298]
Hi Hydra

may I suggest some cleaning of the failsafe code:
- in failsafe.c definition of Vtable uses failsafeCheckPulse (line 179)
- while failsafe.h uses (*checkPulse) (line 38) like rest of the code.

Using same name in all the code could help make it readable.

Regards
Phil

**Comment by hydra** [comment]
the failsafe interface is abstracted from the implementation, but perhaps there is merit in this.  Failsafe is a trial use of vtables for possible mocking/stubbing of failsafe behaviour when testing failsafe integration.

**Comment by hydra** [comment]
Closing, failsafe has been reworked.
