### ISSUE TITLE
 stm32 communication failed, wrong response, expected: 121 (0x79) received: 31 (0x1f)

### ISSUE THREAD

**Issue by kondorpek** [cleanflight/cleanflight#2984]
#Hi! I trying to flash my controller, but always get error
stm32 communication failed, wrong response, expected: 121 (0x79) received: 31 (0x1f)
but blue LED is light...
my flight controler is : Naze32 Rev6 10dof

please help me..

**Comment by mikeller** [comment]
@kondorpek: GitHub is for questions and discussion around the **development** of the firmware and tools. For questions around the configuration and use of cleanflight, please visit [RCGroups](https://www.rcgroups.com/forums/search.php?query=betaflight%20cleanflight%20serial%20connection).
