### ISSUE TITLE
Add target for STEVAL-FCU001V1 

### ISSUE THREAD

**Issue by KiranKanchi** [cleanflight/cleanflight#2988]
# A - Description

Anybody tried FCU001V1 flight controller evaluation board from ST ? 
if yes, any port planned ? 

http://www.st.com/en/evaluation-tools/steval-fcu001v1.html

# C - Video Links

https://www.youtube.com/watch?v=vGFqIDVpMT4

# D - Forum post links

https://github.com/STMicroelectronics-CentralLabs/ST_Drone_FCU_F401

**Comment by mikeller** [comment]
@KiranKanchi: Good suggestion!

**Comment by hydra** [comment]
no-one has picked up on this, closing as there appears to be no interest in the target.
