### ISSUE TITLE
RX - FrSKY 18ms PPM Support

### ISSUE THREAD

**Issue by hydra** [cleanflight/cleanflight#30]
Merge this:

https://github.com/Crashpilot1000/TestCode3/commit/75f7a67587a158ce45854a99724cc8cba7fe65ad

**Comment by hydra** [comment]
New PPM code exists.  A test need to be done with a non-upgraded FrSky RX to make sure the new PPM code works with it before this can be closed.

**Comment by hydra** [comment]
See this for details:

http://diydrones.com/profiles/blogs/frsky-s-cppm-at-27msec-firmware-update-with-ft-prog-and-ftdi-cabl

Basically, the test is to get an old 18ms RX, set all channels to 100% and make sure the values shown in the configurator read 100% / ~2000 and then move each from 0 to 100% ensuring that all the other channels are still displayed correctly.

**Comment by thenickdude** [comment]
Isn't that torture test guaranteed to fail on the 18ms firmware, as the 18ms firmware doesn't have a distinguished longer gap that would signal the end of frame? (so no way to distinguish which channel is which)

**Comment by hydra** [comment]
@thenickdude quite possibly, but we need feedback!
