### ISSUE TITLE
Build - Create HTML documentation build artifacts.

### ISSUE THREAD

**Issue by ulope** [cleanflight/cleanflight#300]
http://readthedocs.org is a (at least in the Python community) very popular (and free for open source) documentation hosting service. They provide a nice online view with search, as well as automatically create offline downloadable versions (PDF, ePub).

IMO it would be very nice to have the docs in a bit more "official" style than the source files on github.

**Comment by hydra** [comment]
I won't be working on this as I'm happy enough but understand other users might want better html docs.

I would accept a PR that introduced a system that builds HTML format docs that could later be uploaded somewhere as part of the automated builds.
