### ISSUE TITLE
Crazepony NRF communication issue

### ISSUE THREAD

**Issue by AsadMasood** [cleanflight/cleanflight#3008]
Hi,
I'm trying to make a swarm of crazepony quadcopters, I'm unable to communicate NRFL24L01+ from my PC to NRF on crazepony quadcopter? anyone help me out?
I wrote same code in C of NRF source code but from PC it is unable to communicate with the NRF of the crazepony quadcopter.

**Comment by mikeller** [comment]
What hardware are you using? I could only find information on crazepony hardware that supports FrSky protocols, not NRF24.

**Comment by AsadMasood** [comment]
Hardware is crazepony ,it has NRF24L01+

https://www.amazon.com/dp/B015MYR1GO

**Comment by mikeller** [comment]
Looks like it's not supported by cleanflight or Betaflight. Ask the manufacturer to supply you with firmware and instructions for it.

**Comment by AsadMasood** [comment]
I have asked but they won't reply.
Actually the issue I'm facing is in communication of NRF with the PC
