### ISSUE TITLE
Eachine Wizard X220 arming issue

### ISSUE THREAD

**Issue by Darkpassenger23** [cleanflight/cleanflight#3012]
I just bought an Eachine Wizard X200 RTF for my first FPV drone to learn on. After going through youtube tutorials, I finally got it set up but it would instantly flip over.

I updated the Yaw setting to 270 as instructed on various forums and it fixed the flipping issue (Looks good now in Betaflight) however it will not arm now.

Does anyone know how to resolve this issue?

**Comment by mikeller** [comment]
@Darkpassenger23: GitHub is for questions and discussion around the **development** of the firmware and tools. For questions around the configuration and use of Betaflight, please visit [RCGroups](https://www.rcgroups.com/forums/search.php?query=betaflight%20cleanflight%20configuration%20use).
