### ISSUE TITLE
Angle mode

### ISSUE THREAD

**Issue by yasha107** [cleanflight/cleanflight#3013]
I have 4 channel radio (FS-T4B) i have naze32 6dof, i don't want to use acro mode (its set do default) i want to use angle mode, how do i do it?? (I cant set it on modes tab because i just don't have any AUX)

**Comment by mikeller** [comment]
@yasha107: GitHub is for questions and discussion around the **development** of the firmware and tools. For questions around the configuration and use of Betaflight, please visit [RCGroups](https://www.rcgroups.com/forums/search.php?query=betaflight%20cleanflight%20configuration%20use).
