### ISSUE TITLE
Radiolink SE100 GPS/Compass Magnetrometer not seen

### ISSUE THREAD

**Issue by alanfj** [cleanflight/cleanflight#3014]
Need help getting Magnetometer to work. GPS is working OK. Has a QMC5883 compass, it may be a HMC5883L clone. I am using a Cleanflight SPRACINGF3 board w/version 2.20. Is it a software issue and/or a hardware problem?

**Comment by hydra** [comment]
Use a supported compass first, if that works then try your new one.  Check that the target firmware you are using has support for the compass you want to use.
