### ISSUE TITLE
Please add feature to reduce Tricopter Tail-Wag.

### ISSUE THREAD

**Issue by ResinSmoker** [cleanflight/cleanflight#3018]
**# A - Description**

Would it be possible to add some sort of Servo or Yaw specific "smoothing" so Tailwag wouldn't be so intense. Often the Wag is out of control making the Tricopter either unflyable or near impossible to tune.
It's as if the Servo is constantly overshooting target regardless of Filter / PID / CLI settings used.

**# B - Steps To Repeat**

Typically high frequency Wag is seen immediately after arming, before throttle up. After which the Wag dissipates while the throttle is being manually held above idle. Later low frequency Wag can often show up during sharp turns and fast straits. This makes the Yaw control sloppy at best, unflyable at its worst.
Lowering the Yaw P-Term to extremely low values does remove the pre-throttle up oscillation but essentially makes the Copter unflyable. Lowering the tri_dynamic_yaw_boost can also help but it gets to the point where it makes the Tricopter unflyable as well.

Note: Full Tail-Tune / calibration completed.

Edit: The Wag appears to be a combination of both Yaw (naturally) and Roll. With the Roll being induced from the motors mass being held slightly above the Servo's pivot point. In a sense the Copters weight is shifting from side to side slightly as the Servo pivots its axis, tossing the motor to one side or the other. There are a large number of copters that handle just fine like this but others, especially those with the more sensitive IMU's tend to overreact badly.

**# C - Video Links**

Examples:
Stationary wag https://www.youtube.com/watch?v=SeXPp4LuZms
Under Throttle https://www.youtube.com/watch?v=f6tYqGBGsXg

**# D - Forum post links**

There are tons of links as this is a very common issue for Tricopters.

**# E - Version Information**

Betaflight 10.1.0
Triflight on Betaflight 3.2.2 v2 / MATEKF405 (MKF4) 3.2.2 Dec 31 2017 / 15:24:22 (30f68c8) MSP API: 1.36

**# E - Other information**

-- Flight controller make/model : MATEK F405 AIO
-- Dump: https://pastebin.com/x3118UF8
-- Diff: https://pastebin.com/0YJesKyN
-- “Aikon” AK32 35A 6S BLHeli_32 ESC’s See image for more ESC details https://flic.kr/p/DXf5Kp
-- FrSky R-XSR with EU firmware from mfr (FW-RXSR-171103)
-- Taranis X9D (EU) FW: opentx-x9d+  Vers: 2.2.1  Date: 2017-12-17 EEPR: 218
-- Schematics (None)
-- Wiring diagrams: https://flic.kr/p/23sQEuz
-- Windows 10
-- Tricopter wired up with 470uf 35v capacitors for all ESC's and 1000uf 35v for Battery.
-- Servo has attached feedback wire.
-- Everything is soft mounted, except for the Sevro and Tilt mechanism (not possible).
-- Also have an F3FC based Tricopter from RCexplorer with the same issues.
-- [Blackbox of Tricopter Tail-Wag 2-21-2018.zip](https://github.com/cleanflight/cleanflight/files/1744846/Blackbox.of.Tricopter.Tail-Wag.2-21-2018.zip)
If for some reason it does not show try using my Google Drive: https://drive.google.com/file/d/1tUX49k2bRePZNE_VHBLZVh-HK8wEIy4f/view?usp=sharing
-- Soon to upgrade the FC to Matek F405 CTR with the less sensitive IMU. Once that's done I'll report back with results.

**Comment by mikeller** [comment]
@lkaino this might be of interest to you.

**Comment by ResinSmoker** [comment]
Adding a Log file but unsure if it's here as I don't see it attached anywhere.

**Comment by ResinSmoker** [comment]
Closing request and reposting to Betaflight
