### ISSUE TITLE
GPS Logging help

### ISSUE THREAD

**Issue by theSkonk** [cleanflight/cleanflight#3020]
would be nice to add gps data to the debug mode so an on board gps unit can logged ( personally for speed data )

**Comment by ledvinap** [comment]
GPS logging is already implemented, as separate GPS frames, in blackbox ..

**Comment by theSkonk** [comment]
really where ?

**Comment by ledvinap** [comment]
https://github.com/betaflight/betaflight/blob/master/src/main/blackbox/blackbox.c#L235-L262
https://github.com/betaflight/betaflight/blob/master/src/main/blackbox/blackbox.c#L1471

**Comment by theSkonk** [comment]
how does one access the data? i cant find any information on how to use it ( sorry if I'm a bit thick )

**Comment by ledvinap** [comment]
Try https://github.com/cleanflight/blackbox-tools .. 
Not sure about blackbox-log-viewer, maybe it doesn't implement it. It would be quite easy to implement

**Comment by theSkonk** [comment]
so put a request into the black box thread? its really not easy to use the tools there are no clear 'how to' information

**Comment by ledvinap** [comment]
Did you read the README for blackbox tools?

**Comment by theSkonk** [comment]
so I've worked it out.. its still really... really, REALLY complicated

**Comment by hydra** [comment]
if you would like to help by improving things to make it easier please create documentation or code and/or submit a PR.  glad you worked it out though.   if you could explain which part in particular you had issues with that would help.

**Comment by theSkonk** [comment]
hey man yeah the phrasing of the commands has to be exactly right as does the file your using and if your not quite familiar with running command line stuff the read me file doesn't give an example so the less smart know what to do..
if the info is embedded in the black box logs would it be east to added it as a plot-able in black box?

**Comment by hydra** [comment]
this is going off-topic now.  closing.  if you have ideas, etc then please create a new issue.  for help using the software please use forums or slack.
