### ISSUE TITLE
SPF3 acro/delux Unable to connect GPS 

### ISSUE THREAD

**Issue by StraTech** [cleanflight/cleanflight#3025]
I tried migrating fron CF F/W Ver 1.14.1 to CL 2.0.0 and up and have been unable to get my GPS to work on my SPRF3 since. Also BT on Softserial port wouldn't work (Tried lowering to 19.200 but no luck)
It works fine when going back ver1.14.1-     GPS (Ublox 7 firmware)
I tried I think all F/W Versions above 2.0.0 and used 2.1.0  but noticed when I set uart2 to GPS AUTO it would set to 57,600 when it was actually 112,500 . I have tried to reconfiguring GPS and no go. Something funny going on.
I'm giving in and will try INAV. But thought I'd just bring this up before trying. I apologise if I missed something.

**Comment by hydra** [comment]
you're probably using a build that doesn't have GPS support compiled in.  GPS support is only compiled in on targets with > 256K FLASH now.

Feel free to build a custom version that has what you need, see documentation.
