### ISSUE TITLE
first drone: "failed to connect to serial port" - NEED HELP :)

### ISSUE THREAD

**Issue by Driyyel** [cleanflight/cleanflight#3038]
hi guys,
I'm building my first drone at the moment, and am stuck at the configuration process of my SP racing F3 flight controller. I installed all the drivers that are recommended at the cleanflight welcome menu, and tried to fix my issue with the impulseRC driver fixer... didn't work. also did some research, but none of the solutions seemed to function for me. here's a picture with the error, if that helps in any way, the fc was connected when I took the screenshot
![capture](https://user-images.githubusercontent.com/37918288/38120720-076ff264-33ba-11e8-82b4-c8540f3a4ad1.PNG)
I'm on windows 7
zadig can't find the usb to uart bridge controller 
![capture](https://user-images.githubusercontent.com/37918288/38121127-e607e106-33bc-11e8-9843-242de94280db.PNG)
f anyone knows how to fix this issue, please tell me, I'm lost
thanks,
timo

**Comment by mikeller** [comment]
Have you tried with a different USB cable?

**Comment by Driyyel** [comment]
sadly didn't make any difference... but thanks anyways. any other idea?

**Comment by hydra** [comment]
please can you use a support forum or slack for support rather than github. thanks.
