### ISSUE TITLE
SPRacingF7DUAL, bind button and UART5_RX conflict.

### ISSUE THREAD

**Issue by emski0** [cleanflight/cleanflight#3045]
To get the ESC sensor telemetry on UART5_RX, the vtx bind button should be disabled.
In _target.h_:
Comment these lines:

//#define USE_BUTTONS
//#define BUTTON_A_PIN            UART5_RX_PIN
//#define BUTTON_A_PIN_INVERTED

Without commenting these line the esc doesn't initialize ,and FC freezes.
--------------------
**CAMERA CONTROL:**

To get Camera Control working on  on the CAM_OSD_CONTROL pin(OSD socket):
A timer needs to be defined in target.c:
DEF_TIM(TIM2,  CH1, PA0,  TIM_USE_ANY,                 0, 0), // // USED FOR CAMERA CONTROL

and comment the led strip timer:
//DEF_TIM(TIM2,  CH2, PA1,  TIM_USE_LED,                 0, 0), // LED Strip

_ADD CAMERA CONTROL PIN:_

One of the two solution:
1)Add camera control pin in target.h:
#define CAMERA_CONTROL_PIN      PA0 // Camera control.
OR
2) IN CLI : 
resource CAMERA_CONTROL 1 A00

**Comment by mikeller** [comment]
You are barking up the wrong tree here, @emski0. The ESCSERIAL functionality is what is used by the `escprog` serial port to ESC forwarding functionality, and **not** by ESC telemetry. ESC telemetry can be used on any UART RX pin (hard or soft serial).

**Comment by emski0** [comment]
@mikeller i didn't know , i thought it's for the esc sensor,
I modified the first post and title

**Comment by hydra** [comment]
yes you are correct, the bind buttons is on the same pin as uart5_rx.  Yes, ideally the bind button code needs to be able to be disabled in software.  There is work going on to enable this kind of thing in betaflight 4.0, for now doing what you suggest and building custom firmware is the solution for you.

**Comment by hydra** [comment]
Should also note that VTX control button ideally also needs to be configurable independently from the bind button.  The button code also needs to be re-worked so that it doesn't pause the main loop waiting for the button to be released, but doing that without allowing it to be disabled is fairly pointless since any device connected to UART5_RX would likely cause the FC to think someone was pressing the button.

**Comment by hydra** [comment]
I think, with the code in `master` now you should be able to use the `cli` resource command to remove the RX pin from UART5.  If this is still an issue and that doesn't work, please re-open this issue.
