### ISSUE TITLE
MSP beginner help needed.

### ISSUE THREAD

**Issue by johthu** [cleanflight/cleanflight#3052]
Hi,

Could we get msp telem back?

https://github.com/cleanflight/cleanflight/issues/1278
This says it's msp but apparently this has been removed.

And how would you tap into this to receive sensor data from the board like the IMU and stick positions and transmit data like PID values etc. Since the configurator can do all this how can I?

Thanks alot!

**Comment by mikeller** [comment]
@johthu: Have you tried `MSP_RC`, `MSP_ATTITUDE`, `MSP_PID` (and many more)?

**Comment by johthu** [comment]
Hi, thanks for the reply,
Do you mean use those commands in the cli?

**Comment by johthu** [comment]
Because they don't seem to work

**Comment by mikeller** [comment]
No, they are MSP commands that you can use to get sensor data, IMU data, and stick positions over MSP.

**Comment by johthu** [comment]
How do I use these?

**Comment by mikeller** [comment]
The same way you'd use MSP telemetry.

Have a look at https://github.com/cleanflight/cleanflight-configurator/blob/master/src/js/msp/MSPHelper.js for application examples.

**Comment by johthu** [comment]
Ah thanks, would it be possible to write this in c or python?

**Comment by mikeller** [comment]
Yes, sure is.

**Comment by mikeller** [comment]
@johthu: Have you looked into using one of the libraries that are out there that implement an MSP client, like https://github.com/fdivitto/MSP ?

**Comment by hydra** [comment]
closing as stale.
