### ISSUE TITLE
Unable to set MSP RX input as receiver mode

### ISSUE THREAD

**Issue by micahterrell** [cleanflight/cleanflight#3055]
Hello, 

The steps to replicate are simply connecting over serial, and setting the receiver mode in the configuration tab.

I'm using v2.1.0 of the configurator, with the firmware being v2.3.2 on the FC.

My FC is an F3_EVO_Brushed.

**Comment by mikeller** [comment]
@micahterrell: RX_MSP support has had to be removed from SPRACINGF3EVO in order to make the firmware fit into the flash space available.
