### ISSUE TITLE
new to all this

### ISSUE THREAD

**Issue by syotosc6** [cleanflight/cleanflight#3056]
# 1. ARE YOU REQUESTING SUPPORT?

-- YES / NO -- yes

# 2. If you answered YES to the above question go here instead:

https://www.rcgroups.com/forums/showthread.php?2249574-Cleanflight-firmware-for-STM32F3-based-FCBs-Check-First-Post-Please%21%21

Alternatively use other forums, slack or IRC for support.

# 3. If you answered NO to the first question.  Delete everything above this line, read the guidelines (see link above this form) and continue.

# A - Description

not getting any reply when i plug unit in to pc, just getting both lights on drone and when i try to connect on cleanflight i get this, please look at image 

![new bitmap image](https://user-images.githubusercontent.com/39659981/41385240-2d21bfc6-6f72-11e8-8e7a-27f71fc8fb8f.jpg)

# C - Video Links

seen videos on youtube how to do so but no luck

# E - Version Information

2018-06-14 @ 01:31:34 -- Running - OS: Windows, Chrome: 67.0.3396.87, Configurator: 2.1.0

# E - Other information

-- flight controller make/model...F3 Flight Controller Acro 6 DOF/Deluxe 10 DOF for RC Multirotor FPV Racing Drone

-- config dump + diff
-- esc make/model/config...Racerstar RS20Ax4 V2 20A BB2 48MHz Blheli_S 2-4S 4 in 1 Opto ESC Support Oneshot42 Multishot 16.5 Dshot600 

-- receiver make/model/config...Turnigy Evolution Digital AFHDS 2A Radio Control System w/TGY-iA6C Receiver (Black) (Mode 2)

-- transmitter make/model/config
-- schematics
-- diagrams
-- operating system...windows 10
-- etc.
please help

**Comment by mikeller** [comment]
Please read the top of your request thoroughly.
