### ISSUE TITLE
OSD feature won't enable

### ISSUE THREAD

**Issue by bhomma** [cleanflight/cleanflight#3057]
# 3. If you answered NO to the first question.  Delete everything above this line, read the guidelines (see link above this form) and continue.

# A - Description

The osd feature in the cleanflight configurator will not stay enabled after I set the osd feature to "on" and then click "save and reboot"

# B - Steps To Repeat

FC is flashed with latest naze firmware.  Connect to configurator and go to the configuration tab in cleanflight.  Go to the features menu and enable osd feature.  Click save and reboot.  

# C - Video Links

-- provide a link to a video showing your problem, as applicable --

# D - Forum post links

-- provide links to forum posts if you have discussed this with others --

# E - Version Information

Cleanflight: vX.X.X or commit SHA
Configurator: vX.X.X or commit SHA

# E - Other information

-- provide additional information such as.
-- flight controller make/model
-- config dump + diff
-- esc make/model/config
-- receiver make/model/config
-- transmitter make/model/config
-- schematics
-- diagrams
-- operating system
-- etc.

**Comment by mikeller** [comment]
NAZE does not have OSD hardware.

**Comment by bhomma** [comment]
the board is the lluminati 32 with built in osd

**Comment by bhomma** [comment]
it says in the configurator that some feature combinations are considered invalid is it possible that I have some features enabled that would cause it to automatically disable the osd feature?

**Comment by mikeller** [comment]
If you'd provided the information that you were asked to provide when opening this issue then you probably could have been helped the first time round...

This board is not supported by cleanflight. Ask the manufacturer / supplier to provide you with updated firmware.
