### ISSUE TITLE
altitude.c

### ISSUE THREAD

**Issue by Cybirbug** [cleanflight/cleanflight#3059]
Looks like baro mode altitude files have been phased out for 2.4,..

I have a different working version of the altitude.c file from 2.3.1 that could use additional testing on other platforms. No other file changes needed when using in 2.3.1 Multirotor on barometer only.

[altitude.zip](https://github.com/cleanflight/cleanflight/files/2233900/altitude.zip)

successful flights on a modified f3 board with a bmp280, with these settings:
set p_alt = 70
set i_alt = 2
set d_alt = 1
set p_vel = 70
set i_vel = 1
set d_vel = 1
set alt_hold_fast_change = OFF

**Comment by hydra** [comment]
thanks for sharing, however the correct way to share code changes is via a pull request.  you can still request changes and target your PR to a maintenance branch if needed.
