### ISSUE TITLE
Accelerometer and Gyroscope not working on STM32F3Discovery

### ISSUE THREAD

**Issue by jonpas** [cleanflight/cleanflight#3072]
**Describe the bug**
Accelerometer and Gyroscope sensors not working on `STM32F3Discovery` since `v2.4.0` or higher (also tested `v2.5.0-RC1`), they work fine with `v2.3.2`.

**To Reproduce**
- Flash `cleanflight_2.4.0_STM32F3DISCOVERY.hex`/`cleanflight_2.5.0_STM32F3DISCOVERY.hex`
- (Install Cleanflight Configurator `v2.5.0-RC1` if 2.5.0)
- Reboot
- Open in Chrome-installed Cleanflight Configurator
- Navigate to Sensors (or stay on first page to see 3D representation)
- See no input from Accelerometer or Gyroscope (Magnetometer works fine however).

**Expected behavior**
Movement in the Accelererometer or Gyroscope graphs and moving 3D model on first tab, just like in `v2.3.2`.

**Flight controller configuration**
It is a fresh flash (on all 3 versions), here is `v2.4.0` example:
```
# diff
# Cleanflight / STM32F3DISCOVERY (SDF3) 2.4.0 Jul 16 2018 / 18:26:35 (73a6edeca) MSP API: 1.39


profile 0

rateprofile 0
```

**Setup / Versions**
 - Flight controller: STM32F303VCT6
 - Other components: None, same result with everything disconnected (sensors are on the board itself)

**Additional context**
None

**Comment by mikeller** [comment]
Looks like the gyro and acc used on-board on the STM32F3DISCOVERY was declared legacy, and support for it removed, since no actual target uses them.

I am currently debating as to whether it makes sense to reinstate these drivers and update them to work with the latest changes.

**Comment by jonpas** [comment]
What would be the quick rundown of required changes?

**Comment by mikeller** [comment]
@jonpas: The L3GD20 and LSM303DLHC gyro / acc drivers have to be updated to conform with the new gyro/acc driver API. I am looking into this, will keep you posted.

**Comment by mikeller** [comment]
@jonpas: Can you please try this to see if this works for you:

[betaflight_4.0.0_STM32F3DISCOVERY.zip](https://github.com/cleanflight/cleanflight/files/2704593/betaflight_4.0.0_STM32F3DISCOVERY.zip)

(from betaflight/betaflight#7241)

**Comment by jonpas** [comment]
Oof, I completely forgot about this. Sadly I no longer have the F3 shortly after last comment on this was made.

**Comment by hydra** [comment]
Ok, thanks for the update, closing this issue.
