### ISSUE TITLE
NAZE firmware 2.3.2 magnetometer not detected

### ISSUE THREAD

**Issue by antoniosap** [cleanflight/cleanflight#3073]
Configurator: 2.5.0
Firmware: CLFL 2.3.2

**Comment by Marineserver** [comment]
> Configurator: 2.5.0
> Firmware: CLFL 2.3.2

Dear fried i have send you an hex file flash it with the same else u r magnetometer might have bad or else your wiring might have wrong or wire may faulty...

**Comment by MauroMombelli** [comment]
@antoniosap what board do you have? can you post the chip model number?

**Comment by Marineserver** [comment]
I have bluepill stm32 mini dev board

**Comment by hydra** [comment]
For development of new FC's or issues wiring up development boards please use the Cleanflight slack channel.
