### ISSUE TITLE
How could I add new hardware support?

### ISSUE THREAD

**Issue by wuyoutech** [cleanflight/cleanflight#3077]
The space on my aircraft is very narrow so I have to customize a new flight control board. I want to try running  Cleanfilght on it. It seems that I need to create a new target.h and some other files, but I'm not sure what needs to be modified, maybe I missed a lot.

So my question is whether these is a document for developer to tell me if I want to support my hardware which parts should I modified and which macros should I define such as USE_GYRO and USE_BARO and so on.
If not, I can still finish my job, but it will cost a lot of effort and may have a ton of bugs.

**Comment by mikeller** [comment]
@wuyoutech: Have a look at existing target configurations - most of the contents should be pretty straightforward if you are into hardware design, and have worked with the components of a flight controller before.

You also might want to join the Betaflight Slack (registration at https://slack.betaflight.com/), a lot of the core developers are on there, and you can ask questions.

**Comment by wuyoutech** [comment]
Thank you !
