### ISSUE TITLE
Eachine E010s Lemon Frsky v1

### ISSUE THREAD

**Issue by tomasris** [cleanflight/cleanflight#3082]
Hello. Can you help do support with Lemon Frsky v1 (Betaflight version dump: # Betaflight / LEMONF3-FRSKYV1 (LEMO) 3.2.3﻿) RC board ? Lot people flashed this with old manuals from youtube, and lost drones. Eachine wrote in manual about your software for any help upgrade firmware :)
https://www.eachine.com/downfile.html?path=2016/eachine/20171026/59f1959228623-Eachine%20E010S%20Flysky%20Manual.pdf

**Comment by mikeller** [comment]
@tomasris: Eachine is breaking the license of Betaflight / cleanflight by publishing firmware for their hardware that is based on Betaflight / cleanflight, and not publishing the sources as well. You should return this hardware to your supplier, as it is most likely against the law in the country you are in to use software that is in breach of licensing restrictions.
Apart from that there is nothing that can be done as long as Eachine is using unlawful practices by not publishing the changes they make to the firmware for the hardware they are selling.
