### ISSUE TITLE
SPracing F3 deluxe - Disarming when moves sticks fast 

### ISSUE THREAD

**Issue by henriquewatanabe** [cleanflight/cleanflight#3083]
When the multicopter is armed and take off to flight and move the sticks of aileron or elevator too fast or agreesive position, and the drone starts move, but in this time the board disarme and you have to turn off the switch and re-arm again.

1 - Arm the quadcopter.
2 - Take off.
3 - Move the sticks of aileron or elevator too fast.
4 - when the drone calculates the angular motion he desarm.
5 - It only occurs when the gyro calculate the angular motion. If you move the sticks of controller
and hold the drone it looks fine.

List of parts:
SP Racing F3 Deluxe. (FC)
Firmware - Cleanflight 2.5
ESC - Sky RC 12a
Receiver - FlySky i6 mode PPM
Motors: 2300kv GOOLRC

Standard settings. Loop time and Gyro 

Observation. If the Super rate is 0.70 up. Cause this issue.
In Betaflight 3.5.7 is the same problem!!!!

**Comment by hydra** [comment]
@henriquewatanabe please retest with latest code from `master` and re-open if there's still an issue.
