### ISSUE TITLE
Serial RX Protocol Add request

### ISSUE THREAD

**Issue by dfmcwhir** [cleanflight/cleanflight#3084]
# A - Description

This is a feature or enhancement request to add a new serial RX protocol. This would be to enable the Yuneec Serial protocol allowing people to use their commercial Yuneec ST16, ST24 and/or ST10(?) radios with cleanflight based DIY drones. 

While this is probably a relatively small group of people who want to do that, I also think this feature would be fairly easy to add because there is already existing code for the protocol for the PX4 firmware (see the ST24 source code here: https://subak.io/code/ardupilot/ArduCopter-3.5/modules/PX4Firmware/src/lib/rc/).

I know the code works to get RX channel data from the yuneec rx because I used that code linked above as an arduino library and programmed a esp8266 to convert the output from that channel data into PPM. It would be nice to not have to have an additional microcontroller to interface the Yuneec RX to a Cleanflight compatible FC. 

# B - Steps To Repeat
N/A
# C - Video Links
N/A
# D - Forum post links

https://yuneecpilots.com/threads/typhoon-h-st-16-controller-can-it-be-re-purposed.9970/

# E - Version Information

Cleanflight: vX.X.X or commit SHA
Configurator: vX.X.X or commit SHA

# E - Other information

-- provide additional information such as.
-- flight controller make/model
-- config dump + diff
-- esc make/model/config
-- receiver make/model/config
-- transmitter make/model/config
-- schematics
-- diagrams
-- operating system
-- etc.

**Comment by hydra** [comment]
Interesting, but I don't thing it's something that would be useful to add at this point in time. 

The main issue is are:
* the amount of users who would benefit
* maintenance of any new code over time (code ownership)
* testability (code owner and QA would need hardware)
* lack of flash space in the MCU's for another RX protocol.
