### ISSUE TITLE
cleanflight_2.5.0 dont work on CC3D board

### ISSUE THREAD

**Issue by fa1ke5** [cleanflight/cleanflight#3085]
2.5.0 and 2.5.0 RC1 version dont working on CC3D, v2.4.0 is working and flashing, but if im flashing v2.5, i have only green led after and no USB device.
im using configurator v2.5.0

**Comment by sergey-prokhorov** [comment]
same problem

**Comment by sreichholf** [comment]
See #3075 (this pretty much for sure, a general issue with al F1 FCs)

**Comment by stray77** [comment]
OpenPilot Final CC3D Release 15.02.02
https://drive.google.com/open?id=0B0Sk1AY5oe7DUnJKMzJteVNjTjg

**Comment by hydra** [comment]
Please build the CC3D target using code in `master` and re-test.  Re-open if there's still an issue.
