### ISSUE TITLE
pwm rx betaflight

### ISSUE THREAD

**Issue by djvanhard** [cleanflight/cleanflight#3086]
**Important: This is not the right place to get help with configuration issues. Your issue will be closed without further comment.**

Please get help from other user support options such as asking the manufacturer of the hardware you are using, RCGroups: https://www.rcgroups.com/forums/showthread.php?2249574, or Slack (registration at http://cleanflight.com/slack/) or other user support forums & groups (e.g. Facebook).
Hello, i can't set "PWM RX INPUT" in betaflight, i set it but when i restart it reset "PPM RX".Why this?

**Comment by hydra** [comment]
Probably as the PWM support is not enabled in the firmware you're using.  Add it and compile custom firmware for your needs, see the `docs` folder.

**Comment by hydra** [comment]
Also, this is the issue tracker for CLEANFLIGHT, not Betaflight. 😄
