### ISSUE TITLE
After flasing to NAZE32 6DOF, nothing happen

### ISSUE THREAD

**Issue by tom9un** [cleanflight/cleanflight#3102]
I have flashed to naze32 6dof and it done, but after I connected nothing happened, there was no 3D drone display as usual. After that I cant flashing again normally, have to flash by boot using baseflight.hex...Is this firmware version can not be use with naze32 6DOF with 64k flash ?...

**Comment by hydra** [comment]
please use the cleanflight slack for support and help with flashing, once you've confirmed there's an issue please report it here and make sure you follow the instructions when creating an issue.
