### ISSUE TITLE
CC3D: SOFTSERIAL <-> LED_STRIP ?

### ISSUE THREAD

**Issue by CopterFail** [cleanflight/cleanflight#311]
As mentioned in #26 the CC3D allows softserial. Board - CC3D.md says pin 4(tx)/5(rx) are used. Pierre_A in #26 says 4(tx)/6(rx) are used. What is correct?
Can I use SOFTSERIAL together with the LED_STRIP? One of them will be automatically disabled.

**Comment by Pierre-A** [comment]
issue ≠26 is old and closed. 
The RC_input connector has been remapped in november (PR≠169) and CC3D.md gives the correct mapping.

**Comment by CopterFail** [comment]
Ok, thank you. That's what I've expected.  
But is there any interference between led-strip and softserial? I did not find any hint in the docs...

**Comment by CopterFail** [comment]
Both modules use TIM3, but different channels and different io's. 
Both modules does a different  TIM_Base_Init (), so it will not work.

**Comment by Pierre-A** [comment]
As said in LedStrip.md, you cannot use led-Strip and Sofserial1 simultaneously as they use the same PA6 line.

**Comment by CopterFail** [comment]
PA6 is mentioned for the Naze.

**Comment by ledvinap** [comment]
ledstris currently needs timer configured in mode that is incompatible with other uses. So all four channels are unusable as timers (but may be at least theoretically used as ADC)

**Comment by Pierre-A** [comment]
oh my bad, you're talking CC3D and not naze
