### ISSUE TITLE
STM32F7 NUCLEO CLOCK I2C 

### ISSUE THREAD

**Issue by Robokishan** [cleanflight/cleanflight#3110]
Hello so i was learning the code for cleanflight and i have improvement for the i2c. I have NUCLEO-F7 and mpu6050 and hmc5883l. i was having 88us avg in gyro reading. which is fine. by seeing the code in here https://github.com/cleanflight/cleanflight/blob/master/src/main/startup/system_stm32f7xx.c#L228  the clock for i2c is set from pclk1. 

and i have attached the screen shot here i am having cpu time almost 50% and gyro avg is at 88us. THIS IS DEFAULT CLEANFLIGHT FIRMWARE
![before](https://user-images.githubusercontent.com/13694097/89991269-35e0ed00-dca1-11ea-844e-7ff38a057b2e.png)

Now I Changed that line ofcourse i2c source clock to sysclock since the board has 216Mhz and pclk1 is at 54mhz so i think it is a good to take advantage of that. and changed lines to this

![code](https://user-images.githubusercontent.com/13694097/89991411-704a8a00-dca1-11ea-8bb7-1d8bb675892e.png)

and then the results are signficance change in cpu time its dropped to 2% I exactly do not know how did it happened but i think  i2c clock source is having bad time with cpu usage. Please confirm if any other stm32f7 board has same thing happening Since i do not have any other stm32f7 board other than nucleo-f7. THIS IS MODIFIED CLEANFLIGHT FIRMWARE FOR I2C CLOCK
![after](https://user-images.githubusercontent.com/13694097/89991512-9112df80-dca1-11ea-913b-8802729e4b00.png)

Sensor readings of acc, gyro and mags are perfect board is giving perfect orientation. 

@hydra

**Comment by hydra** [comment]
Answered in #3111
