### ISSUE TITLE
CC3D Bootloader issue

### ISSUE THREAD

**Issue by arung29** [cleanflight/cleanflight#3118]
Im using CC3D with preloaded openpilot firmware. Trying to flash Cleanflight Bootloader file (.bin) using Libreflight GCS. I have followed al the step as prescribed 1. Click Halt 2. Load .bin file 3. Click "I know what Im doing" 4. Clock flash. At the last step got an error saying error with Abort. Is it the problem with Firmware or .bin file or Hardware. Please advise

**Comment by krisha** [comment]
The latest version I could flash with OpenPilot/LibrePilot GCS was ~1.10 (using rescue button :)). All newer version I tried resulted in an abort.

Anyway 1.10 seems to be not really supported by Cleanflight Configurator 2.6. For me yaw direction was not available and some other parameters were just empty.

With a serial adapter to main port I was able to flash and use 2.3.2. Later versions I could flash but USB wasn't recognized (have an F1 board).

Important for me was to first power up serial adapter and then supply power to CC3D. Else flashing with Cleanflight or STM32CubeProgrammer was not possible. Could be an issue with my serial adapter.

Good luck :)
