### ISSUE TITLE
rssi_scale byte isn't (treated as) unsigned

### ISSUE THREAD

**Issue by cmanley** [cleanflight/cleanflight#312]
This is a minor thingy, but this is what I saw in the CLI (using firmware 1.4.0 for Naze), and it doesn't look right to me:
```
# set rssi_scale = 255
rssi_scale set to -1
# set rssi_scale=254
rssi_scale set to -2
# set rssi_scale=127
rssi_scale set to 127
# set rssi_scale=128
rssi_scale set to -128
```

**Comment by Pierre-A** [comment]
you're right thank you for that !
Verified, corrected and to be merged asap.

**Comment by hydra** [comment]
Fixed
