### ISSUE TITLE
Naze 32 port setup?

### ISSUE THREAD

**Issue by bugilt** [cleanflight/cleanflight#314]
When I upgraded to the new firmware. The GPS information no longer shows up on the osd. I'm guessing it might have something to do with the ports configuration page. 

I hooked it up without knowing the actual port type I'm connecting to. I think the OSD is connected to the uart2. The gps should be on softserial 1 or 2. Neither of those seem to work. I'm just running GPS for osd information.

**Comment by Pierre-A** [comment]
Remember UART1 is shared by USB and Rx/Tx on the board.

**Comment by bugilt** [comment]
The OSD is receiving data from the naze. The GPS data isn't showing up though.

**Comment by hydra** [comment]
Closing this issue. For support visit the forums or irc. The issue tracker is for bug reports and feature requests.

Please see documentation. There are configuration examples.

If documentation isn't clear or doesn't cover what you need please raise that as an issue (stating what needs to be included) or create a pull request to fix the documentation.  Plesse reference this issue in any new issue or pull request.
