### ISSUE TITLE
AUX settings will not apply when you copy paste config into CLI

### ISSUE THREAD

**Issue by Spirre** [cleanflight/cleanflight#325]
This has happened the two latest times when I have upgraded the firmware. But if afterwards copy paste the separately it works fine. I don't if this is a issue or not, but it's quite annoying. Missed the flight mode settings the last time, interesting for a newbie like me :)

**Comment by thenickdude** [comment]
This is because when you paste it all at once, the FC can't keep up and
some data is dropped. I think it's planned to have the Configurator
automatically pause between lines to fix this!
