### ISSUE TITLE
Adjustments - First value applied even when AUX channel is out of range

### ISSUE THREAD

**Issue by maximan** [cleanflight/cleanflight#340]
See screenshot for details. I have AUX2 set up on a pot on the transmitter, and configured a "dead zone" (991 to 1014) so that adjustments can be set to be inactive. However, when in use, flicking the switch on AUX3 up and down will change Pitch P Adjustment, despite AUX2 being out of range.

![adjustment issue](https://cloud.githubusercontent.com/assets/7470626/5695727/bc0a5440-99a7-11e4-8be0-4c58366f7cda.jpg)

**Comment by hydra** [comment]
not a bug, that is incorrect configuration. please see documentation.

to fix this extend the first range to start from 900 and the last range to end at 2100

OR

add two new adjustment ranges that use the unused part of the channel range so they apply 'no changes' to slot 1
