### ISSUE TITLE
Telemetry - Add Light-telemetry (LTM) support

### ISSUE THREAD

**Issue by marksev1** [cleanflight/cleanflight#36]
KipK is maintaining LTM support in his baseflight branch: https://github.com/KipK/baseflight/tree/LTelemetry

Here's how KipK described it:

LTM is an air to ground telemetry, so it's one way only; No ACK & stuffs it just stream datas to the ground at low baudrates.

Depending of flighcontroller implementation & configuration it starts at boot or when armed.

Protocol is binary, using little endian.
There's 3 frames to consider:

.

G Frame (GPS position) (2hz @ 1200 bauds , 5hz >= 2400 bauds): 18BYTES 0x24 0x54 0x47 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xC0
$ T G --------LAT-------- -------LON--------- SPD --------ALT-------- SAT/FIX CRC
A Frame (Attitude) (5hz @ 1200bauds , 10hz >= 2400bauds): 10BYTES
0x24 0x54 0x41 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xC0

$ T A --PITCH-- --ROLL--- -HEADING- CRC

S Frame (Sensors) (2hz @ 1200bauds, 5hz >= 2400bauds): 11BYTES
0x24 0x54 0x53 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xFF 0xC0

$ T S VBAT(mv) Current(ma) RSSI AIRSPEED ARM/FS/FMOD CRC

values are:

LAT/LON: int32 (cm)
SPD ( speed ) : uint8 ( m/s )
ALT ( alititude ) int32 ( cm )
SATS ( number of sat visible ) 6bits
FIX ( sat fix ) 2 bits ( sats & fix are coupled in the same byte )
PITCH/ROLL/HEADING int16 ( deg , -180/180° range )
VBAT( voltage ) uint16 (mv )
Current uint16 ( ma )
RSSI : uint8 ( in % )
AIRSPEED : uint8 (m/s)
ARM/FS/FMOD: uint8 ARM armed status: 1 bit ( first ) FS : failsafe status : 1 bit ( second one ) FMOD: flight mode : last 6 bits: // Flight mode(0-19): 0: Manual, 1: Rate, 2: Attitude/Angle, 3: Horizon, 4: Acro, 5: Stabilized1, 6: Stabilized2, 7: Stabilized3, // 8: Altitude Hold, 9: Loiter/GPS Hold, 10: Auto/Waypoints, 11: Heading Hold / headFree, // 12: Circle, 13: RTH, 14: FollowMe, 15: LAND, 16:FlybyWireA, 17: FlybywireB, 18: Cruise, 19: Unknown
Each frame end with a CRC byte, it's a simple XOR from first payload byte to last one ( starting at 4th byte , headers are not xored )

Attached LTM-log with sample attitude data nothing else (changed text document into picture for attaching here)
![ltm-log](https://cloud.githubusercontent.com/assets/3356571/3838877/d94af830-1e09-11e4-8de0-f29a531cc2ad.png)

**Comment by idefixsin** [comment]
Sorry for that Dominic!

Nick, do let me know if I can help with something to get this implemented.

Thanks !

**Comment by thenickdude** [comment]
idefixsin: do you currently have hardware setup that could test this feature once implemented?

**Comment by thenickdude** [comment]
Apparently support has been implemented as a fork for Baseflight:

https://github.com/KipK/baseflight/compare/LTelemetry

**Comment by idefixsin** [comment]
Hi Nick,

Yes I have the HW (would need to hook the GPS and FSK to the Naze32 first but that shouldn't be the problem). 

Baseflight??..... What's that??  ;-)  lol
I could try and give it a shot based on the fork first if that helps.

**Comment by FenomPL** [comment]
Guys, KipK code looks very clean. I would go this direction...

**Comment by marksev1** [comment]
Just to let you guys be aware of the various use cases for LTM-protocol:

- Ghettostation antenna tracker and telemetry display
- Ghettosd (either ground or air OSD)
- Mwptools software supports ltm (it allows logging, has audio prompts, displays data, map etc.)

I have all of those above ready for testing :)

**Comment by Maarten112** [comment]
It would be awesome to incorporate the LTM(v2) protocol native in cleanflight!

**Comment by hydra** [comment]
@marksev1 one of these days someone might add this, in the mean time there are PR's for Mavlink outstanding.

**Comment by hydra** [comment]
Done

**Comment by marksev1** [comment]
Thanks!

**Comment by Maarten112** [comment]
Thank you hydra, awesome!!
