### ISSUE TITLE
List CLI variables in alphabetical order

### ISSUE THREAD

**Issue by strepto42** [cleanflight/cleanflight#368]
I can never find the variables I want easily. It would be great if they were listed in a predictable order, for example alphabetical.

(Not sure how to label this as an enhancement)

**Comment by ledvinap** [comment]
do you know that 'set text' shows all cli variables that contain 'text' ?

```
# set serial
serial_port_1_scenario = 11
serial_port_2_scenario = 2
serial_port_3_scenario = 3
serial_port_4_scenario = 4
softserial_1_txpin = 1
softserial_1_rxpin = 0
softserial_2_txpin = 8
softserial_2_rxpin = 8
serialrx_provider = 2
```

**Comment by strepto42** [comment]
I did not know it was a free text search - that's handy! I did know you could set <varname> to find its value.

I still think they should be ordered predictably though.

**Comment by hydra** [comment]
current they are grouped together to make reading the configuration dumps that users provide easier.  You can sort the output in a text editor if you need to.

Combined with the 'get <substring>' behavior i don't think this is something we want to implement right now.  I will close this issue.

If you have any suggestion, other than alphabetical, about the ordering then please comment on this issue.
