### ISSUE TITLE
Want to help, where to find the community?

### ISSUE THREAD

**Issue by avoid3d** [cleanflight/cleanflight#388]
Hey, I want to start contributing to this project, but where is the discussion? Is there a wiki or a forum where I can start?

Sorry to use issues for this, but I don't know where to 'join' :P

**Comment by thenickdude** [comment]
There's a bunch of user discussion on RCGroups in this thread:

http://www.rcgroups.com/forums/showthread.php?t=2249574

Most of the developers are hanging out on IRC, details about that channel are in the readme:

https://github.com/cleanflight/cleanflight/blob/master/README.md

**Comment by fiveangle** [comment]
This used to be a spot, but has seen less activity as of late:  http://www.multiwii.com/forum/viewtopic.php?f=23&t=5149

**Comment by avoid3d** [comment]
Thanks guys, been on IRC a lot and that's helped :)
