### ISSUE TITLE
System - Decouple math utility code from the flight code

### ISSUE THREAD

**Issue by avoid3d** [cleanflight/cleanflight#395]
There are functions like normalizeV and DEGREES_TO_DECIDEGREES in main/flight which should move into main/common/maths.

First I am going to write tests, then try move them, is there some reason not to go ahead with this plan?

**Comment by hydra** [comment]
yes, it's fine to move math code into a the common maths code.  tests would be great too.

**Comment by avoid3d** [comment]
Awesome, I have some tests for the math code, will push later :)

**Comment by hydra** [comment]
@avoid3d are you working more on this or shall we close it?

**Comment by avoid3d** [comment]
Hey, thanks for the ping, been very busy moving country, keen to get started coding and flying again soon, will definitely be working more on this!

**Comment by hydra** [comment]
@avoid3d any update, are you working on this or can anyone work on it?
