### ISSUE TITLE
Support different baud rates for each MSP port.

### ISSUE THREAD

**Issue by bajacondor** [cleanflight/cleanflight#40]
Serial ports should have selectable baud rates, not just set for what protocol they are using.  In particular, MSP should be able to work at different baud rates, as the softserial ports don't seem to handle 115200.

**Comment by hydra** [comment]
Still blocked to do time contraints and issus found in testing softserial code.

**Comment by hydra** [comment]
see 5163bef0b2ff8e1f863c4c66d54b4c5ee8b287dc

**Comment by hydra** [comment]
Done, see master branch.  Please re-open if issues are found.
