### ISSUE TITLE
Get response from FC even when no gyro/acc is connected

### ISSUE THREAD

**Issue by LupinIII** [cleanflight/cleanflight#410]
Currently when no sensors are connected you get no response from the flight controller. It took me quite a while today to find out why I couldn't connect to a freshly flashed STM32 dev board with configurator. In my opinion the only thing a missing gyro/acc should prevent is being able to arm the craft. But at least make configurator pop up a message like "CF version x.y was found, but sensors are missing". In my case I would really like to check out GPS or Smartport functionality for example while walking around. It shouldn't need a gyro for that.

**Comment by hydra** [comment]
See fake gyro and fake acc in the code, they are disabled by default since production builds never need this behaviour.  see sensors/initialisation.c.  the fake drivers are for development only and should be perfect for your needs.
