### ISSUE TITLE
Allow MSP to retrieve sonar and barometer readings independently.

### ISSUE THREAD

**Issue by avoid3d** [cleanflight/cleanflight#422]
you can't check the sonar on the baro graph as its not selectable if you only have a sonar device ( i.e. no Baro ) as the graph checkbox is disabled.

I will look into this when my new lidar arrives :)

**Comment by hydra** [comment]
this was discussed in #379

**Comment by rosek86** [comment]
I'm I right that we need separate command to read raw baro only? I think I can handle this. 

How do you feel about refactoring serial_msp to function pointers table, rather than this massive switch statement?

**Comment by hydra** [comment]
Done
