### ISSUE TITLE
Remove profanity from comments

### ISSUE THREAD

**Issue by nebbian** [cleanflight/cleanflight#43]
There are a lot of comments throughout the code that seem to be inherited from the original Baseflight creator.  It seems quite unprofessional to have comments like this in the codebase:

https://github.com/hydra/cleanflight/blob/master/src/main/io/serial_msp.c#L526-L528
https://github.com/hydra/cleanflight/blob/master/src/main/flight/altitudehold.c#L82
https://github.com/hydra/cleanflight/blob/master/src/main/telemetry/frsky.c#L233

**Comment by hydra** [comment]
I haven't found any recently, going to close this.  If we find more we'll remove them as we see them.
