### ISSUE TITLE
Blackbox Compatible with DashWare

### ISSUE THREAD

**Issue by andymac4182** [cleanflight/cleanflight#431]
Hi,

Is it possible to get some example data from Blackbox. Was looking at using the data to overlay some videos using the DashWare software. http://www.dashware.net/how-it-works/ If that is possible it would be great.

**Comment by thenickdude** [comment]
Sure, you can decode any of the logs from [this ticket](https://github.com/cleanflight/cleanflight/issues/381) using the [`blackbox_decode` tool](https://github.com/cleanflight/blackbox-tools) which will turn them into CSV files. Or if you like, here's one of mine already decoded to CSV:

http://s3.nicksherlock.com/LOG00548.01.Armattan%20226.Acro%20LOS.csv.zip

GPS data (in the form of latitude/longitude/altitude coordinates) can also be included in the CSV file, but I'm afraid I don't have an example of that to share.

**Comment by andymac4182** [comment]
That is coming up as access denied for me.

That is okay thanks. I will get a data logger and give it a go.

**Comment by thenickdude** [comment]
Whoops, I mangled the URL, the correct URL is:

http://s3.nicksherlock.com/blackbox/LOG00548.01.Armattan%20226.Acro%20LOS.csv.zip
