### ISSUE TITLE
Board - Add Quanton F4 support

### ISSUE THREAD

**Issue by hydra** [cleanflight/cleanflight#45]
http://www.quantec-networks.de/shop/en/quanton/1/quanton-flight-control-rev.-1

**Comment by blaklite** [comment]
+1 for this to happen =)

**Comment by hydra** [comment]
Quanton Pinout/Wiring

https://docs.google.com/spreadsheets/d/1DNAjixNGpjG3VyTk61cjjHc94rMEi0_3QG-DWvZ9cbU/edit#gid=0

**Comment by hydra** [comment]
Treymarc's baseflight f3f4 branch

https://github.com/treymarc/baseflight/tree/f3f4

**Comment by hydra** [comment]
Blocked by #357 and #884

**Comment by pieri70** [comment]
+1 to this enhancement.. 
Many users are bond to taulabs because that is the only supported system.. 
Thanks

**Comment by davidbuzz** [comment]
see this for quanton support: 
https://github.com/sambas/cleanflight
make TARGET=COLIBRI

**Comment by ther0x** [comment]
any news? I have a quanton but i'm tring to find out an alternative to taulabs thanks

**Comment by davidbuzz** [comment]
I was able to get my quanton to fly using the link I gave above.  I recommend you try it, an let us know how it goes for you.

**Comment by ther0x** [comment]
Thanks david! I have read your link but don't find any reference to quanton or colibri
Sorry i'm a noob :)

**Comment by tedbarth** [comment]
Still no support vor Quanton FC?
