### ISSUE TITLE
PID Controller 1 P_level default value needs changed.

### ISSUE THREAD

**Issue by dave-pitman** [cleanflight/cleanflight#451]
On PID Controller 1,  the default value for Level_P is 90 which from all accounts is very unstable, and is uncontrollable.  Lowering the default value to something like 20 would make it workable.

**Comment by dave-pitman** [comment]
Apparently these defaults cannot easily be changed.  I submitted a pull request to make a note that the user should adjust this value before attempting Angle mode using PID Cont. 2

**Comment by hydra** [comment]
Closing.  PR for documentatio merged. Can't really do anything about this right now.  Further suggestions on how to fix welcome though.  

A longer term goal is to allow the configurator to suggest defaults.
