### ISSUE TITLE
LED Strip - configuration screen not loading

### ISSUE THREAD

**Issue by JohnieBraaf** [cleanflight/cleanflight#458]
I'm experiencing the following issue on Sparky (v1) 1.6 and 1.7:

The configuration manager for the LED string displays message: Waiting for data...
Nothing happens after that, I need to disconnect to make the UI responsive again.
LED Strip feature is enabled

Is my configurator corrupted?

**Comment by hydra** [comment]
old configurator works with old firmware, new configurator works with new firmware.

what combination are you using that doesn't work?

Did you try 1.7 with 0.61.0 ?

**Comment by hydra** [comment]
p.s. release notes of latest configurtor mention this situation.

**Comment by JohnieBraaf** [comment]
Thnx, I was using 0.60.0 which I got as a Chrome extension.
I didn't see version 0.60.0 in cleanflight-configurator(-development) and master , so I've taken it from the development branch now. 
That version works.
