### ISSUE TITLE
Board - Add OpenPilot Revolution support

### ISSUE THREAD

**Issue by hydra** [cleanflight/cleanflight#46]
http://www.openpilot.org/products/openpilot-revolution-platform/

**Comment by simonvc** [comment]
+1 Would love to beta test this for ya.

**Comment by hydra** [comment]
See this:
https://github.com/sambas/cleanflight

**Comment by hydra** [comment]
Blocked by #357 and #884

**Comment by cmwwebfx** [comment]
Is this something that is likely to happen?

**Comment by steadiworkz** [comment]
I have a revo would be up for some testings :)

**Comment by proggod** [comment]
what can be done to get some revo support?

**Comment by cooked** [comment]
Hi,
I'm looking at [https://github.com/sambas/cleanflight](url) ... do you guys know if this is working on the Revolution board (or any F4) ? some development seems to be ongoing there.... looking forward to more news...
