### ISSUE TITLE
IO - Enabling softserial ports as needed

### ISSUE THREAD

**Issue by SupremeFPV** [cleanflight/cleanflight#465]
Is there a possibility to add support for enabling the soft serial ports one by one? 
I am only using one of the softserial ports, but I still want to use current sensor.

Are there some hardware limitations that prevent this from happening or will the current sensor work even if i have softserial enabled?

**Comment by hydra** [comment]
there's no hardware conflict, marking this as a todo for 1.8

**Comment by pinkywafer** [comment]
Is there any reason LED has to be on pin 5, And Current on pin 8 on the naze board? If they were on 7+8 or 5+6 respectively, you could then still use both LED and current, AND one softserial with this enhancement? 
Jenny

**Comment by hydra** [comment]
yes, timer to pin mapping is the reason.

**Comment by P-I-Engineer** [comment]
this is great, this what i was looking for.

i'm assuming this would allow me to run osd on uart 1 and frsky telem on soft serial and still have a current sensor hooked up.

thanks for all the great work.

**Comment by snoekieboe** [comment]
Did this feature make it into 1.8.0? It seems i still cannot make use of LED and Softserial at the same time?

**Comment by hydra** [comment]
Not possible to use led and softserial at the same to.e on the naze.  Is possible to use current meter and softserial since current meter does not use a hardware timer. This ticket will be updated when the latter is done.

**Comment by dkisselev** [comment]
@hydra is there another platform that has more HW timers? Or would it be possible to give LED the option of using a software timer? Looking to use LEDs with always-on telemetry (which requires softserial)

**Comment by thenickdude** [comment]
You can use LEDs with always-on telemetry without using softserial. Just put telemetry on UART2.

**Comment by dkisselev** [comment]
Ahh, my bad, I was going off of this (outdated, especially for 1.8) video: https://www.youtube.com/watch?v=dahGlc3Tf40, but just realized that softserial was needed in that case to handle the GPS as well as telemetry/LED's.

I guess to expand on the question, would it be possible to do always on Telemetry + GPS + LED's? I guess the solution would be to attempt to migrate either softserial or LED's off of a hardware timer, but is that possible (CPU usage-wise?

**Comment by thenickdude** [comment]
I think pull request #177 attempts to use one hardware timer to serve several systems (combine timers). 

Otherwise you could use an F3 based system like the Sparky or Hydra's in-development flight controller, which support 3 hardware serial ports and an additional USB port (so you could have always-on telemetry and GPS on 2 of the hardware ports, CLI/MSP using the USB port, and not use softserial at all).

**Comment by ledvinap** [comment]
@thenickdude : #177 wont help here without quite large LEDs code rewrite. LEDs need whole timer (in 8bit mode). But it may by possible to move things around so that function that don't need timer are on remaining LEDs timer pins.

**Comment by hydra** [comment]
See #375 and #884
