### ISSUE TITLE
CLI Dump does not save servo information

### ISSUE THREAD

**Issue by idefixsin** [cleanflight/cleanflight#468]
I believe the CLI Dump does not save the servo channel and rate % information of set as part of the servo_tilt functionality. I had the issue going to 1.7 both on a naze32 and a sparky. Can someone verify?

**Comment by hydra** [comment]
Yes, you are correct, there are no cli commands for servo min/max/center/forwarding/channel configuration.  That is an oversight inherited from baseflight.

Perhaps some new commands need to be added?
