### ISSUE TITLE
Sensors - Decouple battery voltage monitoring from looptime

### ISSUE THREAD

**Issue by hydra** [cleanflight/cleanflight#469]
https://github.com/cleanflight/cleanflight/blob/master/src/main/mw.c#L242

Currently the VBATFREQ is set to 6 so battery voltage is checked every 6 loop iterations.  It would likely be better that the battery voltage is checked at fixed intervals.

Currently decreasing looptime increases the amount of time the CPU spends checking the battery voltage.

**Comment by ledvinap** [comment]
One possible way is to trigger conversion independently of main loop. ADC DMA can be setup to create queue of measurement(simply increase DMA transfer size to multiple of ADC channels). Then simply fetch new measurement in main loop and filter/use them ...

**Comment by hydra** [comment]
Yup. Good to get the hardware to do it for sure.

**Comment by DarkVegetableMatter** [comment]
Looks like the code is already using DMA to fetch the ADC conversion result. 

VBatt: The code in mw.c is calling the averaging calculation and updating the beeper
IBatt: mw.c calls the averaging (or virtual ammeter) code
RSSI: mw.c calls the averaging calculation and updating the rssi value

So decoupling VBatt/IBatt/RSSI is easy if you can find a suitable fixed period tick - systick handler maybe?

**Comment by ethomas997** [comment]
Would 'executePeriodicTasks()' be good place to handle that stuff?  Could make a new battery voltage/current handler function with 'currentTime' as a parameter.

**Comment by DarkVegetableMatter** [comment]
Well, it looks like the loop() function in mw.c is calling annexCode() and that calls the current VBatt code. loop() also calls. loop() also calls  executePeriodicTasks() 

I don't think that will decouple the code from loop time or am I missing something?

How often do these things need updating anyway? I would think once a second would be enough

**Comment by ethomas997** [comment]
Moving the functionality into 'executePeriodicTasks()' is just to have it in a more logical place.  I think the "decoupling" would want to be accomplished by passing 'currentTime' into the handler and using it to regulate timing, like several of the other functions do.

On my small tricopter the battery alarm is too sensitive; it beeps on every throttle punch out, even with the Vbat settings around 3 volts.  The averaging window really needs to be larger.  This has been bugging me, so I'll probably post a pull request to address these things.

--ET

**Comment by DarkVegetableMatter** [comment]
Maybe that's a new/different issue?

Turns out decoupling the Vbatt monitoring code is easy if we accept
- We will still update every N loops (minimum interval is then 1 loop, same as before)
- The sampling time will/should/can be much greater than loop time i.e once per second

**Comment by hydra** [comment]
PRs merged.
