### ISSUE TITLE
Board - Add BrainFPV support

### ISSUE THREAD

**Issue by hydra** [cleanflight/cleanflight#484]
https://www.brainfpv.com/products/

**Comment by remmec** [comment]
Support for the STM32F4 MC and OSD would make the BrainFPV sell like hotcakes.

**Comment by Trussroads** [comment]
It sure would be a great package with CF on it.. It's a great board and I'd like to see more vendors move the OSD on-board too. Imagine Vector quality OSD with CF capabilities in the air.. Hint hint Dom! LoL.. ;D

**Comment by phobos-** [comment]
There is already a working fork, not sure why it isn't merged yet... I've flown it and it works at a flyable level.
https://github.com/sambas/cleanflight
@sambas ?

**Comment by geekaz01d** [comment]
Is there an update on support for this board?
