### ISSUE TITLE
Allow telemetry Heading output (magnetometer) without GPS

### ISSUE THREAD

**Issue by snoekieboe** [cleanflight/cleanflight#486]
Currently it seems that Naze32 full boards ( with baro and Magnetometer) do not send heading information in telemetry without a GPS module attached.

There is a workaround to force the transmission of heading information without connecting a GPS module:

set frsky_default_lattitude = 1.00
set frsky_default_longtitude = 1.00

it would be nice for Naze32 Full users to have the option to activate the transmission of heading information in telemetry without having to revert to a workaround or connect a GPS module.

An option in the "GPS" tab to enable this would be preferable.

**Comment by hydra** [comment]
PR merged.
