### ISSUE TITLE
Move save button to top of each page and add more elements to adjustment tab

### ISSUE THREAD

**Issue by jistforfun** [cleanflight/cleanflight#497]
Often the save button is at the bottom of a long tab, it would be more convenient to have the save button at the top of each page where the most important items are generally located.

The adjustments tab is a wonderful addition to CF!
Could we add a few more selectable elements to the drop down menu?

Level PID 
Alt PID 
VEL PID
Mag PID

**Comment by andymac4182** [comment]
Hi @jistforfun ,

Can you please submit requests to the configurator issue list https://github.com/cleanflight/cleanflight-configurator/issues. This is for issues with the firmware.

Cheers

**Comment by jistforfun** [comment]
Sure think, 
Yes I am new here...
