### ISSUE TITLE
Fix adjustments page to remember all settings

### ISSUE THREAD

**Issue by Ozzy33** [cleanflight/cleanflight#500]
Fix adjustments page to remember all settings, even when they are not enabled. (clarify:In the adjustments tab, I setup ~6 adjustments (CF 1.7.1 and GUI 0.61.0) , hit save (all fine), then only enable one of them hit save, all other adjustments are deleted (to see this, go to another tab then back to adjustments, all gone but the only enabled one stays).

**Comment by fiveangle** [comment]
Please submit your Cleanflight Configurator enhancement request against the Configurator project instead. Thanks. 

-=dave

**Comment by Ozzy33** [comment]
Done and thanks!
