### ISSUE TITLE
Add to Receiver tab, indicators for when you move your sticks

### ISSUE THREAD

**Issue by Ozzy33** [cleanflight/cleanflight#501]
Add to Receiver tab, indicators for when you move your sticks to show Forward/Backward, Left/Right, Idle/Full Throttle, like KK2 shows in Receiver page. Mainly getting the pitch correct is just a guess for new pilots. TIA

**Comment by thenickdude** [comment]
Please open this issue on the Configurator's issue tracker instead:

https://github.com/cleanflight/cleanflight-configurator/issues

I think this has the potential to confuse people more if they're not sure if they're Mode 1 or Mode 2 or something more exotic or not.
