### ISSUE TITLE
Enabling serial telemetry on serial 4 exhibits heavy lag in CLI

### ISSUE THREAD

**Issue by steveomg** [cleanflight/cleanflight#51]
To replicate:
feature rx_serial
feature telemetry
feature gps
set serial_port_1_scenario=5
set serial_port_2_scenario=3
set serial_port_3_scenario=2
set serial_port_4_scenario=4
set gps_baudrate=9600
set gps_provider=0

Enabling telemetry on port 4 or port 3 while using these settings causes extreme lag in CLI.  Disabling telemetry and all is well.

**Comment by hydra** [comment]
Tested with 1.8.0 development firmware.  Unable to reproduce. Please re-test and re-open if there is still an issue.
