### ISSUE TITLE
CC3D external BMP085 detection problem?

### ISSUE THREAD

**Issue by digitalentity** [cleanflight/cleanflight#521]
I have a BMP085 breakout board connected to CC3D FlexiPort, however cleanflight does not recognize it. UART3 is unused in ports configuration tab. I've tried with cleanflight 1.7.1 & 1.7.2 with no luck.
This breakout board works fine and reports valid data with test code on mbed.

**Comment by hydra** [comment]
I2C support is not broken, my OLED display works just fine.  Check the I2C signals are clean using a scope and try using different pull-up resistor values.

If it's really broken please reopen.

**Comment by digitalentity** [comment]
Thanks for updating the title.

I don't have a scope, so I can not verify the I2C signals, but I'll try to play with pull-up resistors and try to confirm the issue.

**Comment by digitalentity** [comment]
@hydra, I've connected a logic probe to I2C bus and recorded the data exchange while board boots. It looks like cleanflight is able to communicate with I2C device 0x77 (BMP085), reads chip ID (reg 0xD0), reads version (0xD1), reads calibration (0xAA). 

Looks like detectBaro() should return true. I can not verify it, my CC3D board does not have a SWD connector and I am not very good at soldering SMDs.

I looked at the code and it occured to me that sensorsAutodetect function is missing sensorsSet(SENSOR_BARO) at line 390 (right after bmp085Detect). Since CC3D does not have a barometer onboard, SENSOR_BARO bit is not set in SENSORS_SET.
Current code never sets SENSOR_BARO, so external barometer never gets detected and used.

I believe same thing is true for external magnetometer.

**Comment by digitalentity** [comment]
Please see screenshot of reading BMP085 chip id:
![screenshot](https://cloud.githubusercontent.com/assets/11059099/6261999/6431986a-b846-11e4-884a-5210a224dba3.png)

**Comment by digitalentity** [comment]
I also created a proposed patch for 'src/main/sensors/initialisation.c' file:

@@ -396,12 +396,14 @@
 #ifdef USE_BARO_MS5611
     if (ms5611Detect(&baro)) {
+        sensorsSet(SENSOR_BARO);
         return;
     }
 #endif
 #ifdef USE_BARO_BMP085
     if (bmp085Detect(bmp085Config, &baro)) {
+        sensorsSet(SENSOR_BARO);
         return;
     }
 #endif

**Comment by digitalentity** [comment]
I've forked you repo and will try to fix this myself. If my patch will work, I'll create a pull request.

Can you please reopen the issue as I am unable to do it.

**Comment by digitalentity** [comment]
I was able to fix the issue - now external baro (BMP085, BMP180) & magnerometer (HMC5983) are correctly detected and used if connected:
![2015-02-19 16 24 14](https://cloud.githubusercontent.com/assets/11059099/6262671/c708f070-b853-11e4-80b4-8e21efcfdba6.png)

I've created a pull request with the fix.

**Comment by hydra** [comment]
Yes I saw t. Great, thanks for looking into it. I will get that merged asap.

**Comment by hydra** [comment]
Yes I saw t. Great, thanks for looking into it. I will get that merged asap.

**Comment by hydra** [comment]
#525 is merged and i did further cleanup work.  Please checkout the latest master and re-test.  Re-open this if there's still an issue.

**Comment by Tomal2v** [comment]
how to solve this BMP180 detection problem on cc3d
