### ISSUE TITLE
Use external EEPROM for configuration storage

### ISSUE THREAD

**Issue by digitalentity** [cleanflight/cleanflight#528]
Some of supported boards have separate EEPROM chip: CC3D, Sparky. May be cleanflight should use it to store configuration data instead of using STM32's internal flash memory. This way we can preserve internal flash write cycles.

**Comment by ledvinap** [comment]
The flash reliability is specified for 10k cycles, on extreme temperature. Real-life performance will be order of magnitude better. Do you really think memory endurance is problem?

**Comment by hydra** [comment]
Because not all boards have the flash chip this is not an option.  e.g.  acro naze, stm32f3discovery and other development boards.
