### ISSUE TITLE
CC3D - pidcontroller=1 strange behaviour

### ISSUE THREAD

**Issue by shuffleznl** [cleanflight/cleanflight#53]
Enabling pidcontroller=1 on CC3D give strange behaviour.
Mini flipped and broke props.
Rate = flies well
Horizon = flies as if in rate
Angle = left front motor (Output 4) goes crazy.

Video: http://1drv.ms/1v9No7I, you'll see:
Arm in rate, show response
Switch to horizon, show response
Switch to angle, show response

**Comment by hydra** [comment]
could you re-test this with the latest firmware and confirm if it's still a problem?

**Comment by hydra** [comment]
i will have to close this since no there has been no update.  If there is still a problem please re-open.

Knowing the exact ESCs and the dates of the microcontrollers on those ESCs would also help since there has been some bad batches of chips used in ESCs which are known to cause sync issues.
