### ISSUE TITLE
Changed rates but it don't affect flight

### ISSUE THREAD

**Issue by sandmanbr** [cleanflight/cleanflight#533]
I dont know if its an issue of firmware or gui. I build anothe mini quad and copy pids and rates from another person i see in youtube with same setup. The pids was ok but rates was very low. for the first flight i tried 1.0 as rc rate (the original rates was 1.2). My quad rolls and flips was very slow. I flied with 1.1, 1.2, 1.3 and even 1.4 and the quad always fliped too slow. 

I setup the rates for the first time im my desktop and keep tunning with my laptop in flying field.Every i opened the receiver and pid tuning tabs the displayed rates was the expected value (the last i saved). 2 days ago i connected my quad to my desktop to increase the rates to 1.5. I accidentally i messed up the pids so before save i click refresh to restore last saved values. After the refresh all my rates fields in pid tuning and receiver tabs became blank.

 I set up my rates aganin and tried a flight. WOW! now its flip and rolling like a demon!

**Comment by hydra** [comment]
Without your new and previous configs we can't identify what happened. I will close this but if you can reproduce the issue please provide steps to repeat and it can be investigated.

Glad you got it working now.
