### ISSUE TITLE
AlienWii F3 hex file for next release

### ISSUE THREAD

**Issue by MJ666** [cleanflight/cleanflight#534]
@hydra please can you also provide the hex file for the AlienWii F3 target with the next release. Thanks.

**Comment by MJ666** [comment]
@hydra you still have this on your list. Likely public availability will be in 1-2 month if everything is going as expected. Thanks.

**Comment by hydra** [comment]
Just shout nearer the time. Need to automate the release build and upload at some point too.

**Comment by hydra** [comment]
Closing this, it will be done.
