### ISSUE TITLE
WS2801 does not share protocol with WS2812

### ISSUE THREAD

**Issue by Djhg2000** [cleanflight/cleanflight#538]
I just noticed the following in cleanflight/docs/LedStrip.md:
> Note: The initial code may work with WS2801 + External LEDs since the protocol is the same

The WS2801 LED drivers use a 2-wire interface (external data clock) while WS2812 and similar use a 1-wire interface (internal data clock). I do have a WS2801 laying around if you want to implement it, but for now we should probably change this note to not include WS2801.

**Comment by hydra** [comment]
Fixed.  Thanks.
