### ISSUE TITLE
IO - Retractable landing gear

### ISSUE THREAD

**Issue by matbogdan79** [cleanflight/cleanflight#553]
A small but important feature would be nice on the servo retract when your drone have a retractable landing gear ( like DJI Inspire - transformer )
Description:
1. use aux to gear down/gear up
2. optionally auto gear down when altitude is less than some distance from the ground ( sonar metered )
3. optionally don't allow gear up when the motors are disarmed and/or distance is less than a value
4. optionally auto gear up when you are in the air.

All distances should be metered with sonar sensor for this feature and also customisable trough CLI/graphic interface

**Comment by hydra** [comment]
See #201
