### ISSUE TITLE
In flip 32, allow Pin 5  for LED strip while Softserial1 is also configured.

### ISSUE THREAD

**Issue by roger1994** [cleanflight/cleanflight#561]
I have a flip32, configure Softserial1 TX for Frsky telemetry, Softserial1 RX (Pin 5) is not used,

Anyway to still allow Pin 5 be used for LED strip?

**Comment by vadav** [comment]
As of now, softserial is not available when using Leds

**Comment by hydra** [comment]
hardware limitiation, closing.
