### ISSUE TITLE
RPM telemetry reporting incorrect with MOTOR_STOP

### ISSUE THREAD

**Issue by pinkywafer** [cleanflight/cleanflight#562]
When throttle is minimum, and board is armed, frsky telemetry RPM reports Minimum Throttle (ie. motors spinning) whether feature motor_stop is used or not.  When motor_stop is enabled, the RPM should be reporting the Minimum Command when throttle is minimum (as the motors are stopped)

I've made a fix for this in commit fc67c981b4669debc2a53104c68b8ad66c9c22e0 which seems to work well on my naze board.  I'm not sure if this is the best way to do this? can someone advise or test? If this is ok, I'll create a pull request

Thanks
Jenny

**Comment by hydra** [comment]
PR please
