### ISSUE TITLE
SSG (Super Simple Gimbal)

### ISSUE THREAD

**Issue by danielolsman** [cleanflight/cleanflight#563]
Is there a possibility to add the SSG code

more info is found here : http://www.rcgroups.com/forums/showthread.php?t=1793759
Multiwii code is found here : http://www.multiwii.com/forum/viewtopic.php?f=8&t=3079

With this code you could use 2 servo's as a simple gimbal

**Comment by SlyMike** [comment]
Its already supported!
 Tick the "SERVO_TILT" check box in the configurator app

**Comment by danielolsman** [comment]
i don't think SSG is supported.

This is what i mean:

https://www.youtube.com/watch?v=KPBL4pPEzNI\

**Comment by SlyMike** [comment]
Yeah, I watched that. It's actually quite an innovative design, maybe it will end up on someone's to do list.

**Comment by olexs** [comment]
It's supported. See https://github.com/cleanflight/cleanflight/blob/master/docs/Cli.md and specifically the "gimbal_mix" parameter - you want "set gimbal_mix=2".

**Comment by SlyMike** [comment]
@danielolsman looks like you can close this issue thanks to olexs keen eye.

**Comment by danielolsman** [comment]
Ok, thanks for the comments. I will try it. 
issue closed.
