### ISSUE TITLE
Artificial Horizon in Cleanflight configurator is wrong -  IE pitch & roll are reversed

### ISSUE THREAD

**Issue by Rob2160** [cleanflight/cleanflight#567]
Just noticed this. 

When you pitch nose down, your artificial horizon should rise - when you roll left the left side of the horizon should rise. 

Currently the display is opposite to how a real artificial horizon works.  

See my video here. 

https://www.youtube.com/watch?v=fhwFLmB2H0M

This is how it should display. 

https://www.youtube.com/watch?v=dsCt88b5lwI

https://www.youtube.com/watch?v=PUmJOFrIV-c

**Comment by tricopterY** [comment]
Please open an issue in: 
https://github.com/cleanflight/cleanflight-configurator

**Comment by Rob2160** [comment]
Thanks, I have now done so and will close this one.
