### ISSUE TITLE
IO - Servo gimbal on tricopter

### ISSUE THREAD

**Issue by zdar** [cleanflight/cleanflight#573]
Could servo gimbal be allowed on tricopter? At least with one servo? Note: there are two outputs available  - one "servo" and one "esc".

Genarally it would be nice to be able to map "gimbal" (and motors) to any output pin(s). 
Also it would be nice to be able to select which axis should be stabilised...

**Comment by Murphy-c** [comment]
I believe this is issue has already been brought up, see https://github.com/cleanflight/cleanflight/issues/162 for reference.

**Comment by hydra** [comment]
See #357 #884
