### ISSUE TITLE
Flight - No servo output on CC3D when using TRIcopter mode

### ISSUE THREAD

**Issue by lijingwei0710** [cleanflight/cleanflight#586]
flashed the 1.7.2 firmware to CC3D. and using mix tri ,the servo output is S3,but can not found s3 output on CC3D.

**Comment by hydra** [comment]
The pwm mappings and timer allocations needs updating for the CC3D.

**Comment by catchthewind** [comment]
Is it already fixed?
 I have uploaded cleanflight 1.8 to my CC3D but yaw servo is not working at all :(
 I am also using tricopter mix.Tail servo is S1.

**Comment by catchthewind** [comment]
Is there any way to manually map servo to output 4,5 or 6 or get any other way of controlling it?

**Comment by rcaridade** [comment]
I've a tricopter too and can find where to connect servo 1! Nor out 4, 5 or 6 work.

I don't know what to do.

**Comment by catchthewind** [comment]
You need to look for someone who can fix it or wait for project devs to do it..

**Comment by rcaridade** [comment]
I'm a computer programmer and trying to solve this problem, but it's taking a lot of time to understand the code.

**Comment by catchthewind** [comment]
Due to this and other problem #706  I have changed my controller to flip32 which is better supported. i still have CC3D waiting for these problems to get fixed :)

**Comment by CopterFail** [comment]
CC3D and cleanflight 1.8.1 -> still no output for servo S1

**Comment by nickaus** [comment]
I've just brought a CC3D for a Tricopter.
 Spent hours trying to get the tail servo to work then I find this thread.
 Not happy - What are the chances of getting this fixed quickly ?

**Comment by CopterFail** [comment]
Did anyone know, what the last cleanflight version was that was working for a tricopter? Meanwhile I'll try openpilot...

**Comment by hydra** [comment]
Don't think its ever been supported or tested on the CC3D. The CC3D timer layout doesn't make things easy, code-wise.  Check pwm_mapping.c and timer.c

**Comment by CopterFail** [comment]
Ok, I've checked out the 1.8.1 and changed the pwm_mapping of pwm12 to servo. The output is on channel 6 but the pwm is 400Hz and oneshot is a bad idea (the servo seems to be handled as esc).

**Comment by Redshifft** [comment]
Well, Well, no Yaw servo on Naze either untill you open the throttle.....You try that ?
1.8 is the same ! can we get this fixed ?

**Comment by rcaridade** [comment]
Does any one knows if it will be a solution to S1 in CC3D, I was trying to recycle this board and bought Mag and Baro to have better flight.
But unfortunatly Can use it on my tricopter because there is no servo.
Is this going to be fixed on the next version? Or it's better to forget it because there's no solution?

**Comment by catchthewind** [comment]
@rcaridade buy flip32 10dot and you are ready to go :)

**Comment by rcaridade** [comment]
@catchthewind  I know that is the solution, I've two APM and two Flip32+, but as I told you I was only trying to recycle it.

**Comment by catchthewind** [comment]
@rcaridade You can use it with openpilot. I went back on one of my cc3d and its really OK.

**Comment by CopterFail** [comment]
@hydra : Hi, I think this is a "bug" , no "enhancement". Otherwise it should be documented that a CC3D can not be used for tricopters.

**Comment by catchthewind** [comment]
True!

**Comment by rcaridade** [comment]
I would be very please if some one solved it. I'm hoping that it's a simple thing to solve, this way no one has to waste too much time to fix it.
Thanks for your good work.

**Comment by hydra** [comment]
I changed it to bug as requested, but then changed it back to enhancement because it was never working, development happens iteratively; otherwise everything that's not done yet would be a bug and not an enhancement.

**Comment by CopterFail** [comment]
Ok, you are right. But many people know baseflight and cleanflight as a good choice for tricopters. cc3d seems to be supported and is very cheap. So many guys (often beginners) start to build a tricopter project and run into trouble. Maybe another of thoses "cc3d/tricopter issues" will be started...

**Comment by catchthewind** [comment]
I think it should be a BUG and sorted quickly. Otherwise you should add info to CC3D readme stating clearly that CC3D does not support tricopters while using Cleanflight...

**Comment by JohnOCFII** [comment]
@catchthewind The CC3D documentation already states that tricopter support is untested.  Based on the notes above, this does not appear to be a simple fix.

**Comment by catchthewind** [comment]
@JohnOCFII   support untested is not the same as NO support. Tricopter needs a servo. No servo - no tricopter. Documentation should say Cleanflight for CC3D does NOT support tricopters at all.

**Comment by sreichholf** [comment]
I may want to rethink your understanding of "untested" instead of flaming people here for no reason.

For the average Developer untested is totally equal to "Never tried, no idea if it works at all".
And from my personal experience untested things (almost) never work the way they're expected to.

**Comment by catchthewind** [comment]
I am so sorry. I did not intend to flame anyone. I was just sad after spending countless hours on making it work. Now we can say it is tested on a tricopter and not working. Saying no tricopter support would save time for others.

**Comment by CopterFail** [comment]
Any news with this issue? Did anybody try 1.9?

**Comment by fhorinek** [comment]
I made modification to mapping for CC3D and now it is working!
but it is not yet merged to master, I just made pull request
https://github.com/cleanflight/cleanflight/pull/1042

**Comment by CopterFail** [comment]
fhorinek, you are my hero. It works and the YAW servo is displayed in the configurator tab. Min/Max limits  in this tab are 1020/2000 (the default values from rx.h , #define DEFAULT_SERVO_MIN 1020 )

**Comment by renatoa** [comment]
So this is still not fixed even today ? 
Any technical reason for this, should I wait a reasonable time or go back to openpilot ?

**Comment by sppnk** [comment]
Not yet. It seems CC3d is a real problem with cleanfligt : #1076

**Comment by CopterFail** [comment]
It is fixed and works fine, see #1042. But the pull request is still not included... You've to add the 2 line on your own.

**Comment by renatoa** [comment]
Add and compile, not having all the required environment, please, is anyone kind to make a hex for me ?
Thank you !

**Comment by a6j** [comment]
The same would be grateful if someone will bring * .bin firmware

**Comment by renatoa** [comment]
Because nobody did it, finally I built it myself. works... :)
No idea where to post, I can email you.
The build is based on the version committed before September 26th when I downloaded the sources.

**Comment by nathantsoi** [comment]
I fly betaflight on my tricopter. The name is misleading, it is not beta. It is amazing, the FIR filter and loop sync'd to gyro makes it fly so, so well. https://github.com/borisbstyle/betaflight/releases plus, there is a bin for the cc3d :)

**Comment by a6j** [comment]
nathantsoi, tried firmware beta flight CC3D.bin 2.1.0 and 2.1.1, the result is negative. The board CC3D servo is not working.

renato, if you do not complicate please skinte firmware badmentonych@ya.ru

**Comment by renatoa** [comment]
Betaflight, another spin of naze ?!!! :o  is there a compare of features somewhere ?

a6j, sure, will email the build asap

**Comment by a6j** [comment]
Many thanks to Renato! Servo works!

**Comment by renatoa** [comment]
:)

**Comment by EAM5892** [comment]
Renatoa could you explain me how you did it, please?

My email is eam5892@gmail.com

**Comment by renatoa** [comment]
Checkout, changed as posted below, and recompiled:
https://github.com/cleanflight/cleanflight/pull/1042

**Comment by EAM5892** [comment]
Hi renato, thanks for the reply,

I already saw this thread (#1042), but the problem I have is that I don't
know the procedure of recompiling and updating it in Cleanflight.
Could you explain it step by step, please?

**Comment by renatoa** [comment]
Is the procedure explained here:

https://github.com/cleanflight/cleanflight/blob/master/docs/development/Building%20in%20Windows.md

but is simpler to send you the bin, trust me :)

**Comment by kuson** [comment]
@renatoa appreciate if you can send me the bin to kusons @ gmail. com
I can also share it on Dropbox for you if you want :)

**Comment by EAM5892** [comment]
Could you send it to me too, please?

Thanks in advance

**Comment by renatoa** [comment]
What email, please ? 
You can PM me, I think, instead posting here, spam robots are harvesting everywhere :)

**Comment by EAM5892** [comment]
eam5892@gmail.com please

**Comment by a6j** [comment]
I compile the firmware fix for tricopter version 1.10.0 (9f95334).
It is that all mail not to throw.
https://yadi.sk/d/AB6bMsJOkSELZ

**Comment by kuson** [comment]
Thanks Renatoa!  BTW, which Output do I use for Servo 1 on CC3D -- Output 4?  I should flash it from CC3D rescue, and use the bin file right? Thanks ;)

**Comment by renatoa** [comment]
Yes, and yes :)

**Comment by kuson** [comment]
@renatoa, @a6j   I got the firmware flashed.  However, the whole frame goes spinning (if I remember it turns clockwise).   I was under the front CCW+CW and back CCW (standard to CC3D / PixHawk) so I switched to all CCW, and it was still  the same.  Currently if I yaw left on the tx, the servo turns the motor left, and ifI yaw right, the motor turns right.   What I can think of is what I read somewhere that I have to reverse the Servo Direction.  Is this done on Servo0 on the GUI or via the command line? Thanks again, and hope this will also help others :)

**Comment by nathantsoi** [comment]
@kuson

i had to set this in the cli: `smix reverse 5 2 r`

**Comment by renatoa** [comment]
Happened me too, but because wasn't able to reverse it by cli as above, reversed mechanically, changed the servo position, not sure if a solution for you, my mount allowed.

Nathan, in the firmware I built the servo output is pin/ch4, is 5 in your example ok ?

**Comment by a6j** [comment]
I set up the server as follows:
set servo 5 1100 1900 1500 -100 -1

**Comment by renatoa** [comment]
Again, same 5 ... how are output pins numbered ?

**Comment by a6j** [comment]
The servo must be connected to pin 4.
The CLI specify: set servo 5 1100 1900 1500 -100 -1
Servo tab:
servo 5 = 4 pin

**Comment by kuson** [comment]
@a6j @renatoa  thanks, it seems better (not exclusively wanting to Spin)  but I can't get the copter up.  I put a 10 or 15 degree tilt RIGHT, to the back prop at the servo Mid-Point.  Is this ok, or it is not necessary?  Also, Must the propellers be all CCW, or is it ok to have  L: CCW, R:CW, Back: CCW?   Thanks

**Comment by renatoa** [comment]
I have the front props counter-rotating, and the tail no idea atm :)
The motor is less than 10 degree right, when seen from the back.
The heading has no drift with all on default, but yaw P reduced to 4.

**Comment by a6j** [comment]
Caudal axis of the motor should be approximately perpendicular to the axis of the horizon. The controller itself compensates for axial tilt when it is needed.

**Comment by kuson** [comment]
@nathantsoi  thanks way back there. Thanks @renatoa, @a6j.  Action 1. Will adjust the Back Motor back to horizontal.   BTW,  I have a CC3D Micro, use Outputs 1,2,3 for the 3 motors and  Output 4 for the servo at the back.   The Cleanflight "Servo Menu" kind of confuses me, and wonder why the command "set servo 5 1100 1900 1500 -90 90 -100 -1" is ok to my setting of using Output 4 for my servo ; ( Do note I had to put in -90 and 90 in it too, seems to be about the degrees of something in the GUI)   Because the Servo Menu starts at Servo 0, 1,2,3,4,5  (starts at Zero), it would be interesting why 'set servo 5' was used, unless it was hardcoded in this particular firmware.   Would appreciate any explanation

**Comment by catchthewind** [comment]
Is this fix for CC3D already icluded in latest Cleanflight and/or Betaflight or do we still need version recompiled by a6j linked above?

**Comment by a6j** [comment]
Starting with version v1.11.0 everything works without interfering with the code. Checked.

**Comment by catchthewind** [comment]
Thank you for fast answer.
I have tried betaflight 2.1.6 first  and can not get it to work manually or using CLI :(
Command "set servo 5 1100 1900 1500 -90 90 -100 -1" gives error Invalid Name.
I will try CF 1.11.0 soon.

**Comment by a6j** [comment]
If you do not know why you need betaflight my advice to you use the CF and you will schate.

**Comment by catchthewind** [comment]
Is there an easy way to convert hex to bin ?
bin file is missing on https://github.com/cleanflight/cleanflight/releases :(

**Comment by renatoa** [comment]
Not easy, but the only I know...
Download sources and compile with OPBL command line switch

**Comment by a6j** [comment]
No you can not. Starting with version 1.11 support OPBL removed. Only full firmware on the CF including the bootloader. But you can easily go back to the OP.

**Comment by renatoa** [comment]
Then, this notification contains a dose of sarcasm, imo...
So, someone above trumpeted that the fix, that was specifically for a particular board, and nothing else, was been included in a firmware that can't be loaded on THAT board !
Whose paradox is this ? :)

**Comment by a6j** [comment]
You have something to confuse. Firmware perfectly filled, but jammed with the bootloader OPBL. Bootloader OPBL if desired sewn back.

**Comment by a6j** [comment]
You have something to confuse. Firmware perfectly filled, but jammed with the bootloader OPBL. Bootloader OPBL if desired sewn back.
Number of lines of code increases so for guaranteed employment on board CF CC3D just had to cut out unnecessary functionality. Simply put for every certain functions requires a certain amount of memory, memory is not dynamic.

**Comment by renatoa** [comment]
Yeah, dazed and confused :)
This thread is about CC3D, not other board.
CC3D can't be loaded other method than using a bin, via open pilot bl, hex using serial from CF was tried by many people and failed.

**Comment by catchthewind** [comment]
I have tried to upload hex into CC3D using 2 different programmers on main port but is doesnt work :(
@a6j @renatoa 
Could you please send me exact changes made to the code in CF 1.11 so I could pass it to Boris to include into Betaflight which still offers BIN version of the firmware.

Is this https://github.com/cleanflight/cleanflight/pull/1042/files  all or anything else is needed
??

**Comment by Zero9r** [comment]
I have had no issues with loading HEX files with a UART to the Flex Port.  THere was some issues with Boris's releases of Hex files.  But that was something to do with how he was making them.  Other where able to take his files and re compile them to work.  I have been running Boris's betaflight since before it was called Betaflight.   Maybe you have it wired wrong? RX goes to TX and TX goes to RX.

**Comment by catchthewind** [comment]
Lucky you :) I have tried both combinations starting with crossed one you have suggested,  Could someone please confirm changes needed to fix it. I would like to ask Boris to merge it with BF and use regular BIN file via USB port.

**Comment by a6j** [comment]
I do not know why you need it, sew through the UART and everything will work fine.
Patch version 1.11.0 here: https://github.com/cleanflight/cleanflight/commit/165adfa755053e68224b9efa664fa6052372a3cf

**Comment by catchthewind** [comment]
I have managed to upload hex with new programmer. CF 1.11 works fine on a tricopter and CC3D.
I have also tested Betaflight 2.2 RC2 and this fix was implemented there as well (both hex and bin available).

Thank you All for help. Have a great party tonight and a great 2016 :)

**Comment by renatoa** [comment]
Please, details. Interface used, pins, everything we might need to be happy as well.

**Comment by catchthewind** [comment]
After uploading CF 1.11 hex using ftdi programmer to CC3D  main port I have connected motors to output 1,2,3. Servo goes to output 4 and works out of the boax after choosing TRICOPTER setup.

Controller Multiwii (rewrite) YAW P lowered to 5, servo digtial so Ive changed set servo_pwm_rate = 400 (could be 333 depending od the servo used). Default 50 is however also fine for slower analog servos.
To get more JAW authority RC RATE for YAW changed to 0.5 but I always keep 3 different RATE selections under 3 position switch.
