### ISSUE TITLE
CC3D with FrSky TFR4-SB

### ISSUE THREAD

**Issue by Heliot1** [cleanflight/cleanflight#593]
Hey there,

acutally i got an issue with the receiver above. I can't get it working. There is absolutely nothing coming into the FC. Docs say, that i won't need an inverter with the cc3d. The courious thing...on openflight it isn't working, too. Maybe because of the Banggood board?! Are there different hardware versions of the cc3d?
With an "normal" TFR6 with PWM i can get every channel working...exept of YAW. Really strange...

Regards from Germany
Thorsten

**Comment by hydra** [comment]
Please use the forums or IRC for support.  SBus without external inverter via main port works with latest firmware on CC3D when correctly configured - tested with FrSky X4RSB, X8R.
