### ISSUE TITLE
Implement MW baro calibration on gyro stick command

### ISSUE THREAD

**Issue by stronnag** [cleanflight/cleanflight#60]
In multiwii, when you use the stick gyro calib, it also resets the baro. Please consider implementing this in cleanflight. I find it quite useful (on MW) in that by the time I've connected the LiPo and moved the vehicle to the launch point (for a non-acro machine), the FC has warmed up enough to reach its "affect the baro" temperature, and a quick gyro stick reset before arming brings sanity to the elevation readings.

It appears (from observation and my limited code reading ability) that the current {base,clean}flight does not do this.

**Comment by hydra** [comment]
Ok, so nothing to do.  Closing.  Re-open if there's a problem still please.
