### ISSUE TITLE
Cleanflight quad image

### ISSUE THREAD

**Issue by 3flyguy3** [cleanflight/cleanflight#615]
The quad image in Cleanflight has changed to an image of a 'brick'. See attached. Why? How do I fix?
Is this the correct support page for Cleanflight?  I was directed to this page by a more experienced user.
![img_4053](https://cloud.githubusercontent.com/assets/11441229/6619058/9d1327f2-c895-11e4-82db-50ddb7a06fd8.JPG)

**Comment by vadav** [comment]
Best place for support would be our IRC channel #cleanflight on freenode

**Comment by hydra** [comment]
Duplicate, see https://github.com/cleanflight/cleanflight-configurator/issues/105

Please raise configurator issues int he configurator tracker.

**Comment by Akfreak** [comment]
Fixed..
