### ISSUE TITLE
System - Cleanup soft-reboot detection.

### ISSUE THREAD

**Issue by digitalentity** [cleanflight/cleanflight#619]
Do we really need to use backup registers in isMPUSoftReset function [https://github.com/cleanflight/cleanflight/blob/master/src/main/drivers/system_stm32f10x.c#L64]? 
Following code is faster, cleaner and more reliable:

```
    if (RCC->CSR & RCC_CSR_SFTRSTF)
        return true;
    else
        return false;
```

**Comment by digitalentity** [comment]
I believe the code, that uses backup registers was ported from baseflight [https://github.com/multiwii/baseflight/blob/master/src/drv_system.c#L209]. 
According to ST's reference manual, STM32F1xx family has the CSR and SoftReset flag. Using those to detect a soft-reset is a much cleaner way than magic values in backup memory. I've created a PR #620 with the change.

**Comment by hydra** [comment]
What about the F3 targets?

**Comment by digitalentity** [comment]
F3 targets are using this approach in isMPUSoftReset() already.
