### ISSUE TITLE
Need a way to change looptime without CLI

### ISSUE THREAD

**Issue by anthonycake** [cleanflight/cleanflight#630]
It would be great if the looptime could be changed without the use of the CLI (and it's required reboot). 
OSDs which allow PIDs and related parameters to be set 'in bulk', can already set most parameters that would change from one 'expert setting' to another. Looptime is one exception to this.

**Comment by hydra** [comment]
This is done in the firmware.  There is an open pull request to add GUI support but needs a bit more work.
