### ISSUE TITLE
RC1.8.0 Parallel PWM missing channels

### ISSUE THREAD

**Issue by nebbian** [cleanflight/cleanflight#636]
Using Release Candidate 1.8.0 and parallel PWM, my receiver channels for throttle and rudder are not coming through.  Aux 1 is coming through as throttle, and aux 2 is coming through for rudder.

**Comment by OpCode1300** [comment]
Had this issue on Rev5 Naze32

**Comment by reelflyt** [comment]
Using Afro Naze 32  release 1.8.0 lost rudder and throttle channel . Still had Ale. Ele . Aux 2 and Aux 3 
Receiver was Orange 9 channel DSMX .

**Comment by xanido** [comment]
Had the exact same issue on Naze32 rev5.
