### ISSUE TITLE
Cleanflight 1.8.0. Can not save values for Naze32 board

### ISSUE THREAD

**Issue by hawaiianer** [cleanflight/cleanflight#638]
Hello,
I just got a new Naze32 (Clone) from Ebay and flashed the 1.8.0. Cleanflight on it. 
I can not save any values (configuration or reciever or modes) with this version. With 1.7.2 it is working.
(I have two of those boards, both have the issue)

Is this issue know or am I the only lucky one?

Regards,

Luz

**Comment by rocky77** [comment]
Hello,  yo need cleanflight-configurator v0.63

--- Message initial ---

De : "hawaiianer" <notifications@github.com>
Envoyé : 17 mars 2015 20:21
A : "cleanflight/cleanflight" <cleanflight@noreply.github.com>
Objet : [cleanflight] Baseflight 1.8.0. Can not save values for Naze32 board (#638)

Hello,
I just got a new Naze32 (Clone) from Ebay and flashed the 1.8.0. Cleanflight on it.
I can not save any values (configuration or reciever or modes) with this version. With 1.7.2 it is working.
(I have two of those boards, both have the issue)

Is this issue know or am I the only lucky one?


Regards,

Luz

---
Reply to this email directly or view it on GitHub:
https://github.com/cleanflight/cleanflight/issues/638

**Comment by hydra** [comment]
Closing, please read release notes.

**Comment by thenickdude** [comment]
That sounds like you are not using the required development version of the
configurator (0.63.0). Please follow these instructions to install it:

http://www.rcgroups.com/forums/showthread.php?t=2249574&page=319#post31078207
