### ISSUE TITLE
Gps mode not enable

### ISSUE THREAD

**Issue by Piradoxlanieve** [cleanflight/cleanflight#643]
I am trying to activate the gps modes but never changes color and not activated. need 3d fix it? and 5 satellites. I use flip32+ and cleanfligh 1.7.2
![gps](https://cloud.githubusercontent.com/assets/10765838/6721500/060bf8e6-cdce-11e4-996d-593b85cedd0e.jpg)

**Comment by thenickdude** [comment]
The indicator represents the current flight mode. The GPS flight modes are not available until 5 satellites have been locked, which is why it is showing red for that status.

**Comment by Piradoxlanieve** [comment]
thanks and sorry, not know there was a section in this forum
