### ISSUE TITLE
LED Strobe

### ISSUE THREAD

**Issue by alvins82** [cleanflight/cleanflight#645]
It would be great if a strobe effect was possible using LEDs driven by Naze32. Similiar to how these work - http://www.hobbyking.com/hobbyking/store/__26238__LED_PCB_Strobe_White_3_3_5_5V.html.

Ideally you could program the strips with this behaviour. Ultimately can program stuff like this in - http://en.wikipedia.org/wiki/Navigation_light#Aviation_navigation_lights.

**Comment by handsomejackuk** [comment]
just regular leds would be good to and not just ws2812b...

**Comment by hydra** [comment]
Duplicate of #471. See also #473
