### ISSUE TITLE
Port refactored beeper code from Baseflight

### ISSUE THREAD

**Issue by thenickdude** [cleanflight/cleanflight#648]
Creating this issue to help track issues that are blocked waiting for beeper code to be ported over from upstream and progress on implementation.

Related issues: 

#647 Add beep when changing flight modes
#481 Morse code beeps for failure states
#408 CLI command to play/test warning tones
#317 Beep to sound on arm/disarm

**Comment by hydra** [comment]
Thanks for opening this nick.  Much appreciated.

**Comment by ethomas997** [comment]
Is anyone currently working on this task?  If not then I'll work on it and post a PR.

--ET

**Comment by thenickdude** [comment]
@ethomas997 haven't heard anyone mention it on the IRC channel (I'm not working on it, at least).

**Comment by hydra** [comment]
@ethomas997 please go ahead and do this! Many thanks.

**Comment by ethomas997** [comment]
Alright, PR is posted.  http://github.com/cleanflight/cleanflight/pull/669
I've been flying this version with no issues.

--ET

**Comment by hydra** [comment]
Nice!  I'll check this out.

**Comment by TadasSu** [comment]
Hi All.
All beeps are very quiet in CleanFlight (in comparison with baseflight). 
It seems that beeps in BF are way longer (maybe double the time).
Low Voltage beeps almost can not be heard (or hear the difference between low and critical alarm) when flying.
Is it possible to make them louder (longer)?

**Comment by dkisselev** [comment]
@TadasSu Have you tried the new beeper code in #669? It'll be in CF 1.9.x and some of the sounds have been changed to be louder/closer to baseflight sounds.

**Comment by ethomas997** [comment]
If anyone wants to try out a test hex file I've posted one here:  http://www.etheli.com/CF/refactoredBeeperCode

--ET

**Comment by TadasSu** [comment]
Thanks, I will try it :)

**Comment by ethomas997** [comment]
Updated PR for this is here:  Port of refactored beeper code 181_1 #730
As far as I know it's ready for merging.

--ET

**Comment by hydra** [comment]
done
