### ISSUE TITLE
Serial doc has lost information

### ISSUE THREAD

**Issue by mmartinmate** [cleanflight/cleanflight#651]
Hi 
I have found that samples of serial configuration have been lost form manual.pdf and also in serial.md since version 1.7.2 after adding the new baud rates.

Yours sincerely,
    Miguel.

**Comment by thenickdude** [comment]
That's those are really too hard to configure by hand (they use bitmasks which are unreasonable to compute by hand), use the new 0.63.0 Configurator's GUI interface to configure the ports instead.
