### ISSUE TITLE
Buzzer - Change buzzer pin to RC_Output_6 on CC3D

### ISSUE THREAD

**Issue by digitalentity** [cleanflight/cleanflight#653]
According to docs on CC3D pin 6 of RC_Output connector is always unused. Also, buzzer uses simple GPIO bit banging. Why don't use pin 6 of RC_Output to drive an external buzzer?

**Comment by digitalentity** [comment]
This will allow us to attach a beeper to CC3D without precise soldering.

**Comment by Pierre-A** [comment]
refered in issue ≠832

**Comment by hydra** [comment]
See #357 and #884.

If the pin is indeed always unused then it would certainly be a good candidate, yes.  Someone verify this and submit a PR please.

**Comment by Pierre-A** [comment]
PR for buzzer on CC3D output 6 is on the way

**Comment by digitalentity** [comment]
Oops, sorry @Pierre-A, didn't see you comment.

**Comment by digitalentity** [comment]
@hydra, I've been flying with changes from b9f281fdc5bab98e46cddad703a9f517497721cf for a while - no problem so far. The next one 53ce4b224d130a437fc5f5be9ffcb3882a52903b is untested.

**Comment by Pierre-A** [comment]
no problem **digitalentity**, so it's done !
