### ISSUE TITLE
Allow mapping of any aux channel

### ISSUE THREAD

**Issue by zatalian** [cleanflight/cleanflight#66]
rcmap is only 8 positions, so it is not possible to map aux5-8 with the cli "map" function. only AETR1234 can be mapped.

**Comment by bmedici** [comment]
it would be really great to take advantage of s-bus channels to change modes and make adjustments.

**Comment by ledvinap** [comment]
It is already possible to use the channels. Order of first 8 channels can be permuted, higher channels (aux5-aux12) are used directly.

Is there any use for mapping higher channels?

**Comment by bmedici** [comment]
Mapping the upper channels may not be a real need. One great thing though is to be configure CH4-8 for AETR in order to use physical PWM ports on a X4R receiver for example.
Using SBUS here, can't get the upper channels (8>16) to work, AUX 5-12 are not moving accordingly.

**Comment by hydra** [comment]
Mapping should work with these values `AERT12345678abcdefgh`.

Closing, nothing to do, if there's a problem please open a new issue and reference this.

**Comment by ledvinap** [comment]
@hydra : AERT12345678abcdefgh is IMO used only for display, just first few can be remapped (and case lowercase letters are unusable for remap)
