### ISSUE TITLE
LuxFloat I value not able to be tuned effectively

### ISSUE THREAD

**Issue by nebbian** [cleanflight/cleanflight#668]
Several people including myself have noticed that when using PID Controller #2 (LuxFloat), the I term is not able to be set high enough to effectively hold angle properly.  The pull request below has been flight tested by myself and others, and solves the issue.

Pull request is here
https://github.com/cleanflight/cleanflight/pull/666

**Comment by hydra** [comment]
What size aircraft have you tried this on?

**Comment by nebbian** [comment]
This was apparent on a 250 size "Zippa" mini quad, and FinalGlide noticed the issue on a 250 size Blackout quad.

**Comment by ummagawd** [comment]
Confirmed on vortex prototype on 1.7.2

**Comment by hydra** [comment]
@ummagawd thanks for the feedback.

**Comment by hydra** [comment]
PR is merged for 1.8.0.
