### ISSUE TITLE
Missing channel data when using SBus.

### ISSUE THREAD

**Issue by zatalian** [cleanflight/cleanflight#67]
sbus is working correctly, but only 12 channels are available. frsky sbus is 16 channels.

**Comment by andymac4182** [comment]
Is this related to https://github.com/cleanflight/cleanflight/issues/283 ?

**Comment by hydra** [comment]
i have sbus working just fine here with X8R and X4RSB with full 16 channels.

You haven't given me enough information to work with here.  What TX, RX.  Did you configure TX to send all 16 channels.  Is TX running latest opentx, etc.

**Comment by hydra** [comment]
This has been working for a long time now, closing.
