### ISSUE TITLE
Obsolete docs for softserial

### ISSUE THREAD

**Issue by xoxota99** [cleanflight/cleanflight#671]
Setting serial_port_xx_scenario appears to no longer exist in 1.8. Configurator "ports" tab appears all jacked up (showing "UART1" multiple times, and nothing else, on Naze32). See attached.
![screen shot 2015-03-24 at 10 57 37 pm](https://cloud.githubusercontent.com/assets/3106132/6819124/466c8e1e-d279-11e4-896e-32bebd0f87fe.png)

**Comment by thenickdude** [comment]
You're using the wrong Configurator version, please use the 0.63.0 version mentioned as required in the release notes:

https://github.com/cleanflight/cleanflight-configurator/tree/development

**Comment by xoxota99** [comment]
Thanks! Doesn't configurator update automatically? How can I tell what version I'm using?

**Comment by xoxota99** [comment]
Uninstalled and redownloaded the latest version from Chrome web store. No change.

**Comment by digitalentity** [comment]
Please read release notes to 1.8.0 release here: https://github.com/cleanflight/cleanflight/releases/tag/v1.8.0
You cannot use the Configurator from the Chrome Web Store, you should manually install configurator from "development" branch here: https://github.com/cleanflight/cleanflight-configurator/tree/development

You install it this way:
1) Download it as zip, unpack to some directory (for example D:/cleanflight-configurator)
2) Start Chromium or Google Chrome and go to tools -> extension
3) Check the "Developer mode" checkbox
4) Click on load unpacked extension and point it to the Cleanflight Configurator directory (for example D:/cleanflight-configurator)

**Comment by hydra** [comment]
Yes, all that and please search before opening new issues!
