### ISSUE TITLE
"Save and Reboot" from Configuration tab doesn't do either of those things on Naze32.

### ISSUE THREAD

**Issue by xoxota99** [cleanflight/cleanflight#672]
Repro:
1) Connect to Naze32 (running Cleanflight/NAZE 1.8.0 Mar 20 2015 / 18:39:17 (730d0fe))
2) Go to "Configuration" tab.
3) Change any setting, e.g. set "Yaw Adjustment" to -90. 
4) Click "Save and Reboot". Observe the board does not appear to reboot.
5) Disconnect the board and reconnect. Observe the change to "Yaw Adjustment" has not actually been saved. Same prblem occurs for all settings, on all tabs. Only place settings can actually be saved reliably is through the CLI tab.

**Comment by digitalentity** [comment]
Make sure you are using 0.63 version of the configurator. "Save and Reboot" is apparently working on my Flip32 (Naze32 clone) with 1.8.0 cleanflight and 0.63 configurator.

**Comment by xoxota99** [comment]
Thanks. Where can I get latest version? I uninstalled and reinstalled from Chrome web store, and no difference (that appears to be v 0.62.1?)

**Comment by xoxota99** [comment]
Resolving, as this is a configurator issue. This is the wrong issues repo.
