### ISSUE TITLE
After saving in CLI tab, CLI is unresponsive

### ISSUE THREAD

**Issue by xoxota99** [cleanflight/cleanflight#673]
Repro:
1) Connect to Naze32 (running Cleanflight/NAZE 1.8.0 Mar 20 2015 / 18:39:17 (730d0fe))
2) Go to CLI tab, change a setting (e.g. set failsafe_throttle = 1100)
3) type "save". Observe the setting is correctly saved, and the board reboots.
4) After rebooting, configurator is still connected. Attempt to type anything else in the CLI tab. Observe there is no response. CLI is unresponsive until you switch away to another tab, and back.

**Comment by digitalentity** [comment]
I believe this is the wrong place to post this issue. It is configurator related and should be opened there.

**Comment by xoxota99** [comment]
Crap. Sorry. Resolving.
