### ISSUE TITLE
Blackbox strange axisI data 

### ISSUE THREAD

**Issue by muellerr** [cleanflight/cleanflight#678]
I'm using Cleanflight 1.8 and a naze32 board on one of my quadcopters. Thanks to the newest version of Cleanflight I can now log flight data to the onboard memory.
Most of the data makes sense. What does not make sense is the "axisI" that does not change over very long periods of time. See the following image:
![blackbox_log](https://cloud.githubusercontent.com/assets/11670132/6856362/f0d883bc-d3ff-11e4-974e-483d8dee7be4.png)
What could be the cause of the problem?

**Comment by thenickdude** [comment]
That's normal, the I term can only be reduced when the error changes sign, which will either happen when you change direction, when you're hovering, or if the I term is correcting for an offset CoG it might never drop.

**Comment by thenickdude** [comment]
(the I term saturates due to limiters which is why it flattens out like that. If there were no limiters you'd probably see it moving around freely instead of sitting at the saturation point)

**Comment by ledvinap** [comment]
@muellerr : What PID are you using?

**Comment by muellerr** [comment]
@thenickdude: thanks for your answer. There seem to be at least two different levels present. Do these limits change depending on flight mode?

@ledvindap: On the axis shown I use P=4, I=0.025, D=25. But it seems far from the optimum.

**Comment by ledvinap** [comment]
@muellerr : And what PIS are you using? (`set pid_controller=n`)

**Comment by muellerr** [comment]
I'm using 0.
