### ISSUE TITLE
FrSky - GPS speed incorrect for D-series telemetry

### ISSUE THREAD

**Issue by SamuelBrucksch** [cleanflight/cleanflight#679]
static void sendSpeed(void)
{
    if (!STATE(GPS_FIX)) {
        return;
    }
    //Speed should be sent in m/s (GPS speed is in cm/s)
    sendDataHead(ID_GPS_SPEED_BP);
    serialize16((GPS_speed * 0.01 + 0.5));
    sendDataHead(ID_GPS_SPEED_AP);
    serialize16(0); //Not dipslayed
}
#endif

should actually be transmitted in knots as per specification of frsky protocol:
http://www.frsky-rc.com/download/down.php?id=126

Not sure if its the same for x-series...

**Comment by samcook** [comment]
Fixed in #743

**Comment by hydra** [comment]
@samcook Thanks for feedback.
