### ISSUE TITLE
Blackbox - Record flight mode and failsafe state

### ISSUE THREAD

**Issue by digitalentity** [cleanflight/cleanflight#684]
This feature will further improve ability to investigate flight issues. I personally was trying to figure out why gps poshold does not work. Blackbox log was showing 9 sats in view, mode switch was configured correctly, but gps poshold mode simply didn't work. It took me a while to figure out my GPS receiver was buggy - didn't report a 3d fix and poshold mode didn't get enabled. If blackbox was logging active flight mode, investigating my issue would took much less time.

**Comment by payne92** [comment]
+1 for this request

We're trying to debug a problem now, possibly related to a flight mode issue.

**Comment by nathantsoi** [comment]
Agreed, lmk if I can help get this pulled in.
