### ISSUE TITLE
LED -  Move Sparky ledstrip output from pwm5 to pwm7

### ISSUE THREAD

**Issue by bhuism** [cleanflight/cleanflight#688]
The ledstrip is hard wired to pwm5 on (at least) Sparky, this makes it impossible to use the ledstrip on a tricopter configuration since it clashes with pwm5 for the third motor. Please move it to an unused pin, pwm7? (pwm8 + pwm9 are proposed for ADC in #635)

**Comment by DaTwo** [comment]
I would also love to see this. I use the gimbal feature to tilt the camera. Looks like I cant use that and LEDS at the same time. Is there a way to do this currently?

**Comment by hydra** [comment]
See #884

**Comment by hydra** [comment]
See #357 too.

Basically, right now, no. But we can investigate this further once resource allocation is improved.
