### ISSUE TITLE
Support for dual Spektrum Satellite receivers 

### ISSUE THREAD

**Issue by fiveangle** [cleanflight/cleanflight#69]
There is no current support for dual Spektrum Satellite receivers, in order to provide diversity without requiring an entire external receiver and satellites.  There should be a way to designate a serial port scenario where one port can be designated a primary satellite port (which would require a dedicated UART for a Spektrum satellite, for example) and then designate a secondary satellite on a UART that can be shared (with CLI for example) and the data from both used to provide diversity.  RSSI could be emulated and reported to MPC based on a calculation tallying the response from both sats.

-=dave

**Comment by hydra** [comment]
Closing, no-one seems to want it.  If people really do want it please comment on here and say why.

Current solution is just to buy a better receiver for your aircraft that has built in diversity.
