### ISSUE TITLE
Can't have FrSky telemetry on both UART1 and SOFTSERIAL1

### ISSUE THREAD

**Issue by thenickdude** [cleanflight/cleanflight#692]
A user reported that their FrSky telemetry wasn't working on SOFTSERIAL1 on 1.8.0. It turned out that they accidentally also had FrSky telemetry enabled for their UART1 port. Disabling FrSky on UART1 made the SOFTSERIAL1 FrSky telemetry suddenly start working.

I was able to replicate this here on my Naze32, starting with an empty config and just enabling RX_PPM SOFTSERIAL TELEMETRY features and setting telemetry_inversion = 1. I then added FrSky to SOFTSERIAL1's port config and it immediately started working fine. Then I added FrSky to UART1 and the SOFTSERIAL1 telemetry stopped working, whether armed or disarmed.

I think this is mostly a documentation issue, because the docs don't mention that FrSky can't be sent over multiple ports (it's not a very useful configuration to support). The serial port configuration should probably be automatically amended to remove FrSky from extra ports after the first one it is configured for.

**Comment by hydra** [comment]
Documentation updated.
