### ISSUE TITLE
Build - Create platform-agnostic building instructions

### ISSUE THREAD

**Issue by Petfrogg** [cleanflight/cleanflight#700]
In the end of https://github.com/cleanflight/cleanflight/blob/master/docs/development/Building%20in%20Mac%20OS%20X.md it says:

make clean TARGET=NAZE
make TARGET=NAZE

I suggest change it to the following:

In case of NAZE
make clean TARGET=NAZE
make TARGET=NAZE

For other available boards type:
make help

CC3D and Openflight as flashing tool
If you are using a CC3D board and updating the firmware using Openflight you need to compile it using these lines in order to get it to work:
make TARGET=CC3D OPBL=yes

**Comment by thenickdude** [comment]
I don't think these instructions belong in the Mac-specific building notes, we probably need a more general doc file for them.

**Comment by hydra** [comment]
@thenickdude agreed.

@Petfrogg can you perhaps submit a pull request and create a general 'Building.md' file with this information and add links from it to the platform specific sections/files?

**Comment by thenickdude** [comment]
This could probably fit in https://github.com/cleanflight/cleanflight/blob/master/docs/development/Development.md now
