### ISSUE TITLE
LED - Show GPS 3D fix status

### ISSUE THREAD

**Issue by skaman82** [cleanflight/cleanflight#709]
Is there a way to indicate 3D fix on the LED Strip? (naze32)

**Comment by hydra** [comment]
no, but it's a good idea.  I had the same idea a long time ago when i added the led strip code but never got round to it.

**Comment by hydra** [comment]
Satellite count could also be blinked out too.

**Comment by skaman82** [comment]
That would be great!

**Comment by multimartin** [comment]
Any progress on this one ? - just the "lock" status would be extremely helpful - blinking or similar...

**Comment by meup** [comment]
I would also very much like to see this feature, please!

**Comment by rvbcrs** [comment]
Hi, please this should really be a default function for the led strip! If I want to use the GPS function there should be a way to know what the status is. Best would be through led strip. Is there any progress on this?

**Comment by gaelj** [comment]
Patience....

**Comment by skaman82** [comment]
thanks, closing
