### ISSUE TITLE
Buzzer - Show visual representation of beep codes in documentation.

### ISSUE THREAD

**Issue by heathicus** [cleanflight/cleanflight#711]
Include a description (or even links to sound files) of the various beep codes and their meanings.

**Comment by JohnieBraaf** [comment]
Not really solving the issue, but this is a interesting read of potentially upcoming functionality. https://github.com/cleanflight/cleanflight/pull/669 it might be done in one go.

**Comment by ethomas997** [comment]
There's an updated PR:   Port of refactored beeper code 181_1 #730 

--ET

**Comment by payne92** [comment]
I'm working on documenting this in more detail.  Any thoughts on the best way to render buzzer patterns visually in Github markdown?

What about Unicode?

&#8212;  

or 

&#65293; 

or 

&#65293;&#65293;&#65293;

or

&#9608; &#9608;&#9608;&#9608;  (I like this one the best)

**Comment by JohnieBraaf** [comment]
Sweet, I like the last one.

**Comment by hydra** [comment]
I like the last one too, gotta make sure it renders in the PDF version of the manual though.

**Comment by payne92** [comment]
Excellent point, I will keep that in mind.
