### ISSUE TITLE
Full duplex (dual function) UART port

### ISSUE THREAD

**Issue by JohnieBraaf** [cleanflight/cleanflight#713]
As enhancement, would it be possible to use a UART port in 2 ways:

RX pin: connected to receiver (SBUS, PPM)
TX pin: connected to minimiosd (MSP)

For example on the Sparky board in this sense, PWM6 (PA2 which is UART2_TX) could be used for this purpose. You effectively save 1 UART port.

In cleaflight-configurator 0.1.63.0, the new PORT tab layout could be used to check the right box.

**Comment by thenickdude** [comment]
OSDs require a bidirectional port (MSP protocol requires that you ask for the data you want, and OSDs even change settings over MSP which will always require a bidirectional connection).

**Comment by JohnieBraaf** [comment]
Hmmm, ok gonna close this one then.
