### ISSUE TITLE
pid_at_min_throttle incompatible with retarded_arm

### ISSUE THREAD

**Issue by thenickdude** [cleanflight/cleanflight#719]
With `retarded_arm` set to 1, the craft is armed with zero throttle and full *roll*. This is incompatible with `pid_at_min_throttle` because full roll causes the craft to roll over on the ground (the pid_at_min_throttle implementation ignores yaw on the ground, but doesn't currently ignore roll when retarded_arm is enabled, so it's not compatible with retarded_arm).

**Comment by hydra** [comment]
Does anyone actually use 'retarded_arm'?  Can we delete it?

**Comment by iacopo** [comment]
That’s a very timecop-sy thing to say :)
Honestly I get no mode-2 pilot will ever use retarded_arm, but as a mode-1 pilot I find it extremely useful to disarm using a single stick instead of two.
That said, I think I will leave retarded_arm off and start plaing with pid_at_min_throttle, because it looks very cool to do stunt at 0 throttle!

**Comment by hydra** [comment]
ahh yes, mode 1 people.  that makes sense now :smile:

**Comment by iacopo** [comment]
so many times I thought about switching to mode 2, but it was too late! Like trying to become left-handed.

**Comment by hydra** [comment]
Current solution is to disable `pid_at_min_throttle` when `retarded_arm` is enabled.

Please feel free to open a PR with a better solution.  I think this is acceptable for now and won't result in any suprises for mode-1 users.

**Comment by nebbian** [comment]
It's useful for tricopter pilots who don't want their tail rotor to hit the ground when disarming.  This happened to me a lot when I was flying a tricopter.  I always rolled my eyes and looked longingly back at my KK2 which never had this problem, it is smart enough to realise that vectored thrust is only useful when there is thrust to vector.
