### ISSUE TITLE
Beeping on "Save" in PID Tuning - UI

### ISSUE THREAD

**Issue by Petfrogg** [cleanflight/cleanflight#724]
While connected with bluetooth and when pushing "Save" the model should be able to give some feedback. The usability of this is best depicted when doing PID changes using bluetooth.

I suggest 2 impulses (or more if it collides with any already in use) sent to the beeper when saving or refreshing while using any wireless connection.

**Comment by thenickdude** [comment]
You mean to confirm receipt of the command to save? In theory the Configurator can already react to that, because when an MSP command is received, it replies with a "success" message. When no "success" message is received, the Configurator should print a timeout error message to the log at the top.

**Comment by ethomas997** [comment]
Seems like when I'm connected via bluetooth and the connection is wonky, when I do a save (that fails) the Configurator shows no response message at all (no "EPROM saved" or error message).  A confirmation beep on save would be a plus, IMO.

--ET

**Comment by hydra** [comment]
This is a GUI issue, please open something appropriate in the other issue tracker.

**Comment by Petfrogg** [comment]
I thought the beeping is something that relates to cleanflight and not the configurator. Since it is the board that needs to do the beeping shouldn't it be here then? Please direct me on where to post this.

**Comment by thenickdude** [comment]
IMO this is a Configurator bug. The configurator already (should) know if
its command has made it safely to the FC or not (by listening for a serial
ack), so there's no reason why we need the FC to confirm it separately. The
configurator needs updated so it properly communicates the success status
to the user (assuming it doesn't already, check the error log at the top).

**Comment by thenickdude** [comment]
Also note that the FC cannot beep unless the flight battery is connected
(by Naze32 design) so we couldn't add a reliable beep anyway.
