### ISSUE TITLE
1.8 flash cc3d board to cleanflight

### ISSUE THREAD

**Issue by eranme** [cleanflight/cleanflight#726]
Got a new board from fpvmodel.com flashed with. Cleanflight 1.8 stable can not connect via usb i am using win 8.1 64  the led light on the board is orange no issues in devices on the pc.  The pic make a sound that a device is connected no error but the software can not find the board

**Comment by dascons** [comment]
You need to use some drivers if you don't use open pilot:
http://www.st.com/web/en/catalog/tools/PF257938

**Comment by jamieharwood** [comment]
I have the same problem on my Mac. Is there a similar driver I need to install?

**Comment by eranme** [comment]
Thank you dascons i installed the driver as explained and no luck....

**Comment by eranme** [comment]
i tried connecting it to my Mac no luck...

**Comment by eranme** [comment]
jamieharwood
click on the link https://wiki.openpilot.org/display/WIKI/Bootloader+Update
it will help you to revert back 
i will wait for a fix and then try to flash back to cleanflight

**Comment by tricopterY** [comment]
Power up the FC using its USB port via your PC/Mac. If you have the driver installed your computer would detect the FC and allocate a virtual com port. Then open the Chrome based CleanFlight Configurator. 
Configurator should find all the virtual com ports and populate a dropdown list. You should select one com port and attempt the connection. If it fails, close the Configurator, then restart it and try other reported com port(s) from the dropdown list.

**Comment by Telnoi** [comment]
both the usb cable and the lipo have to be connected. Without lipo, my cc3d will not connect either.

**Comment by FranzAr** [comment]
I've made a small Video on installing Cleanflight on CC3D. Read also the description and comments. Cleanflight on CC3D is a bit tricky to handle, but if you follow the instructions all works fine.
https://youtu.be/_9zxu2vmdlY

**Comment by Indy6** [comment]
Hi guys,
As I understood, on a mac with a CC3D, I have to plug a battery? So that means I can't synchronise my ESC with Cleanflight since the first step is to put the motors to the max without the battery, isn't it?

**Comment by FranzAr** [comment]
No problem, first connect with battery plugged. Then unplug battery, the USB connection will remain active! Go to Motor Tab and synchronize as usual.

**Comment by Indy6** [comment]
Thanks FranzAr, unfortunately it's my stupid day. Trying to synchronize my Emax Simonk ESC with the throttle, I made a mistake and set the ESC to bidirectional. Now it seems I can't enter the program mode, the security doesn't allow me to start throttle up... I'm stuck... ;( thanks anyways

**Comment by A-Z-que** [comment]
hello i have a cc3d and i connected the battery and openpilot is discontinued and my CC3D wont connect to cleanflight
