### ISSUE TITLE
Autotune - altitude climb when thrust to weight ratio is high

### ISSUE THREAD

**Issue by NullVoxPopuli** [cleanflight/cleanflight#728]
I tired using auto tune on my warpquad, and as it was making adjustments, it was climbing. 
I have yet to complete an auto tune session, cause of how high it gets :-\

**Comment by acceleroto** [comment]
There's lots of development talk about autotune right now.  The short story is that it doesn't work.  My strong recommendation is: Don't use it.

**Comment by NullVoxPopuli** [comment]
Oh ok. cool. thanks :-)

(I'm fine flying in acro) :-)

**Comment by acceleroto** [comment]
You might want to try G-Tune then.  It's still in development, so be careful.

**Comment by illuxion** [comment]
autotune with this code is EVIL.  It's not only the problem of high thrust to weight, but that it ignores all failsafes, or at least it sets the PIDs so whacky what the failsafes are ignored.  I spent 2 weeks building and testing a mini quad bros kit, replacing the acro with a full Naze32, adding sonar, and a few other goodies(wish I would have added GPS).  I had been honing my PIDs and had a pretty well behaved quad with a little bit of Z and yaw issue so I decided to hit auto tune.  It did a few normal back and fourths then absolutely lost it's mind and went skyward.  I hit disarm but it continued up so I turned off my taranis, but it STILL continued up.  Failsafe and disarm should take priority over EVERTHING else, but they don't so I'm out a few hundred bucks.

**Comment by anees042** [comment]
when ever i enable auto tune, my quad falls from the sky, the altitude normally is about 5 meters. any recommendations?

**Comment by acceleroto** [comment]
Ummm, don't use autotune.  The docs say not to use it right now.

**Comment by hydra** [comment]
autotune has been replaced with G-Tune.
