### ISSUE TITLE
Anomaly with the Graupner HoTT Telemetry

### ISSUE THREAD

**Issue by Pierre-A** [cleanflight/cleanflight#73]
Using the Graupner HoTT telemetry on a simple Naze32 configuration : nothing connected to the Naze (no GPS) except the Graupner Rx whose telemetry pin is connected as usual with a 1N4148 diode on RC5/RC6 (SoftSerial 1).
The corresponding CLI parameters are (serial_port_3_scenario = 4   and   gps_provider = 1) but, in order to get the expected data on the Graupner Tx, the  serial_port_2_scenario  has to be set to zero (unused).
If not (as  serial_port_2_scenario  default value is 2), no data frame is provided on RC6.

**Comment by hydra** [comment]
The documentation was updated to reflect this now-expected behavior.
