### ISSUE TITLE
CC3D PWM Inputs - Only 4 channels seen with VBat disabled

### ISSUE THREAD

**Issue by dkjab** [cleanflight/cleanflight#738]
With VBAT enabled channels behave as documented. When VBAT is disabled, Pin 7 should be CH4 and  Pin 8 should be CH5. Pin 7 does not respond to input. I have 3 boards all doing this with different RX modules and TXs. PPM  works fine.

**Comment by hydra** [comment]
I tested this when #612 was closed and found no issue.  This is kinda weird.  Please confirm that you are running v1.8.1 and provide a complete dump of your config (include all output from the 'dump' command).

**Comment by dkjab** [comment]
Flashed boards to v1.8.1rc and issue resolved.

**Comment by hydra** [comment]
@dkjab thanks for confirmation.
