### ISSUE TITLE
Virtual Current Sensor documentation unclear

### ISSUE THREAD

**Issue by dkisselev** [cleanflight/cleanflight#740]
I'm trying to setup the virtual current sensor, but the docs aren't quite clear on how to do it.

```
Adjust current_meter_scale until the mAh draw reported by Cleanflight matches the charging data given by your battery charger after the flight (if the mAh draw is lower than reported by your battery charger, increase current_meter_scale, and vice-versa).
```

By the time you get home to the charger, the board's been powered off so CF's mah count it lost and you can't tweak it.

I'd like to help improve the docs to make the setup more clear, but don't know what the process should be. I'm guessing it's either linear or a multiplier, ie. if CF reports 1000mah but the reality was 1500, set the offset to 500, but don't know for sure.

If anyone's done it and has a step-by-step worked out, I'd love to hear it, otherwise I'll poke around and post my finding here (and update the doc if I get somewhere conclusive)

**Comment by hydra** [comment]
Perhaps check the closed PR's to find the author of the virtual current meter code and ask them, you can just mention their github username in a comment.

**Comment by dkisselev** [comment]
Here's my data for a few packs, it looks like the current sensor is actually really accurate even with no configuration on some builds (I have a 450). Virtual is what CF reported at time of flight, charger is how much I put back into the pack.

Virtual: 1346mah  
Charger: 1219mah

Virtual: 1266mah  
Charger: 1185mah

Virtual: 1260mah
Charger: 1148mah

Just leaving this here for anyone's reference. Gonna play around with the the code to see if I can get it even more accurate.

**Comment by handsomejackuk** [comment]
nice one i need to monitor this too....

**Comment by payne92** [comment]
Could someone here eyeball doc edits #820 to see if they address the questions here?  Thanks!

**Comment by digitalentity** [comment]
I just did so, looks much more clear and understandable to me.

**Comment by dkisselev** [comment]
@digitalentity We need to actually test a full cycle to make sure the instructions/calculations actually work (they do in Theory, but a live test would be best).

I've just been too busy to go out and fly twice since the discussion started so haven't been able to charge my batteries and test the real usage after making my changes.

**Comment by payne92** [comment]
@dkisselev I agree, but I worry that there's a dependency on the accuracy of the particular battery charger that may make it work for some and not work so well for others.  

My preference is to disclaim that and highlight that this is an *approximate* method, better than nothing, but not a full substitute for a current meter.

**Comment by digitalentity** [comment]
@dkisselev, I fly with virtual current sensor - don't have needed hardware yet. Calibrated it using an ammeter and now it is pretty reliable. However I agree that we must state that it is an approximation of actual current draw.

**Comment by payne92** [comment]
Good comments, I updated #820 accordingly, adding:

"Note:
+ This method depends on the accuracy of your battery charger; results may vary.
+ If you add or replace equipment that changes the in-flight current draw (e.g. video transmitter, 
+ camera, gimbal, motors, prop pitch/sizes, ESCs, etc.), you should recalibrate."
