### ISSUE TITLE
Build - Code Metric and Smell analysis reports

### ISSUE THREAD

**Issue by NullVoxPopuli** [cleanflight/cleanflight#752]
I really admire the goal of cleanflight - applying good software engineering principles, etc
But I think it would be awesome to see the current state of existing smells and another static analysis metrics.

Maybe something like http://oclint.org/ could help?
(I don't do much C/C++ programming yet, so I don't know what would be best here. (I'm doing Ruby (personal projects) and VB.net (client project) at the moment))

**Comment by hydra** [comment]
Yes, it would be good to add some report generation to the automated Travis builds.

**Comment by NullVoxPopuli** [comment]
Travis is great! I use it for my ruby gems.
I can try to set that up, but I figure travis should be in your name, yeah? @hydra

**Comment by NullVoxPopuli** [comment]
I think we want this for code coverage: https://coveralls.zendesk.com/hc/en-us

**Comment by NullVoxPopuli** [comment]
We might want landscape.io for code analysis? https://landscape.io/github/NullVoxPopuli/ardupilot I'm not sure how well it works yet, but it's going over my ardupilot code now. o.o

**Comment by dkisselev** [comment]
Coveralls would be my vote.

I've also seen [Scrutinizer](https://scrutinizer-ci.com) used a lot, but I find that having half a dozen CI badges on a project tends to look bad, so maybe just the two is enough.

**Comment by NullVoxPopuli** [comment]
I think meaningful badges make a project look good.
