### ISSUE TITLE
Setting mixer variables on CLI/restoring dumps when profile<>0 causes setting corruption

### ISSUE THREAD

**Issue by thenickdude** [cleanflight/cleanflight#766]
The `yaw_direction`, `tri_unarmed_servo`, `servo_lowpass_freq` and `servo_lowpass_enable` variables are wrongly marked with the `PROFILE_VALUE` flag, despite the fact that they're part of the master config and not part of `profile_t`. This means that when the current profile isn't zero, reading or writing to these variables on the CLI causes a read/write to an unexpected memory location (i.e. the address of the setting plus 1 or 2 times the size of `profile_t` depending on which profile is selected). 

This causes memory corruption when restoring dumps, and makes these settings impossible to read/write on the CLI while in profile 1 or 2. For example, setting `tri_unarmed_servo` to 1 while in profile 1 on 1.8.1 causes the upper limit of profile 0's aux 17 range to be overwritten instead. Setting `tri_unarmed_servo` to 1 while in profile 2 causes the upper limit of profile 1's aux 17 range to be overwritten.

**Comment by hydra** [comment]
Good spot, looks like this was missed during the cleanup in 4a12d00d1e23fbab5f7c0effda5bf07b79f7a1d5
