### ISSUE TITLE
RC_RATE vs ROLL_RATE/PITCH_RATE/YAW_RATE Documenation

### ISSUE THREAD

**Issue by rscarawa** [cleanflight/cleanflight#773]
Can we get an update in the documentation about the difference between RC_RATE and the various axis rates?  What does each do?  Do they effect each other?  Best practice for configuring each?  The current doc has no definitions for these variables.

Thx

Scot

**Comment by Redshifft** [comment]
Good point,

This might help for the time being..
http://www.multiwii.com/forum/viewtopic.php?f=17&t=1346&sid=63088b4436d8d2404aa40fa286705ece

**Comment by hydra** [comment]
Please check documentation again, there have been some updates.  See `PID Tuning.md` - If it's still not clear please re-open.
