### ISSUE TITLE
GPS - uBlox NEO M8N module configuration

### ISSUE THREAD

**Issue by AhLeeYong** [cleanflight/cleanflight#783]
Hi,
i had bought the M8N module recently, just saw one of youtube videos setting this up and combination of those two shows an impressive GPS altitude hold, just like NAZA did! 

https://www.youtube.com/watch?v=g5e_68fUn4E

but... my M8N wont talk to Naze32, i wonder y?... i had flash the newest CF FW and configured the 2nd port to be GPS port with 9600baudrates but nothing happens. and another thing, the M8N cant be configured to other baudrates, if i choose to modify to baudrate in u-center under PRT options, let say 57600, the value change when i click send but, the u center just keep on connecting at that current baud rate of 9600bauds. other steps and parameters are also followed as shown in the CF pdf manual.

appreciate your workout on this matter, M8N+Naze32@port2.
cheers!
-ALi

**Comment by stronnag** [comment]
This is a support matter, not an issue. Please close and do not waste developer time on support matters, instead followup on IRC, RCGroups and the MW board.
* The device demonstrably works for other users
* Your device appears not to work in ucentre.
