### ISSUE TITLE
Inverted RSSI (EZUHF)

### ISSUE THREAD

**Issue by DaTwo** [cleanflight/cleanflight#788]
Adding the ability to invert the RSSI display for RX such as the EZUHF.

The EZUHF system can output the RSSI on the PPM signal as well as link quality. The main issue with this is that "0" actually indicates full signal strength and "100" indicates a lost signal. Inverting this would make it a more logical reading in Cleanflight and on your OSD.

Here is the link to the user manual of the EZUHF if needed.
http://www.immersionrc.com/?download=3061

**Comment by JohnieBraaf** [comment]
Hey. missed your message. Indeed OpenLRS is the way to go ;)

**Comment by hydra** [comment]
This is done.
