### ISSUE TITLE
Rewrite compass code to match Acc/Gyro multi-sensor capabilities

### ISSUE THREAD

**Issue by adamclaassen** [cleanflight/cleanflight#79]
Unlike the ACC and GYRO sensors, which allow for different sensor drivers to be used, the MAG sensor support is geared exclusively to one sensor. This should be changed to allow easy adding of different mag sensors, such as the LSM303DLHC on the STM32F3DISCOVERY target.

**Comment by hydra** [comment]
This no longer applies since the Sparky code.  Cleanflight supports different compass sensors now.

@adamclaassen I will close this, but please create new PR's for other compass sensors as required.
