### ISSUE TITLE
bug in annexCode

### ISSUE THREAD

**Issue by csurf** [cleanflight/cleanflight#809]
There's an order of operations bug within annexCode that's being carried over from legacy MW code.
The bug relates to how the "rcCommand" values for both throttle & pitch/roll are calculated when factoring in inbuilt expo:
http://pastebin.com/uKkWduni

The bug is evident on lines #3&4 and #10&11.
Apparently, the parentheses were left out, so the order of op's causes the center term to always evaluate to zero, thus nullifying any subsequent expressions. The solution would be to correct the order of ops & test the resulting throttle/pitch/roll values for correctness.

**Comment by thenickdude** [comment]
Isn't it currently computing (top % 100) by doing an integer divide by 100, multiplying by 100, then subtracting it from the original value?
