### ISSUE TITLE
CC3D - USB support

### ISSUE THREAD

**Issue by shuffleznl** [cleanflight/cleanflight#81]
Please look into supporting USB connection on CC3D.
First flash (and telemetry) via MainPort is good, might be preferable to have USB connection available for people without BT or FTDI knowledge.

**Comment by hydra** [comment]
Done!

http://forums.openpilot.org/topic/43569-baseflightcleanflight-ported-to-cc3d/?p=401045

Please can you test and re-open this if there are issues.
