### ISSUE TITLE
Support for roll_pitch_rate

### ISSUE THREAD

**Issue by automat64** [cleanflight/cleanflight#812]
Would it be possible to bring back the roll_pitch_rate command in order to maintain compatibility with previous configurators? Especially mobile apps and most importantly IOS apps which take a lot of time for new versions to be accepted in the appstore.

**Comment by hydra** [comment]
No clients should ever by using the CLI to configure the FC.  Only MSP should be used.

No, the old CLI command won't come back since it would require lots of new code, this new code would not be useful for any other configuration paramters and would just bloat the code-base.

Sorry.
