### ISSUE TITLE
LED - Configurable colors for flight modes

### ISSUE THREAD

**Issue by ExplodingFist** [cleanflight/cleanflight#819]
It would be nice if we could change the colors of the armed state LEDs, so that we can have the safety feature as well as flight colors being definable (instead of blue). At a minimum, you could make it so that ledstrip.c uses the colors defined in the 'color' command instead of hard coding the RGB values separately. Right now the only way to make this change is changing the hard coded values.

An alternative would be to allow for the selected flight color to override 'armed' (in this specific example).

**Comment by Arakon** [comment]
Agreed, that would be nice. Maybe combine it with the mode screen, i.e. have a drop down box next to the aux box to select from a choice of colors.

**Comment by JurikRistjouw** [comment]
Agreed. I am working on ledstrip.c privatly. I would have to learn the interaction between the configurator and firmware in terms of variables/constants so it can be made congifurable. I am thinking in terms of a flightmode color configuration per mode as an enhancement on the led page. Any ideas?
