### ISSUE TITLE
no rudder with power off

### ISSUE THREAD

**Issue by Buzzliteyear** [cleanflight/cleanflight#824]
Is this a setting change or bug

Airplane mode there is no rudder control when you power off coming in for landing

there is no rudder movement without motor running

cheers 
Brett

**Comment by hydra** [comment]
can you try with 1.7.x

**Comment by thenickdude** [comment]
This is due to the changes to support pid_at_min_throttle, which added code that zeros out the yaw RC channel when the throttle is low. That probably shouldn't happen on the airplane mixer.

**Comment by Buzzliteyear** [comment]
will try 1.7  in a couple of days (weather) thanks

yes same as the yaw on a tri-copter when motors aren't spinning

no its hard to land with no rudder when you need to power off

**Comment by Buzzliteyear** [comment]
tested with 1.7.2 rudder works as it should normal movement armed or disarmed

While testing it reminded me that with 1.8 loaded changing flights modes between Angle and Horizon motor was dis arming in Flight but with 1.7.2 it does not do this
