### ISSUE TITLE
Implement RC Yaw Expo

### ISSUE THREAD

**Issue by borisbstyle** [cleanflight/cleanflight#846]
I never considered it as really necessary before, but with the latest yaw improvements and very snappy yaw performance on some multirotors and agility to do yaw acrobatics I highly see a need to make Yaw expo available in Cleanflight as Enhancement

here is a blackbox demonstration of how well yaw works on my Mini H setup. You can clearly can see that my yaw input is very minimal when using pid controller 2 with these rate settings:
RC Rate 1.0
Roll rate 0.5
Pitch rate 0.5
Yaw rate 0.4
RC Expo 0.65
https://www.youtube.com/watch?v=zQtE0nrz2Sk

**Comment by borisbstyle** [comment]
Ok I did an attempt to implement it. Is there anybody who can help testing/reviewing the code with me before I make a PR?

https://github.com/borisbstyle/cleanflight

**Comment by borisbstyle** [comment]
And I made a PR for this

https://github.com/cleanflight/cleanflight/pull/847

**Comment by hydra** [comment]
Done
