### ISSUE TITLE
Unable to use Sparky.bin

### ISSUE THREAD

**Issue by snakescb** [cleanflight/cleanflight#859]
Hi, for the 1.8.x versions for Sparky, there is just a .bin file, no .hex anymore. Unfortunately, also using the 3.0.2 version of the DfuSe File Manager, I am not able to produce a valid dfu file to load to sparky. There is a dfu produced, but this will not download. If possible, please release the Sparky.hex also for 1.8.x versions

**Comment by defritonc1** [comment]
I am having the same problem.

**Comment by defritonc1** [comment]
The .bin file works.
When converting to dfu, you have to make sure you put the start address of the loaded file as 08000000.

![image](https://cloud.githubusercontent.com/assets/12320935/7552135/c8fd07a2-f671-11e4-8215-4cd8366cb472.png)

**Comment by snakescb** [comment]
This solves the issue, thanks for the quick help
