### ISSUE TITLE
Use modified version of Gimli to fix words_with_underscores in PDF manual

### ISSUE THREAD

**Issue by thenickdude** [cleanflight/cleanflight#860]
Currently in the manual PDF, when there is a word with multiple underscores in it (like "servo_center_pulse" in the CLI listing) the middle words gets put in italics and the underscores are removed, so the manual can't really be used as an accurate CLI reference.

This is because the default Markdown dialect in Gimli treats underscores as emphasis, even when they occur inside words. GitHub Flavored Markdown, on the other hand, does not. We can run a tweaked version of Gimli to bring its dialect closer to GitHib Flavor.

My fork of Gimli has the small patch applied to it to fix this problem:

https://github.com/thenickdude/gimli/tree/no-intra-emphasis

Before:

![Before patch](https://cloud.githubusercontent.com/assets/1921411/7530611/e829cd68-f59f-11e4-998c-f4bc83668a27.png)

After:

![After patch](https://cloud.githubusercontent.com/assets/1921411/7530609/e22d8972-f59f-11e4-8700-e8c283c48912.png)

**Comment by pulsar256** [comment]
Any chance you could integrate it into https://github.com/cleanflight/cleanflight/blob/master/.travis.sh? I have been also experimenting with an alternative pdf generation pipeline: https://github.com/pulsar256/cleanflight/blob/pdf_manual_tryouts/support/manual/build_docs.sh which produces a bit nicer looking pdfs and does not suffer from that underscore issue: http://cleanflight.memoryleaks.org/builds/testing/Manual.pdf

Perhaps it is worth moving to the generate-md -> wkhtmltopdf  approach?

**Comment by thenickdude** [comment]
I've added a PR which fixes this now by using a patched version of Gimli!
