### ISSUE TITLE
GPS HOLD is permanently on with Naze32 (Full)

### ISSUE THREAD

**Issue by max3228** [cleanflight/cleanflight#87]
Yesterday on 19th Sept I decided to try Cleanflight (from using Baseflight) Configurator and did firmware flash (On-Line) with a full chip erase first. Because of the coding differences between the two I then manually transferred all my previous settings in Baseflight. Then when I selected Auxiliary Config Tab in Cleanflight and proceeded to set up my Tx Switches. It was only then that i noticed GPS HOLD was permanently ON (Green). The only way I could get it back to RED was to disconnect everything USB / Battery / restart Cleanflight and re-connect everything. Then when I flick the AUX 3 switch again the same thing happens, by the way I am also unable to select GPS Hold although SB three way switch moves between the three positions correctly (Low-Med-High) indicated in Cleanflight. Also please note that the Naze32 is indicating a good GPS Lock (7 to 8 Sats) with a flashing red LED and that it was (the AUX 3 config) working correctly in Baseflight. Please see the image below ....... 

![cleanflight1](https://cloud.githubusercontent.com/assets/8843694/4345743/7842a900-40de-11e4-94a8-ae8363ba2691.jpg)

Cleanflight Configurator Version: 0.50.1
Running OS: Windows XP Home Version 2002 SP3
Chrome Version: 37.0.2062.120
Github Firmware Info:
Date: 09.19.2014
Note:Full Chip Erase
Hardware List:
Naze32 (Full) FC
Fatshark 25mW Video Tx
Ublox NEO 6M GPS
FrSKY D8-XP Rx
Taranis X9D 2.4GHz Tx
(Minim OSD currently disconnected)
# dump
# mixer

mixer QUADX
# map

map AETR1234

set looptime = 3500
set emf_avoidance = 0
set mid_rc = 1500
set min_check = 1100
set max_check = 1900
set rssi_channel = 0
set input_filtering_mode = 0
set min_throttle = 1150
set max_throttle = 1850
set min_command = 1000
set 3d_deadband_low = 1406
set 3d_deadband_high = 1514
set 3d_neutral = 1460
set 3d_deadband_throttle = 50
set motor_pwm_rate = 400
set servo_pwm_rate = 50
set retarded_arm = 0
set disarm_kill_switch = 1
set small_angle = 25
set flaps_speed = 0
set fixedwing_althold_dir = 1
set serial_port_1_scenario = 1
set serial_port_2_scenario = 2
set serial_port_3_scenario = 0
set serial_port_4_scenario = 0
set reboot_character = 82
set msp_baudrate = 115200
set cli_baudrate = 115200
set gps_baudrate = 115200
set gps_passthrough_baudrate = 115200
set gps_provider = 1
set gps_sbas_mode = 0
set serialrx_provider = 0
set telemetry_provider = 0
set telemetry_switch = 1
set frsky_inversion = 0
set vbat_scale = 111
set vbat_max_cell_voltage = 43
set vbat_min_cell_voltage = 35
set current_meter_scale = 400
set current_meter_offset = 0
set multiwii_current_meter_output = 0
set align_gyro = 0
set align_acc = 0
set align_mag = 0
set align_board_roll = 0
set align_board_pitch = 0
set align_board_yaw = 0
set max_angle_inclination = 500
set gyro_lpf = 42
set moron_threshold = 32
set gyro_cmpf_factor = 600
set gyro_cmpfm_factor = 250
set yaw_control_direction = 1
set acc_hardware = 0
# dump profile
# aux

aux 0 4
aux 1 400
aux 2 32
aux 3 384
aux 4 384
aux 5 0
aux 6 0
aux 7 0
aux 8 0
aux 9 256
aux 10 128
aux 11 0
aux 12 0
aux 13 0
aux 14 0
aux 15 0
aux 16 0
aux 17 0
aux 18 0
aux 19 2048
aux 20 0

set gps_pos_p = 11
set gps_pos_i = 0
set gps_pos_d = 0
set gps_posr_p = 20
set gps_posr_i = 8
set gps_posr_d = 45
set gps_nav_p = 14
set gps_nav_i = 20
set gps_nav_d = 80
set gps_wp_radius = 200
set nav_controls_heading = 1
set nav_speed_min = 100
set nav_speed_max = 300
set nav_slew_rate = 30
set alt_hold_deadband = 40
set alt_hold_fast_change = 1
set throttle_correction_value = 0
set throttle_correction_angle = 800
set deadband = 0
set yaw_deadband = 0
set yaw_direction = 1
set tri_unarmed_servo = 1
set rc_rate = 90
set rc_expo = 65
set thr_mid = 50
set thr_expo = 0
set roll_pitch_rate = 0
set yaw_rate = 0
set tpa_rate = 0
set tpa_breakpoint = 1500
set failsafe_delay = 10
set failsafe_off_delay = 200
set failsafe_throttle = 1200
set failsafe_min_usec = 985
set failsafe_max_usec = 2115
set gimbal_flags = 1
set acc_lpf_factor = 4
set accxy_deadband = 40
set accz_deadband = 40
set accz_lpf_cutoff = 5.000
set acc_unarmedcal = 1
set acc_trim_pitch = 0
set acc_trim_roll = 0
set baro_tab_size = 21
set baro_noise_lpf = 0.600
set baro_cf_vel = 0.985
set baro_cf_alt = 0.965
set mag_declination = 200
set pid_controller = 0
set p_pitch = 40
set i_pitch = 30
set d_pitch = 23
set p_roll = 40
set i_roll = 30
set d_roll = 23
set p_yaw = 85
set i_yaw = 45
set d_yaw = 0
set p_pitchf = 2.500
set i_pitchf = 0.600
set d_pitchf = 0.060
set p_rollf = 2.500
set i_rollf = 0.600
set d_rollf = 0.060
set p_yawf = 8.000
set i_yawf = 0.500
set d_yawf = 0.050
set level_horizon = 3.000
set level_angle = 5.000
set p_alt = 50
set i_alt = 0
set d_alt = 0
set p_level = 90
set i_level = 10
set d_level = 100
set p_vel = 120
set i_vel = 45
set d_vel = 1
# feature

Enabled features: RX_PPM VBAT MOTOR_STOP GPS

**Comment by Jasonm222** [comment]
Simple thing but i need to mention it.... Has your D8R-XP been updated to allow so many ppm channels to work? I had issues using three switches until i upgraded the frsky d8r firmare to a slower ppm framerate

**Comment by Jasonm222** [comment]
Here is a link to the update for anyone interested. [http://www.frsky-rc.com/download/index.php?sort=&cate_id=0&pro_id=21](url)
