### ISSUE TITLE
SmartPort - current multiplied by 10 on Taranis

### ISSUE THREAD

**Issue by ledvinap** [cleanflight/cleanflight#874]
Current reported over SmartPort is wrong, displayed value is 10x larger than actual.

There was some discussion about current resolution - is this intended behavior?

**Comment by hydra** [comment]
What version of OpenTX are you seeing this on?  And is this already addressed in the 'smartport fixes' PR?

**Comment by hydra** [comment]
This is the other PR with some SmartPort (S-Port) fixes #821

**Comment by ledvinap** [comment]
Tested on 2.0.17, the displayed values is 10x larger ... 

#821 does not address this

**Comment by kilrah** [comment]
No it would be the Curr value. 

I don't have a current sensor to connect to my Naze so didn't test that. I use a separate FrSky current sensor that is hooked together with the Naze on the smart port.
