### ISSUE TITLE
Add sonar values to blackbox recording

### ISSUE THREAD

**Issue by alvins82** [cleanflight/cleanflight#878]
Currently it looks sonar values are not recorded as part of blackbox logs. Would be good to see sonar values in blackbox for debugging alt-hold issues.

**Comment by thenickdude** [comment]
Do you have a sonar? If so, please test this new build out for me and post the resulting log, it should add logging of sonar data:

https://github.com/sherlockflight/cleanflight-dev/releases/tag/blackbox-sonar

**Comment by alvinpb** [comment]
Yes - will test and report back shortly.

**Comment by alvins82** [comment]
Looks like it works nice. Screenshot and log attached.

Based on the blackbox log looks like I may have an unrelated issue with Sonar in - values seem to be jumping around.

https://dl.dropboxusercontent.com/u/7607766/blackbox_log_2015-05-12_174111.TXT

![screen shot 2015-05-12 at 5 48 06 pm](https://cloud.githubusercontent.com/assets/1214275/7582254/14896350-f8cf-11e4-9a17-d8f768f8d7a7.png)

**Comment by thenickdude** [comment]
Hm, those are some pretty big jumps. Do you see jumps like that in the Configurator's readout of the sonar?

From the code, it almost looks like if it sends out one pulse but hears two echos, it'll report two distances (first the shorter distance and then the longer distance). If you're indoors then it could be hearing a secondary echo off a wall. If so, this is probably a bug.

**Comment by alvins82** [comment]
I am indoors and on carpet.

I just checked the configurator readout and no jumps. I am guessing this is due to the low resolution of 10ms of the configurator whereas the blips in blackbox are only for a few loop iterations.

**Comment by thenickdude** [comment]
I've now merged this feature with e6a40d732d8f303599b56f2848f3d262d3a7218b. I'll open a separate ticket to investigate the sonar blips.
