### ISSUE TITLE
Target - Add support for Sparky 2

### ISSUE THREAD

**Issue by VirtualEnder** [cleanflight/cleanflight#885]
Please, oh please! I would REALLY love to see support for this board! At some point... If possible!

http://www.hobbiesfly.com/multi-rotors/flight-controller/taulabs-sparky2-0.html
![sparky2-3-650x489_0](https://cloud.githubusercontent.com/assets/2568963/7591258/c6b549b6-f89a-11e4-85cb-3b55aec5fb7e.jpg)

**Comment by readerror67** [comment]
lul

**Comment by JohnieBraaf** [comment]
I think getting cleanflight to compile on a Discovery F4 would be a good starter.

**Comment by sambas** [comment]
I've been playing with F4 targets in https://github.com/sambas/cleanflight, my own AnyFC, revo and colibri works at flyable level.

**Comment by JohnieBraaf** [comment]
Good stuff, together with this repo https://github.com/treymarc/baseflight it should be possible to draft a  F4 PR.

**Comment by hydra** [comment]
F4 support wont happen until hardware resource allocation is cleaned up.  Please help by commenting on and testing #884

**Comment by brat002** [comment]
I am interested this feature too. TL for me is not interesting more.

**Comment by VirtualEnder** [comment]
@brat002 Work is being done over here: http://www.rcgroups.com/forums/showthread.php?t=2533601

It's already flyable on the Revo, and Spark 2 isn't far behind! Hooray!
