### ISSUE TITLE
LED - Landing lights

### ISSUE THREAD

**Issue by Fvk1960** [cleanflight/cleanflight#896]
The ledstrip function is impressive. Really nice.
But I am missing the function as in multiwii for landinglights for copter and maybe ledflasher for planes.
Landinglights (all white color) for downward facing leds when altitude becomes belong configurable value. Maybe also for GPS flashing white while in RTH and contineous on when landing.
Flashing lights for orientation leds.
Thanks

**Comment by hydra** [comment]
Please keep feature requests focused on one feature only.  In this feature request we will discuss landing lights only.  Please search for other appropriate feature requests regarding GPS led indications and open a new request or comment as appropriate.

Yes, landing lights would be fine, IIRC there is already a flag from multiwii and available by MSP that can be used for this which can be enabled/disabled by mode ranges (aux). `LLIGHTS`

The flashing code should be reusable, as per #471 See also #473
