### ISSUE TITLE
Cannot change yaw servo direction from CLI (Tricopter)

### ISSUE THREAD

**Issue by stronnag** [cleanflight/cleanflight#90]
If I set the yaw_direction = -1 in the CLI and save, it has no effect. The yaw direction is not reversed. Using the configurator, setting live mode and setting yaw direction to reverse works just fine.

This is inconvenient, as in the field, my chromebook won't connect to the configurator over BT (even though my desktop does...), and it any case, I find it much more convenient to restore the deltas to the defaults from a saved dump file rather than trying to remember every cranny of the GUI (and in extremis, I can do this in the field with picocom or mwp/naze-cli over BT).

**Comment by thenickdude** [comment]
It's now possible to reverse the yaw servo direction on the CLI using the new "servo" command.
