### ISSUE TITLE
BlackBox - Support logging via I2C

### ISSUE THREAD

**Issue by hydra** [cleanflight/cleanflight#916]
advantages (some are assumptions):
1. keeps serial port free
2. I2C has more bandwidth = higher logging rate
3. less error prone

Hardware already exists:
- http://www.seeedstudio.com/depot/SDLogger-Open-Hardware-Data-Logger-p-723.html
- http://www.hobbytronics.co.uk/ardulog2

**Comment by jaimevisser** [comment]
Both are quite a bit bigger than the openlogger. SPI would be a lot better as it would allow direct access to the SD card requiring less external hardware. Might be possible with an F3?
