### ISSUE TITLE
Comms - Expose alarms via MSP.

### ISSUE THREAD

**Issue by DarkVegetableMatter** [cleanflight/cleanflight#958]
At the moment MWOSD et al request VBatt from the FC and then do the maths (again) to alert the user to a low battery condition. If the OSD can fetch VBatt _and_ BatteryState then

-Only have to configure it once (in CF)
-OSD doesn't care if you change number of cells, FC sorts it out

We can't break compatibility by changing the size of a message (i.e. add an 'alarms' field to MSP_STATUS) so how about a new MSP_ALARMS message? Only MSP clients that know about MSP_ALARMS will request it and know how to handle it, everything else doesn't care.

This could be useful for RSSI too. I guess a UINT8 would be enough for 3 flags

**Comment by DarkVegetableMatter** [comment]
Maybe GPS lock lost too?

**Comment by JohnOCFII** [comment]
Remember that some people use MWOSD without connecting to a flight controller, so changes in CF may not equate with many savings for the MWOSD developers.

**Comment by hydra** [comment]
I'm wondering if there should be a more generic system state MSP command... Hmm.

**Comment by DarkVegetableMatter** [comment]
I think so too. Current system where FC & OSD have to agree on limits and alarms is broken. Much better if OSD has to know nothing and FC has all the smarts
