### ISSUE TITLE
Unable to configure Softserial in Configurator

### ISSUE THREAD

**Issue by udvlp** [cleanflight/cleanflight#959]
since a370d60 I'm not able to configure softserial ports in configurator. They are not listed on the Ports tab and the feature SOFTSERIAL becomes unchecked after reboot.

My flightcontroller is a Naze32 rev5 and all settings are defaults.

**Comment by hydra** [comment]
Enable softserial first. Reopen if you have issues

**Comment by thenickdude** [comment]
>feature SOFTSERIAL becomes unchecked after reboot

Are you sure your receiver isn't set to parallel PWM? Parallel PWM takes up the softserial pins so SOFTSERIAL can't be enabled when the receiver is set to parallel PWM.

**Comment by udvlp** [comment]
Thank you, @thenickdude & @hydra. I now understand that features can disable other features that are conflicting.
 
So this is a documentation/support issue. Before a370d60, I was able to configure ports on the ports tab and then all features on the Configuration tab.

Now, as a new user, coming from default settings, I have to follow the following steps:

1. On the Configuration tab, enable SOFTSERIAL and SERIALRX (SBUS). Save and Reboot.

2. On the Ports tab, configure Blackbox on Uart1, GPS on softserial etc.

3. On the Configuration tab, enable the rest of the features (Blackbox, GPS...)

All right, problem solved for me, but perhaps this could be documented by someone who speaks English fluently.

Thanks again.

**Comment by hydra** [comment]
@udvlp It is documented

https://github.com/cleanflight/cleanflight/blob/master/docs/Serial.md#constraints

**Comment by thenickdude** [comment]
As for Blackbox specifically, you can enable that before its port is
configured if you like.

**Comment by udvlp** [comment]
@hydra, I don't want to be nit-picky, but the following sentence from Serial.md: "Configure serial ports first, then enable/disable features that use the ports."  is misleading and (since a370d60) not true anymore for the two specific features SOFTSERIAL and RX_SERIAL.

**Comment by Propitiation** [comment]
I think this might be the same issue I am having with my quad. Cleanflight configurator 1.1 will not allow me to enable serialRX in ports tab under UART2, it just won't save. I have tried enabling sbus and serialRX in config tab first and second and still nothing. My quad flies with baseflight so I know its not a wiring thing. I'm using a naze32 rev5 from Armattan.

**Comment by thenickdude** [comment]
Take a screenshot of the ports tab before you're trying to save it. (You
can attach it here by dragging and dropping)

**Comment by Propitiation** [comment]
![image](https://cloud.githubusercontent.com/assets/16974224/12700442/9e020820-c7b0-11e5-89e3-9f176c79be95.png)
 
if i turn on UART2 it saves, but Serial RX never saves. I've tried doing config tab first second still nothing.

**Comment by Propitiation** [comment]
![image](https://cloud.githubusercontent.com/assets/16974224/12700456/588dcf44-c7b1-11e5-8df8-ada72147a9dc.png)

Sorry, this is what it looks like before I hit save, the first image I posted is what it looks like after I hit save.

**Comment by thenickdude** [comment]
By "turn on UART2" you mean ticking serial rx for UART2, right? Because
there's no switch to "turn on" that port. You aren't enabling MSP for UART2
by mistake are you?

**Comment by thenickdude** [comment]
Yeah untick MSP for UART2, you can't run MSP and SerialRX on the same port,
which is why the configuration gets rejected.

**Comment by Propitiation** [comment]
You Rock! yep that was my problem, I figured it would be something stupid... I don't know why cleanflight doesn't do this automatically when you click sbus...

**Comment by edgeflyer30** [comment]
Where can you click sbus?
