### ISSUE TITLE
CLI does not accept baudrates >115200

### ISSUE THREAD

**Issue by udvlp** [cleanflight/cleanflight#960]
Example:

```
# set serial_port_1_blackbox_baudrate = 5
serial_port_1_blackbox_baudrate set to 5

# set serial_port_1_blackbox_baudrate = 6
Value assignment out of range

# set serial_port_1_blackbox_baudrate = 7
Value assignment out of range
```

**Comment by hydra** [comment]
This is by design. Is there some reason you want to use or need a higher baudrate?

**Comment by thenickdude** [comment]
Ah @hydra I think you mean it's by design that MSP doesn't run faster than 115,200. Blackbox should be able to but currently has the wrong maximum set in serial_cli.

**Comment by udvlp** [comment]
I've noticed this problem when I tried to restore a CLI dump with Blackbox configured at 250kBd. Thanks for the fix, @thenickdude. I'm new to Git, next time I'll try to create a pull request myself.

**Comment by hydra** [comment]
@thenickdude yes. I missed the blackbox reference because the problem description wasnt clear.  Thanks for the fix.
