### ISSUE TITLE
LED - Flash LEDs mode for lost model

### ISSUE THREAD

**Issue by ATA250** [cleanflight/cleanflight#961]
Hi all,
  I think it would be useful to have a mode where LEDs flash on and off slowly; in combination with the beeper mode set to an aux channel and activated by a switch on your TX, this could be useful for creating both an audio and visual alert to help you locate a lost model (flashing lights are more visible than static ones).

**Comment by hydra** [comment]
Done.

Do you also want LED Strip warning LEDs to flash when the buzzer mode is on?

**Comment by ATA250** [comment]
Sounds like a good idea, thanks Hydra!
