### ISSUE TITLE
Failsafe - CC3D PPM RX failsafe not activating

### ISSUE THREAD

**Issue by magnazan** [cleanflight/cleanflight#967]
-Cleanflight v1.8.1
-Configurator v0.64.0
-CC3D FC
-FRSKY D4R-II PPM
-CF FS On 1000 throttle

I can successfully activate the RX failsafe when turning off the TX and all motors stop. When trying to check the FC FS by unplugging the RX whilst motors are on the throttle channel goes to 1000 but the motors continue to spin. Have confirmed throttle FS position goes to 1000 via bluetooth and configurator.

Have exactly the same setup on another machine which does shut off the motors.

**Comment by hydra** [comment]
Failsafe has been reworked for 1.9.0. Please try latest 1.9.0 release candidate binaries.  Re-open if there's an issue.
