### ISSUE TITLE
[SONAR + 1.9.X] Issue with Hex-X configuration

### ISSUE THREAD

**Issue by alex-savin** [cleanflight/cleanflight#971]
Hi,
I have tried pre-release and nightly build of 1.9.X branch and got strange issue while sonar enabled, my Hex-X multicopter doesn't spin 5 and 6 motors. But in configuration everything seems okay.
With Great Regards

**Comment by hydra** [comment]
Thanks for the report. There was some code cleanup with regards to pin allocation for sonar when cc3d sonar support was added so maybe theres an issue with it.

**Comment by hydra** [comment]
Sonar tested with Naze32 in Parallel PWM and PPM mode. No issue found.  Please see documentation regarding which pins to use for sonar.  PWM: M5/M6, PPM: RC7/8

Sonar + Parallel PWM + HEX = Impossible on Naze32, not enough IO pins are available.

**Comment by alex-savin** [comment]
Hi,
Once again about this issue. I guess have found a cause - enabling Current Meter and Sonar simultaneously. After these action I've lost motors number 5 and 6. But when I disabled Current Meter, but Sonar left enabled, motors start spinning again. 
With Great Regards
