### ISSUE TITLE
Sensors - Invalid compass code

### ISSUE THREAD

**Issue by ledvinap** [cleanflight/cleanflight#972]
alignSensors() is repeatedly applied if no new value is returned from `mag.read(magADC);`, possibly rotating last value indefinitely.

https://github.com/cleanflight/cleanflight/blob/master/src/main/sensors/compass.c#L75

**Comment by digitalentity** [comment]
Actually, same issue is present for both accel and gyro.

**Comment by hydra** [comment]
Yeah. I noticed this ages ago. I think i opened a ticket for it.
