### ISSUE TITLE
Failsafe is not disabled when it should be.

### ISSUE THREAD

**Issue by flygemaskin** [cleanflight/cleanflight#981]
When I have failsafe set to be DISABLED and throttle goes below rx_min_usec then throttle jumps to 1500 and stays there!
This can result in flyaways in powerful multicopters.

**Comment by hydra** [comment]
RX loss detection != failsafe.

There are other issues that cover this.

This is also not new behavior - the limits of 750 and 2250 have now been made configurable and define a smaller range than before.

See #918 #939 #982 etc, closing as duplicate.

In particular see this comment:

https://github.com/cleanflight/cleanflight/pull/982#issuecomment-108633159
