### ISSUE TITLE
CLI in cleanflight configurator does not work

### ISSUE THREAD

**Issue by larryho5** [cleanflight/cleanflight#990]
As the top, after upgrade to current version, the CLI has no data after I type anything in the CleanFlight Configurator.

**Comment by digitalentity** [comment]
What version of cleanflight and configurator are you using? Also what is your flight controller board? Just tested a build for CC3D at commit 98f7549aa48759f4f7442a8f3b7e40229800f59d and I was able to use CLI without any problems.

**Comment by larryho5** [comment]
Sorry, my mistake.
