### ISSUE TITLE
BlackBox - Gyro data and quad model is missing 

### ISSUE THREAD

**Issue by ksal0** [cleanflight/cleanflight#996]
Gyro data is no longer rendered. The new gyroADC data when rendered are basically strait lines and now useless. 

Also the quad model is missing. 
1.9.0 pre release was good. 
This started with 1.9.0 stable
Image is at 1/1 sample rate

![blackbox new data](https://cloud.githubusercontent.com/assets/11943719/8004823/408d4cb6-0b83-11e5-8607-f852db2840fb.jpg)

**Comment by digitalentity** [comment]
I also have the similar issue - blackbox_decode with --simulate-imu option shows an error: "Can't simulate the IMU because accelerometer or gyroscope data is missing"

**Comment by strfn** [comment]
Same issue here.

**Comment by SteveAmor** [comment]
I guess I broke this when refactoring the cleanflight code, replacing gyroData with gyroADC. gyroData is in the Blackbox viewer code. I'll look to fix later.

**Comment by SteveAmor** [comment]
Fixed in PR#998

**Comment by ksal0** [comment]
Thanks!

**Comment by SteveAmor** [comment]
Officially fixed with updated black box viewer and tools. This issue can be closed.
